### ISSUE TITLE
flux cask failing to install

### ISSUE THREAD

**Issue by gcapizzi** [Homebrew/brew#7682] opened 2020-06-03 15:31 UTC
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing the `flux` cask.

## What happened (include command output)

Installation failed.

<details>
  <summary>Command output</summary>
  <pre>
$ brew cask install flux
Updating Homebrew...
==> Downloading https://justgetflux.com/mac/Flux40.1.zip
##O#- #                                                                       
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Download failed on Cask 'flux' with message: Download failed: https://justgetflux.com/mac/Flux40.1.zip
  </pre>
</details>

## What you expected to happen

Installation succeeded.

## Step-by-step reproduction instructions (by running `brew` commands)

<pre>
$ brew cask install flux
</pre>

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 77e09fc166f5fb7197b239d5e2727ddc0791c121
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e0be4f59211e15b278b65cc5cfdf73ec9d43e102
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by claui** [comment] 2020-06-03 15:37
Thanks for reaching out @gcapizzi.
This is almost certainly a duplicate of #7667.

**Closed by claui** 2020-06-03 15:37 UTC

**Comment by gcapizzi** [comment] 2020-06-03 15:40
@claui ouch sorry, I did search through issues but missed that 😞
