### ISSUE TITLE
gem broke for brew ruby(2.6.3)

### ISSUE THREAD

**Issue by DolaBMOon** [Homebrew/brew#6081] opened 2019-05-01 01:20 UTC
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

I've seen Homebrew/homebrew-core#11636, but it didn't work for me. 

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

$ echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
$ source .bash_profile
$ gem

# What happened (include command output)

<details>
  <summary>Ignoring bigdecimal-1.4.3 because its extensions are not built. Try: gem pristine bigdecimal --version 1.4.3
Ignoring bigdecimal-1.3.5 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.5
Ignoring bond-0.5.1 because its extensions are not built. Try: gem pristine bond --version 0.5.1
Ignoring commonmarker-0.20.1 because its extensions are not built. Try: gem pristine commonmarker --version 0.20.1
Ignoring commonmarker-0.17.13 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.13
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring executable-hooks-1.3.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.10.0 because its extensions are not built. Try: gem pristine ffi --version 1.10.0
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring ffi-1.9.18 because its extensions are not built. Try: gem pristine ffi --version 1.9.18
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Ignoring gem-wrappers-1.3.2 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.3.2
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
Ignoring nokogiri-1.10.3 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.3
Ignoring nokogiri-1.8.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.4
Ignoring nokogiri-1.8.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.1
Ignoring openssl-2.1.1 because its extensions are not built. Try: gem pristine openssl --version 2.1.1
Ignoring psych-3.0.2 because its extensions are not built. Try: gem pristine psych --version 3.0.2
Ignoring redcarpet-3.4.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.4.0
Error loading RubyGems plugin "/Users/dolabmoon/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/executable-hooks-1.3.2/lib/rubygems_plugin.rb": cannot load such file -- executable-hooks/wrapper (LoadError)
Error loading RubyGems plugin "/Users/dolabmoon/.rvm/gems/ruby-2.4.1/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb": cannot load such file -- gem-wrappers (LoadError)
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
Traceback (most recent call last):
	14: from /usr/local/opt/ruby/bin/gem:21:in `<main>'
	13: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/gem_runner.rb:44:in `run'
	12: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/gem_runner.rb:79:in `do_configuration'
	11: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/gem_runner.rb:79:in `new'
	10: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/config_file.rb:198:in `initialize'
	 9: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/config_file.rb:346:in `load_file'
	 8: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:701:in `load_yaml'
	 7: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	 4: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/dolabmoon/.rvm/gems/ruby-2.4.1/gems/psych-3.0.2/lib/psych.rb:9:in `<top (required)>'
	 1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/psych.so (LoadError)
	15: from /usr/local/opt/ruby/bin/gem:21:in `<main>'
	14: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/gem_runner.rb:44:in `run'
	13: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/gem_runner.rb:79:in `do_configuration'
	12: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/gem_runner.rb:79:in `new'
	11: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/config_file.rb:198:in `initialize'
	10: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/config_file.rb:346:in `load_file'
	 9: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:701:in `load_yaml'
	 8: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	 5: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/dolabmoon/.rvm/gems/ruby-2.4.1/gems/psych-3.0.2/lib/psych.rb:8:in `<top (required)>'
	 2: from /Users/dolabmoon/.rvm/gems/ruby-2.4.1/gems/psych-3.0.2/lib/psych.rb:11:in `rescue in <top (required)>'
	 1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': incompatible library version - /Users/dolabmoon/.rvm/gems/ruby-2.4.1/gems/psych-3.0.2/lib/psych.bundle (LoadError)</summary>
  <pre>
  
  
  
  </pre>
</details>

# What you expected to happen

# Step-by-step reproduction instructions (by running `brew` commands)

$ echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
$ source .bash_profile
$ gem

**Comment by DolaBMOon** [comment] 2019-05-01 01:20
I've seen Homebrew/homebrew-core#11636, but it didn't work for me.

**Comment by MikeMcQuaid** [comment] 2019-05-01 07:58
This looks `rvm` related and should be fixed by running `gem pristine` like mentioned. Also, this is not a bug with a `brew` command so should not be filed in this repository.

**Closed by MikeMcQuaid** 2019-05-01 07:58 UTC
