### ISSUE TITLE
Ruby 2.4.0 tests issue.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#2184] opened 2017-02-25 16:23 UTC
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

`brew tests` run against a `bundler` installed with `ruby` 2.4.0 throws this error:

```
......................dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/gems/json-2.0.3/lib/json/ext/generator.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/gems/json-2.0.3/lib/json/ext/generator.bundle
  Expected in: flat namespace
```

Not really sure what to suggest, barring forcing the system gem or something. Reproduction instructions at least for me:

```
rm -rf ~/.bundle
rm -rf /usr/local/Homebrew/Library/Homebrew/vendor/bundle
rbenv install 2.4.0
rbenv global 2.4.0
gem install bundler
brew tests
```

Tested with a clean Homebrew installation. Flipping back to the system version of Ruby works fine.

**Comment by MikeMcQuaid** [comment] 2017-02-26 13:57
@reitermarkus @alyssais Looks like we shouldn't be sharing these gems between Ruby versions, right?

**Comment by alyssais** [comment] 2017-02-26 18:18
This is likely [my fault](https://github.com/Homebrew/brew/pull/1028).

**Comment by MikeMcQuaid** [comment] 2017-02-26 20:27
@alyssais Thanks for figuring that out. I think hardcoding the directory somewhere under e.g. vendor for everyone would be good (even if that means a bit of duplication).

**Comment by alyssais** [comment] 2017-02-26 21:13
@MikeMcQuaid that sounds like the right approach to me. 👍

**Comment by DomT4** [comment] 2017-02-28 18:20
CC @reitermarkus re https://github.com/Homebrew/brew/pull/2203#issuecomment-282719357. Not sure there's a lot you can do about it still, but, that's the origin of the problem.

**Comment by reitermarkus** [comment] 2017-03-01 13:59
@DomT4, I seriously have no idea what in https://github.com/Homebrew/brew/commit/e40c63f77c83254970c0e98f69ea76685536a905 would have caused this. The only thing that was added was the `minitest-reporters` Gem, which has now been removed again.

**Comment by DomT4** [comment] 2017-03-01 14:10
Looks like that was it 😕. Latest `brew` commit here is unproblematic on this front. `brew tests` now throws another issue but I'm not sure where this one is coming from. It may well be what Homebrew affectionately calls _"user configuration"_ given my use of `rbenv` rather than system/brewed Ruby.

```
./usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find json-2.0.3 in any of the sources (Bundler::GemNotFound)
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:80:in `map!'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:80:in `materialize'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/definition.rb:176:in `specs'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/definition.rb:235:in `specs_for'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/definition.rb:224:in `requested_specs'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:19:in `setup'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler.rb:100:in `setup'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/setup.rb:20:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
.ErrorDuringExecution: Failure while executing: /usr/local/bin/brew tap homebrew/core -q
  /usr/local/Homebrew/Library/Homebrew/utils.rb:285:in `safe_system'
  /usr/local/Homebrew/Library/Homebrew/tap.rb:539:in `ensure_installed!'
  /usr/local/Homebrew/Library/Homebrew/tap.rb:578:in `alias_dir'
  /usr/local/Homebrew/Library/Homebrew/tap.rb:350:in `alias_files'
  /usr/local/Homebrew/Library/Homebrew/tap.rb:356:in `aliases'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:1447:in `core_aliases'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:1459:in `aliases'
  /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:390:in `<class:FormulaAuditor>'
  /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:141:in `<top (required)>'
  /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/Homebrew/Library/Homebrew/test/dev-cmd/audit_spec.rb:1:in `<top (required)>'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/bin/rspec:22:in `load'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/bin/rspec:22:in `<top (required)>'
.bundler: failed to load command: rspec (/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/bin/rspec)
```

**Comment by reitermarkus** [comment] 2017-03-01 23:38
> It may well be what Homebrew affectionately calls "user configuration"

Well then, what does your configuration look like? 😄

**Comment by DomT4** [comment] 2017-03-02 00:19
If I try to run it directly it sheds more light:
```
~> /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/bin/rspec
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem rspec-core (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/bin/rspec:22:in `<main>'
```

But I don't know why, it's there 😓:
```
~> ls -1 /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0/gems
codecov-0.1.9
diff-lcs-1.3
docile-1.1.5
json-2.0.3
parallel-1.10.0
parallel_tests-2.13.0
rspec-3.5.0
rspec-core-3.5.4
rspec-expectations-3.5.0
rspec-its-1.2.0
rspec-mocks-3.5.0
rspec-support-3.5.0
rspec-wait-0.0.9
simplecov-0.13.0
simplecov-html-0.10.0
url-0.3.2
```

**Comment by reitermarkus** [comment] 2017-03-02 00:59
Are you setting `GEM_HOME` manually?

**Comment by DomT4** [comment] 2017-03-02 01:01
Nope:
```
env | grep GEM
env | grep RUBY
```
Both return nothing. I tried downgrading to the latest 2.3.3 release because I know `rspec` upstream isn't testing against a stable 2.4.0 yet but no luck there either.

**Comment by reitermarkus** [comment] 2017-03-02 01:13
Which `bundler` does actually get executed? Because of course it will fail if it calls it with a `2.4.0` shebang.

**Comment by DomT4** [comment] 2017-03-02 01:39
Adding a `puts which("bundle")` to `tests` gives me `/usr/local/var/rbenv/shims/bundle`. No gems are getting installed into `~/.gem`, only `/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.4.0`. That shim referenced above contains:

```bash
#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

program="${0##*/}"
if [ "$program" = "ruby" ]; then
  for arg; do
    case "$arg" in
    -e* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export RBENV_DIR="${arg%/*}"
        break
      fi
      ;;
    esac
  done
fi

export RBENV_ROOT="/usr/local/var/rbenv"
exec "/usr/local/Cellar/rbenv/1.1.0/libexec/rbenv" exec "$program" "$@"
```

And the `bundle` it is pointing at reads:
```ruby
#!/usr/local/var/rbenv/versions/2.4.0/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

load Gem.activate_bin_path('bundler', 'bundle', version)
```

And just for fun, if I `gem uninstall bundle bundler`, open a new shell session and then try to run `brew tests` nothing happens at all 🤷‍♂️. If I delete `rbenv` entirely and then `gem install bundler` using Homebrew's Ruby, which is also 2.4.0, same thing happens.

If I do this:
```
brew rm rbenv
brew rm ruby
cd
gem install bundler --user
brew tests
```
No problem at all.

**Comment by DomT4** [comment] 2017-03-02 02:08
Clean clone of the `brew` repo + doing `brew install ruby && rehash && gem install bundler && brew tests` blows up. I think Ruby 2.4.0 is the problem here, but I'm not sure why it's getting used.

**Comment by reitermarkus** [comment] 2017-03-02 03:17
Ok, so I tried it with 2.4.0 myself, and I cannot reproduce this. It's working, except for some actual tests failing.

**Comment by DomT4** [comment] 2017-03-02 04:01
Hmm. I'm not doing anything overly weird in this environment.
```
HOMEBREW_CACHE=/usr/local/var/homebrewcache
HOMEBREW_LOGS=/usr/local/var/homebrewcache/logs
HOMEBREW_DEVELOPER=1
HOMEBREW_SANDBOX=1
HOMEBREW_NO_AUTO_UPDATE=1
HOMEBREW_NO_ANALYTICS=1
HOMEBREW_GITHUB_API_TOKEN=blahblahblahblah
```

**Comment by MikeMcQuaid** [comment] 2017-03-02 08:12
Keep talking but just closing this because it's not reproducible now.

**Closed by MikeMcQuaid** 2017-03-02 08:12 UTC
Labels: help wanted

**Comment by reitermarkus** [comment] 2017-03-02 13:42
So even though you haven't set `HOMEBREW_RUBY_PATH`, it still uses `rbenv`'s `ruby`. Might want to take a look at what exactly `utils/ruby.sh` is selecting.

**Comment by DomT4** [comment] 2017-03-02 20:35
```diff
diff --git a/Library/Homebrew/utils/ruby.sh b/Library/Homebrew/utils/ruby.sh
index 6945c068b..07dbb7e9b 100644
--- a/Library/Homebrew/utils/ruby.sh
+++ b/Library/Homebrew/utils/ruby.sh
@@ -54,4 +54,5 @@ setup-ruby-path() {
   fi
 
   export HOMEBREW_RUBY_PATH
+  echo $HOMEBREW_RUBY_PATH
 }
```

Cleanup between each test:
```
rm -rf ~/.bundle
rm -rf /usr/local/Homebrew/Library/Homebrew/vendor/bundle
rm -rf ~/.gem
```

System Ruby only installed:
```
~> brew tests
/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby
==> Installing or updating 'bundler' gem
Fetching: bundler-1.14.5.gem (100%)
Successfully installed bundler-1.14.5
1 gem installed
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Unable to use the platform-specific () version of simplecov (0.13.0) because it has different dependencies from the ruby version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Unable to use the platform-specific () version of rspec-expectations (3.5.0) because it has different dependencies from the ruby version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Unable to use the platform-specific () version of rspec-mocks (3.5.0) because it has different dependencies from the ruby version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Unable to use the platform-specific () version of rspec-wait (0.0.9) because it has different dependencies from the ruby version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Rubygems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Installing json 2.0.3 with native extensions
Installing docile 1.1.5
Installing simplecov-html 0.10.0
Installing url 0.3.2
Installing diff-lcs 1.3
Installing parallel 1.10.0
Installing rspec-support 3.5.0
Using bundler 1.14.5
Installing simplecov 0.13.0
Installing parallel_tests 2.13.0
Installing rspec-core 3.5.4
Installing rspec-expectations 3.5.0
Installing rspec-mocks 3.5.0
Installing codecov 0.1.9
Installing rspec-its 1.2.0
Installing rspec 3.5.0
Installing rspec-wait 0.0.9
Bundle complete! 6 Gemfile dependencies, 17 gems now installed.
Bundled gems are installed into /usr/local/Homebrew/Library/vendor/bundle.
...
1195 examples, 0 failures, 3 pendings

Took 72 seconds (1:12)
```

That pattern doesn't change regardless of whether I use Homebrew's Ruby or a 2.4.0 installed via `rbenv` now. 

The only thing I've changed on this system in terms of Ruby since yesterday was finding that I'd installed `bundler` with the system `gem` in the past and that was living in `/Library/Ruby/Gems/2.0.0/gems`. I don't know if that was getting picked up somehow and causing issues 😕, but I can no longer reproduce my original issue and now I'm very confused but relieved.

**Comment by DomT4** [comment] 2017-03-02 20:38
5 days of chasing this around and it vanishes overnight. Of course 😕. Thanks for talking this through everyone, appreciate the input. Software is fun.
