### ISSUE TITLE
brew info transmission retrieves version 3.00 instead of the latest version (and it applicable to other situations)

### ISSUE THREAD

**Issue by ashr123** [Homebrew/brew#15299] opened 2023-04-24 09:58 UTC
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  pycparser
  cffi
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.14-115-g4ddebd9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4ddebd9bd58d1bac7eadc70c5f48c73676173f09
Last commit: 34 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: db371ec7510651e00ebfb242887aa6119b22199f
Core tap last commit: 9 weeks ago
Core tap branch: master
Core tap JSON: 24 Apr 06:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.aMeWrWPGYs/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

install the latest `transmission`

### What happened (include all command output)?

```bash
brew info transmission
```

> Warning: Use transmission-cli instead of deprecated transmission
> Warning: Treating transmission as a formula. For the cask, use homebrew/cask/transmission
> ==> transmission-cli: stable 3.00 (bottled)
> Lightweight BitTorrent client
> https://www.transmissionbt.com/
> Not installed
> From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/transmission-cli.rb
> License: GPL-2.0-only or GPL-3.0-only
> ==> Dependencies
> Build: pkg-config ✔
> Required: libevent ✘, openssl@1.1 ✔
> ==> Caveats
> This formula only installs the command line utilities.
> 
> Transmission.app can be downloaded directly from the website:
>   https://www.transmissionbt.com/
> 
> Alternatively, install with Homebrew Cask:
>   brew install --cask transmission
> 
> To restart transmission-cli after an upgrade:
>   brew services restart transmission-cli
> Or, if you don't want/need a background service you can just run:
>   /opt/homebrew/opt/transmission-cli/bin/transmission-daemon --foreground --config-dir /opt/homebrew/var/transmission/ --log-info --logfile /opt/homebrew/var/transmission/transmission-daemon.log
> ==> Analytics
> install: 33 (30 days), 1,436 (90 days), 11,567 (365 days)
> install-on-request: 33 (30 days), 1,436 (90 days), 11,565 (365 days)
> build-error: 0 (30 days)

### What did you expect to happen?

The same version as the following commands
```bash
brew info transmission-cli
```
or
```bash
brew info --cask transmission
```

### Step-by-step reproduction instructions (by running `brew` commands)

Just execute

```bash
brew info transmission
```

and
```bash
brew info transmission-cli
```
for example

In addition see this comment: https://github.com/orgs/Homebrew/discussions/4449#discussioncomment-5705843

**Comment by MikeMcQuaid** [comment] 2023-04-24 10:03
I'd suggest running `brew untap homebrew/core` unless you still need it.

**Comment by ZhongRuoyu** [comment] 2023-04-24 10:06
Thanks @ashr123 -- I asked them to open this issue. The problem is that `brew info <alias>` seems to be using the results from `Formulary::TapLoader`.

A simple repro:

```shell
unset HOMEBREW_NO_INSTALL_FROM_API
git -C `brew --repo homebrew/core` checkout db371ec  # checkout an outdated commit
brew info transmission  # shows version in tap (3.00)
brew info transmission-cli  # shows latest (4.0.3)
```

`brew info --debug transmission` output:

```
$ brew info --debug transmission
Warning: Use transmission-cli instead of deprecated transmission
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/transmission-cli.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading transmission
Warning: Treating transmission as a formula. For the cask, use homebrew/cask/transmission
==> transmission-cli: stable 3.00 (bottled)
Lightweight BitTorrent client
https://www.transmissionbt.com/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/transmission-cli.rb
License: GPL-2.0-only or GPL-3.0-only
==> Dependencies
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading pkg-config from API
Build: pkg-config ✔
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libevent from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openssl@1.1 from API
Required: libevent ✔, openssl@1.1 ✔
==> Caveats
This formula only installs the command line utilities.

Transmission.app can be downloaded directly from the website:
  https://www.transmissionbt.com/

Alternatively, install with Homebrew Cask:
  brew install --cask transmission

To restart transmission-cli after an upgrade:
  brew services restart transmission-cli
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/transmission-cli/bin/transmission-daemon --foreground --config-dir /usr/local/var/transmission/ --log-info --logfile /usr/local/var/transmission/transmission-daemon.log
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.14-121-g763c41f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail https://formulae.brew.sh/api/formula/transmission-cli.json
==> Analytics
install: 30 (30 days), 1,399 (90 days), 11,525 (365 days)
install-on-request: 30 (30 days), 1,398 (90 days), 11,523 (365 days)
build-error: 0 (30 days)
```

**Comment by ZhongRuoyu** [comment] 2023-04-24 10:07
---
@ashr123 to answer your question: we have switched to using a JSON API for formula installation by default since version 4.0.0 (see [4.0.0 release notes](https://brew.sh/2023/02/16/homebrew-4.0.0/)). Unless you need `Homebrew/core`'s Git repository for development or other purposes, it is not required anymore.

**Comment by Bo98** [comment] 2023-04-27 13:00
This looks to be due to not supporting formula renames, which we now do as of today so this should be fixed now.

**Closed by Bo98** 2023-04-27 13:00 UTC
Labels: bug, help wanted, install from api
