### ISSUE TITLE
Homebrew won't install on M1 Mac (macOS 11.2.1)

### ISSUE THREAD

**Issue by geraint360** [Homebrew/brew#10684] opened 2021-02-23 18:14 UTC
**`brew config` output**

    zsh: command not found: brew

**`brew doctor` output**

    zsh: command not found: brew

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Attempts to run brew update resulted in a Ruby error. To remediate, tried to reinstall Homebrew from scratch. This results in the same error, seemingly linked to various gems ("missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/..."). The example shows bigdecimal, but other installs have failed with date.  

**What happened (include all command output)?**

```
geraint@MacBookM1 ~ % sudo rm -rf /Library/Developer/CommandLineTools
Password:
geraint@MacBookM1 ~ % xcode-select --install
xcode-select: note: install requested for command line developer tools
geraint@MacBookM1 ~ % which git
/usr/bin/git
geraint@MacBookM1 ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
==> Checking for `sudo` access (which may request your password).
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew
==> The following new directories will be created:
/opt/homebrew/bin
/opt/homebrew/etc
/opt/homebrew/include
/opt/homebrew/lib
/opt/homebrew/sbin
/opt/homebrew/share
/opt/homebrew/opt
/opt/homebrew/share/zsh
/opt/homebrew/share/zsh/site-functions
/opt/homebrew/var/homebrew/linked
/opt/homebrew/Cellar
/opt/homebrew/Caskroom
/opt/homebrew/Frameworks

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/opt /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew/linked /opt/homebrew/Cellar /opt/homebrew/Caskroom /opt/homebrew/Frameworks
==> /usr/bin/sudo /bin/chmod g+rwx /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/opt /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew/linked /opt/homebrew/Cellar /opt/homebrew/Caskroom /opt/homebrew/Frameworks
==> /usr/bin/sudo /usr/sbin/chown geraint /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/opt /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew/linked /opt/homebrew/Cellar /opt/homebrew/Caskroom /opt/homebrew/Frameworks
==> /usr/bin/sudo /usr/bin/chgrp admin /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/opt /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew/linked /opt/homebrew/Cellar /opt/homebrew/Caskroom /opt/homebrew/Frameworks
==> /usr/bin/sudo /usr/sbin/chown -R geraint:admin /opt/homebrew
==> /usr/bin/sudo /bin/mkdir -p /Users/geraint/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/geraint/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown -R geraint /Users/geraint/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 175045 (delta 0), reused 44 (delta 0), pack-reused 175000
Receiving objects: 100% (175045/175045), 45.50 MiB | 65.07 MiB/s, done.
Resolving deltas: 100% (129975/129975), done.
From https://github.com/Homebrew/brew
 * [new branch]      dependabot/bundler/Library/Homebrew/sorbet-0.5.6287 -> origin/dependabot/bundler/Library/Homebrew/sorbet-0.5.6287
 * [new branch]      master     -> origin/master

[...deleted...]

HEAD is now at 3efab3efa Merge pull request #10421 from SeekingMeaning/uninstall-cask-binaries
==> Tapping homebrew/core
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 915154 (delta 11), reused 12 (delta 6), pack-reused 915133
Receiving objects: 100% (915154/915154), 368.72 MiB | 67.47 MiB/s, done.
Resolving deltas: 100% (624088/624088), done.
From https://github.com/Homebrew/homebrew-core
 * [new branch]      master     -> origin/master
HEAD is now at d2b25e00f4 node@12: update 12.21.0 bottle.
Traceback (most recent call last):
	19: from /opt/homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	18: from /opt/homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	17: from /opt/homebrew/Library/Homebrew/global.rb:23:in `<top (required)>'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.3/lib/active_support/core_ext/numeric/time.rb:3:in `<top (required)>'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.3/lib/active_support/duration.rb:3:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.3/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.3/lib/active_support/xml_mini.rb:5:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/bigdecimal-3.0.0/lib/bigdecimal.rb:1:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/bigdecimal-3.0.0/lib/bigdecimal.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/bigdecimal-3.0.0/lib/bigdecimal.bundle - /Library/Ruby/Gems/2.6.0/gems/bigdecimal-3.0.0/lib/bigdecimal.bundle (LoadError)
Failed during: /opt/homebrew/bin/brew update --force --quiet
geraint@MacBookM1 ~ % which ruby
/usr/bin/ruby
```

**What did you expect to happen?**

Homebrew to install

**Step-by-step reproduction instructions (by running `brew` commands)**

```
xcode-select --install
bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

**Comment by carlocab** [comment] 2021-02-23 18:17
Duplicate of #10662.

There are many posts on the discussions page about this issue (and related issues). Please check there for solutions. For example:

https://github.com/Homebrew/discussions/discussions/666
https://github.com/Homebrew/discussions/discussions/657
https://github.com/Homebrew/discussions/discussions/698
https://github.com/Homebrew/discussions/discussions/671
https://github.com/Homebrew/discussions/discussions/501
https://github.com/Homebrew/discussions/discussions/668
https://github.com/Homebrew/discussions/discussions/814

**Closed by carlocab** 2021-02-23 18:17 UTC
Labels: bug

**Comment by geraint360** [comment] 2021-02-23 18:26
Apologies @carlocab, I didn't see them despite various searches. Thank you.

**Comment by geraint360** [comment] 2021-02-23 18:38
Forgive me @carlocab but all of these issues appear to relate to Git but as far as I can tell, the Git clone is working fine and I was able to run a clone of homebrew/core without problem.

**Comment by carlocab** [comment] 2021-02-23 18:40
If the ones I linked to don't help, and you can't find any other related ones on the discussions page, you can open a new post there asking for help.

**Comment by geraint360** [comment] 2021-02-23 19:09
Thank you again @carlocab. It turned out to be quite a lot of failing (presumably, incompatible Intel) gems so I uninstalled them all. I had incorrectly assumed these gems were being installed as part of Homebrew given they appear to be a dependency. Thank you again for your help.

**Comment by carlocab** [comment] 2021-02-23 19:11
Yea, a bunch of Ruby Gems don't seem to be working very well on ARM. If you need them, I recommend using `rbenv` to install an isolated Ruby environment so you can switch them off easily when they cause trouble.
