### ISSUE TITLE
Shallow copy on install

### ISSUE THREAD

**Issue by wieczorek1990** [Homebrew/brew#14284] opened 2022-12-22 13:27 UTC
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Please shallow copy a branch during installation to safe install time.

### What is the motivation for the feature?

Time consumption.

### How will the feature be relevant to at least 90% of Homebrew users?

Faster install time.

### What alternatives to the feature have been considered?

Staying with the current behavior which is copying the whole repository.

**Comment by carlocab** [comment] 2022-12-22 13:48
Duplicate of https://github.com/Homebrew/brew/issues/11693

**Closed by carlocab** 2022-12-22 13:48 UTC
Labels: features
