### ISSUE TITLE
Ripgrep upgrade fails to due bad dependency

### ISSUE THREAD

**Issue by lc9er** [Homebrew/brew#7224] opened 2020-03-26 14:25 UTC
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade ripgrep 11.0.2 -> 12.0.0

## What happened (include command output)

It failed, citing "asciidoc: macOS is required". I'm running Ubuntu 19.04 on WSL.

<details>
  <summary>Command output</summary>
  <pre>

  ❯ brew upgrade
Updating Homebrew...
==> Upgrading 1 outdated package:
ripgrep 11.0.2 -> 12.0.0
==> Upgrading ripgrep 11.0.2 -> 12.0.0
==> Installing dependencies for ripgrep: asciidoc, docbook-xsl, pkg-config, libssh2, binutils, curl and rust
asciidoc: macOS is required.
Error: ripgrep: An unsatisfied requirement failed this build.
==> Checking for dependents of upgraded formulae...
==> No dependents found!

  </pre>
</details>

## What you expected to happen

ripgreg should grade to v12.0.0.

## Step-by-step reproduction instructions (by running `brew` commands)

brew upgrade ripgrep

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew config
HOMEBREW_VERSION: 2.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa8fe0fc396550c23156043cd07550fc6ae6a27a
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 73ff595ab6aee6445e4e84db2bc92733e33f3b7d
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/bjm25/.cache/Homebrew
HOMEBREW_LOGS: /home/bjm25/.cache/Homebrew/Logs
CPU: octa-core 64-bit icelake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.20.1 => /usr/bin/git
Curl: 7.65.3 => /usr/bin/curl
Kernel: Linux 4.4.0-18362-Microsoft x86_64 GNU/Linux
OS: Ubuntu 19.10 (eoan)
Host glibc: 2.30
/usr/bin/gcc: 9.2.1
glibc: N/A
gcc: N/A
xorg: N/A

❯ brew doctor
Your system is ready to brew.
</pre>

**Comment by bayandin** [comment] 2020-03-26 14:29
Duplicate of https://github.com/Homebrew/linuxbrew-core/issues/19885

**Closed** 2020-03-26 14:32 UTC

**Comment by lc9er** [comment] 2020-03-26 14:42
> 
> 
> Duplicate of [Homebrew/linuxbrew-core#19885](https://github.com/Homebrew/linuxbrew-core/issues/19885)

Whoops. My apologies. Wasn't aware of the project structure. Thank you.
