### ISSUE TITLE
`brew cleanup` is too thorough

### ISSUE THREAD

**Issue by maxim-belkin** [Homebrew/brew#6276] opened 2019-07-03 15:19 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

### What you were trying to do (and why)

Clean up Homebrew directory in a safe and reliable manner

### What happened (include command output)

Homebrew removed directories that are saved from deletion in formulae (_via_ `skipclean`).

<details>
  <summary>brew cleanup</summary>
  <pre>
rmdir /home/linuxbrew/.linuxbrew/lib/ruby/vendor_ruby/2.6.0/x86_64-linux
rmdir /home/linuxbrew/.linuxbrew/lib/ruby/vendor_ruby/2.6.0
rmdir /home/linuxbrew/.linuxbrew/lib/ruby/vendor_ruby
rmdir /home/linuxbrew/.linuxbrew/lib/ruby/site_ruby/2.6.0/x86_64-linux
rmdir /home/linuxbrew/.linuxbrew/lib/ruby/site_ruby/2.6.0
rmdir /home/linuxbrew/.linuxbrew/lib/ruby/site_ruby
rmdir /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.30.0/x86_64-linux-thread-multi
rmdir /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.30.0
rmdir /home/linuxbrew/.linuxbrew/lib/perl5/site_perl
rmdir /home/linuxbrew/.linuxbrew/etc/openssl/private
rmdir /home/linuxbrew/.linuxbrew/etc/openssl/certs
  </pre>
</details>

### What you expected to happen

Formula `perl` has 
```ruby
skip_clean "lib/perl5/site_perl
```
so I expected `brew cleanup` to _not_ delete 
```
/home/linuxbrew/.linuxbrew/lib/perl5/site_perl
```

### Step-by-step reproduction instructions (by running `brew` commands)

```
# Uninstall Homebrew perl formula if it is currently installed
# Delete /home/linuxbrew/.linuxbrew/lib/perl5 if present
brew install perl
brew cleanup
```

---

### Update 1 (@geoff-nixon):

> `brew cleanup` also iterates through **each** installed formula in Cellar, shelling out each time with a `find ... -name .DS_Store -delete`, then repeats itself by doing the the same thing on the _entire_ Cellar directory

<p align="right"><i>updated on August 30, 2019</i></p>

**Comment by GauthamGoli** [comment] 2019-07-07 15:25
I was looking at fixing this issue and could not reproduce this locally. 
```bash
➜  Homebrew git:(master) brew cleanup --prune=0 perl
Removing: /Users/gauthamhome/Library/Caches/Homebrew/perl--5.30.0.high_sierra.bottle.tar.gz... (16.3MB)
```

**Comment by retokromer** [comment] 2019-07-07 15:28
This is on Linux:
```
# Delete /home/linuxbrew/.linuxbrew/lib/perl5 if present
```
while that is on macOS:
```
Removing: /Users/gauthamhome/Library/Caches/Homebrew/perl--5.30.0.high_sierra.bottle.tar.gz... (16.3MB)
```

**Comment by maxim-belkin** [comment] 2019-07-07 16:18
@GauthamGoli, set `HOMEBREW_VERBOSE` to `1`. You would then see:

```
$ brew cleanup
rmdir /usr/local/lib/perl5/site_perl/5.30.0/darwin-thread-multi-2level
rmdir /usr/local/lib/perl5/site_perl/5.30.0
rmdir /usr/local/lib/perl5/site_perl
Pruned 0 symbolic links and 3 directories from /usr/local
```

**Comment by geoff-nixon** [comment] 2019-08-13 05:18
In the general category of "`brew cleanup` is too thorough": 

I'll throw in that `brew cleanup` also iterates through **each** installed formula in Cellar, shelling out each time with a `find ... -name .DS_Store -delete`, then repeats itself by doing the the same thing on the _entire_ Cellar directory...

**Comment by MikeMcQuaid** [comment] 2019-08-13 07:17
> I'll throw in that `brew cleanup` also iterates through **each** installed formula in Cellar, shelling out each time with a `find ... -name .DS_Store -delete`, then repeats itself by doing the the same thing on the _entire_ Cellar directory...

@geoff-nixon Could you submit a PR for that?

**Comment by veera83372** [comment] 2019-08-13 10:33
@geoff-nixon, @MikeMcQuaid  I would like to work on it

**Comment by MikeMcQuaid** [comment] 2019-08-13 13:08
@veera83372 Go for it.

**Comment by geoff-nixon** [comment] 2019-08-15 09:23
@veera83372 Cool.

**Comment by MikeMcQuaid** [comment] 2019-08-29 07:13
Thanks @geoff-nixon. I've posted on the PR that looks most like what we want (https://github.com/Homebrew/brew/pull/6404/files#r318916931) which is to preserve the same behaviour on `brew cleanup formula` but ensure `brew cleanup` doesn't do the duplicate cleanups you've mentioned.

**Comment by geoff-nixon** [comment] 2019-08-29 17:03
So, I gave it my best shot. Notes on the PR. Unfortunately, might need to keep that "help wanted" flag up for a while.

**Comment by MikeMcQuaid** [comment] 2019-09-18 10:45
> ```ruby
> skip_clean "lib/perl5/site_perl
> ```

This is an instruction to the installer but not to `brew cleanup`. `brew cleanup` cannot sensibly parse this attribute from every formula to figure out to avoid cleaning empty directories. Putting a `.keepme` file in that directory is the best bet to avoid cleaning.

> `brew cleanup` also iterates through **each** installed formula in Cellar, shelling out each time with a `find ... -name .DS_Store -delete`, then repeats itself by doing the the same thing on the _entire_ Cellar directory

This will be addressed in https://github.com/Homebrew/brew/pull/6468.

**Closed by MikeMcQuaid** 2019-09-18 10:45 UTC
Labels: help wanted

**Comment by maxim-belkin** [comment] 2019-09-18 14:26
> `brew cleanup` cannot sensibly parse this attribute from every formula to figure out to avoid cleaning empty directories.

`.keepme` or similar is one solution. Another would require Homebrew to keep track of such folders in a separate location similar to linkage information.
