### ISSUE TITLE
Symlink in /usr/local/opt without destination breaks almost every command

### ISSUE THREAD

**Issue by kirb** [Homebrew/brew#104] opened 2016-04-17 06:24 UTC
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:
Somehow, I had a symlink in /usr/local/opt, specifically `gnu-which`, that was created with a null destination.

```shellsession
$ ls -d /usr/local/opt/gnu-which
lrwxr-xr-x  1 kirb staff   24 Apr 14 21:39 gnu-which ->
```

This broke almost all brew commands, which would throw this:

```
Error: pathname contains null byte
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/extend/pathname.rb:340:in `initialize'
/usr/local/Library/Homebrew/extend/pathname.rb:340:in `readlink'
/usr/local/Library/Homebrew/extend/pathname.rb:340:in `resolved_path'
/usr/local/Library/Homebrew/keg.rb:189:in `optlinked?'
/usr/local/Library/Homebrew/formulary.rb:215:in `each'
/usr/local/Library/Homebrew/formulary.rb:215:in `detect'
/usr/local/Library/Homebrew/formulary.rb:215:in `from_rack'
/usr/local/Library/Homebrew/diagnostic.rb:1339:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Library/Homebrew/diagnostic.rb:1336:in `reject'
/usr/local/Library/Homebrew/diagnostic.rb:1336:in `check_for_unlinked_but_not_keg_only'
/usr/local/Library/Homebrew/cmd/doctor.rb:38:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:31:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:31:in `doctor'
/usr/local/Library/brew.rb:97:in `<main>'
```

Obviously this isn’t very helpful to finding the culprit, and I only found the culprit by luck. I don’t know how the bad symlink was created in the first place – after deleting it, I inspected its directory in the cellar and nothing seems out of place. Linking it manually also worked.

### Feature Requests:
I would figure there should be a check to confirm the destination is not empty when creating symlinks. Possibly also add a check for this to `brew doctor`? It was the first thing I tried, hoping it would fix it.

**Comment by UniqMartin** [comment] 2016-04-17 18:06
Thanks for the report, @kirb! Can you provide the output of `brew config` and `brew doctor` just in case those information help us narrow down the circumstances under which this can happen? This seems to be the same issue like in #26. Sadly, I'm not able to reproduce this, thus I'm not sure how to best debug this or improve on our error handling …

**Comment by apjanke** [comment] 2016-04-18 00:10
Also possibly related: an older issue with symlinks due to apparent filesystem corruption: https://github.com/Homebrew/legacy-homebrew/issues/41640

**Comment by kirb** [comment] 2016-04-18 00:30
brew config:

```
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: f15b631875ef19599bcb4e774d3e67596d1f93ac
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b396048d6dfc0987a2adea82fbe5749a36e04a53
Core tap last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.4-x86_64
Xcode: 7.3
CLT: N/A
Clang: 7.3 build 703
X11: N/A
System Ruby: 2.0.0-p648
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.22.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
Java: N/A
```

brew doctor:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default OS X filesystem is case-insensitive. Please report any apparent problems.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    gpg-agent

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
    homebrew/dupes/bzip2
```

(gpg-agent conflicts with GPGTools gpg-agent, and I intentionally force linked bzip2.)

**Comment by mikemcquaid** [comment] 2016-05-03 14:53
@UniqMartin I see you assigned this; what are your thoughts here?

**Comment by UniqMartin** [comment] 2016-05-03 15:29
@mikemcquaid I'd like to look into this and improve the error handling, but haven't done so yet. (Using assignments as some form of TO DO list.)

**Comment by mikemcquaid** [comment] 2016-05-03 15:40
@UniqMartin Cool, thanks.

**Comment by MikeMcQuaid** [comment] 2016-08-10 09:27
If this is still broken for you: we'll accept PRs for this but we're not actively working on it at this time.

**Closed by MikeMcQuaid** 2016-08-10 09:27 UTC
Labels: bug, usability
