### ISSUE TITLE
Same version in output on upgrade

### ISSUE THREAD

**Issue by n-bes** [Homebrew/brew#11991] opened 2021-09-07 17:47 UTC
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 84f4fbf3cf5e83d33de0b28b2658fcb50aaa761e
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a742fbce05702688a0e65fe3453419e86f6a9bdd
Core tap last commit: 8 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.T1mbyh2ux2/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  lua@5.1

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  lua@5.1
  openexr
  kubernetes-cli

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?
```
➜  ~ brew upgrade
==> Upgrading 6 outdated packages:
pv 1.6.6 -> 1.6.19
imagemagick@6 6.9.12-20 -> 6.9.12-21
elixir 1.12.2 -> 1.12.3
zimg 3.0.2 -> 3.0.3
imagemagick 7.1.0-5 -> 7.1.0-6
python@3.9 3.9.6 -> 3.9.7
==> Upgrading imagemagick@6
  6.9.12-20 -> 6.9.12-21

==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/6/manifests/6.9.12-
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/6/blobs/sha256:7487
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Pouring imagemagick@6--6.9.12-21.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/imagemagick@6/6.9.12-21: 770 files, 28MB
Removing: /usr/local/Cellar/imagemagick@6/6.9.12-20... (770 files, 28MB)
Removing: /Users/n1/Library/Caches/Homebrew/imagemagick@6--6.9.12-20... (9.2MB)
==> Upgrading pv
  1.6.6 -> 1.6.19

==> Downloading https://ghcr.io/v2/homebrew/core/pv/manifests/1.6.19
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pv/blobs/sha256:4ea237c542c6ede
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Pouring pv--1.6.19.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/pv/1.6.19: 5 files, 114.4KB
Removing: /usr/local/Cellar/pv/1.6.6... (5 files, 79.4KB)
==> Upgrading elixir
  1.12.2 -> 1.12.3

==> Downloading https://ghcr.io/v2/homebrew/core/elixir/manifests/1.12.3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/elixir/blobs/sha256:cefbc6925f5
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Pouring elixir--1.12.3.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/elixir/1.12.3: 434 files, 6.4MB
Removing: /usr/local/Cellar/elixir/1.12.2... (434 files, 6.4MB)
Removing: /Users/n1/Library/Caches/Homebrew/elixir--1.12.2... (4.6MB)
==> Upgrading zimg
  3.0.2 -> 3.0.3

==> Downloading https://ghcr.io/v2/homebrew/core/zimg/manifests/3.0.3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/zimg/blobs/sha256:ad43a31d0f773
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Pouring zimg--3.0.3.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/zimg/3.0.3: 27 files, 2.3MB
Removing: /usr/local/Cellar/zimg/3.0.2... (27 files, 2.2MB)
Removing: /Users/n1/Library/Caches/Homebrew/zimg--3.0.2... (681.6KB)
==> Upgrading imagemagick
  7.1.0-5 -> 7.1.0-6

==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/manifests/3.9.7
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:41d9904
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/manifests/7.1.0-6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:adffba
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Installing dependencies for imagemagick: python@3.9
==> Installing imagemagick dependency: python@3.9
==> Pouring python@3.9--3.9.7.big_sur.bottle.tar.gz
==> /usr/local/Cellar/python@3.9/3.9.7/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.7/bin/python3 -m pip install -v --no-deps --no-index --upgrade --isolated --target=/usr/local/lib/python3.9/site-packages /usr/local/Cellar/python@3.9/3.9.7/Frameworks
🍺  /usr/local/Cellar/python@3.9/3.9.7: 3,080 files, 54.7MB
==> Installing imagemagick
==> Pouring imagemagick--7.1.0-6.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/imagemagick/7.1.0-6: 799 files, 30.3MB
Removing: /usr/local/Cellar/imagemagick/7.1.0-5... (799 files, 30.3MB)
Removing: /Users/n1/Library/Caches/Homebrew/imagemagick--7.1.0-5... (10.2MB)
==> Upgrading python@3.9
  3.9.7 -> 3.9.7

Removing: /usr/local/Cellar/python@3.9/3.9.6... (3,157 files, 55.5MB)
Removing: /Users/n1/Library/Caches/Homebrew/python@3.9--3.9.6... (13.6MB)
➜  ~ brew upgrade --cask $(brew list --cask)
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 3 formulae.
```

### What happened (include all command output)?
```
==> Upgrading python@3.9
  3.9.7 -> 3.9.7
```

### What did you expect to happen?
```
==> Upgrading python@3.9
  3.9.6 -> 3.9.7
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
-
```

**Comment by n-bes** [comment] 2021-09-07 17:52
Seems like duplicate of https://github.com/Homebrew/brew/issues/11900

**Comment by carlocab** [comment] 2021-09-07 22:50
It is indeed a duplicate. Closing in favour of the other one.

**Closed by carlocab** 2021-09-07 22:50 UTC
Labels: bug

**Comment by carlocab** [comment] 2021-09-09 09:40
Duplicate of #11900
