### ISSUE TITLE
brew audit spurious error about “revision should not decrease”

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#10101] opened 2020-12-22 19:52 UTC
In this bottle build job for bdw-gc (https://github.com/Homebrew/homebrew-core/runs/1595745519?check_suite_focus=true):

```
==> brew audit bdw-gc --online --git --skip-style
==> FAILED
bdw-gc:
  * revision should not decrease (from 1 to 0)
Error: 1 problem in 1 formula detected
```

There is no change in revision here, so audit should not complain. This is blocking an ARM bottle from being built.

**Comment by dtrodrigues** [comment] 2020-12-22 20:23
The issue is coming from https://github.com/Homebrew/homebrew-core/pull/44735 where bdw-gc has both a revision bump commit and revision unbump commit. Since they both got merged into master, the audit is complaining that the revision decreased in https://github.com/Homebrew/homebrew-core/pull/44735/commits/c48ba172ad90255d1d5f508f8df56dfa81f1ebbf.

**Comment by fxcoudert** [comment] 2020-12-22 20:30
Well it's not actionable as an audit, is it? I don't see the point in preventing actual work being done now, because at some point in the past something happened.

**Comment by dtrodrigues** [comment] 2020-12-22 20:53
This audit in particular has existed for a while and I've made a few changes lately to clean up false positives, but it keeps popping up over and over again.  I know @MikeMcQuaid did the last major refactoring to audit -- I'm not sure what his current stance on it is.

Without a significant rewrite/rescoping or disabling of this audit, a short-term solution might be to bump this back to revision 1.

**Comment by iMichka** [comment] 2020-12-22 20:59
As removing revisions should never happen, I also agree that bumping this to revision 1 (it should even be 2 right now ...) is what should have happened.

**Comment by dtrodrigues** [comment] 2020-12-22 21:02
The bump and unbump happened within a single PR without a bottle for revision 1, so there hasn't been any negative impact. Since the current revision is 0, jumping to 2 will lead to
```
bdw-gc:
  * revisions should only increment by 1
Error: 1 problem in 1 formula detected
```
so it'd need to go to 1 first.

**Comment by MikeMcQuaid** [comment] 2020-12-23 09:09
I agree this should be fixed so that we're not showing audit failures like this unless it's within the relevant PR.

**Comment by MikeMcQuaid** [comment] 2020-12-23 09:09
I'm also fine with the `revision` being temporarily bumped to override this.

**Comment by MikeMcQuaid** [comment] 2021-02-26 11:04
This audit failure should never trigger unless the relevant formula `revision`/`version`/`version_scheme` has actually changed in the PR being tested.

**Comment by MikeMcQuaid** [comment] 2022-01-03 14:28
Closing this as no-one has complained for a while.

**Closed** 2022-01-03 14:28 UTC
Labels: bug, help wanted

**Comment by carlocab** [comment] 2022-01-03 15:41
This actually came up again while bottling for Monterey. It'll probably show up again for the next macOS version if not fixed before then.

I think the cause is different the times I saw, it though. AFAICT, `brew` is unable to parse formulae in the Git log with the old bottle blocks, so isn't able to use them as reference points for `revision` bumps. This causes the audit to mistakenly conclude that the `revision` decreased.

**Comment by MikeMcQuaid** [comment] 2022-01-03 15:44
@carlocab I'm kinda loathe to keep this open indefinitely given that no-one touched it for a year. Thoughts?

**Comment by carlocab** [comment] 2022-01-03 15:46
I'm fine with keeping it closed. Just leaving notes here in case someone picks this up again at some point.
