### ISSUE TITLE
brew cannot uninstall any casks because of an outdated formula

### ISSUE THREAD

**Issue by NightMachinery** [Homebrew/brew#13707] opened 2022-08-16 16:06 UTC
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.9-108-g5047d42
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5047d4249e938d448ce8c80641beb4d42e90dbad
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 293794f50909f1ace277aec636b57d72088a5aa3
Core tap last commit: 17 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 604800
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs.dash
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
http_proxy: http://127.0.0.1:1087
https_proxy: http://127.0.0.1:1087
no_proxy: 127.0.0.1,localhost
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 13.0.0 build 1300
Git: 2.33.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-x86_64
CLT: 13.0.0.0.1.1627064638
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.4.


Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  drip
  cmc
  python@2
  git-hooks
  osx-dictionary
  joplin
  wine
  llvm@5
  buck
  unrar
  phantomjs
  eta
  szip

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  antibody
  elinks
  fasd
  googler
  groovyserv
  httping
  libav
  ntfs-3g
  rsstail
  simple-mtpfs

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/evar/.cargo/bin/cargo-install-update-config
  /Users/evar/anaconda/bin/icu-config
  /Users/evar/anaconda/bin/freetype-config
  /Users/evar/anaconda/bin/libpng16-config
  /Users/evar/anaconda/bin/python3.7-config
  /Users/evar/anaconda/bin/libpng-config
  /Users/evar/anaconda/bin/xml2-config
  /Users/evar/anaconda/bin/python3.7m-config
  /Users/evar/anaconda/bin/python3-config
  /Users/evar/anaconda/bin/ncursesw6-config
  /Users/evar/anaconda/bin/pcre-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libQtShadowsocks.2.1.0.dylib
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/QtShadowsocks/crypto/chacha.h
  /usr/local/include/QtShadowsocks/crypto/cipher.h
  /usr/local/include/QtShadowsocks/crypto/encryptor.h
  /usr/local/include/QtShadowsocks/crypto/rc4.h
  /usr/local/include/QtShadowsocks/network/httpproxy.h
  /usr/local/include/QtShadowsocks/network/socketstream.h
  /usr/local/include/QtShadowsocks/network/tcprelay.h
  /usr/local/include/QtShadowsocks/network/tcprelayclient.h
  /usr/local/include/QtShadowsocks/network/tcprelayserver.h
  /usr/local/include/QtShadowsocks/network/tcpserver.h
  /usr/local/include/QtShadowsocks/network/udprelay.h
  /usr/local/include/QtShadowsocks/types/address.h
  /usr/local/include/QtShadowsocks/types/profile.h
  /usr/local/include/QtShadowsocks/util/addresstester.h
  /usr/local/include/QtShadowsocks/util/common.h
  /usr/local/include/QtShadowsocks/util/controller.h
  /usr/local/include/QtShadowsocks/util/export.h
  /usr/local/include/bicon/bconsole.h
  /usr/local/include/bicon/bconsole_ligature.h
  /usr/local/include/bicon/bconsole_log2con.h
  /usr/local/include/bicon/bjoining.h
  /usr/local/include/bicon/bjoining_charprop.h
  /usr/local/include/bicon/bjoining_compose.h
  /usr/local/include/bicon/bjoining_log2cuni.h
  /usr/local/include/bicon/bjoining_vis2cuni.h
  /usr/local/include/bicon/bjoining_ye.h
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/QtShadowsocks.pc

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  tag-ag
  docker
  python@2
  awk
  joplin
  minimal-racket
  wego
  lua
  speedtest-cli
  emacs-mac
  sshfs-mac
  emacs-plus@29
  rename
  python@3.10
  m-cli
  python@3.8
  jpeg-turbo

Warning: Some installed formulae are not readable:
  drip: Unsupported special dependency :java

  unravel: wrong number of arguments (given 1, expected 0)

  buck: Unsupported special dependency :java

  phantomjs: uninitialized constant #<Class:0x00007fcafdea7de0>::MinimumMacOSRequirement

  eta: wrong number of arguments (given 1, expected 0)

  let-alist: wrong number of arguments (given 1, expected 0)

  unxip: wrong number of arguments (given 1, expected 0)

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
   M Formula/sshfs.rb
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I can't uninstall any casks:

```
❯ brew remove emacs-plus@29                                                     
Error: Cask 'kite' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :lion
```

```
❯ brew remove kite
Error: Cask 'kite' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :lion
```

### What happened (include all command output)?

_

### What did you expect to happen?

I expected these casks to be removed from my machine.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I don't really know how to reproduce this.
```

**Comment by NightMachinery** [comment] 2022-08-16 16:12
BTW, I do know that this problem can probably be resolved by finding the tap from which this invalid formula comes and untapping it; but finding the tap is difficult. I think a better error message needs to be generated.

It would also be better to just skip problematic formulas rather exiting.

**Comment by apainintheneck** [comment] 2022-08-21 02:15
I think you diagnosed the problem pretty well. It seems like we should probably catch the invalid cask definition error inside of the uninstall process in certain circumstances.

I worked on something similar a few months ago where the same error was stopping people from reinstalling casks (see below) and we decided to just catch the error and default to the new cask definition. I'm not sure if that would work in this case because you're saying that there was no newer cask definition and you could only use the cached one to uninstall. Is that right?

Relevant Issue:
-  https://github.com/Homebrew/brew/issues/10833

**Comment by apainintheneck** [comment] 2022-08-21 02:20
Also, I assume the `--force` flag didn't work for you, right?

**Comment by apainintheneck** [comment] 2022-08-21 02:54
Actually, I think what might be happening here is that it's simply failing to [turn the named arguments into casks](https://github.com/Homebrew/brew/blob/93bf9e5ba2c9af5195ec5c1c6eca3a5f2484caba/Library/Homebrew/cmd/uninstall.rb#L48-L51) because the cask file is old and invalid and no newer cask file exists (it will default to a newer cask file if the old one is invalid).

**Comment by apainintheneck** [comment] 2022-09-03 02:49
@amit-srt I would be happy to assign this to you but I'm not sure how this should be approached or if it's something we want to fix anyway. Normally we put `Help Wanted` labels on issues that we want to be worked on and you can just grab one of those without asking to assigned to it.

I think the thing here is that assuming I'm correct and that the issue is inside the parser (specifically the [named_args.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cli/named_args.rb) file when casks get loaded for the first time) I'm not sure we want to fix this. Essentially, the parser is used for every sub-command and it's a nice feature that it validates cask and formula definitions before loading them. Creating an exception where an invalid cask or formula could be loaded seems like it could be a dangerous thing to do. If it is invalid enough, it might cause other errors during uninstall for example.

We could, in theory, add something to the parser that ignores this specific `invalid "depends_on macOS"` error and only use it for special cases like `brew uninstall` but even then I'm a bit hesitant. How do you think we should approach this?

**Comment by fergusmeiklejohn** [comment] 2022-11-01 04:58
I was about to open a new issue but I wonder if it would be better to add it here: Homebrew won't install or upgrade packages because I don't have a version of xCode installed that is not yet released. HB wants 14.1 and errors on upgrading packages but apple have only released 14.0.1 (14.1 is only RC)
![image](https://user-images.githubusercontent.com/11864025/199161842-e4b88a01-a47b-4cc9-bcd6-251661a55120.png)

**Comment by MikeMcQuaid** [comment] 2023-07-18 10:02
Closing this out as we've not seen movement or repeated reports this year.

**Closed by MikeMcQuaid** 2023-07-18 10:02 UTC
Labels: bug, help wanted

**Comment by NightMachinery** [comment] 2023-07-20 17:23
@apainintheneck I don't really remember this issue anymore.
