### ISSUE TITLE
brew leaves lists formulaes which are dependencies of installed packages

### ISSUE THREAD

**Issue by raszi** [Homebrew/brew#3100] opened 2017-08-28 20:54 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

# Outputs

## brew doctor

```
~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

This is fine I am using fish.

## brew config

```
~ $ brew config
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 420482004c6f5f43e6f1c25bc00a53900ecd9ce7
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.14.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92
macOS: 10.12.4-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

# Actual

```
~ $ brew leaves
fish
git
grc
htop
httpie
jq
mobile-shell
planck
python3
ripgrep
tig
~ $ brew uses --installed python3
grc                                                                 httpie
```

# Expected

The list should not contain `python3`.

**Comment by DomT4** [comment] 2017-08-29 03:41
This is a problem with requirements in general. Presumably `leaves` is not resolving the requirement to the `default_formula` and thus the `default_formula` ends up being declared unnecessary even though that is what is fulfilling said requirement.

**Comment by raszi** [comment] 2017-09-19 07:49
Hey, this should not be closed it is a valid issue and needs a fix.

**Comment by MikeMcQuaid** [comment] 2017-09-19 08:33
@raszi If no-one is working on it eventually it will be closed, sorry.

**Comment by raszi** [comment] 2017-09-19 10:13
Why is that a good practice? You'll be loosing valid reports.

**Comment by MikeMcQuaid** [comment] 2017-09-19 17:51
@raszi Otherwise our issue tracker fills up with things that are unlikely to ever be fixed and it makes the issue tracker hard to use.

**Comment by fjarlq** [comment] 2017-09-28 01:26
I just noticed my `brew leaves` is reporting two installed packages that `brew remove` won't remove due to dependencies that `brew leaves` is apparently unaware of:

```
$ brew leaves | egrep 'shared-mime-info|xmlto'
shared-mime-info
xmlto
$ brew remove shared-mime-info
Error: Refusing to uninstall /usr/local/Cellar/shared-mime-info/1.9
because it is required by gtk+ 2.24.31_1, librsvg 2.40.18, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies shared-mime-info
$ brew remove xmlto
Error: Refusing to uninstall /usr/local/Cellar/xmlto/0.0.28
because it is required by tig 2.2.2, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies xmlto
```

I don't understand the `shared-mime-info` dependency. I can't see it when examining the formulas for `gtk+` and `librsvg`, which are indeed installed on my system.

I think I do understand the `xmlto` issue: the formula for `tig` only `depends_on "xmlto"` when the `--with-docs` option is specified at install time. Does this mean `brew leaves` isn't considering installation options when determining dependencies?

**Comment by maxim-belkin** [comment] 2017-10-12 14:47
Is there a reproducible test case?

**Comment by ilovezfs** [comment] 2017-10-12 15:07
This is actually just a duplicate of https://github.com/Homebrew/homebrew-core/issues/18353. See https://github.com/Homebrew/homebrew-core/issues/18353#issuecomment-332797114 for the pseudo solution.

Basically whenever there's a discrepancy between the bottle and the formula things don't make sense until you look more closely and notice it's just following what's in the receipt for the installed bottle as opposed to what's in the formula (which is what leaves is looking at).

**Comment by maxim-belkin** [comment] 2017-10-12 15:11
should leaves look at receipts for formulae that were installed from bottles?

**Comment by ilovezfs** [comment] 2017-10-12 15:17
`brew leaves` as a command existed long before the new-ish `brew remove` code that @alyssais added that is aware of INSTALL_RECEIPTs. I'm not totally convinced it's actually useful to rewrite leaves to be aware of INSTALL_RECEIPTs (it basically becomes some other command at that point) but there's no reason in principle it couldn't be.

**Comment by Paalon** [comment] 2017-10-19 21:08
I don't know so much about the mechanism of homebrew but I encountered this and I feel this is not useful.

**Comment by maxim-belkin** [comment] 2017-10-19 21:09
> [Is there a reproducible test case?](https://github.com/Homebrew/brew/issues/3100#issuecomment-336160342)

**Comment by Paalon** [comment] 2017-10-19 21:13
I installed R.
`$ brew install r
$ brew leaves
r
gcc`
`gcc` is not leave. I encountered this.

**Comment by maxim-belkin** [comment] 2017-10-19 21:27
`r` formula references `gcc` but does not explicitly declare it as a dependency:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/r.rb#L97

_you can use triple backticks (<code>```</code>) for blocks of code_

**Comment by DomT4** [comment] 2017-10-19 21:43
> Is there a reproducible test case?

Anything with an unconditional `:python`, I suspect. Or just anything with `:python3` in general. Do something like `brew install vim` which mandates Homebrew's `python` by default, and then run `brew leaves | grep python` and 🎉.

**Comment by maxim-belkin** [comment] 2017-10-19 21:49
@DomT4 Thank you!

@sjackman: should some of the steps from `def install` in `r` be moved to `post_install`?

**Comment by sjackman** [comment] 2017-10-19 22:33
> @sjackman: should some of the steps from `def install` in `r` be moved to `post_install`?

Which steps?

**Comment by maxim-belkin** [comment] 2017-10-23 21:50
@sjackman I thought some of the steps after `make install` could be moved to `post_install` but that is probably not the case. `gcc` dependency is brought in by Fortran requirement, not by the use of `Formula["gcc"]` within the formula.

**Closed** 2017-10-24 09:28 UTC
Labels: help wanted
