### ISSUE TITLE
SSL error when downloading from homebrew.bintray.com

### ISSUE THREAD

**Issue by wagnerand** [Homebrew/brew#10739] opened 2021-02-28 15:11 UTC
**`brew config` output**

```
HOMEBREW_VERSION: 3.0.2-112-g236c622
ORIGIN: https://github.com/Homebrew/brew
HEAD: 236c622b201fc00c36d7cf89d38ecb95db148c1c
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2eac3c31694fe4a1a4a4ee69d32215eddb949b16
Core tap last commit: 43 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

**`brew doctor` output**

```
Your system is ready to brew.
```

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

`brew upgrade`

**What happened (include all command output)?**

```
% brew upgrade -v
==> Upgrading 4 outdated packages:
boost 1.75.0_1 -> 1.75.0_2
icu4c 67.1 -> 68.2
harfbuzz 2.7.4 -> 2.7.4_1
node 15.10.0 -> 15.10.0_1
==> Upgrading icu4c 67.1 -> 68.2
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2-112-g236c622\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.2.2\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2-112-g236c622\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.2.2\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2-112-g236c622\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.2.2\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/andreas/Library/Caches/Homebrew/downloads/9f189274160b8c0c4884e1b43cd8fb135852a035496379bf9dc447028120d8da--icu4c-68.2.big_sur.bottle.tar.gz.incomplete https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "icu4c"
Download failed: https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
==> Upgrading boost 1.75.0_1 -> 1.75.0_2
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2-112-g236c622\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.2.2\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2-112-g236c622\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.2.2\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2-112-g236c622\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.2.2\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/andreas/Library/Caches/Homebrew/downloads/9f189274160b8c0c4884e1b43cd8fb135852a035496379bf9dc447028120d8da--icu4c-68.2.big_sur.bottle.tar.gz.incomplete https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "icu4c"
Download failed: https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
```

[...same for other packages...]

**What did you expect to happen?**

Upgrade completes successfully

**Step-by-step reproduction instructions (by running `brew` commands)**

Run `brew upgrade -v`, see above.

**Comment by pridkett** [comment] 2021-02-28 15:15
Confirm the same problem on MacOS 10.15.7. ISP is Spectrum as sometimes that has something to do with it too.

```
$ brew config
HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2eac3c31694fe4a1a4a4ee69d32215eddb949b16
Core tap last commit: 51 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.xCfFz0deER/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 11.0 build 1100
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 11.0.33.17
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

**Comment by DrDonk** [comment] 2021-02-28 15:18
I can also confirm there is an issue as I cannot install any packages with brew on 11.2.1 with the same error.

```
HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2eac3c31694fe4a1a4a4ee69d32215eddb949b16
Core tap last commit: 54 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: N/A
Xcode: 12.4
```

**Comment by Bo98** [comment] 2021-02-28 15:22
> Despite that, [the bintray status page says everything is fine](https://status.bintray.com/).

Could possibly be CDN related (Bintray use AWS Cloudfront). It is working fine for me in the UK.

**Comment by the-dr-lazy** [comment] 2021-02-28 15:23
Same issue on GitHub actions.

```bash
brew install libjwt
/bin/bash --noprofile --norc -eo pipefail /tmp/knicknic/os-specific-run/412a92a6-9412-4c03-b5b4-b63794aa3deb
==> Downloading https://homebrew.bintray.com/bottles/jansson-2.13.1.catalina.bottle.tar.gz
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "jansson"
Download failed: https://homebrew.bintray.com/bottles/jansson-2.13.1.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://digip.org/jansson/releases/jansson-2.13.1.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/libjwt-1.12.1.catalina.bottle.tar.gz
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "libjwt"
Download failed: https://homebrew.bintray.com/bottles/libjwt-1.12.1.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://homebrew.bintray.com/bottles/automake-1.16.3.catalina.bottle.tar.gz
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "automake"
Download failed: https://homebrew.bintray.com/bottles/automake-1.16.3.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://git.savannah.gnu.org/cgit/config.git/snapshot/config-0b5188819ba6091770064adf26360b204113317e.tar.gz
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.savannah.gnu.org:443 
Error: Failed to download resource "automake--config"
Download failed: https://git.savannah.gnu.org/cgit/config.git/snapshot/config-0b5188819ba6091770064adf26360b204113317e.tar.gz
Error: The process '/bin/bash' failed with exit code 1
```

**Comment by omnicr0n** [comment] 2021-02-28 15:29
I'm getting the same. Running macOS Catalina 10.15.7:
Homebrew 3.0.2
Homebrew/homebrew-core (git revision 6a059e; last commit 2021-02-28)
Homebrew/homebrew-cask (git revision 7678095; last commit 2021-02-28)

```
==> Upgrading icu4c 67.1 -> 68.2
==> Downloading https://homebrew.bintray.com/bottles/icu4c-68.2.catalina.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "icu4c"
Download failed: https://homebrew.bintray.com/bottles/icu4c-68.2.catalina.bottle.tar.gz
==> Upgrading python@3.8 3.8.8 -> 3.8.8_1
==> Downloading https://homebrew.bintray.com/bottles/python%403.8-3.8.8_1.catalina.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "python@3.8"
Download failed: https://homebrew.bintray.com/bottles/python%403.8-3.8.8_1.catalina.bottle.tar.gz
==> Upgrading boost 1.75.0_1 -> 1.75.0_2
==> Downloading https://homebrew.bintray.com/bottles/icu4c-68.2.catalina.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "icu4c"
Download failed: https://homebrew.bintray.com/bottles/icu4c-68.2.catalina.bottle.tar.gz
==> Upgrading harfbuzz 2.7.4 -> 2.7.4_1
==> Downloading https://homebrew.bintray.com/bottles/libpthread-stubs-0.4.catalina.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "libpthread-stubs"
Download failed: https://homebrew.bintray.com/bottles/libpthread-stubs-0.4.catalina.bottle.tar.gz
==> Upgrading cairo 1.16.0_4 -> 1.16.0_5
==> Downloading https://homebrew.bintray.com/bottles/libpthread-stubs-0.4.catalina.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "libpthread-stubs"
Download failed: https://homebrew.bintray.com/bottles/libpthread-stubs-0.4.catalina.bottle.tar.gz
==> Upgrading node 15.10.0 -> 15.10.0_1
==> Downloading https://homebrew.bintray.com/bottles/icu4c-68.2.catalina.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "icu4c"
Download failed: https://homebrew.bintray.com/bottles/icu4c-68.2.catalina.bottle.tar.gz
```

**Comment by carlocab** [comment] 2021-02-28 15:30
Same error [on Homebrew CI](https://github.com/Homebrew/homebrew-core/pull/72162/checks?check_run_id=1998620814#step:7:76).

**Comment by ModdedGamers** [comment] 2021-02-28 15:35
Confirming this issue on macOS Mojave 10.14.2,
Homebrew 3.0.2
Homebrew/homebrew-core (git revision 6a059e; last commit 2021-02-28)
Homebrew/homebrew-cask (git revision 7678095; last commit 2021-02-28)

```
==> Upgrading 1 outdated package:
python@3.9 3.9.1_8 -> 3.9.2_1
==> Upgrading python@3.9 3.9.1_8 -> 3.9.2_1
==> Downloading https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "mpdecimal"
Download failed: https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
```

**Comment by ekinnee** [comment] 2021-02-28 15:37
Does it have anything to do with this? https://github.com/Homebrew/discussions/discussions/691

**Comment by Bo98** [comment] 2021-02-28 15:38
No, that happens in May. This is just an outage - and seemingly one only affecting certain regions.

**Comment by ekinnee** [comment] 2021-02-28 15:39
Also, if you NEED to upgrade you can build from source.

**Comment by ModdedGamers** [comment] 2021-02-28 15:39
US East coaster here, it seems to be working again.

**Comment by unikitty37** [comment] 2021-02-28 15:42
Still failing here:

macOS 10.14.6 (18G8022)
Homebrew 3.0.2
Homebrew/homebrew-core (git revision 6a059e; last commit 2021-02-28)
Homebrew/homebrew-cask (git revision 7678095; last commit 2021-02-28)

```
└─▷ brew upgrade -v ansible
==> Upgrading 1 outdated package:
ansible 2.10.7 -> 3.0.0
==> Upgrading ansible 2.10.7 -> 3.0.0
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/user/Library/Caches/Homebrew/downloads/81f5f82c87fb624c3581143afc1f1aa78f8fecab90f98f001df6dd552841e380--mpdecimal-2.5.1.mojave.bottle.tar.gz.incomplete https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "mpdecimal"
Download failed: https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
```

I don't suppose Homebrew has an option for ignoring SSL errors?

**Comment by ModdedGamers** [comment] 2021-02-28 15:43
It seems to be a server-side cert error, so I don't think a local toggle will help.

**Comment by ekinnee** [comment] 2021-02-28 15:43
> Still failing here (UK):
> 
> macOS 10.14.6 (18G8022)
> Homebrew 3.0.2
> Homebrew/homebrew-core (git revision 6a059e; last commit 2021-02-28)
> Homebrew/homebrew-cask (git revision 7678095; last commit 2021-02-28)
> 
> ```
> └─▷ brew upgrade -v ansible
> ==> Upgrading 1 outdated package:
> ansible 2.10.7 -> 3.0.0
> ==> Upgrading ansible 2.10.7 -> 3.0.0
> /usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
> ==> Downloading https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
> /usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
> /usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/user/Library/Caches/Homebrew/downloads/81f5f82c87fb624c3581143afc1f1aa78f8fecab90f98f001df6dd552841e380--mpdecimal-2.5.1.mojave.bottle.tar.gz.incomplete https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
> Error: Failed to download resource "mpdecimal"
> Download failed: https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.mojave.bottle.tar.gz
> ```
> 
> I don't suppose Homebrew has an option for ignoring SSL errors?

I think there is, but the Bintray site itself is unreachable for me in North Central Texas, not just the SSL side.

**Comment by wagnerand** [comment] 2021-02-28 15:45
> I don't suppose Homebrew has an option for ignoring SSL errors?

Personally, I'd rather wait for the issue to be resolved than to ignore the security provided by SSL.

**Comment by vincentbernat** [comment] 2021-02-28 15:48
The remote end is not speaking SSL: it's speaking in plain text. Check http://homebrew.bintray.com:443/ with a browser.

**Comment by fluffy** [comment] 2021-02-28 15:48
This seems to be more the CDN can't connect to the server. If you do just go to http://homebrew.bintray.com/ (no https) with a browser, you will get an error from the CDN of 

403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: 6DYVF26w8y8gGxPhclHORfebbB4aehGPr1rGG7eLRqzsCvjO8QD75Q==

**Comment by EmreYYZ** [comment] 2021-02-28 16:00
Same issue.

Trying to do:
`brew install nettle`

`brew config` result:

`HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6a059e9f7322a3069abbcd9ca1099806beab213a
Core tap last commit: 42 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false`

`brew doctor` result:
`Your system is ready to brew.`

`brew install nettle` output:
`==> Downloading https://homebrew.bintray.com/bottles/nettle-3.7.1.arm64_big_sur.

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "nettle"
Download failed: https://homebrew.bintray.com/bottles/nettle-3.7.1.arm64_big_sur.bottle.tar.gz`

**Comment by gmkey** [comment] 2021-02-28 16:04
https://github.com/Homebrew/discussions/discussions/962

**Comment by retokromer** [comment] 2021-02-28 16:09
Same in Switzerland:
```
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

**Comment by neverfox** [comment] 2021-02-28 16:10
Same in NC USA. Not sure if it's related but I had run a brew upgrade just prior to outage and openssl 1.1.1j was poured in that update.

**Comment by shinoshu** [comment] 2021-02-28 16:12
+1

**Comment by riasat-pathlit** [comment] 2021-02-28 16:13
Singapore (possibly region) is affected as well since 2330-ish

**Comment by kapitainsky** [comment] 2021-02-28 16:15
in UK all worked yesterday but does not today.  openssl 1.1.1j was updated on 19th of Feb - so do not think it is related.

**Comment by lucacasonato** [comment] 2021-02-28 16:15
Responding to this issue with "Me too!" without any additional context is not useful. Please use the 👍 button on the original message (and the subscribe button if you want to be notified about comments) unless you have something meaningful to add that could help in fixing this issue.

**Comment by ayypril** [comment] 2021-02-28 16:18
> The remote end is not speaking SSL: it's speaking in plain text. Check http://homebrew.bintray.com:443/ with a browser.

This is CloudFront's normal behavior if you send a HTTP request to the HTTPS port. Try with "http://aws.amazon.com:443" for the same behavior.

**Comment by fran2a** [comment] 2021-02-28 16:27
same problem in France. ISP Orange.

**Comment by ayypril** [comment] 2021-02-28 16:32
As a temporary workaround, I've found adding this to your /etc/hosts works:
`54.188.157.32 homebrew.bintray.com`

It looks like the bintray subdomains are all now CNAMEs to `jfrog.com` without valid certificates, so CloudFront drops the connection. This IP is one that was found on a bintray.com subdomain a few days ago:
![image](https://user-images.githubusercontent.com/51252578/109425888-2e203600-79b0-11eb-8cbc-0a143b884a1f.png)
![image](https://user-images.githubusercontent.com/51252578/109425914-48f2aa80-79b0-11eb-97e4-4f3ce74172a6.png)

**Comment by JQ555888** [comment] 2021-02-28 16:34
Was working 20 minutes ago from these ISPs: Azure (Microsoft), AWS, Janet University Network (UK), Vultr but suddenly none of these work and then eventually found this thread.

**Comment by arsenieciprian** [comment] 2021-02-28 16:36
Same here . Romania

**Comment by AbuzerAsif** [comment] 2021-02-28 16:37
Facing the issue here, Its not working...

Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.big_su
#=#=#                                                                         
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "openssl@1.1"

**Comment by pheiduck** [comment] 2021-02-28 16:44
same here trying to install clamav
```
$ brew install clamav
==> Downloading https://homebrew.bintray.com/bottles/json-c-0.15.catalina.bottle.tar.gz
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "json-c"
Download failed: https://homebrew.bintray.com/bottles/json-c-0.15.catalina.bottle.tar.gz
```

**Comment by JQ555888** [comment] 2021-02-28 16:50
> Was working 20 minutes ago from these ISPs through a VPN: Azure (US West), AWS (Korea), Janet University Network (UK), Vultr (Japan) but suddenly none of these work and then eventually found this thread.
> 
> Thought it may be useful to add: also tried requesting with different user-agents: curl, chrome, firefox, safari; tried curl with -k ie. ignore certificate errors; tried http to remove ssl entirely, none of these work.

As another workaround, if you're in a hurry like I am and don't have root, other than manually overriding routing policies through /etc/hosts, consider switching to Procursus (packages hosted on GitHub) or MacPorts (using a different delivery system). These are actively maintained and generally more stable.

**Comment by Bo98** [comment] 2021-02-28 16:51
As a workaround, you may temporarily use `HOMEBREW_BOTTLE_DOMAIN=https://dl.bintray.com/homebrew` (don't do this permanently or you'll have issues when we switch over from Bintray in the coming weeks)

**Comment by KevinVitale** [comment] 2021-02-28 16:51
Having the same issue:
```
==> Upgrading openssl@1.1 1.1.1i -> 1.1.1j 
==> Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.catalina.bottle.tar.gz

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "openssl@1.1"
Download failed: https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1j.catalina.bottle.tar.gz
```

**Comment by brunaschneiders** [comment] 2021-02-28 17:05
> As a workaround, you may temporarily use `HOMEBREW_BOTTLE_DOMAIN=https://dl.bintray.com/homebrew` (don't do this permanently or you'll have issues when we switch over from Bintray in the coming weeks)

Hi, how can I do that?

**Comment by JQ555888** [comment] 2021-02-28 17:06
> HOMEBREW_BOTTLE_DOMAIN=https://dl.bintray.com/homebrew

export HOMEBREW_BOTTLE_DOMAIN=https://dl.bintray.com/homebrew

**Comment by sfuerte** [comment] 2021-02-28 17:07
> > The remote end is not speaking SSL: it's speaking in plain text. Check http://homebrew.bintray.com:443/ with a browser.
> 
> This is CloudFront's normal behavior if you send a HTTP request to the HTTPS port. Try with "http://aws.amazon.com:443" for the same behavior (in cURL, in a browser it may automatically upgrade you to HTTPS through HSTS).

@ayypril, while it's a normal behaviour but it work when an endpoint recognizes and serves both HTTP & HTTPS. In this case it looks like due to misconfiguration HTTPS  has been disabled and only HTTP is enabled at the moment. 

Here was a very similar issue - https://github.com/kubernetes/ingress-nginx/issues/3556

**Comment by sfuerte** [comment] 2021-02-28 17:08
> > Hi, how can I do that?
> 
> export HOMEBREW_BOTTLE_DOMAIN=https://dl.bintray.com/homebrew

or inline
```
HOMEBREW_BOTTLE_DOMAIN=https://dl.bintray.com/homebrew brew upgrade
```

**Comment by PassionPenguin** [comment] 2021-02-28 17:38
# CHINESE USER's WORKAROUND

Well if you are using Tuna (Like many other developers in China), you can use the bottles from tsinghua university or other mirrors:

https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/

```zsh
if [[ "$(uname -s)" == "Linux" ]]; then BREW_TYPE="linuxbrew"; else BREW_TYPE="homebrew"; fi
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/${BREW_TYPE}-core.git"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/${BREW_TYPE}-bottles"
```

=>

```
penguin@Penguins-MacBook-Pro ~ % brew install openssl                  
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles/op
######################################################################## 100.0%
==> Pouring openssl@1.1-1.1.1j.big_sur.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1j: 8,071 files, 18.5MB
Removing: /usr/local/Cellar/openssl@1.1/1.1.1g... (8,059 files, 18MB)
Removing: /usr/local/Cellar/openssl@1.1/1.1.1h... (8,067 files, 18.5MB)
Removing: /Users/penguin/Library/Caches/Homebrew/openssl@1.1--1.1.1i.big_sur.bottle.tar.gz... (5.4MB)
```

**Comment by jsbobatea** [comment] 2021-02-28 17:54
Glad I found this, reinstalled brew and all. Now I know it's just not me. US-West (California).

**Comment by vijayhardaha** [comment] 2021-02-28 17:59
Same Issue.

```
❯ brew upgrade icu4c
Updating Homebrew...
==> Upgrading 1 outdated package:
icu4c 67.1 -> 68.2
==> Upgrading icu4c 67.1 -> 68.2
==> Downloading https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.t

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "icu4c"
Download failed: https://homebrew.bintray.com/bottles/icu4c-68.2.big_sur.bottle.tar.gz
```

**Comment by bglezseoane** [comment] 2021-02-28 18:28
> > Despite that, [the bintray status page says everything is fine](https://status.bintray.com/).
> 
> Could possibly be CDN related (Bintray use AWS Cloudfront). It is working fine for me in the UK.

Changing VPN location to UK solves issue for me. Before I was connected to a server in Spain and I got this error.

**Comment by amingilani** [comment] 2021-02-28 18:30
As a **temporary** workaround, I've been using the Nix package manager to [search](https://search.nixos.org/packages) and install packages.

**Comment by ljharb** [comment] 2021-02-28 18:33
The env var workaround doesn’t seem to be working for nvm: https://github.com/ljharb/nvm/runs/1999125389

**Comment by Bo98** [comment] 2021-02-28 18:35
For Linux, the URL should contain `linuxbrew` instead of `homebrew`.

I'm hearing reports that this is starting to work for people (just as I was considering releasing a workaround update!). Does it work for anyone now?

**Comment by ayypril** [comment] 2021-02-28 18:38
@Bo98 It does indeed look like Bintray's fixed their DNS. Works for me without any workaround now.
```
;; ANSWER SECTION:
homebrew.bintray.com.	59	IN	CNAME	dl.bintray.com.
dl.bintray.com.		59	IN	A	54.68.82.35
dl.bintray.com.		59	IN	A	52.27.102.247
dl.bintray.com.		59	IN	A	52.41.162.188
dl.bintray.com.		59	IN	A	52.24.200.146
dl.bintray.com.		59	IN	A	52.32.87.245
dl.bintray.com.		59	IN	A	44.239.142.179
dl.bintray.com.		59	IN	A	44.229.253.11
dl.bintray.com.		59	IN	A	52.36.31.250
```

**Comment by ljharb** [comment] 2021-02-28 18:44
Confirmed; it seems to be fixed.

**Comment by dtrodrigues** [comment] 2021-02-28 20:14
Closing as the Bintray issue is now resolved.

**Closed by dtrodrigues** 2021-02-28 20:14 UTC
Labels: bug
