### ISSUE TITLE
rubocop: Investigate setting `EnabledByDefault` and fixing sensible cops

### ISSUE THREAD

**Issue by issyl0** [Homebrew/brew#15297] opened 2023-04-23 22:44 UTC
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Suggested in https://github.com/Homebrew/brew/pull/15265#issuecomment-1516750224, we should investigate RuboCop's [`EnabledByDefault` config](https://docs.rubocop.org/rubocop/configuration.html#enabled) to see if there are cops that we're not aware of that would be good for us.

Currently (2023-04-23) setting `EnabledByDefault` on everything reveals `1170 files inspected, 42077 offenses detected, 21649 offenses autocorrectable`, which is loads and far too huge to be doable.

Expand the categories below for a breakdown of what specific cops there are, docs links to learn more about them, and how many offenses show up.

<details>
<summary>`Bundler` cops with offenses</summary>

| Cop Name | Number of Offenses | Notes |
|---|---|---|
| [Bundler/GemComment](https://docs.rubocop.org/rubocop/cops_bundler.html#bundlergemcomment) | 34 | | 
| [Bundler/GemVersion](https://docs.rubocop.org/rubocop/cops_bundler.html#bundlergemversion) | 36 | | 

</details>

<details>
<summary>`Layout` cops with offenses</summary>

| Cop Name | Number of Offenses | Notes |
|---|---|---|
| [Layout/ClassStructure](https://docs.rubocop.org/rubocop/cops_layout.html#layoutclassstructure) | 77 | | 
| [Layout/EmptyLineAfterMultilineCondition](https://docs.rubocop.org/rubocop/cops_layout.html#layoutemptylineaftermultilinecondition) | 103 | | 
| [Layout/FirstArrayElementLineBreak](https://docs.rubocop.org/rubocop/cops_layout.html#layoutfirstarrayelementlinebreak) | 133 | | 
| [Layout/FirstHashElementLineBreak](https://docs.rubocop.org/rubocop/cops_layout.html#layoutfirsthashelementlinebreak) | 12 | | 
| [Layout/FirstMethodArgumentLineBreak](https://docs.rubocop.org/rubocop/cops_layout.html#layoutfirstmethodargumentlinebreak) | 266 | | 
| [Layout/FirstMethodParameterLineBreak](https://docs.rubocop.org/rubocop/cops_layout.html#layoutfirstmethodparameterlinebreak) | 27 | | 
| [Layout/MultilineArrayLineBreaks](https://docs.rubocop.org/rubocop/cops_layout.html#layoutmultilinearraylinebreaks) | 455 | | 
| [Layout/MultilineAssignmentLayout](https://docs.rubocop.org/rubocop/cops_layout.html#layoutmultilineassignmentlayout) | 797 | | 
| [Layout/MultilineHashKeyLineBreaks](https://docs.rubocop.org/rubocop/cops_layout.html#layoutmultilinehashkeylinebreaks) | 4 | | 
| [Layout/MultilineMethodArgumentLineBreaks](https://docs.rubocop.org/rubocop/cops_layout.html#layoutmultilinemethodargumentlinebreaks) | 765 | | 
| [Layout/MultilineMethodParameterLineBreaks](https://docs.rubocop.org/rubocop/cops_layout.html#layoutmultilinemethodparameterlinebreaks) | 109 | | 
| [Layout/RedundantLineBreak](https://docs.rubocop.org/rubocop/cops_layout.html#layoutredundantlinebreak) | 821 | | 
| [Layout/SingleLineBlockChain](https://docs.rubocop.org/rubocop/cops_layout.html#layoutsinglelineblockchain) | 272 | | 

</details>

<details>
<summary>`Lint` cops with offenses</summary>

| Cop Name | Number of Offenses | Notes |
|---|---|---|
| [Lint/ConstantResolution](https://docs.rubocop.org/rubocop/cops_lint.html#Lintconstantresolution) | 16476 | | 
| [Lint/NumberConversion](https://docs.rubocop.org/rubocop/cops_lint.html#lintnumberconversion) | 97 | | 
| [Lint/RescueException](https://docs.rubocop.org/rubocop/cops_lint.html#lintrescueexception) | 23 | |
</details>

<details>
<summary>`Style` cops with offenses</summary>

| Cop Name | Number of Offenses | Notes |
|---|---|---|
| [Style/ArrayCoercion](https://docs.rubocop.org/rubocop/cops_style.html#stylearraycoercion) | 3 | | 
| [Style/AsciiComments](https://docs.rubocop.org/rubocop/cops_style.html#styleasciicomments) | 4 | | 
| [Style/CaseEquality](https://docs.rubocop.org/rubocop/cops_style.html#stylecaseequality) | 3 | | 
| [Style/ClassMethodsDefinitions](https://docs.rubocop.org/rubocop/cops_style.html#styleclassmethodsdefinitions) | 28 | | 
| [Style/ConstantVisibility](https://docs.rubocop.org/rubocop/cops_style.html#styleconstantvisibility) | 363 | | 
| [Style/DateTime](https://docs.rubocop.org/rubocop/cops_style.html#styledatetime) | 15 | | 
| [Style/DocumentationMethod](https://docs.rubocop.org/rubocop/cops_style.html#styledocumentationmethod) | 70 | | 
| [Style/ImplicitRuntimeError](https://docs.rubocop.org/rubocop/cops_style.html#styleimplicitruntimeerror) | 96 | | 
| [Style/InlineComment](https://docs.rubocop.org/rubocop/cops_style.html#styleinlinecomment) | 182 | | 
| [Style/InvertibleUnlessCondition](https://docs.rubocop.org/rubocop/cops_style.html#styleinvertibleunlesscondition) | 20 | https://github.com/Homebrew/brew/pull/15265 | 
| [Style/IpAddresses](https://docs.rubocop.org/rubocop/cops_style.html#styleipaddresses) | 7 | | 
| [Style/MethodCallWithArgsParentheses](https://docs.rubocop.org/rubocop/cops_style.html#stylemethodcallwithargsparentheses) | 11732 | | 
| [Style/MethodCalledOnDoEndBlock](https://docs.rubocop.org/rubocop/cops_style.html#stylemethodcalledondoendblock) | 304 | | 
| [Style/MissingElse](https://docs.rubocop.org/rubocop/cops_style.html#stylemissingelse) | 1076 | | 
| [Style/MultilineMethodSignature](https://docs.rubocop.org/rubocop/cops_style.html#stylemultilinemethodsignature) | 1 | | 
| [Style/OptionHash](https://docs.rubocop.org/rubocop/cops_style.html#styleoptionhash) | 15 | | 
| [Style/RequireOrder](https://docs.rubocop.org/rubocop/cops_style.html#stylerequireorder) | 353 | | 
| [Style/Send](https://docs.rubocop.org/rubocop/cops_style.html#stylesend) | 89 | | 
| [Style/SingleLineBlockParams](https://docs.rubocop.org/rubocop/cops_style.html#stylesinglelineblockparams) | 1 | | 
| [Style/StaticClass](https://docs.rubocop.org/rubocop/cops_style.html#stylestaticclass) | 6 | | 
| [Style/StringHashKeys](https://docs.rubocop.org/rubocop/cops_style.html#stylestringhashkeys) | 953 | | 
| [Style/TopLevelMethodDefinition](https://docs.rubocop.org/rubocop/cops_style.html#styletoplevelmethoddefinition) | 7 | | 
| [Style/TrailingCommaInBlockArgs](https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainblockargs) | 3 | | 
| [Style/YodaExpression](https://docs.rubocop.org/rubocop/cops_style.html#styleyodaexpression) | 14 | | 

</details>

<details>
<summary>Generator shell script</summary>

```bash
categories=(Bundler Gemspec Layout Lint Metrics Migration Naming Security Style)
for category in "${categories[@]}"
do
  brew style --only="${category}" | awk -F"${category}/" '{ print $2 }' | awk -F':' '{ print $1 }' | sort > sorted_"${category}"_offense_names
  cat sorted_"${category}"_offense_names | uniq > uniq_"${category}"_offense_names
  echo "| Cop Name | Number of Offenses | Notes |"
  echo "|---|---|---|"
  for cop in $(cat uniq_"${category}"_offense_names)
  do
    number=$(grep -c "${cop}" sorted_"${category}"_offense_names)
    lowercase_category=$(echo "${category}" | tr '[:upper:]' '[:lower:]')
    lowercase_cop=$(echo "${cop}" | tr '[:upper:]' '[:lower:]')
    url="https://docs.rubocop.org/rubocop/cops_${lowercase_category}.html#${lowercase_category}${lowercase_cop}"
    echo "| [${category}/${cop}](${url}) | ${number} | | "
  done
done
```
</details>

### What is the motivation for the feature?

It was suggested in https://github.com/Homebrew/brew/pull/15265#issuecomment-1516750224. Better code, in theory.

### How will the feature be relevant to at least 90% of Homebrew users?

It won't be. It might not even be a reasonable thing to start fixing.

### What alternatives to the feature have been considered?

Not doing it.

**Comment by MikeMcQuaid** [comment] 2023-04-24 08:02
Thanks @issyl0! My thinking is it's probably worth:
- unconditionally enabling all those where we have no offences
- enable them with `brew style --fix` one by one starting with those with single digit numbers of offences and stopping before we reach triple digit numbers of offences (all of those can be disabled forever IMO)
- at some point during this: enable by default and disable the rest. This could be done first, if desired.

**Comment by issyl0** [comment] 2023-04-24 09:15
> at some point during this: enable by default and disable the rest. This could be done first, if desired.

Yeah, first sounds good then we have a list of things to work on fixing when people are feeling bored or want to start contributing again. I'll do this this week.

**Comment by issyl0** [comment] 2023-04-25 23:19
I realised I didn't count `Sorbet`, `Performance` or `RSpec` cops in the initial numbers breakdown in this issue. 🙈

**Comment by issyl0** [comment] 2023-04-27 09:22
To set expectations, this will be something I'll chip away at gradually!

**Comment by issyl0** [comment] 2023-05-18 15:36
Do we still want this? There was [strong disagreement in the first tranche of cops that I proposed](https://github.com/Homebrew/brew/pull/15340).

**Comment by carlocab** [comment] 2023-05-18 15:44
Among the ones we don't enable, are there any particular ones that make a lot of sense to you that you want to enable?

**Comment by Bo98** [comment] 2023-05-18 15:48
It's worth looking into the reasons things are disabled IMO. If it's because of a high false positive rate, we shouldn't enable them. If it's just because of styling disagreements or whatever then they could be ok to enable.

**Comment by MikeMcQuaid** [comment] 2023-05-18 19:58
> Do we still want this?

Yes.



> There was [strong disagreement in the first tranche of cops that I proposed](https://github.com/Homebrew/brew/pull/15340).

The issues there were caught by PR review so: our workflow served its purpose.

> If it's just because of styling disagreements or whatever then they could be ok to enable.

There are multiple of these.

> which means a higher risk of regressions for `homebrew-core` in particular where we don't run CI.

We run `brew style` on homebrew/core on every Homebrew/brew commit.

**Comment by Bo98** [comment] 2023-05-18 20:16
> We run `brew style` on homebrew/core on every Homebrew/brew commit.

That does not test runtime behavioural changes. The problem was that with some of those cops enabled, `brew style` was telling you to do the wrong thing so `brew style` cannot be relied on as sole CI if we enable those cops.

**Comment by MikeMcQuaid** [comment] 2023-05-19 07:17
> The problem was that with some of those cops enabled, `brew style` was telling you to do the wrong thing and changed the behaviour of the code, so `brew style` cannot be relied on as sole CI if we enable those cops.

It is not. We also have `brew readall`. We also have human review (which literally caught these problems in https://github.com/Homebrew/brew/pull/15340).

> I actually only spotted the other issues when I read the RuboCop documentation & commit history on why they were disabled rather than when I did code review

You did spot these issues, though. Additionally, `Style/YodaExpression` caused CI failures and demonstrated, to me at least, that we're using `Pathname#+` in places where `Pathname#/` makes a lot more sense.

You're being unnecessarily conservative here. This reminds me a lot of the issues we get where users open an issue saying "when X happened I did Y to fix it and everything is fine but not everyone will know to do Y so it shouldn't be necessary": in both cases it begs the question "given this has not been a real problem for you/us: what evidence is there that it will be?".

> I would be more comfortable having something that on RuboCop updates notes down which disabled-by-default cops have been added, but I'm not sure if there's any interest in that.

If you would like to work on this: I have no issues with you doing so. I don't think it's fair to make that a prerequisite of this moving forward.

---

If you read https://github.com/Homebrew/brew/pull/15265#issuecomment-1516750224 you will see the original motivation: this seems nicer than manually enabling every cop that don't have any failures and seems to make sense. I have done this on a work project and it has worked well. To repeat myself, `Style/YodaExpression` has also helped to illustrate a case where some existing code is harder to follow than it needs to be.

If you'd rather we/I just enable all the existing cops that make sense instead: ok, we can do that instead.

**Comment by Bo98** [comment] 2023-05-19 09:54
> It is not. We also have `brew readall`.

`brew readall` does not check runtime behaviour of install and test blocks (unless it's a syntax error, which none of these caused), and almost all style fixes happen there.

We absolutely do not do enough CI on Homebrew/core to verify style fixes, but we deemed the risk as minimal as `brew style` rarely/never produces false positives for taps - there is _no_ `rubocop:disable` in Homebrew/core and that's a good thing for those sort of repos given we centralise RuboCop rules in Homebrew/brew and have been against allowing third-party taps have their own configs.

> You did spot these issues, though. Additionally, `Style/YodaExpression` caused CI failures and demonstrated, to me at least, that we're using `Pathname#+` in places where `Pathname#/` makes a lot more sense.
> 
> You're being unnecessarily conservative here.

The point I'm making is that I only spotted these issues _because_ I was very suspicious after realising how many false positives `Style/YodaExpression` causes, but you're saying that I'm being over-suspicious. If that PR was created with `Style/YodaExpression`, I can almost guarantee I was unlikely to have noticed the others - I actually left the pull request after commenting about `Style/YodaExpression` before returning when realising that I couldn't trust the other cops.

If we should not be trusting `brew style` as much, that's fine: but that is a change and should be communicated more clearly. >50% of cops in that sample were problematic and disabled for good reason, this seems way too high but admittedly a small sample so I'm interested to see what the rest are like.

To be clear: I'm just one person so am not blocking anything here, and can sit out of the rest of discussion here and future PRs if preferred.

> If you'd rather we/I just enable all the existing cops that make sense instead: ok, we can do that instead.

To also be clear: I don't have a problem enabling default-disabled cops. I just believe we should be aware of what each of them do rather than blindly enable all, including all future ones - and that should be based on why they are disabled rather than whether CI is red. Even cops that have no failures: how has enabling them been beneficial and do we agree with what it is supposed to flag?

**Comment by MikeMcQuaid** [comment] 2023-05-19 10:36
> > It is not. We also have `brew readall`.
> 
> `brew readall` does not check runtime behaviour of install and test blocks (unless it's a syntax error, which none of these caused), and almost all style fixes happen there.

You said `brew style` is the sole CI. I clarified it is not and `brew readall` catches some bad RuboCop autocorrections.

> We absolutely do not do enough CI on Homebrew/core to verify style fixes

I disagree. I do not see style fixes being in even the top 10 issues with Homebrew's CI today.

> The point I'm making is that I only spotted these issues _because_ I was very suspicious after realising how many false positives `Style/YodaExpression` causes

You spotted these issues, Carlo spotted these issues, I spotted these issues, CI caught these issues. 

> I'm just one person so am not blocking anything here

Thanks for making this explicit 🙇🏻 

> I just believe we should be aware of what each of them do rather than blindly enable all

This is not being done blindly.

> that should be based on why they are disabled rather than whether CI is red

A similar argument could be made for why we enable `NewCops` or really allow any cop to be enabled by upstream without our explicit enabling.

> Even cops that have no style violations: how has enabling them been beneficial and do we agree with what it is supposed to flag?

The short answer is: we're already hugely under-resourced as a project and leaning more on RuboCop saves us more time than it costs. Getting in-editor and in-CI nudges to confirm to our existing style is a good thing.

**Comment by Bo98** [comment] 2023-05-19 14:13
> I disagree. I do not see style fixes being in even the top 10 issues with Homebrew's CI today.

I covered this. I agree it's not because of the reasons I stated - the false positive rate of `brew style` today is effectively zero. It won't be if we enable cops with documented false positives.

> You spotted these issues, Carlo spotted these issues, I spotted these issues, CI caught these issues.

Did you? The PR was approved saying that everything made sense. (I'm not trying to point fingers here so please don't see this as blaming.)

CI didn't catch everything I mentioned either.

> This is not being done blindly.

`EnabledByDefault` implies the opposite.

> A similar argument could be made for why we enable NewCops or really allow any cop to be enabled by upstream without our explicit enabling.
>
> The short answer is: we're already hugely under-resourced as a project and leaning more on RuboCop saves us more time than it costs. Getting in-editor and in-CI nudges to confirm to our existing style is a good thing.

I agree we should lean on RuboCop as we always have been - but we're proposing to stop leaning on RuboCop telling us what cops are unsafe. I don't see how this is saving us resources.

---

In order to stop wasting any more time, I've spent lunch going through the disabled by default cops so do whatever with this information:

<details>
<summary>Research</summary>

* `Bundler/GemComment` - requires each gem to have a comment. Reason for disable: most gemfiles don't do this as it's often pointless. I can see the usefulness however with later-added `OnlyFor: ['restrictive_version_specifiers']`, rather than the default configuration.
* `Bundler/GemVersion` - requires each gem to have a version bound. We don't need/want this. Reason for disable: this is only useful for certain use cases, which does not include most.
* `Gemspec/DependencyVersion` - requires gemspecs to specify version bounds. I like this but it's not applicable to Homebrew/brew (but also not problematic like the others). Reason for disable: same as `Bundler/GemVersion` apparently?
* `Layout/ClassStructure` - requires a specific order of definitions in classes (e.g. includes first, then constants, then attributes, then public methods, etc.). This is ok if it doesn't flag stuff in formulae, where we alreaady have our own component ordering. Reason for disable: "it requires some deliberation on the end user to make proper use of this cop" - it may require a lot of code moving to fix and you may want to configure `ExpectedOrder` rather than rely on the default. We would also need to configure `attribute_macros` for `attr_rw`, `attr_predicate` etc. It also has 18(!) open bugs, due to wrong autofixing (despite being marked safe) and both false positives and negatives. There's WIP work to refactor upstream but it's a lot of work so hasn't made much progress. 
* `Layout/EmptyLineAfterMultilineCondition` - requires a blank line after an `if` condition that spans multiple lines. Purely a preference thing, and most of our existing code suggests we do the opposite of this. Reason for disable: "this style is not very common in practice", but is safe to enable I think.
* `Layout/FirstArrayElementLineBreak` - requires a blank line before the first element in a multi-line array. Purely a preference thing - not sure if we want this or not. Also has a `AllowMultilineFinalElement` option. Reason for disable: not explicitly documented, but I think it's the same as above.
* `Layout/FirstHashElementLineBreak` - see above
* `Layout/FirstMethodArgumentLineBreak` - see above
* `Layout/FirstMethodParameterLineBreak` - see above
* `Layout/HeredocArgumentClosingParenthesis` - requires the closing parenthesis for a heredoc argument to be on the line that opens the heredoc. I couldn't actually find a reason for disabling this one (part of a series of open sourcing Flexport cops), so I'm happy enabling this.
* `Layout/MultilineArrayLineBreaks` - ensures that each item in a multi-line array starts on a separate line. I don't think we want this in many cases for argument arrays, as this will make them harder to read - this in particular affects Homebrew/core. Reason for disable: unknown (again part of a series of open sourcing Flexport cops), but I don't think we want this.
* `Layout/MultilineAssignmentLayout` - requires a newline after the assignment operator in `foo = if expression` lines. Existing code suggests we don't want the default configuration but `EnforcedStyle: same_line` may be useful. Reason for disable: "rubocop source does not pass the cop by default" (wrong default `EnforcedStyle` I reckon, which can't be changed now without it being a breaking change).
* `Layout/MultilineHashKeyLineBreaks` - see `Layout/MultilineArrayLineBreaks`
* `Layout/MultilineMethodArgumentLineBreaks` - see above
* `Layout/MultilineMethodParameterLineBreaks` - see above
* `Layout/RedundantLineBreak` - "checks whether certain expressions, e.g. method calls, that could fit completely on a single line, are broken up into multiple lines unnecessarily". Reason for disable: this is seen as very heavy-handed. I agree that makes sense for upstream to disable by default, so would be interested in seeing the before & after for Homebrew/brew and Homebrew/core. Other than style, I think it's safe to enable.
* `Layout/SingleLineBlockChain` - forbids single line block chains like `arr.select { |item| item.cond? }.first`. Purely a preference thing, but based on existing code I'm not convinced we want this. Reason for disable: "the style it enforces is not universally preferred".
* `Lint/ConstantResolution` - requires `::` before reference constants. I already know Mike wouldn't want this. Reason for disable: "it would mark a lot of offenses unnecessarily".
* `Lint/HeredocMethodCallPosition` - requires method calls on heredocs to be on the line of the opening tag. Happy to enable this. Reason for disable: see `Layout/HeredocArgumentClosingParenthesis`.
* `Lint/NumberConversion` - forbids `to_i`, `to_f` etc. This is so highly used in Homebrew that we probably don't want this. Reason for disable: "it’s not necessarily always correct".
* `Naming/InclusiveLanguage` - reason for disable upstream: politics.
* `Style/ArrayCoercion` - already discussed. Reason for disable: high false positive rate.
* `Style/AsciiComments` - disallows non ASCII in comments. Meh, we don't really gain anything from this either way so I don't really care. Reason for disable: "it is too restrictive".
* `Style/AutoResourceCleanup` - requires `File.open` to always be passed a block. Note that this hasn't been updated much since it was introduced so only covers `File.open` and not alternatives like `Pathname#open` that we tend to prefer. This is so old that I cannot find the associated pull request for a reason for disabling.
* `Style/ClassMethodsDefinitions` - forbids `class << self` in favour of `def self.` (where appropriate). We use both interchangably a lot currently. Reason for disable: there's a lot of disagreements in different style guides on the preferred style. Despite all that, I would actually like to see this enabled.
* `Style/CollectionMethods` - "enforces the use of consistent method names from the Enumerable module" (e.g. `find` instead of `detect`). This sounds nice, but the reason for disable is that it has a high false positive rate. This is due to the limitations of static analysis - some methods are equivalent in `Enumerable` but actually aren't in `Hash`.
* `Style/ConstantVisibility` - "checks that constants defined in classes and modules have an explicit visibility declaration". I like the intentions of this, though probably is a bit noisy having `public_constant` everywhere. Reason for disable: "not many users have spent time caring about this".
* `Style/Copyright` - requries a copyright notice at the top of each file. Reason for disable is obvious.
* `Style/DateTime` - requires usage `Time` instead of `DateTime`. Not safe to enable, nor does it really make the codebase any better. Reason for disable: "these classes, although highly overlapping, have particularities that make them not replaceable in certain situations". This cop is documented as "autocorrection is not safe", but has not actually been marked as unsafe for autocorrection as disabling it entirely was preferred, since the problem is in the offences themselves.
* `Style/DisableCopsWithinSourceCodeDirective` - blocks `rubocop:disable` in source code. We've moved to doing this more, so we don't want this.
* `Style/DocumentationMethod` - requires each public method to have documentation. We selectively enable this for `formula.rb` and I agree we only need this for files a part of public API. We definitely do not want to enforce this on taps. Reason for disable: quite a lot of work to properly enable on existing codebases.
* `Style/ImplicitRuntimeError` - requires `raise` to throw an explicit error. This will take some work, but I'm fine with enabling this. It however shouldn't be enabled for formulae, or potentially even taps in general.
* `Style/InlineComment` - forbids comments on the same line as code `recv.call # like this`. We don't want this. Reason for disable: most other people don't want this either.
* `Style/IpAddresses` - forbids hardcoded IP addresses. We don't need this, and can cause problems in formula tests that use `127.0.0.1`. Reason for disable not explicitly documented, but it seems highly situational when you want this.
* `Style/MethodCallWithArgsParentheses` - mandates parenthesis is used in method calls. We definitely do not want this for taps with Casks and formulae, unless we keep a full list of DSL in `AllowedMethods`. Usage elsewhere is a preference thing. Reason for disable: there's quite a lot of default Ruby DSL that's not handled by default either.
* `Style/MethodCalledOnDoEndBlock` - forbids method chaining after `do end` blocks. Purely a preference thing. Reason for disable: "the rule is not really mainstream".
* `Style/MissingElse` - require if/case expressions to have an else branches. This is bit of a bizarre cop to be honest. I really don't need to say more about this one except that I'm pretty confident we don't want this.
* `Style/MultilineMethodSignature` - forbids multiline method signatures. Weird story this one: this was disabled by default by mistake. The promised follow up PR to fix that never happened.
* `Style/OptionHash` - forbids hashs as method paremeters. This is definitely not exhaustive as RuboCop cannot determine types, so this is based on whether the parameter has a default of `{}`, and was actually overeager in some cases, so this was later chaanged to check for parameters with names `args` or `options` (or similar). For typing reasons, this would be nice to enable but will require some work. We will need to also make sure this doesn't break existing API. Reason for disable: compatibility concerns.
* `Style/RequireOrder` - requires `require` lines to be in alphabetical order. Enabling this will break Homebrew - we have some code that has a very specific order of requires, like the load path stuff. Reason for disable: "this cop has a large impact and may or may not be acceptable depending on the preference of the project"
* `Style/ReturnNil` - forbids `return nil`. I'm fine with enabling this. Reason for disable: styling disagreements - some people see it as semantically different.
* `Style/Send` - forbids `send` in favour of `__send__` as `send` "may overlap with existing methods". It won't for us, but I wouldn't mind changing some references to `public_send`. Reason for disable: "too strict to be enabled by default"
* `Style/SingleLineBlockParams` - this is bizarre and just bad. Requires blocks to have specific parameter names. We don't want this. Reason for disable is obvious.
* `Style/StaticClass` - prevents classes which only have class methods. Not sure how much this affects us, but we can try it. Reason for disable: fixing this can result in breaking changes to API.
* `Style/StringHashKeys` - forbids strings to be used as hash keys. Reason for disable: there are a lot of cases where you want strings as hash keys - including in Homebrew.
* `Style/StringMethods` - requires `to_sym` over `intern`. Seems sensible but reason for disable is concerning: "cop is likely to generate false positives".
* `Style/TopLevelMethodDefinition` - forbids top level method definitions. Fine for Homebrew I think. Reason for disable: scripts don't want this.
* `Style/TrailingCommaInBlockArgs` - this disallows trailing commas in block args, but this actively produces incorrect code so we don't want this.
* `Style/YodaExpression` - discussed
</details>

Note this is just base rubocop and not rubocop-performance etc.

We shouldn't enable most of those, but there's a couple that are safe to enable, and a few more that can be safe when changing the configuration.

**Comment by MikeMcQuaid** [comment] 2023-05-19 14:40
> I covered this. I agree it's not because of the reasons I stated - the false positive rate of `brew style` today is effectively zero. It won't be if we enable cops with documented false positives.

Could not disagree more as the person who makes most of the bulk `brew style --fix` PRs for homebrew-core and Homebrew. It will regularly make suggestions, corrections and say things need fixed that don't. We've adjusted our rules heavily from the defaults because of this.

> Did you? The PR was approved saying that everything made sense. (I'm not trying to point fingers here so please don't see this as blaming.)

I approved it seeing the CI was red, knowing that it would require changes before being merged and saying that it looked fine. I did not do a close review.

> CI didn't catch everything I mentioned either.

It caught enough.

> > This is not being done blindly.
> 
> `EnabledByDefault` implies the opposite.

No, no it doesn't. We're having a lengthy discussion here, we had a lengthy discussion on that PR.

> I agree we should lean on RuboCop as we always have been - but we're proposing to stop leaning on RuboCop telling us what cops are unsafe. I don't see how this is saving us resources.

We already had `NewCops: enable` before any of these changes or debate. We already passed `--autocorrect-all` (`Autocorrect offenses (safe and unsafe)`) instead of `--safe-autocorrect` or `--autocorrect`. We already have extensive changes from the RuboCop defaults in our configuration files. 

Implying that this would be the biggest or first major change from the RuboCop upstream defaults is not a well informed position.

> I've spent lunch going through the disabled by default cops so do whatever with this information

Thanks!

> * `Bundler/GemComment` - requires each gem to have a comment.
> * `Layout/ClassStructure` - requires a specific order of definitions in classes

Scanning the first few: these are good examples of things that would help our readability and help us enforce it. I would say that many of these rules would help make things better.

Random note:

> * `Style/RequireOrder` - requires `require` lines to be in alphabetical order. Enabling this will break Homebrew

It requires you to put extra line breaks between items to indicate that their ordering matters. I have found this to help readability and indicate when ordering matters vs. doesn't.

I agree that doing a `brew style --fix` unconditionally here will break Homebrew: as above, that has been the case many times before and will be made times in future, even on default rules, even with `--safe-autocorrect`.

> but there's a couple that are safe to enable, and a few more that can be safe when changing the configuration.

Agreed.

**Closed** 2023-06-05 13:59 UTC
Labels: features
