### ISSUE TITLE
default one-line install.sh fails to recognise password-less sudo

### ISSUE THREAD

**Issue by torgefaehrlich** [Homebrew/brew#12381] opened 2021-11-05 12:07 UTC
Duplicate of: https://github.com/Homebrew/install/issues/369
### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 3.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9daf5e2d28396c7a4379605e89e029d9fccb41e6
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ed31c642e0f5d830588dae10d7619fde576ecb49
Core tap last commit: 41 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 1
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: single-core 64-bit haswell
Clang: N/A
Git: 2.32.0 => /bin/git
Curl: 7.76.1 => /bin/curl
Kernel: Linux 4.14.248-189.473.amzn2.x86_64 x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.26
/usr/bin/gcc: 7.3.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
# after applying my fix, adding brew to the path and installing dev tools (group install), see What did you expect to happen?
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Tried to install homebrew on a freshly created ec2-instance with standard amazon linux2 ami (ami-01cc34ab2709337aa).
Tried to do so using the one-liner from this documentation:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-install-linux-alt.html
##### edit start
Which is, as far as I can tell, the same one-liner as mentioned here:
https://brew.sh
##### edit end
Why? Well, ultimately I wanted to run terraform on that instance in a version-agnostic way, but tfenv is not in the distribution's repositories.

### What happened (include all command output)?

Installation script prompted for sudo password, even though this is not needed, and not known.

### What did you expect to happen?

I expected the install to proceed without a sudo prompt.
At first attempt I tried <return> to enter an empty password --> didn't work
I then resorted to installing to home-folder using <Control-D>.
This is probably amply enough for the use-case at hand, but still quite an awkward user experience.

If I'm not mistaken, it boils down to this configuration quirk in (some/most?) ubuntu derivatives which are using NOPASSWD configurations: https://askubuntu.com/a/1211226

I applied the solution mentioned there and sure enough, install ran through without a password prompt.
Will also try to address that with amazon support, but theirs might not the only NOPASSWD sudoers file without the "any" Defaults entry. So maybe a good idea to fix the user-experience for that case.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ ssh ec2-user@<public IP of fresh instance>
$ sudo yum install git
[some output, no sudo-prompt]
Is this ok [y/d/N]: y
[some more output, still no sudo-prompt]
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
==> Checking for `sudo` access (which may request your password).
==> Select the Homebrew installation directory
- Enter your password to install to /home/linuxbrew/.linuxbrew (recommended)
- Press Control-D to install to /home/ec2-user/.linuxbrew
- Press Control-C to cancel installation

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
```

**Comment by MikeMcQuaid** [comment] 2021-11-05 12:21
> ```shell
> Not applicable, error happens during installation
> ```

Please supply it anyway, it is applicable to us, particularly `brew doctor`.

> Tried to do so using the one-liner from this documentation:
> https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-install-linux-alt.html

This is not Homebrew's documentation.

> So maybe a good idea to fix the user-experience for that case.

I'm not sure I understand what the case is based on the information you've provided.

> ### Step-by-step reproduction instructions (by running `brew` commands)
> 
> ```shell
> $ ssh ec2-user@<public IP of fresh instance>
> ```

Please provide a reproduction that doesn't need us to spin up AWS, thanks, e.g. with a given `sudo` configuration.

**Comment by torgefaehrlich** [comment] 2021-11-05 12:40
```
sudo cat /etc/sudoers | grep -vE '^ *#' | grep -vxF ""
Defaults   !visiblepw
Defaults verifypw = any ### my change!
Defaults    always_set_home
Defaults    match_group_by_gid
Defaults    always_query_group_plugin
Defaults    env_reset
Defaults    env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE KDEDIR LS_COLORS"
Defaults    env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
Defaults    env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
Defaults    env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"
Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin
root	ALL=(ALL) 	ALL
%wheel	ALL=(ALL)	ALL
```

**Comment by MikeMcQuaid** [comment] 2021-11-05 17:07
What user are you running this as? Which is the relevant line of configuration here?

**Comment by Bo98** [comment] 2021-11-05 17:22
Sounds like this might be a duplicate of https://github.com/Homebrew/install/issues/369?

**Comment by torgefaehrlich** [comment] 2021-11-08 08:01
@Bo98 , yes, that it correct. It is actually a 100% duplicate of that one.
Sorry for not finding it -- I overlooked that "install" is actually its own project.
I don't think the discussion over there is very structured and to the point, though.

**Closed** 2021-11-08 14:05 UTC
Labels: bug
