### ISSUE TITLE
Apple Silicon: /opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory on every brew command run

### ISSUE THREAD

**Issue by slaffcheff** [Homebrew/brew#11151] opened 2021-04-15 11:35 UTC
### `brew config` output

```shell
/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory
HOMEBREW_VERSION: 3.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc9b98aa0ba777889218ac51f67ccc76b0be6a28
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f8462fccd0fe1bfa9bed3d3d5d91f60c35840584
Core tap last commit: 69 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory
Your system is ready to brew.
```

### 

I ran `brew update` and am still able to reproduce my issue.
I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I have Mac M1 and have both arm and intel installations. One of node tools I am using failed hard on arm architecture (aws-azure-login) and tried to install it under intel arch.

### What happened (include all command output)?

The installation of node tool wasn't successful. It still looked at the wrong paths in /opt instead of /usr/local. I tried to fix PATH, uninstalled homebrew and reinstall in only on ARM but on every possible brew command it spams: /opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory even after unstall and install.

### What did you expect to happen?

After I ran uninstall brew script and reinstalled it clearly, I expected this to stop appearing:
/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
What I did: had 2 brew installation under /opt/homebrew and /usr/local/homebrew. I tried to install some stuff under /opt/homebrew and other under /usr/local/homebrew using arch command beforew brew command. I used to recommended brew commands for PATH to transfer everything under /usr/local/homebrew, then decided to uninstall /usr/local/homebrew but script didn't work. Then I did rm -rf /usr/local/homebrew but it seems it didn't work because now I have on every run /opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory after clean install.
```

**Comment by MikeMcQuaid** [comment] 2021-04-15 12:27
What does `which brew` output?

Closing as this is not a bug with Homebrew but an issue with your local setup.

**Closed by MikeMcQuaid** 2021-04-15 12:27 UTC
Labels: bug

**Comment by slaffcheff** [comment] 2021-04-15 12:30
It's kind of a bug because uninstall didn't uninstall correctly intel arch homebrew. Can you at least guide me where to look at in order to resolve this? brew doctor is not helping here unfortunately.

**Comment by slaffcheff** [comment] 2021-04-15 12:32
`$ which brew
/opt/homebrew/bin/brew`

**Comment by MikeMcQuaid** [comment] 2021-04-15 12:33
You've run https://github.com/homebrew/install#uninstall-homebrew?

**Comment by slaffcheff** [comment] 2021-04-15 12:36
I've run `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"`

**Comment by gromgit** [comment] 2021-04-15 13:19
> uninstall didn't uninstall correctly intel arch homebrew
> ...
> I've run `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"`

I think that uninstalls _ARM_ Homebrew on an M1 Mac. Try:
```
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
```

**Comment by slaffcheff** [comment] 2021-04-15 14:01
Tried both uninstall scripts but after another install I still see the error.

**Comment by slaffcheff** [comment] 2021-04-15 14:36
Issue resolved, it was broken symlink.

`lrwxr-xr-x  1 user  admin    28B Apr 15 14:07 /usr/local/bin/brew -> /usr/local/Homebrew/bin/brew`

`rm -rf /usr/local/bin/brew`

`$ brew update                                                                                                                                                                                                                                                                                                                                                         
Already up-to-date.`
