### ISSUE TITLE
Not upgrading a pinned package should be a warning

### ISSUE THREAD

**Issue by Kerndog73** [Homebrew/brew#6362] opened 2019-08-12 23:40 UTC
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

`brew update && brew upgrade && brew cleanup`

# What happened (include command output)

`brew upgrade` returns a positive error code when there are pinned packages. This means that `brew cleanup` doesn't run in the above invokation.

<details>
  <summary>Command output</summary>
  <pre>
Error: Not upgrading 1 pinned package:
emscripten 1.38.41
==> No packages to upgrade
  </pre>
</details>

# What you expected to happen

Not upgrading a pinned package should be a warning so `brew upgrade` should return a zero error code when encountering pinned packages.

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew install package
brew pin package
# wait for package to become outdated...
brew update
brew upgrade
# upgrade returns a positive error code
echo $?
```

**Comment by iMichka** [comment] 2019-08-13 05:39
Duplicate of #6231

**Closed by iMichka** 2019-08-13 05:39 UTC
