### ISSUE TITLE
Error on `brew autoremove`

### ISSUE THREAD

**Issue by adikpb** [Homebrew/brew#14550] opened 2023-02-07 15:06 UTC
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/ss_conn_lib2.dylib
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-309-g206d4c8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 206d4c86b36d2d9e093dc886988be9fbb2b28a12
Last commit: 27 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c27f57133838d853c5114fbce01dd678ba6db0e2
Core tap last commit: 13 days ago
Core tap branch: master
Core tap JSON: 07 Feb 14:19 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### What were you trying to do (and why)?

Removing dependencies that were installed, and are not need anymore since those casks/formulas are uninstalled now.

### What happened (include all command output)?

```
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/parsec.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:578:in `autoremove'
/usr/local/Homebrew/Library/Homebrew/cmd/autoremove.rb:25:in `autoremove'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

Expected brew to remove unwanted formulas.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew autoremove
```

**Comment by nodeg** [comment] 2023-02-07 15:11
Duplicate of https://github.com/Homebrew/brew/issues/14542.

**Comment by carlocab** [comment] 2023-02-07 15:19
Duplicate of #14542.

**Closed by carlocab** 2023-02-07 15:19 UTC
Labels: bug
