### ISSUE TITLE
`brew update` has become painfully slow

### ISSUE THREAD

**Issue by telemachus** [Homebrew/brew#4755] opened 2018-08-26 23:22 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`:

```
HOMEBREW_VERSION: 1.7.2-46-g3705956
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 3705956f53f9f47ac043934e22c2361e37b7bc83
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4053e90b4db4efe2a76e2ee8847e5a6b4ef2d8fb
Core tap last commit: 46 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT: git
HOMEBREW_NO_ANALYTICS: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_60
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: N/A
```

`brew doctor`:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.5m/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h
  /usr/local/include/python3.7m/greenlet/greenlet.h
```

- What you were trying to do (and why): run `brew update`
- What happened (include command output): it took a very, very long time (see below for details)
- What you expected to happen: I expected it to go faster than this.
- Step-by-step reproduction instructions (by running `brew` commands): run `brew update`

Starting late last week, Friday I think, `brew update` has been very, very slow. It appears to just stop for 2-3 minutes before eventually finishing. I'm not having any network problems—I can browse the web while `brew update` is still waiting, and the issue with `brew doctor` has been there for years without any issues.

```
$ time brew up
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
Updated Homebrew from 9bc17c8a82 to 3705956f53.
Updated 2 taps (homebrew/cask, homebrew/core).
==> Updated Formulae
dartsim                    mdcat                      yubico-piv-tool
goenv                      saxon

real	3m34.739s
user	2m56.636s
sys	0m32.126s
```

**Comment by MikeMcQuaid** [comment] 2018-08-27 07:32
> Auto packing the repository in background for optimum performance.
> See "git help gc" for manual housekeeping.

That's why that run was slow.

What happens if you run it (`brew update --verbose`) multiple times in a row? I can't reproduce this being slow in that case. Closing because I can't reproduce but can keep discussing here.

**Closed by MikeMcQuaid** 2018-08-27 07:32 UTC

**Comment by telemachus** [comment] 2018-08-27 11:44
@MikeMcQuaid Your guess is right that if I run `brew update` multiple times in a row, it's fine after the first time. However, in my mind a problem remains: my experience is that `brew update` is very slow multiple times a day. I first noticed this late last week, as I said. (I mention that just to flag it if there was some relevant change around then.)

In terms of reproducing the issue, I'm not sure how to create a test situation other than asking people to be aware of what happens when they type `brew update` or go to install something for the first time on a given day!

Another way to put the problem is this: should we now expect `brew update` to be this slow once a day or more? That doesn't seem great to me.

**Comment by MikeMcQuaid** [comment] 2018-08-27 13:25
> (I mention that just to flag it if there was some relevant change around then.)

Gotcha. It's not cache migration stuff, is it CC @reitermarkus? Can you `brew update --force --verbose` and try to figure out what bit is slow?

**Comment by reitermarkus** [comment] 2018-08-27 14:45
> It's not cache migration stuff, is it CC @reitermarkus?

I don't think so, otherwise the “Migrating cache entries ...” message would show up.

**Comment by MikeMcQuaid** [comment] 2018-08-27 14:50
@reitermarkus I'm wondering if there's a performance regression somewhere with the Ruby update code?

**Comment by reitermarkus** [comment] 2018-08-27 15:06
It's hard to know without any sort of reference point of how fast it should be.

**Comment by MikeMcQuaid** [comment] 2018-08-27 15:09
@reitermarkus Could you do some testing between the last few tags to see if the `brew update --force` case has had a notable slowdown?

**Comment by reitermarkus** [comment] 2018-08-27 15:28
Can't exactly do that, since updating from `< 1.7.2` will run the cache migration. But even with the migration, it only takes 11s, compared to 6s on `master`. And last time I checked, the migration took about 5s, so there doesn't seem to be any notable slowdown.

**Comment by MikeMcQuaid** [comment] 2018-08-27 15:37
Ok, thanks @reitermarkus.

**Comment by telemachus** [comment] 2018-08-28 01:08
For whatever it is worth, I just rand `brew update --force --verbose` at home, and here was the result: https://gist.github.com/telemachus/64827cc0c561ace6a82dfe3474ce8204.

I was here while it ran, and the main delay was when updating the homebrew-cask tap. I will untap that, and see if it has any effect.

**Comment by reitermarkus** [comment] 2018-08-28 01:15
You seem to have a bunch of deprecated taps.

```
brew untap homebrew/dupes
brew untap homebrew/python
brew untap homebrew/versions
```

And throw in a `brew update-reset` for good measure. 😉

**Comment by telemachus** [comment] 2018-08-28 01:26
@reitermarkus Thanks very much for the tips!

**Comment by telemachus** [comment] 2018-08-28 11:03
I did what @reitermarkus recommended, but today's first-of-the-day `brew up` was still took three minutes to complete. (I don't have a timer or verbose log, because I assumed the problem would be fixed. That's my bad, and I'm sorry.)

I'm happy to take any advice for further things to check, but my question at this point is this: is a three-minute wait normal for the first `brew up` of a day? I don't remember things being anywhere near so slow in the past.

**Comment by MikeMcQuaid** [comment] 2018-08-28 12:51
no worries, can try again tomorrow 😉. If you can provide `/usr/bin/time brew update --verbose --debug` output that would be useful. I do expect that if you run `/usr/bin/time brew update --verbose --debug --force` you'll probably produce the same timing.

> is a three-minute wait normal for the first brew up of a day? I don't remember things being anywhere near so slow in the past.

It depends on many things:

- the speed of your internet connection
- the speed of your machine
- the distance from GitHub
- the load on the GitHub API
- the load on GitHub's git layer
- how many commits you need to fetch for each repository

To be clear, I'm open to this being improved but until we've got something actionable here I don't think it's worth having an open issue.

**Comment by MikeMcQuaid** [comment] 2018-08-28 12:52
> Auto packing the repository in background for optimum performance.
> See "git help gc" for manual housekeeping.

Whenever you see this: it's your local machine and it's expected that it'll be slow.
