### ISSUE TITLE
Quarantine (PR #4656) causes 'brew cask install' to fail on 10.11

### ISSUE THREAD

**Issue by jabenninghoff** [Homebrew/brew#4809] opened 2018-09-03 19:20 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

Hi, PR #4656 appears to break `brew cask install` on 10.11. I get an error on 10.11, but not on 10.12. As a workaround, re-running with the `--no-quarantine` flag is successful. I'm not sure why this swift feature isn't available, my OS is up to date.

**Expected result:** quarantine is skipped since `quarantinePropertiesKey` fails on 10.11.
**Actual result:** error.

Steps to reproduce:
```
$ brew cask install acorn
==> Satisfying dependencies
==> Downloading https://secure.flyingmeat.com/download/Acorn.zip
==> Downloading from https://s3.amazonaws.com/flyingmeat/Acorn.zip
######################################################################## 100.0%
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/quarantine.swift:29:30: error: 'quarantinePropertiesKey' is only available on OS X 10.10 or newer
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/quarantine.swift:29:30: note: add 'if #available' version check
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^
Error: Failed to quarantine /Users/agamemnon/Library/Caches/Homebrew/downloads/bb23310f9b4a7a78a42a60dd1909bf2a0a8a59de50e6dbf7dda82026e37f3593--Acorn.zip. Here's the reason:
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/quarantine.swift:29:30: error: 'quarantinePropertiesKey' is only available on OS X 10.10 or newer
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/quarantine.swift:29:30: note: add 'if #available' version check
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^

$ brew cask install acorn --no-quarantine
==> Satisfying dependencies
==> Downloading https://secure.flyingmeat.com/download/Acorn.zip
Already downloaded: /Users/agamemnon/Library/Caches/Homebrew/downloads/bb23310f9b4a7a78a42a60dd1909bf2a0a8a59de50e6dbf7dda82026e37f3593--Acorn.zip
==> Verifying checksum for Cask acorn
==> Installing Cask acorn
Warning: macOS's Gatekeeper has been disabled for this Cask
==> Moving App 'Acorn.app' to '/Applications/Acorn.app'.
🍺  acorn was successfully installed!
```

Output of `brew config` and `brew doctor`:
```
$ brew config
HOMEBREW_VERSION: 1.7.2-122-g61ace27
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 61ace27006a1cb444552c0be10087fcbc3051643
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 05a504a06b524d450f8d82afc3b07b6013e0d38c
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GITHUB_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: N/A
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 8.2.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
```

**Comment by amyspark** [comment] 2018-09-03 21:34
Hi @jabenninghoff !

Please run `swift -v` with the following snippet:
```swift
import Foundation
#if os(macOS) 
    print("macOS deployment target:", __MAC_OS_X_VERSION_MIN_REQUIRED) 
#endif
```
If it returns **anything other than** `101106`, please let me know.

**Comment by jabenninghoff** [comment] 2018-09-03 21:51
Hm. I got this with the above snippet as `test.swift`:

```
$ swift -v test.swift
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -interpret - -target x86_64-apple-macosx10.9 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -color-diagnostics -module-name main
macOS deployment target: 1090
```

Is something possibly wrong with my Xcode install?

**Comment by amyspark** [comment] 2018-09-03 21:56
Yes, its SDK is too old; we need a deployment target of at least 10.10 for this feature to work.

@Homebrew/maintainers : please close this issue as duplicate of Homebrew/homebrew-cask#51554 .

**Closed** 2018-09-03 22:35 UTC

**Comment by jabenninghoff** [comment] 2018-09-03 22:42
OK thanks. FYI, I completely uninstalled and reinstalled Xcode and the command line tools on my 10.10 system, and got the same results. As far as I can tell, it's not possible to set a deployment target of 10.10 with Xcode 8.2.1, which is the newest version supported on 10.10.

I see that you have PR #4796 opened which should fix the error. Thanks!
