### ISSUE TITLE
`brew upgrade --cask <outdated_formula>` throws the error "No Cask with this name exists."

### ISSUE THREAD

**Issue by slebedev** [Homebrew/brew#14478] opened 2023-02-02 07:30 UTC
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-171-g4ded574
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4ded574330899f1eed7605bd344a619fc6b348db
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9d2fca0f48c1a7966a141aad47456dfb92bc934c
Core tap last commit: 9 days ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: N/A
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

After running `brew update` and getting new casks outdated by `brew outdated --cask --greedy` output, I've decided to update any of casks listed.

### What happened (include all command output)?

```
==> Upgrading 1 outdated package:
Error: Cask 'fsnotes' is unavailable: No Cask with this name exists.
```

### What did you expect to happen?

Successful upgrade of outdated cask.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew update && brew outdated && brew outdated --cask --greedy
==> Updated Homebrew from 7a5f6143d to 4ded57433.
Updated 1 tap (homebrew/cask-drivers).
==> Outdated Formulae
apr                              apr-util                         libde265
==> Outdated Casks
fsnotes

You have 3 outdated formulae and 1 outdated cask installed.
You can upgrade them with brew upgrade
or list them with brew outdated.
apr (1.7.1) < 1.7.2
apr-util (1.6.2) < 1.6.3
libde265 (1.0.10) < 1.0.11
fsnotes (6.1.2) != 6.1.3
font-ibm-plex-mono (latest) != latest
fsnotes (6.1.2) != 6.1.3
google-chrome (109.0.5414.119) != 110.0.5481.77

$ brew upgrade --cask fsnotes google-chrome
==> Upgrading 2 outdated packages:
Error: Cask 'fsnotes' is unavailable: No Cask with this name exists.

$ brew info --cask fsnotes
==> fsnotes: 6.1.3
https://fsnot.es/
/opt/homebrew/Caskroom/fsnotes/6.1.2 (121B)
==> Name
FSNotes
==> Description
Notes manager
==> Artifacts
FSNotes.app (App)
==> Analytics
install: 107 (30 days), 339 (90 days), 1,471 (365 days)

$ brew upgrade --cask fsnotes
==> Upgrading 1 outdated package:
Error: Cask 'fsnotes' is unavailable: No Cask with this name exists.
```

**Comment by slebedev** [comment] 2023-02-02 07:35
Upgrade by ommitting any of formulas in the command throws this error also:

```bash
$ brew upgrade --cask
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
Error: Cask 'fsnotes' is unavailable: No Cask with this name exists.
```

Installing of some new cask is successful:

```bash
$ brew install --cask dynamist
==> Downloading https://dynalist.io/standalone/download?file=Dynalist.dmg
Warning: No checksum defined for cask 'dynalist', skipping verification.
==> Installing Cask dynalist
==> Moving App 'Dynalist.app' to '/Applications/Dynalist.app'
🍺  dynalist was successfully installed!
```

**Comment by gromgit** [comment] 2023-02-02 07:58
Probably a duplicate of https://github.com/Homebrew/brew/issues/14463.

**Comment by slebedev** [comment] 2023-02-02 08:07
@gromgit Thank you, Adrian! Let me check, I'll close the issue if it's related to that one.

**Comment by slebedev** [comment] 2023-02-02 08:31
```bash
$ brew readall homebrew/cask
$ # previous command has finished without any error
$ brew upgrade --cask --debug fsnotes
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-171-g4ded574\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/fsnotes.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-171-g4ded574\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --progress-bar --max-time 5 --retry 3 --location --remote-time --output /Users/drago/Library/Caches/Homebrew/api/cask.json --time-cond /Users/drago/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-171-g4ded574\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source//opt/homebrew/Caskroom/fsnotes/.metadata/6.1.2/20230125112421.396/Casks/fsnotes.rb.rb
Error: Cask 'fsnotes' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:342:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:351:in `load'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `map'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

The issue looks the same, but I don't understand how formula may be corrupted:

```bash
$ cd /opt/homebrew/Library/Taps/homebrew/homebrew-cask
/o/h/L/T/h/homebrew-cask $ curl https://raw.githubusercontent.com/Homebrew/homebrew-cask/master/Casks/fsnotes.rb > /tmp/fsnotes.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   596  100   596    0     0  16848      0 --:--:-- --:--:-- --:--:-- 19866
/o/h/L/T/h/homebrew-cask $ diff /tmp/fsnotes.rb Casks/fsnotes.rb
/o/h/L/T/h/homebrew-cask $ # No difference! Maybe we should look them in binary format?..
/o/h/L/T/h/homebrew-cask $ diff <(xxd /tmp/fsnotes.rb) <(xxd Casks/fsnotes.rb)
/o/h/L/T/h/homebrew-cask $ # No difference also...
```

**Comment by gromgit** [comment] 2023-02-02 09:46
>```
>/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-171-g4ded574\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source//opt/homebrew/Caskroom/fsnotes/.metadata/6.1.2/20230125112421.396/Casks/fsnotes.rb.rb
>```

This is a symptom of the first issue I mentioned in the linked issue above. `export HOMEBREW_NO_INSTALL_FROM_API=1` to stop this from happening, then run your `brew upgrade`s again.

> The issue looks the same, but I don't understand how formula may be corrupted:

Local formula/cask file corruption isn't likely, but that's easy to test with `brew readall`, so there's no reason to ignore that possibility.

**Comment by slebedev** [comment] 2023-02-02 10:36
> Local formula/cask file corruption isn't likely, but that's easy to test with `brew readall`, so there's no reason to ignore that possibility.

Yeah, I did it before running `brew upgrade --cask --debug fsnotes`, it finished without any error.

And I've tried with `HOMEBREW_NO_INSTALL_FROM_API=1` also 🙁:

```bash
$ brew config
HOMEBREW_VERSION: 3.6.20-171-g4ded574
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4ded574330899f1eed7605bd344a619fc6b348db
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9d2fca0f48c1a7966a141aad47456dfb92bc934c
Core tap last commit: 9 days ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: N/A
Xcode: 14.2
Rosetta 2: false
$ brew upgrade --cask
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to
==> Upgrading 1 outdated package:
Error: Cask 'fsnotes' is unavailable: No Cask with this name exists.
```

**Comment by gromgit** [comment] 2023-02-02 10:42
Then you'll have to do the other half of my recommendation in the linked issue:
```
rm -fr $(brew --caskroom)/fsnotes
brew reinstall --cask --force fsnotes
```

**Comment by slebedev** [comment] 2023-02-02 10:48
I've restored local metadata for `fsnotes==6.1.2` version and then upgrade perfoms successfully.

So the main question is why local formula wasn't there?..

**Comment by slebedev** [comment] 2023-02-02 11:04
hm... after successful upgrade `fsnotes.rb` local formula isn't exist

```bash
$ curl https://raw.githubusercontent.com/p-linnane/homebrew-cask/cb76bdaa98e8109c6d67b7e864cc320fc64c6baa/Casks/fsnotes.rb > $(brew --caskroom)/fsnotes/.metadata/6.1.2/20230125112421.396/Casks/fsnotes.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   596  100   596    0     0   3819      0 --:--:-- --:--:-- --:--:--  3947

$ brew upgrade --cask fsnotes
==> Upgrading 1 outdated package:
fsnotes 6.1.2 -> 6.1.3
==> Upgrading fsnotes
==> Downloading https://github.com/glushchenko/fsnotes/releases/download/6.1.3/FSNotes_6.1.3.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be
######################################################################## 100.0%
==> Backing App 'FSNotes.app' up to '/opt/homebrew/Caskroom/fsnotes/6.1.2/FSNotes.app'
==> Removing App '/Applications/FSNotes.app'
==> Moving App 'FSNotes.app' to '/Applications/FSNotes.app'
==> Purging files for version 6.1.2 of Cask fsnotes
🍺  fsnotes was successfully upgraded!

$ find (brew --caskroom) -iname "*.rb"
$ # empty result
```

**Comment by slebedev** [comment] 2023-02-02 11:15
```bash
$ find $(brew --caskroom)/fsnotes
/opt/homebrew/Caskroom/fsnotes
/opt/homebrew/Caskroom/fsnotes/6.1.3
/opt/homebrew/Caskroom/fsnotes/6.1.3/FSNotes.app
/opt/homebrew/Caskroom/fsnotes/.metadata
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3/20230202104712.517
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3/20230202104712.517/Casks
/opt/homebrew/Caskroom/fsnotes/.metadata/config.json

$ rm -rf (brew --caskroom)/fsnotes

$ brew reinstall --cask --force fsnotes
==> Downloading https://github.com/glushchenko/fsnotes/releases/download/6.1.3/FSNotes_6.1.3.zip
Already downloaded: /Users/drago/Library/Caches/Homebrew/downloads/fb38a64431c6b3e35ebe81df3528a75337a50245e8d68dfe55bf64635a5cd9d5--FSNotes_6.1.3.zip
==> Installing Cask fsnotes
Warning: It seems there is already an App at '/Applications/FSNotes.app'; overwriting.
==> Removing App '/Applications/FSNotes.app'
==> Moving App 'FSNotes.app' to '/Applications/FSNotes.app'
🍺  fsnotes was successfully installed!

 $ find $(brew --caskroom)/fsnotes
/opt/homebrew/Caskroom/fsnotes
/opt/homebrew/Caskroom/fsnotes/6.1.3
/opt/homebrew/Caskroom/fsnotes/6.1.3/FSNotes.app
/opt/homebrew/Caskroom/fsnotes/.metadata
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3/20230202111311.489
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3/20230202111311.489/Casks
/opt/homebrew/Caskroom/fsnotes/.metadata/config.json
```

**Comment by slebedev** [comment] 2023-02-02 11:20
@gromgit oh, thanks for this catch! What should be there when it's set?

```bash
$ env | grep HOMEBREW_
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_INSTALL_FROM_API=1
$ brew config | grep HOMEBREW_
HOMEBREW_VERSION: 3.6.20-171-g4ded574
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 10
```

**Comment by slebedev** [comment] 2023-02-02 11:24
@gromgit thanks a lot for this catch, I didn't notice I've copied wrong variable 🙈

I can confirm it's ok when correct one is set:

```bash
$ brew config | grep HOMEBREW_
HOMEBREW_VERSION: 3.6.20-171-g4ded574
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_INSTALL_FROM_API: set

$ find (brew --caskroom)/fsnotes
/opt/homebrew/Caskroom/fsnotes
/opt/homebrew/Caskroom/fsnotes/6.1.3
/opt/homebrew/Caskroom/fsnotes/6.1.3/FSNotes.app
/opt/homebrew/Caskroom/fsnotes/.metadata
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3/20230202111311.489
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3/20230202111311.489/Casks
/opt/homebrew/Caskroom/fsnotes/.metadata/config.json

$ rm -rf $(brew --caskroom)/fsnotes

$ brew reinstall --cask --force fsnotes
==> Downloading https://github.com/glushchenko/fsnotes/releases/download/6.1.3/FSNotes_6.1.3.zip
Already downloaded: /Users/drago/Library/Caches/Homebrew/downloads/fb38a64431c6b3e35ebe81df3528a75337a50245e8d68dfe55bf64635a5cd9d5--FSNotes_6.1.3.zip
==> Installing Cask fsnotes
Warning: It seems there is already an App at '/Applications/FSNotes.app'; overwriting.
==> Removing App '/Applications/FSNotes.app'
==> Moving App 'FSNotes.app' to '/Applications/FSNotes.app'
🍺  fsnotes was successfully installed!
 ~  find (brew --caskroom)/fsnotes                             2898ms  Thu Feb  2 13:22:09 2023
/opt/homebrew/Caskroom/fsnotes
/opt/homebrew/Caskroom/fsnotes/6.1.3
/opt/homebrew/Caskroom/fsnotes/6.1.3/FSNotes.app
/opt/homebrew/Caskroom/fsnotes/.metadata
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3/20230202112208.975
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3/20230202112208.975/Casks
/opt/homebrew/Caskroom/fsnotes/.metadata/6.1.3/20230202112208.975/Casks/fsnotes.rb
/opt/homebrew/Caskroom/fsnotes/.metadata/config.json
```

So should we close the issue as it seems like a duplicated one?..

**Closed** 2023-02-05 12:37 UTC
Labels: bug, install from api

**Comment by Rylan12** [comment] 2023-02-05 12:49
The underlying issue should now be fixed, so you should be able to unset `HOMEBREW_NO_INSTALL_FROM_API` and have upgrades work.

You might need to run `brew reinstall --force` once on casks that were already broken, but after doing that you should be good.

**Comment by slebedev** [comment] 2023-02-05 13:52
Thank you @Rylan12! 🙏🏻
