### ISSUE TITLE
Display list of versions when using "switch"

### ISSUE THREAD

**Issue by kud** [Homebrew/brew#7336] opened 2020-04-12 15:10 UTC
# A detailed description of the proposed feature

It could be great by doing `brew switch name-of-the-formula`, it displays the list of versions available.

# The motivation for the feature

Sometimes, homebrew tells me to switch to another version but I really do not know what it is installed. I would like to know what versions are installed like for instance `pyenv` does.

# How the feature would be relevant to at least 90% of Homebrew users

People want to know what versions they've got!

# What alternatives to the feature have been considered

I've tried to do `brew info name-of-the-formula` to see what it's installed, but nope. The only solution was to go to /Cellar/ and see the folders.

**Comment by MikeMcQuaid** [comment] 2020-04-13 07:52
Duplicate of https://github.com/Homebrew/brew/issues/7329.

**Closed by MikeMcQuaid** 2020-04-13 07:52 UTC
