### ISSUE TITLE
Something broke `brew edit`

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#2538] opened 2017-04-24 02:55 UTC
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

Pick a formula, say `libtiff`.  Sometime within I would guess the last 24 hours, this is now happening:
```
brew edit libtiff
Editing /usr/local/hb/Library/Taps/homebrew/homebrew-core/Formula/libtiff.rb
--: /usr/local/hb/Library/Taps/homebrew/homebrew-core/Formula/libtiff.rb: Permission denied
```
I checked the permissions on that file, the Formula directory, and my whole `brew prefix`.  They're fine.  I can `cd` there and do `vim libtiff.rb`, for example.

```
brew config
HOMEBREW_VERSION: 1.1.13-95-gcfe2c3c90
ORIGIN: https://github.com/Homebrew/brew
HEAD: cfe2c3c9007ae919267eb0767ef84c27748829c4
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 36926753cb08fe932b296cea312d2aa587b084f4
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/hb
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.0.0.1.1490382677
X11: N/A
```
Also, the doctor says I'm ready to brew.

**Comment by MikeMcQuaid** [comment] 2017-04-24 07:50
Assuming dupe of https://github.com/Homebrew/brew/issues/2533. If your relevant `EDITOR` variable doesn't have a space in it: shout.

**Closed** 2017-04-24 09:02 UTC

**Comment by chdiza** [comment] 2017-04-24 14:42
That was it, thanks.  I hadn't seen the issue of which this was a dupe, or maybe I had but forgot that I do have a space in `$HOMEBREW_EDITOR`

**Comment by MikeMcQuaid** [comment] 2017-04-24 14:55
No worries; glad either way it's sorted.
