### ISSUE TITLE
Migration to Homebrew API causes applications on brew services to break

### ISSUE THREAD

**Issue by ericswpark** [Homebrew/brew#14924] opened 2023-02-18 15:41 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew gist-logs code-server
Error: No logs.

➜  ~ brew config
HOMEBREW_VERSION: 4.0.1-60-g6ad9294
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6ad92949e910041416d84a53966ec46b873e069f
Last commit: 11 hours ago
Core tap JSON: 18 Feb 15:33 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2

➜  ~ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Upgrade `code-server` to `4.10.0` and use it through `brew services`

### What happened (include all command output)?

`code-server` crashes immediately on start-up. The output of `brew services`:

```
➜  ~ brew services                  
Name        Status       User       File
caddy       started      ericswpark ~/Library/LaunchAgents/homebrew.mxcl.caddy.plist
code-server error  19968 ericswpark ~/Library/LaunchAgents/homebrew.mxcl.code-server.plist
```

`/usr/local/var/log/code-server.log` is not created, so I can't even check there.

### What did you expect to happen?

Launch and work properly

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update && brew upgrade
brew install code-server
brew services start code-server
```

**Comment by SMillerDev** [comment] 2023-03-08 13:35
Transferred it since the issue is `brew` pouring bottles with the home directory of the CI runner.

**Comment by SMillerDev** [comment] 2023-03-08 13:40
Closing in favor of https://github.com/Homebrew/brew/issues/14925

**Closed by SMillerDev** 2023-03-08 13:40 UTC
Labels: bug
