### ISSUE TITLE
Brew update fail's on Mac OSX High Sierra

### ISSUE THREAD

**Issue by paatz04** [Homebrew/brew#3511] opened 2017-11-30 12:06 UTC
# Please always follow these steps:
- [ X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [ X] Ran `brew update` and retried your prior step?
- [- ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ X] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Updating brew
- What happened (include command output)
`brew update
Error: /usr/local is not writable. You should change the ownership
and permissions of /usr/local back to your user account:
  sudo chown -R $(whoami) /usr/local
`
Running:
 `sudo chown -R $(whoami) /usr/local`

Gives me:
`chown: /usr/local: Operation not permitted`

Running 
`udo chown -R $(whoami) $(brew --prefix)`

gives me the same error

The brew doctor output is the following:

> Warning: /usr/local is not writable.
> 
> You should change the ownership and permissions of /usr/local
> back to your user account.
>   sudo chown -R $(whoami) /usr/local
> 
> Warning: /usr/local is not writable.
> Even if this directory was writable when you installed Homebrew, other
> software may change permissions on this directory. For example, upgrading
> to OS X El Capitan has been known to do this. Some versions of the
> "InstantOn" component of Airfoil or running Cocktail cleanup/optimizations
> are known to do this as well.
> 
> You should change the ownership and permissions of /usr/local back to
> your user account.
>   sudo chown -R $(whoami) /usr/local
> 
> Warning: You are using OS X 10.13.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.
> 
> Warning: Ruby version 2.3.3 is unsupported on 10.13. Homebrew
> is developed and tested on Ruby 2.0, and may not work correctly
> on other Rubies. Patches are accepted as long as they don't cause breakage
> on supported Rubies.
> 
> Warning: Homebrew's sbin was not found in your PATH but you have installed
> formulae that put executables in /usr/local/sbin.
> Consider setting the PATH for example like so
>   echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
> 
> Warning: Your Homebrew is outdated.
> You haven't updated for at least 24 hours. This is a long time in brewland!
> To update Homebrew, run `brew update`.

The brew config output is the following:

> HOMEBREW_VERSION: 0.9.9
> ORIGIN: https://github.com/Homebrew/brew.git
> HEAD: 092d4712a1d00bc08eb0515d8e61f7859c7a2de0
> Last commit: 1 year, 4 months ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: b9aa599879e235ec202a06ef3d466b02f3b8470e
> Core tap last commit: 1 year, 4 months ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_REPOSITORY: /usr/local
> HOMEBREW_CELLAR: /usr/local/Cellar
> HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
> CPU: octa-core 64-bit haswell
> Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
> Clang: 8.1 build 802
> Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
> Perl: /usr/bin/perl
> Python: /usr/bin/python
> Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
> Java: 1.8.0_92, 1.7.0_79
> OS X: 10.13.1-x86_64
> Xcode: 8.3.3
> CLT: N/A
> X11: 2.7.9 => /opt/X11

**Comment by ilovezfs** [comment] 2017-11-30 12:59
```
sudo chown -R $(whoami) /usr/local/*
```

**Comment by amyspark** [comment] 2017-11-30 13:30
duplicate of #3285?

**Closed** 2017-11-30 13:45 UTC
