### ISSUE TITLE
macOS install packages should be signed

### ISSUE THREAD

**Issue by MScottBlake** [Homebrew/brew#14687] opened 2023-02-17 14:27 UTC
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The macOS packages that are being built with Github Actions (https://github.com/Homebrew/brew/pull/14265) should be signed with an Apple Developer certificate to strengthen security and lower barriers to installation. 

The current installer package is telling users that it cannot be opened because it is from an unidentified developer.
![image](https://user-images.githubusercontent.com/945258/219680823-6f6ec576-b72c-4da8-965d-2854073ac27b.png)

Sure, there are workarounds for performing this installation anyway, but this message will ward off many potential installations.

### What is the motivation for the feature?

To strengthen security and lower barriers to installation

### How will the feature be relevant to at least 90% of Homebrew users?

It will make it easier for macOS users to install the product.

### What alternatives to the feature have been considered?

Writing more documentation about how to work around the errors displayed by macOS. This will still result in excess support requests.

**Comment by MikeMcQuaid** [comment] 2023-02-17 14:39
Duplicate of https://github.com/Homebrew/install/issues/739

**Closed by MikeMcQuaid** 2023-02-17 14:39 UTC
Labels: features
