### ISSUE TITLE
`brew.sh` website does not support SSL

### ISSUE THREAD

**Issue by Katee** [Homebrew/brew#1478] opened 2016-11-10 20:03 UTC
The instructions on `http://brew.sh` recommend using the following command to install brew:
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

The URL to curl uses SSL, however the webpage the command is shown on does not. This means that a user being MITM'd could be shown a modified webpage with a non `https` link or a completely different link to curl into ruby which could be malicious content.

Getting a certificate for `brew.sh` and setting up redirection to SSL is relatively easy and free with letsencrypt.org.

**Comment by MikeMcQuaid** [comment] 2016-11-10 20:07
Closing as a duplicate of https://github.com/Homebrew/install/issues/85.

**Closed by MikeMcQuaid** 2016-11-10 20:07 UTC

**Comment by Katee** [comment] 2016-11-10 20:12
@MikeMcQuaid Homebrew/install#85 does not appear to be related at all. Was that the correct ticket?

**Comment by MikeMcQuaid** [comment] 2016-11-10 20:16
@Katee apologies, wrong paste. It's https://github.com/Homebrew/homebrew.github.io/issues/98

**Comment by Katee** [comment] 2016-11-10 20:25
@MikeMcQuaid 👍
