### ISSUE TITLE
Linux: post-install PATH wrong when used with "brew install"

### ISSUE THREAD

**Issue by iMichka** [Homebrew/brew#14053] opened 2022-10-26 19:56 UTC
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.7-28-g560f571
ORIGIN: https://github.com/Homebrew/brew
HEAD: 560f5717ad4dc1e3feed9f3c0b7c84aa1498b84c
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2eb4c98a43df07caa6be40bcbc2275fa7cdb5e7e
Core tap last commit: 47 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit skylake
Clang: N/A
Git: 2.38.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.10.104-linuxkit x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.35
/usr/bin/gcc: 11.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

The PATH is wrong when running `brew install` on Linux. It is correct for `brew post-install`.
This can be seen by printing the PATH in the post-install block.

`brew install`

> /usr/bin:/bin:/usr/sbin:/sbin

vs

`brew post-install`

> /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

This prevents the post install block to rely on keg-only stuff (for example the `docbook` formula needs access to `libxml2` commands.

### What happened (include all command output)?

linuxbrew@f288a1835162:~/$ brew install docbook
==> Downloading https://ghcr.io/v2/homebrew/core/docbook/manifests/5.1_1
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/f535f42662e0d894361c489a448ac2f5462b01ecb12c3c54876cb43570da5558--docbook-5.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/docbook/blobs/sha256:dcab543bb0e0ae56e0aa106b61f77a111d52aa002c0418aae93f9fe6ac3cb332
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/e90f601ac20f941724103a824af06bf7f3ca2f3dcad7d817b7b68435089f3f4c--docbook--5.1_1.x86_64_linux.bottle.tar.gz
==> Pouring docbook--5.1_1.x86_64_linux.bottle.tar.gz
==> xmlcatalog --noout --create /home/linuxbrew/.linuxbrew/etc/xml/catalog
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/docbook/post_install.01.xmlcatalog:
2022-10-26 19:06:12 +0000

xmlcatalog
--noout
--create
/home/linuxbrew/.linuxbrew/etc/xml/catalog

Warning: The post-install step did not complete successfully

### What did you expect to happen?

An installation/postinstall without error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install docbook` on Linux.
```

**Comment by carlocab** [comment] 2022-12-12 03:23
I'm confused by this. The failure seems to be occurring during `postinstall`, so the `PATH` at install time doesn't seem relevant.

I was initially under the impression (because of the `PATH` discussion) that `xmlcatalog` was not being found during postinstall, but that doesn't seem consistent with the facts presented so far. We know that `docbook` depends on `libxml2`, which is not keg-only on Linux, and provides `xmlcatalog`. We also know that `home/linuxbrew/.linuxbrew/bin` is in `PATH` during `postinstall`, which is when we call `xmlcatalog`.

So, while I don't know what the problem is, I don't think the issue has anything to do with our `PATH` configuration.

**Comment by carlocab** [comment] 2022-12-12 03:39
Ah, I think I see. I misunderstood the issue the first time I read this. The problem is that the `PATH` during `postinstall` differs between when it is called indirectly through `brew install` and directly with `brew postinstall`. That is certainly an issue.

In the case of `docbook`, Homebrew/homebrew-core#117903 should help. But this should be fixed more generally.

**Comment by iMichka** [comment] 2022-12-12 21:20
> The problem is that the PATH during postinstall differs between when it is called indirectly through brew install and directly with brew postinstall

Exactly. And I could find out in brew where that happens.

**Comment by cho-m** [comment] 2022-12-17 05:42
I think directly running `brew postinstall` uses the current shell's `PATH` while postinstall run during `brew install` uses value set by Homebrew.

Can reproduce behavior using `brew postinstall` by using previous `docbook` formula and adjusting shell `PATH`:
```console
$ PATH="/usr/bin:/bin:/usr/sbin:/sbin" /home/linuxbrew/.linuxbrew/bin/brew postinstall docbook
==> Postinstalling docbook
==> xmlcatalog --noout --del file:///home/linuxbrew/.linuxbrew/opt/docbook/docbook/xml/4.2/catalog.xml /home/linuxbrew/.linuxbrew/etc/xml/catalog
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/docbook/post_install.01.xmlcatalog:
2022-12-17 05:39:08 +0000

xmlcatalog
--noout
--del
file:///home/linuxbrew/.linuxbrew/opt/docbook/docbook/xml/4.2/catalog.xml
/home/linuxbrew/.linuxbrew/etc/xml/catalog
```

**Comment by MikeMcQuaid** [comment] 2023-01-25 15:57
I can't reproduce this with either `docbook` or any other formula any more. Happy to reopen if/when that changes.

**Closed by MikeMcQuaid** 2023-01-25 15:57 UTC
Labels: bug, help wanted
