### ISSUE TITLE
Brew update should show new and updated Formulaes when HOMEBREW_UPDATE_REPORT_ALL_FORMULAE is set 

### ISSUE THREAD

**Issue by rbatllet** [Homebrew/brew#14720] opened 2023-02-20 10:24 UTC
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17c872fb5275d87922a56416587cb439a5064354
Last commit: 4 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b0c460e871522d95e4aace16fd05fa40bc2afddf
Core tap last commit: 3 days ago
Core tap branch: master
Core tap JSON: 20 Feb 10:18 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_UPDATE_REPORT_ALL_FORMULAE: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.7.4-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### What were you trying to do (and why)?

I would like to get all the updated and new formulas that have been added to Brew.

The setting 
```
export HOMEBREW_UPDATE_REPORT_ALL_FORMULAE=true
```
 no longer works with the new version 4.

### What happened (include all command output)?

![Screenshot 2023-02-20 at 08 41 59](https://user-images.githubusercontent.com/3993987/220078822-ffa1e665-8fc2-4d96-bff5-cddd2c49b7f1.png)

### What did you expect to happen?

Show all updates and new formulas.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update && brew upgrade && brew cleanup
```

**Comment by MikeMcQuaid** [comment] 2023-02-20 14:37
Duplicate of https://github.com/Homebrew/brew/issues/14706

**Closed by MikeMcQuaid** 2023-02-20 14:37 UTC
Labels: bug

**Comment by rbatllet** [comment] 2023-02-20 15:37
It is nonsense that settings that worked before, in the new version stop working without prior notice and there is no intention to fix what is broken because there is nothing planned. In the end we will have no choice but to use MacPorts.

**Comment by MikeMcQuaid** [comment] 2023-02-20 16:05
> In the end we will have no choice but to use MacPorts.

@rbatllet Please feel free if it's a better fit for you (and doubly so if you're unable to be polite when filing bug reports).

**Comment by rbatllet** [comment] 2023-02-20 17:53
I am not using the "HOMEBREW_INSTALL_FROM_API" setting but the "HOMEBREW_UPDATE_REPORT_ALL_FORMULAE" setting does not work anymore and in the Changelog, It does not say anything about this. 

If it won't work anymore, it doesn't cost anything to write it down in the Changelog, right?

**Comment by MikeMcQuaid** [comment] 2023-02-20 19:25
@rbatllet That's because it being broken is a bug and was not an intentional change. That's why this issue was marked as a duplicate of another, closed issue: https://github.com/Homebrew/brew/issues/14706
