### ISSUE TITLE
include is installing in wrong place

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#5700] opened 2019-02-10 14:42 UTC
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

install include from source tarball to `#{prefix}/include` via `prefix.install "include"` or `include.install "include"`

# What happened (include command output)

include is installed to `#{prefix}/include/include`
# What you expected to happen

include is installed to `#{prefix}/include`

# Step-by-step reproduction instructions (by running `brew` commands)

https://github.com/Homebrew/homebrew-core/pull/36875
<details><summary>brew doctor</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libdiskmgt.1.dylib
  /usr/local/lib/libnvpair.1.dylib
  /usr/local/lib/libuutil.1.dylib
  /usr/local/lib/libzfs.2.dylib
  /usr/local/lib/libzfs_core.1.dylib
  /usr/local/lib/libzpool.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libzfs/libnvpair.h
  /usr/local/include/libzfs/libuutil.h
  /usr/local/include/libzfs/libuutil_common.h
  /usr/local/include/libzfs/libuutil_impl.h
  /usr/local/include/libzfs/libzfs.h
  /usr/local/include/libzfs/libzfs_core.h
  /usr/local/include/libzfs/libzfs_impl.h
  /usr/local/include/libzfs/sys/crypto/api.h
  /usr/local/include/libzfs/sys/crypto/common.h
  /usr/local/include/libzfs/sys/crypto/icp.h
  /usr/local/include/libzfs/sys/lua/lauxlib.h
  /usr/local/include/libzfs/sys/lua/lua.h
  /usr/local/include/libzfs/sys/lua/luaconf.h
  /usr/local/include/libzfs/sys/lua/lualib.h
  /usr/local/include/libzfs/zfeature_common.h
  /usr/local/include/libzfs/zfs_comutil.h
  /usr/local/include/libzfs/zfs_deleg.h
  /usr/local/include/libzfs/zfs_fletcher.h
  /usr/local/include/libzfs/zfs_namecheck.h
  /usr/local/include/libzfs/zfs_prop.h
  /usr/local/include/libzfs/zpios-ctl.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libdiskmgt.la
  /usr/local/lib/libnvpair.la
  /usr/local/lib/libuutil.la
  /usr/local/lib/libzfs.la
  /usr/local/lib/libzfs_core.la
  /usr/local/lib/libzpool.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libdiskmgt.a
  /usr/local/lib/libnvpair.a
  /usr/local/lib/libuutil.a
  /usr/local/lib/libzfs.a
  /usr/local/lib/libzfs_core.a
  /usr/local/lib/libzpool.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  hunspell
  kdenlive
  bash-completion
```
</details>
<details><summary>brew config</summary>

```
HOMEBREW_VERSION: 2.0.1-10-g7ce517c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7ce517cb2d882f7ad130c89de5189c7dc3971084
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 36a597b5c99e73cc03ea88fddbc6b967600f7808
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/yurikoles/Library/Logs/Homebrew
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2, 11.0.1, 1.8.0_202, 1.8.0_192
macOS: 10.14.3-x86_64
CLT: N/A
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

</details>

**Comment by yurikoles** [comment] 2019-02-10 14:43
`include.install "include/spirv_cross"` doesn't install any files at all

**Comment by fxcoudert** [comment] 2019-02-10 19:49
We have plenty of examples in core that install a whole directory under include:

```
glui.rb:      include.install "include/GL"
irrlicht.rb:    include.install "include" => "irrlicht"
leveldb.rb:    include.install "include/leveldb"
libcuefile.rb:    include.install "include/cuetools/"
libreplaygain.rb:    include.install "include/replaygain/"
```

**Comment by fxcoudert** [comment] 2019-02-10 20:04
A minimal example taken from your linked PR works fine for me:

```
[fx:/usr … homebrew-core/Formula] master* ± cat toto.rb
class Toto < Formula
  url "https://github.com/KhronosGroup/SPIRV-Cross/archive/2019-01-31.tar.gz"
  sha256 "1876b044cd21942752492c99f12fcd7e69debb6a63c52277ae83303bd6437f59"

  def install
    include.install "include/spirv_cross"
  end
end
[fx:/usr … homebrew-core/Formula] master* ± brew install toto
==> Downloading https://github.com/KhronosGroup/SPIRV-Cross/archive/2019-01-31.t
Already downloaded: /Users/fx/Library/Caches/Homebrew/downloads/9804dc6105bb197de5c6e659ee499c6c536283adcbfb125cbc2cb8d71a23b715--SPIRV-Cross-2019-01-31.tar.gz
🍺  /usr/local/Cellar/toto/01-31: 10 files, 50.7KB, built in 4 seconds
[fx:/usr … homebrew-core/Formula] master* 7s ± ls /usr/local/Cellar/toto/*/include
spirv_cross
[fx:/usr … homebrew-core/Formula] master* ± ls /usr/local/Cellar/toto/*/include/*
barrier.hpp            image.hpp              sampler.hpp
external_interface.h   internal_interface.hpp thread_group.hpp
```

**Comment by yurikoles** [comment] 2019-02-10 20:09
sorry, I had forgotten to mention that there is already `#{prefix}/include/spirv_cross`, I just wanted to install *additional* headers there.

**Comment by fxcoudert** [comment] 2019-02-10 20:40
OK, then it's because it will not overwrite the directory, indeed. You can use:

```
(include/"spirv_cross").install Dir["foo/bar/*.h"]
```

Closing as “not a bug”, I think.

**Closed by fxcoudert** 2019-02-10 20:40 UTC
