### ISSUE TITLE
Why is homebrew requesting https://formulae.brew.sh/api/formula.json even with "brew services"?

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/brew#14462] opened 2023-01-29 13:46 UTC
I'm trying to restart redis with `brew services restart redis`

And brew tries to load the `https://formulae.brew.sh/api/formula.json` url

```
curl: (28) Operation timed out after 5004 milliseconds with 258940 out of 3443866 bytes received
curl: (28) Operation timed out after 5004 milliseconds with 63690 out of 3443866 bytes received
curl: (28) Operation timed out after 5001 milliseconds with 37044 out of 3443866 bytes received
curl: (28) Operation timed out after 5002 milliseconds with 80167 out of 3443866 bytes received
Error: Failure while executing; `/usr/local/homebrew/Library/Homebrew/shims/shared/curl xxxxx --silent https://formulae.brew.sh/api/formula.json` exited with 28. Here's the output:
curl: (28) Operation timed out after 5004 milliseconds with 258940 out of 3443866 bytes received
curl: (28) Operation timed out after 5004 milliseconds with 63690 out of 3443866 bytes received
curl: (28) Operation timed out after 5001 milliseconds with 37044 out of 3443866 bytes received
curl: (28) Operation timed out after 5002 milliseconds with 80167 out of 3443866 bytes received
```

This was introduced recently, I just need to restart a service and not updating a package, why doing this?

**Comment by CaledoniaProject** [comment] 2023-01-29 13:49
This basically means user can't restart a service when the network is unavailable, is that by design?

**Comment by gromgit** [comment] 2023-01-29 15:32
What's the output of `brew config`?

**Comment by CaledoniaProject** [comment] 2023-01-29 23:41
Hi @gromgit, I believe this is unrelated, I just need to know how to disable this behavior.

**Comment by CaledoniaProject** [comment] 2023-01-29 23:44
@apainintheneck Will `HOMEBREW_NO_INSTALL_FROM_API` help here?

**Comment by apainintheneck** [comment] 2023-01-30 01:55
Yeah, it seemed related but I hadn't had time to test it. If you run `brew config`, you should be able to see if `HOMEBREW_INSTALL_FROM_API` is set. If it is, set `HOMEBREW_NO_INSTALL_FROM_API` and it shouldn't require an internet connection anymore.

```
~ $ brew services restart redis --debug
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --fail --progress-bar --max-time 5 --retry 3 --location --remote-time --output /Users/kevinrobell/Library/Caches/Homebrew/api/formula.json --time-cond /Users/kevinrobell/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading redis from API
Stopping `redis`... (might take a while)
==> Successfully stopped `redis` (label: homebrew.mxcl.redis)
==> Successfully started `redis` (label: homebrew.mxcl.redis)
~ $ HOMEBREW_NO_INSTALL_FROM_API=1 brew services restart redis --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/redis.rb
Stopping `redis`... (might take a while)
==> Successfully stopped `redis` (label: homebrew.mxcl.redis)
==> Successfully started `redis` (label: homebrew.mxcl.redis)
```


Note that we just started testing `HOMEBREW_INSTALL_FROM_API` on developers recently in https://github.com/Homebrew/brew/pull/14384 and we're still working out some of these kinks. I agree that `brew services` shouldn't need an internet connection either way.

**Comment by Moulick** [comment] 2023-01-30 06:15
@CaledoniaProject if you ran any of the [brew developer commands](https://docs.brew.sh/Manpage#developer-commands), the install from API will be enabled by default now. `HOMEBREW_NO_INSTALL_FROM_API` is the way to disable it

**Comment by CaledoniaProject** [comment] 2023-01-30 06:39
@Moulick I first met this problem from `brew install --build-from-source XXX`, and it prompts me build from source is not possible with HOMEBREW_INSTALL_FROM_API. Is `--build-from-source` also considered as a developer command?

**Comment by Moulick** [comment] 2023-01-30 06:42
I am not sure, you can check by running `brew developer` to check if it's enabled. Also, there is some discussion around this here https://github.com/Homebrew/brew/pull/14412#issuecomment-1403273966

**Comment by rverma-nsl** [comment] 2023-02-03 00:27
It seems `HOMEBREW_NO_INSTALL_FROM_API` is also not working.
```
❯ brew config
HOMEBREW_VERSION: 3.6.20-184-gcdf58fe
ORIGIN: https://github.com/Homebrew/brew
HEAD: cdf58fe392beea957cb0a77007d5308aee3e336f
Last commit: 12 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 482f27271966a2712680195430ca58c37717c765
Core tap last commit: 7 days ago
Core tap branch: master
Core tap JSON: 03 Feb 04:53
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
❯ sudo brew services stop openfortivpn
curl: (6) Could not resolve host: formulae.brew.sh
curl: (6) Could not resolve host: formulae.brew.sh
curl: (6) Could not resolve host: formulae.brew.sh
```

**Comment by gromgit** [comment] 2023-02-03 02:41
@rverma-nsl, what's the output of `sudo brew services stop openfortivpn`?

**Comment by MikeMcQuaid** [comment] 2023-02-03 08:36
Marking as a duplicate of https://github.com/Homebrew/brew/issues/14451

**Closed by MikeMcQuaid** 2023-02-03 08:36 UTC
Labels: bug, install from api

**Comment by laggardkernel** [comment] 2023-02-25 14:21
Now the `sudo brew services` doesn't work at all. It complains the api stuff even the api files have been downloaded already.

```
❯ sudo brew services restart adguardhome
Password:
Error: Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.
```

---

Never mind, I just rolled back to 3.6.12.

**Comment by gromgit** [comment] 2023-02-25 14:34
> Never mind, I just rolled back to 3.6.12.

That seems like an overreaction, especially since `brew` told you exactly what you needed to do to fix it:

> ```
> Error: Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.
> ```

**Comment by laggardkernel** [comment] 2023-02-25 14:42
Thank for your suggestion. But I checked my Homebrew cache and `formula.jws.json` has been downloaded there already. Some change just broke `brew services` **with `sudo`**. I had no problem several days before.

I guess I'll stick with 3.x for a few days until the `sudo` support gets fixed.

**Comment by gromgit** [comment] 2023-02-25 14:59
> Thank for your suggestion. But I checked my Homebrew cache and `formula.jws.json` had been downloaded there already. Some change just broke `brew services` **with `sudo`**. I had no problem several days before.

That *is* a bugfix: https://github.com/Homebrew/brew/pull/14782. The original behavior (`sudo brew services` triggered downloads as root) actually broke normal Homebrew stuff for users: https://github.com/Homebrew/brew/issues/14516#issuecomment-1441201398
 
> I guess I'll stick with 3.x for a few days until the `sudo` support gets fixed.

There's no point waiting. Warning about stuff done as root _that shouldn't be_ is a Homebrew rule of thumb, and I don't see this decision being walked back, especially when it's known to break stuff for users.

**Comment by laggardkernel** [comment] 2023-02-25 15:09
I know Homebrew discourages use of `sudo`, and that's usually what I do with `brew`. The problem here is some rare applications use priviliged ports. There must be a way to start it with `sudo`, considering `brew servcies` is just a wrapper upon `launchctl` and the latter works with `sudo` perfectly.

**Comment by Moulick** [comment] 2023-02-25 15:15
I suppose now after the bug fix, if the file was downloaded with sudo beforehand, it would need to be deleted once and then run `brew update` once to get a fresh non root copy. Then I suppose `sudo brew service` should work.

**Comment by laggardkernel** [comment] 2023-02-25 16:16
> it would need to be deleted once and then run brew update once to get a fresh non root download.

It needs to be deleted from the default cache location `~/Library/Caches/Homebrew/api`, but not from my custom `HOMEBREW_CACHE`. 

Thanks for the help. @gromgit @Moulick

**Comment by gromgit** [comment] 2023-02-26 01:59
> It needs to be deleted from the default cache location `~/Library/Caches/Homebrew/api`, but not from my custom `HOMEBREW_CACHE`.

That's because `sudo` resets the child environment for security reasons, so you'd have to explicitly tell `sudo` to preserve your custom env setting.

**Comment by Moulick** [comment] 2023-02-26 03:24
@gromgit that's interesting, I never knew that. Is there somewhere where I can read more about sudo resetting the child env?

**Comment by gromgit** [comment] 2023-02-26 08:58
Start with [sudo's own FAQ on the subject](https://www.sudo.ws/docs/troubleshooting/#why-does-sudo-modify-the-commands-environment) for the rationale, and [this tutorial](https://www.baeldung.com/linux/sudo-manage-environment-variables) for the basic options. The `sudo` man page is the canonical "source of truth" in this matter, but it takes a lot of careful reading.

(You could just use `-E`if you're lazy or on a hurry, but that opens you up to attackers who manipulate your environment, then cackle with glee as you `sudo` their malware into running as root. You have been warned.)

**Comment by Moulick** [comment] 2023-02-26 09:11
Thanks, much appreciated. Personally, I stay away from root/sudo as much as possible unless absolutely necessary.
