### ISSUE TITLE
Brew doesn't handle xcode-select path correctly

### ISSUE THREAD

**Issue by samdmarshall** [Homebrew/brew#1795] opened 2017-01-06 23:30 UTC
I plugged my MacBook in to charge while it was performing a Time Machine backup and when to install a new formula to try it out and found that I was unable to install anything from `brew` because I have an older copy of Xcode on a drive that was connected to the MacBook at the time.

<details>
<summary>Log</summary>
<pre><code>
Samantha: brew config
HOMEBREW_VERSION: 1.1.6-25-g1c710adb4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c710adb44cfaa53c3f2b051dcd68c406709dd85
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ec7845be62b72b60db01cadd656cfdbda5e83128
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.2-x86_64
Xcode: 5.1.1 => /Volumes/Macintosh HD 1/Applications/Xcode.app/Contents/Developer
CLT: 8.2.0.0.1.1480973914
X11: N/A
Samantha: brew install gost
Checking if we need to fetch /usr/local/Homebrew...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/mistydemeo/homebrew-formulae...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/samdmarshall/homebrew-formulae...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/simeji/homebrew-jid...
Error: Your Xcode (5.1.1) is too outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from the App Store.
Error: Kernel.exit

Samantha: xcode-select -p
/Library/Developer/CommandLineTools
</code></pre>
</details>
<br>

I strongly believe this to be incorrect behavior as the developer directory as defined by `xcode-select` *and used by `xcrun`) would not be the same as the one that `brew` assumes is correct.

**Comment by MikeMcQuaid** [comment] 2017-01-07 12:53
I agree this is incorrect behaviour. This is a duplicate of https://github.com/Homebrew/brew/issues/1587 which I plan to fix at some point (if no-one beats me to it).

**Closed by MikeMcQuaid** 2017-01-07 12:53 UTC
