### ISSUE TITLE
audit complaint "revision should not decrease" only shows after merging to master

### ISSUE THREAD

**Issue by scpeters** [Homebrew/brew#1229] opened 2016-10-05 23:14 UTC
### Bug reports:

We recently updated a formula in one of our taps in https://github.com/osrf/homebrew-simulation/pull/146, which contained 3 commits.

* https://github.com/osrf/homebrew-simulation/pull/146/commits/18106a93a06c44a1fa6738374daeb89d7efd94b6 updated the url and its sha256 (but forgot to reset the revision)
* https://github.com/osrf/homebrew-simulation/pull/146/commits/bb4059ea61a2e05653e33d9388769cac3a2465b9 removed the revision and also an outdated patch
* https://github.com/osrf/homebrew-simulation/pull/146/commits/7d7e2602551daa3bbfa6272821769097a6ea84a6 updated the bottle hash

Our travis script calls `brew audit` and a few other things on all the formulae in our tap, and it was [happy with that third commit](https://travis-ci.org/osrf/homebrew-simulation/builds/165350964) (not green because I merged and deleted before a 10.11 executor was available). Anyway, the point is that `brew audit` passed in that branch.

We merged to default with a merge commit (no squashing or rebasing), and now I see a [brew audit complaint](https://travis-ci.org/osrf/homebrew-simulation/jobs/165368015#L292-L293) when I check that formula on master:

~~~
osrf/simulation/ignition-transport2:
  * revision should not decrease
~~~

I believe this happens because the first commit https://github.com/osrf/homebrew-simulation/pull/146/commits/18106a93a06c44a1fa6738374daeb89d7efd94b6 that has version 2.1.0_2 was merged to default without squashing. `brew audit` doesn't realize that was a mistake that was reverted and could have been squashed, but I didn't think it would matter.

To reproduce:

1. Find a formula that has a non-zero revision and checkout a new branch
2. Update a formula url and sha256 in one commit
3. Remove revision in second commit
4. `brew audit` should be happy on that branch
5. merge or rebase without squashing that branch to master, and then `brew audit` will start to complain

Workaround:

Always remove the revision in the same commit that bumps a formula version. I'm not sure if there's an easy way to detect this or if squashing should be recommended in the documentation.

**Comment by MikeMcQuaid** [comment] 2016-10-07 16:05
I strongly advise your Travis script use `brew test-bot --ci-auto` for taps and additionally not use merge commits on formulae-based taps. I'm closing this out not because it's not a bug but as it doesn't affect our workflow we'll probably need a PR to get this fixed. Sorry but thanks for the great bug report.

**Closed by MikeMcQuaid** 2016-10-07 16:05 UTC

**Comment by scpeters** [comment] 2016-10-07 17:28
I totally understand about closing the issue. If I get a flash of insight, I'll work on a fix, but in the meantime I'll try adding your recommendations to the [Tap maintenance docs](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by MikeMcQuaid** [comment] 2016-10-07 17:41
@scpeters Another thing I was thinking about that could be in the docs and/or https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/tap-readme.rb is a default `.travis.yml` file that runs `brew test-bot` and sets the typical environment variables. Feel free to open a PR for either/both and we can discuss specifics there.
