### ISSUE TITLE
Make `autoremove` idempotent

### ISSUE THREAD

**Issue by MedeaMelana** [Homebrew/brew#17970] opened 2024-08-06 09:44 UTC
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I would like `autoremove` to be idempotent: running it a second time immediately should not have any new effects.

To achieve this, the command would not only uninstall packages that are unnecessary now, but also any packages that become unnecessary after the first pass of `autoremove`, recursively.

### What is the motivation for the feature?

The command's current behaviour surprised me. The user's intention when running the command is to remove any deps that are no longer necessary, and for the command to potentially leave newly unnecessary packages feels unintuitive to me.

My experience was this:
```
% brew autoremove
==> Autoremoving 1 unneeded formula:
c-ares
Uninstalling /opt/homebrew/Cellar/c-ares/1.31.0... (166 files, 872.6KB)
c-ares 1.30.0 is still installed.
To remove all versions, run:
  brew uninstall --force c-ares
% brew autoremove
==> Autoremoving 1 unneeded formula:
c-ares
Uninstalling /opt/homebrew/Cellar/c-ares/1.30.0... (168 files, 873.1KB)
```

In this case, this was the end, but looks like I could have needed to re-run `autoremove` any number of times to completely uninstall all unnecessary dependencies.

### How will the feature be relevant to at least 90% of Homebrew users?

I expect it to match most if not all users' expectations.

### What alternatives to the feature have been considered?

The new feature as described could also be implemented behind a flag like `--recursive`, however I expect the recursive behaviour to better match the user's intention in the majority of cases.

If desired, the current behaviour could be retained by a flag like `--max-depth-1` or `--max-depth <n>`.

**Comment by carlocab** [comment] 2024-08-06 10:09
It should be idempotent in a default configuration, I think. Do you have `HOMEBREW_NO_INSTALL_CLEANUP` or `HOMEBREW_NO_CLEANUP_FORMULAE` set?

That said, I am inclined to agree this should maybe be idempotent regardless of configuration.

**Comment by gromgit** [comment] 2024-08-06 11:11
> It should be idempotent in a default configuration, I think.

That's been my experience too. In addition:

> > the command would not only uninstall packages that are unnecessary now, but also any packages that become unnecessary after the first pass of `autoremove`, recursively.

`autoremove` already does this, as far as I'm aware. I've never had `autoremove` surface a _different_ set of formulae to auto-remove after the first run.

The situation being presented here has nothing to do with idempotency. It asks a different but difficult question instead: should `autoremove` default to be a super-`uninstall`, purging all versions of targeted formulae?

**Comment by carlocab** [comment] 2024-08-06 11:36
> It asks a different but difficult question instead: should `autoremove` assume that multiple versions of a targeted formula were not intended, and should therefore blindly purge them all?

To be fair, I think this does have something to do with idempotency.

**Comment by MedeaMelana** [comment] 2024-08-06 12:08
> It should be idempotent in a default configuration, I think. Do you have `HOMEBREW_NO_INSTALL_CLEANUP` or `HOMEBREW_NO_CLEANUP_FORMULAE` set?

I don't think I have any environment variables set (`env | grep BREW` reports none).

**Comment by carlocab** [comment] 2024-08-06 12:31
Seems like this should be a bug report rather than a feature request, then. Though it's not very clear where the bug is -- we only know that you happen to have an old install of `c-ares` that you weren't expecting to be there (right?).

**Comment by MikeMcQuaid** [comment] 2024-08-06 12:45
@MedeaMelana Can I see your `brew config` and `brew doctor` output please?

**Comment by MikeMcQuaid** [comment] 2024-08-06 12:46
The bug/feature to me, as-is, smells like: unless `HOMEBREW_NO_INSTALL_CLEANUP` is set: `brew autoremove` should remove all versions of a formula, not just the latest one.

**Comment by MedeaMelana** [comment] 2024-08-06 20:09
I don't know how or why exactly I ended up with two versions of `c-ares`. Some wild guesses are:
* A run of `brew upgrade`
* Installing both `node` and `node@20`
* Uninstalling one or both of the packages in some order
* A combination of the above

Please let me know if you'd like me to convert this issue to a bug. Are there specific instructions I should follow?

> @MedeaMelana Can I see your `brew config` and `brew doctor` output please?

Certainly!

```
% brew config
HOMEBREW_VERSION: 4.3.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1e560120a65be3b3c7b8a42083d54f795e1d0ec4
Last commit: 2 days ago
Core tap JSON: 06 Aug 11:14 UTC
Core cask tap JSON: 06 Aug 11:14 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4 => /Users/Redacted/Downloads/Xcode.app/Contents/Developer
Rosetta 2: false

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

**Comment by MedeaMelana** [comment] 2024-08-28 08:00
Do you need anything else from me for this?

**Comment by carlocab** [comment] 2024-08-28 08:22
A way to reproduce `autoremove` not being idempotent would be a start, because it should be idempotent. But without a reproducer this would be pretty difficult to fix.

**Comment by MikeMcQuaid** [comment] 2024-08-28 08:26
Closing until we can reproduce, sorry.

**Closed** 2024-08-28 08:25 UTC
Labels: features
