### ISSUE TITLE
brew install folly on 10.10 (Yosemite)

### ISSUE THREAD

**Issue by abhi18av** [Homebrew/brew#1044] opened 2016-09-20 13:03 UTC
### Bug reports:

Hii Homebrew team)

I'm unable to install the [Facebook's Folly C++ library ](https://github.com/facebook/folly) as a brew formula, even though all dependencies have been met.

<img width="1440" alt="screen shot 2016-09-20 at 6 22 58 pm" src="https://cloud.githubusercontent.com/assets/12799326/18670955/cba04d16-7f5f-11e6-8b1e-d990f770aede.png">
<img width="1440" alt="screen shot 2016-09-20 at 6 23 06 pm" src="https://cloud.githubusercontent.com/assets/12799326/18670961/d0126adc-7f5f-11e6-80fd-bc474832dc17.png">

**Comment by zmwangx** [comment] 2016-09-20 13:55
As said El Capitan or newer is required. From the formula:

```ruby
  # https://github.com/facebook/folly/issues/451
  depends_on macos: :el_capitan
```

Therefore, you should track the issue at https://github.com/facebook/folly/issues/451 (bug upstream developer until they fix it I guess).

> even though all dependencies have been met.

Homebrew has another layer of "dependencies" called "requirements", and `:el_capitan` is a requirement. Take a look at #1004 for a sneak peak of better communication of those requirements.

**Comment by zmwangx** [comment] 2016-09-20 13:56
I'm closing this issue because this is expected behavior and we can't fix it on our side.

**Closed by zmwangx** 2016-09-20 13:56 UTC

**Comment by abhi18av** [comment] 2016-09-20 14:04
Okay, thanks @zmwangx . I guess, this is a pointer in the right direction )
