### ISSUE TITLE
brew autoupdate status 

### ISSUE THREAD

**Issue by janewar** [Homebrew/brew#18633] opened 2024-10-25 01:10 UTC
### `brew doctor` output

```shell
Warning: Calling `brew autoupdate'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.
Please report this issue to the Homebrew/homebrew-autoupdate tap, or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate/cmd/autoupdate.rb:11

Autoupdate is installed and running.

Autoupdate was initialised on 10/25/24.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Warning: Calling `brew autoupdate'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.
Please report this issue to the Homebrew/homebrew-autoupdate tap, or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate/cmd/autoupdate.rb:11

Autoupdate is installed and running.

Autoupdate was initialised on 10/25/24.
```

### What were you trying to do (and why)?

Warning: Calling `brew autoupdate'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.
Please report this issue to the Homebrew/homebrew-autoupdate tap, or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate/cmd/autoupdate.rb:11

Autoupdate is installed and running.

Autoupdate was initialised on 10/25/24.

### What happened (include all command output)?

Warning: Calling `brew autoupdate'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.
Please report this issue to the Homebrew/homebrew-autoupdate tap, or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate/cmd/autoupdate.rb:11

Autoupdate is installed and running.

Autoupdate was initialised on 10/25/24.

### What did you expect to happen?

Warning: Calling `brew autoupdate'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.
Please report this issue to the Homebrew/homebrew-autoupdate tap, or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate/cmd/autoupdate.rb:11

Autoupdate is installed and running.

Autoupdate was initialised on 10/25/24.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Warning: Calling `brew autoupdate'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.
Please report this issue to the Homebrew/homebrew-autoupdate tap, or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate/cmd/autoupdate.rb:11

Autoupdate is installed and running.

Autoupdate was initialised on 10/25/24.
```

**Comment by carlocab** [comment] 2024-10-25 01:32
Duplicate of https://github.com/DomT4/homebrew-autoupdate/issues/147

**Closed** 2024-10-25 01:32 UTC
Labels: bug
