### ISSUE TITLE
`brew deps` sometimes incorrectly returns an empty list

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#9333] opened 2020-11-28 17:34 UTC
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I ran `brew deps tree-sitter`, because I was interested in the footprint of this package on my system.

## What happened (include command output)

Nothing happened. This was surprising because tree-sitter _does_ have dependents. The dependency tree is reported correctly by `brew deps --tree tree-sitter`.

Other formulae seem to report their dependencies correctly (e.g. python@3.9).

<details>
  <summary>Command output</summary>
  <pre>
❯ brew deps tree-sitter
❯ brew deps --tree tree-sitter
tree-sitter
├── emscripten
│   ├── binaryen
│   ├── node
│   │   └── icu4c
│   ├── python@3.9
│   │   ├── gdbm
│   │   ├── openssl@1.1
│   │   ├── readline
│   │   ├── sqlite
│   │   │   └── readline
│   │   └── xz
│   └── yuicompressor
│       └── openjdk
└── node
    └── icu4c

❯ brew deps python@3.9
gdbm
openssl@1.1
readline
sqlite
xz
  </pre>
</details>

## What you expected to happen

I expected `brew deps tree-sitter` to correctly report tree-sitter's dependencies.

## Step-by-step reproduction instructions (by running `brew` commands)

Just `brew deps tree-sitter`.

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew config
HOMEBREW_VERSION: 2.5.12-275-gef75518
ORIGIN: https://github.com/Homebrew/brew
HEAD: ef755182bbd11bf8f49b0139d089046596ab8fb7
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6de7edb5a4024433e8cf9e78f8bb9be1c153d244
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: N/A

❯ brew doctor
Your system is ready to brew.
</pre>

**Comment by jonchang** [comment] 2020-11-29 02:14
Try running it with `brew deps --verbose --debug tree-sitter` to see what might be going on. There's likely an error somewhere that we're silently ignoring in `brew deps`.

**Comment by carlocab** [comment] 2020-11-29 11:22
Not sure if this says anything useful:
```
❯ brew deps --verbose --debug tree-sitter
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tree-sitter.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rust.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.9.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libssh2.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/emscripten.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/binaryen.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yuicompressor.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjdk.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb

```

It seems like `deps` finds all the formulae that `tree-sitter` depends on just fine (though I suppose that it no surprise given that it works with `--tree`), it's just not printing them.

I'll try to have a poke around `cmd/deps.rb` to see if I can figure something out.

**Comment by EricFromCanada** [comment] 2020-11-30 00:21
Could be related to `@use_runtime_dependencies`. Try running `brew deps --include-test --verbose --debug tree-sitter` which will force it to be false.

**Comment by carlocab** [comment] 2020-11-30 00:34
Yes, I had discovered that `brew deps --include-test tree-sitter` correctly returns the (recursive) list of dependencies. I tried each of the possible flags for `deps`. Didn't try combinations of them though.

Adding the flags `--verbose` and `--debug` just prepends that list with the output from my last comment.

In case it's helpful:
- `n`: nothing
- `1`: complete
- `include-build`: complete
- `union`: nothing
- `full-name`: nothing
- `include-test`: complete
- `annotate`: nothing
- `include-requirements`: `:macOS >= 10.11`
- `installed`: nothing
- `--for-each`: just `tree-sitter:`

Of course, "complete" is with respect to what that flag is supposed to print out.

**Comment by EricFromCanada** [comment] 2020-11-30 03:04
Try running `brew ruby -e 'puts "tree-sitter".f.runtime_dependencies'`. For me it returns this, but it might be blank for you: 
```
$ brew ruby -e 'puts "tree-sitter".f.runtime_dependencies'
binaryen
icu4c
node
gdbm
openssl@1.1
readline
sqlite
xz
python@3.9
openjdk
yuicompressor
emscripten
```

**Comment by carlocab** [comment] 2020-11-30 03:11
I don't understand enough of the `brew` codebase to figure out what's happening, but I did wonder if other formulae were also not reporting their dependencies correctly.

I wrote a little script to check:

```
#!/usr/bin/env zsh

formulae_dir="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula"

for formula in $formulae_dir/*.rb; do
    if [[ -n "$(brew deps --include-test $formula)" ]]; then
        if [[ -z "$(brew deps $formula)" ]]; then
            echo $formula
        fi
    fi
done
```

I don't actually recommend you run that, because it will take ages. However, I did run a version of this using `parallel`. This will produce false positives: some formulae may have no dependencies other than those required for testing.

After filtering out the formulae that actually do have test dependencies, I came up with this list:

```
acme
ddrescue
ed
lcs
make
moe
ocrad
snap7
spim
tree-sitter
```

It seems there's a second kind of problem, where `brew deps --include-test` falsely reports non-existent dependencies.

For example:
```
❯ cd $(brew --repo homebrew/core)/Formula
❯ grep ':test' acme.rb
❯ brew deps --include-test acme
apr
apr-util
gettext
lz4
openssl@1.1
perl
readline
sqlite
subversion
utf8proc
❯ brew deps --tree acme
acme

```

`brew deps --tree acme` is correct: `acme` has no listed dependencies.

**Comment by carlocab** [comment] 2020-11-30 03:12
> Try running `brew ruby -e 'puts "tree-sitter".f.runtime_dependencies'`.

It is blank for me.

**Comment by Rylan12** [comment] 2020-11-30 05:07
> It seems there's a second kind of problem, where `brew deps --include-test` falsely reports non-existent dependencies.

I _can_ reproduce this one 🤔. It seems that `brew deps --include-test acme` and `brew deps --include-build acme` show lists of dependencies that, according to [the formula file](https://github.com/Homebrew/homebrew-core/blob/master/Formula/acme.rb), don't exist (as the formula seems to declare no dependencies).

Based on the output of `brew info acme` and adding `--tree` to the above commands, it seems that `subversion` is appearing as a build dependency of `acme`. Not sure why 🤔

```console
$ brew info acme
acme: stable 0.97 (bottled)
Crossassembler for multiple environments
https://sourceforge.net/projects/acme-crossass/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/acme.rb
License: GPL-2.0-or-later
==> Dependencies
Build: subversion
==> Analytics
install: 639 (30 days), 1,763 (90 days), 9,978 (365 days)
install-on-request: 638 (30 days), 1,758 (90 days), 9,953 (365 days)
build-error: 0 (30 days)
```

```console
$ brew deps --tree acme
acme
```

```console
$ brew deps --include-test --tree acme
acme
└── subversion
    ├── apr
    ├── apr-util
    │   ├── apr
    │   └── openssl@1.1
    ├── gettext
    ├── lz4
    ├── openssl@1.1
    ├── perl
    ├── sqlite
    │   └── readline
    └── utf8proc
```

```console
$ brew deps --include-build --tree acme
acme
└── subversion
    ├── openjdk
    │   └── autoconf
    ├── pkg-config
    ├── python@3.9
    │   ├── pkg-config
    │   ├── gdbm
    │   ├── openssl@1.1
    │   ├── readline
    │   ├── sqlite
    │   │   └── readline
    │   └── xz
    ├── scons
    │   └── python@3.9
    │       ├── pkg-config
    │       ├── gdbm
    │       ├── openssl@1.1
    │       ├── readline
    │       ├── sqlite
    │       │   └── readline
    │       └── xz
    ├── swig
    │   └── pcre
    ├── apr
    │   └── autoconf
    ├── apr-util
    │   ├── apr
    │   │   └── autoconf
    │   └── openssl@1.1
    ├── gettext
    ├── lz4
    ├── openssl@1.1
    ├── perl
    ├── sqlite
    │   └── readline
    └── utf8proc
```

**Comment by MikeMcQuaid** [comment] 2020-11-30 11:49
> I _can_ reproduce this one 🤔. It seems that `brew deps --include-test acme` and `brew deps --include-build acme` show lists of dependencies that, according to [the formula file](https://github.com/Homebrew/homebrew-core/blob/master/Formula/acme.rb), don't exist (as the formula seems to declare no dependencies).

The formula file is not authoritative for installed formulae, the actual detected linkage of the formula is. 

Closing as the original issue cannot be reproduced by multiple maintainers. Feel free to continue discussion here though.

**Closed by MikeMcQuaid** 2020-11-30 11:49 UTC

**Comment by carlocab** [comment] 2020-11-30 13:48
> The formula file is not authoritative for installed formulae, the actual detected linkage of the formula is.

Doesn't brew need the formula installed to detect linkage though? At least, that's my guess since `brew linkage <formula>` returns an error for formulae that are not installed (which `brew help linkage` also mentions).

This makes the `acme` example troubling for me, as it seems to detect linkage (or otherwise think there's a dependency) even though I don't have `acme` installed.
 
> Closing as the original issue cannot be reproduced by multiple maintainers. Feel free to continue discussion here though.

Right. I just tried it again and I can't reproduce it anymore either, so... 🤷 Apologies if this was all a waste of time.

**Comment by EricFromCanada** [comment] 2020-11-30 13:56
`acme` has `subversion` as a build dependency because its URL is [detected to be for an SVN repo](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/download_strategy.rb#L1223) and your system's Xcode or CLT don't ship with `svn`.

**Comment by carlocab** [comment] 2020-11-30 14:02
Cool. I wish I understood how `brew deps` actually resolved dependencies.

Thanks for taking the time to look into this, everyone.
