### ISSUE TITLE
Still warning/erroring about breaking things that are on the list to be uninstalled

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#1583] opened 2016-11-27 07:50 UTC
CC @alyssais @MikeMcQuaid 

I thought this one had been nipped in the bud, but unfortunately apparently not:
```
Josephs-MacBook-Pro:Cellar joe$ brew uninstall -f gperftools leveldb lz4 rocksdb snappy influxdb08
Warning: /usr/local/Cellar/gperftools/2.5, /usr/local/Cellar/snappy/1.1.3, /usr/local/Cellar/leveldb/1.19, /usr/local/Cellar/lz4/r131, /usr/local/Cellar/rocksdb/4.11.2_1 are required by influxdb08, which is currently installed.
You can silence this warning with:
  brew uninstall --ignore-dependencies gperftools, snappy, leveldb, lz4, rocksdb
Uninstalling gperftools... (101 files, 3.8M)
Uninstalling leveldb... (26 files, 1.3M)
Uninstalling lz4... (19 files, 409.3K)
Uninstalling rocksdb... (84 files, 13.7M)
Uninstalling snappy... (20 files, 421.0K)
Uninstalling influxdb08... (6 files, 12.4M)
```

**Comment by MikeMcQuaid** [comment] 2016-11-27 08:24
Will try to prioritise this but a dupe of https://github.com/Homebrew/brew/issues/1524.

**Closed by MikeMcQuaid** 2016-11-27 08:24 UTC
