### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by chmaynard** [Homebrew/brew#574] opened 2016-07-22 13:38 UTC
I'm not sure if the error message below refers to the afl-fuzz archive or to Homebrew in general. I removed the archive and tried again. Same message.

```
==> Upgrading afl-fuzz
==> Downloading http://lcamtuf.coredump.cx/afl/releases/afl-2.20b.tgz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: f84f3b2e6e52fc03b737f2cb7988996b88668da8de9810dfd797d81cc17de23b
Actual: b7e2d422aa9bc104ddd2bf49f932d55c73627722cc38736124a8febdd64e9431
Archive: /Users/craig/Library/Caches/Homebrew/afl-fuzz-2.20b.tgz
To retry an incomplete download, remove the file above.
```

**Comment by bfontaine** [comment] 2016-07-22 13:48
I can reproduce:

```
$ curl -sL 'http://lcamtuf.coredump.cx/afl/releases/afl-2.20b.tgz' | shasum -a 256
b7e2d422aa9bc104ddd2bf49f932d55c73627722cc38736124a8febdd64e9431  -
```

> I'm not sure if the error message below refers to the afl-fuzz archive or to Homebrew in general

It refers to the checksum of the archive that’s recorded in the formula. When a formula get upgraded we write the new archive’s checksum down so that we can then verify we download the correct one. Getting a SHA256 mismatch usually means either you have a proxy or something that changes what you download (but that’s not the case here since I can reproduce) or upstream got hacked and someone replaced their archives, or upstream updated the archive without bumping the version.

**Comment by DomT4** [comment] 2016-07-22 14:34
@alex Any chance upstream retagged this since your merged PR yesterday? It did pass CI at the time, so it might have been correct then.

**Comment by alex** [comment] 2016-07-22 14:38
Yes, upstream did: https://groups.google.com/forum/#!topic/afl-users/tTR5KcoecGs

**Comment by DomT4** [comment] 2016-07-22 14:47
Thanks for the confirmation! I see someone has already pointed out upstream retags are more problematic than bumping the version a little, so I won't ask us to do that again 😄.

Anyone who wants to file a PR to bump the formula revision & update the SHA256 is welcome to do so, otherwise I'll get to it in half an hour or so.

**Comment by chmaynard** [comment] 2016-07-22 15:09
@bfontaine Thanks for the clarification.

**Closed** 2016-07-22 16:25 UTC

**Comment by DomT4** [comment] 2016-07-22 16:32
Should be fixed after a `brew update`. Thanks for the report @chmaynard!
