### ISSUE TITLE
A newer Command Line Tools release is available. But no.

### ISSUE THREAD

**Issue by alexeikaratai** [Homebrew/brew#5011] opened 2018-10-01 14:33 UTC
system:
MAC OS 10.14 
```
brew -v
Homebrew 1.7.6-47-g1f53099
Homebrew/homebrew-core (git revision afeeb; last commit 2018-10-01)
Homebrew/homebrew-cask (git revision 802d48; last commit 2018-10-01)
```
- What you were trying to do (and why)
**Try to run command brew update && brew upgrade && brew doctor && brew info**
- What happened (include command output)
```
$ brew update && brew upgrade && brew doctor && brew info
Updated 1 tap (homebrew/core).
==> Updated Formulae
opencv
Updating Homebrew...
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

$xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
$ softwareupdate --list
Software Update Tool

Finding available software
No new software available.
```
- What you expected to happen
no warnings and errors

**Comment by MikeMcQuaid** [comment] 2018-10-01 14:34
Duplicate of 
https://github.com/Homebrew/brew/issues/5006

From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Closed by MikeMcQuaid** 2018-10-01 14:34 UTC
