### ISSUE TITLE
install failed on Arch Linux

### ISSUE THREAD

**Issue by matmis** [Homebrew/brew#6970] opened 2020-01-27 19:17 UTC
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install brew to try something

## What happened (include command output)

Install failed

<details>
  <summary>Command output</summary>
  <pre>

$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/matthijs/.cache/Homebrew/
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at e47a6ac4c Merge pull request #6967 from sjackman/bottle-root-url
Traceback (most recent call last):
        4: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
        3: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
        2: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:13:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force

  </pre>
</details>

## What you expected to happen

Install without failure

## Step-by-step reproduction instructions

sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
Traceback (most recent call last):
        4: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
        3: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
        2: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:13:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)

</pre>
<pre>
$ brew doctor
Traceback (most recent call last):
        4: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
        3: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
        2: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:13:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)

</pre>

**Comment by dawidd6** [comment] 2020-01-27 19:27
Duplicate of: https://github.com/Homebrew/brew/issues/6952

**Closed** 2020-01-27 20:04 UTC
