### ISSUE TITLE
Stack too deep

### ISSUE THREAD

**Issue by romerve** [Homebrew/brew#12407] opened 2021-11-10 00:21 UTC
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 64fb3c86f87eaf4a4b2ba64ddec0a5a3f2530b4c
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ac1b30bfd9c124d67297af0c3731acde848591d2
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-x86_64
CLT: 13.1.0.0.1.1633545042
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  bicep
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the argoproj/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/argoproj/homebrew-tap/kubectl-argo-rollouts.rb:8

Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:42:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:359:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:351:in `+'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:310:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:547:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:547:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:418:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:484:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:457:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1704:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1703:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1703:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1703:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:700:in `check_deprecated_disabled'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Simply trying to update and then upgrade brew

### What happened (include all command output)?

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the argoproj/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/argoproj/homebrew-tap/kubectl-argo-rollouts.rb:8

Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/tap.rb:46:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/tap.rb:46:in `any?'
/usr/local/Homebrew/Library/Homebrew/tap.rb:46:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:308:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'

### What did you expect to happen?

brew to successfully upgrade

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
brew list
==> Formulae
augeas				dapr-cli			kubectl-argo-rollouts		openssl@1.1
azure-cli			dialog				libev				python@3.8
azure-functions-core-tools@3	gdbm				libnghttp2			python@3.9
bicep				gh				libuv				readline
brotli				helm				mpdecimal			sqlite
c-ares				icu4c				nghttp2				tcl-tk
ca-certificates			jemalloc			node				xz
certbot				jq				oniguruma

==> Casks
docker-edge		dotnet-sdk		dotnet-sdk3-1-400	github-beta		sfdx
```

**Comment by carlocab** [comment] 2021-11-10 00:27
Duplicate of #12370

**Closed by carlocab** 2021-11-10 00:27 UTC
Labels: bug
