### ISSUE TITLE
SCRCPY not working on Huawei

### ISSUE THREAD

**Issue by ixlatall** [Homebrew/brew#8936] opened 2020-10-17 04:33 UTC
# Please fill out one of the templates on: https://github.com/Homebrew/brew/issues/new/choose or we will close it without comment.
Hey guys.  I installed scrcpy on my 2012 Macbook Pro (High Sierra). It works flawlessly with my Moto G7 but I am getting the following results with my Huawei P30 Lite.  (I have debugging and ADB turned on, and I've tried every combination I can think of with debugging and File Transfer options. 

Can anyone help please?

![Screen Shot 2020-10-16 at 10 31 28 PM](https://user-images.githubusercontent.com/62350398/96328357-261eb580-1010-11eb-800e-abf79dc9dfb0.png)

**Comment by iMichka** [comment] 2020-10-17 07:06
Duplicate of #8937

**Closed by iMichka** 2020-10-17 07:06 UTC
