### ISSUE TITLE
`brew bump --open-pr <token>` fails on `gpg` signing step

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#16266] opened 2023-11-29 11:00 UTC
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.22-4-g0ed0d9b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0ed0d9bafc033b1dd542e0751cbd54b5901d2513
Last commit: 15 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3a8825306d1f7a20e24fc12ac8f89193c2c85ce8
Core tap last commit: 23 minutes ago
Core tap branch: master
Core tap JSON: 29 Nov 10:19 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: subl -w
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/opt/git/bin/git
Curl: 8.4.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 14.1.1-arm64
CLT: 15.1.0.0.1.1699597245
Xcode: 15.1 => /Applications/Xcode_15.1_b3.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

I want to bump some formulas or casks with brew `bump --open-pr <token>` while `gpg` signing is enabled in `git` config.

I'm volunteering to fix this issue, I just want to make sure it wouldn't be rejected because just some unsupported config in my setup causes it. Furthermore, I'm able to reproduce with `GnuPG`, as well as on ArchLinux machine, but it has the same set of configs as on my Mac. IIRC `gpg` on Linux needs to be unlocked first by making some commit in interactive shell in order to `brew bump*` family of commands start to work.

### What happened (include all command output)?

```
╭─yurikoles at Air-M1-16GB in ~ 23-11-29 - 10:14:09
╰─○ brew bump mlt --open-pr
==> mlt
Current formula version:  7.20.0
Latest livecheck version: 7.22.0
Latest Repology version:  7.22.0
Open pull requests:       none
Closed pull requests:     none
==> Downloading https://github.com/mltframework/mlt/releases/download/v7.22.0/mlt-7.22.0.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/4019052/6c4329fd-1111-4a40-8cc6-a778
############################################################################################################################### 100.0%
Warning: Cannot verify integrity of '13839669d08132753d8ea3a9ce6ca5493d4db81691e657c47dcc2a1767ffaec8--mlt-7.22.0.tar.gz'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "7cf4d9573a061d76902c6e12a2f09f5f461e7c697635233df82a63a3fe4d6da6"
==> replace /https:\/\/github\.com\/mltframework\/mlt\/releases\/download\/v7\.20\.0\/mlt\-7\.20\.0\.tar\.gz/ with "https://github.com
==> replace "7472372b31f76b2eb0ac66c756391be7cb859a3a779c97ccb7dcf7086ac9d816" with "7cf4d9573a061d76902c6e12a2f09f5f461e7c697635233df
M	Formula/m/mlt.rb
Switched to a new branch 'bump-mlt-7.22.0'
error: cannot run gpg: No such file or directory
error: gpg failed to sign the data:
(no gpg output)
fatal: failed to write commit object
Error: Failure while executing; `git commit --no-edit --verbose --message=mlt\ 7.22.0 -- /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m/mlt.rb` exited with 128.
```

### What did you expect to happen?

`brew bump --open-pr <token>` should successfully sign a commit and produce a PR, just like `brew bump-formula-pr ...` or `brew bump-cask-pr ...`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
╭─yurikoles at Air-M1-16GB in ~ 23-11-29 - 10:48:58
╰─○ git config --global commit.gpgsign     
true
╭─yurikoles at Air-M1-16GB in ~ 23-11-29 - 10:49:03
╰─○ git config --global user.signingKey                 
725379F6ADCB49E5
╭─yurikoles at Air-M1-16GB in ~ 23-11-29 - 10:49:24
╰─○ type -a git
git is /opt/homebrew/bin/git
git is /usr/bin/git
╭─yurikoles at Air-M1-16GB in ~ 23-11-29 - 10:49:40
╰─○ type -a gpg
gpg is /usr/local/MacGPG2/bin/gpg
gpg is /opt/homebrew/bin/gpg
```

**Comment by MikeMcQuaid** [comment] 2023-11-29 11:12
> I'm volunteering to fix this issue, I just want to make sure it wouldn't be rejected because just some unsupported config in my setup causes it.

We'll review a PR, thanks. Closing here though because I cannot reproduce and signing works fine here.

**Closed by MikeMcQuaid** 2023-11-29 11:12 UTC
Labels: bug
