### ISSUE TITLE
`brew install` checks out master branch of tap while editing formula

### ISSUE THREAD

**Issue by jacobsa** [Homebrew/brew#792] opened 2016-08-23 00:46 UTC
I'm attempting to update the formula for gcsfuse, within homebrew/homebrew-fuse. I've got a branch for my change in the git client, and it is checked out:

    cd ~/.homebrew/Library/Taps/homebrew/homebrew-fuse
    git checkout gcsfuse-0.19.0

However, every time I run `brew install -v gcsfuse` to test installing it, I get the old version of the formula. Afterward, my git client is back to the `master` branch. It appears the first thing `brew install` does is `git checkout master` in the tap.

This looks like new behavior; I only recently updated homebrew after a long time. Is there a flag to disable this when testing a new version of a formula?

**Comment by MikeMcQuaid** [comment] 2016-08-23 09:22
Duplicate of https://github.com/Homebrew/brew/issues/737. In short: set `HOMEBREW_DEVELOPER` for now but I'm aware it's not the best behaviour so am going to improve it.

**Closed by MikeMcQuaid** 2016-08-23 09:22 UTC

**Comment by anthonygreen** [comment] 2016-09-05 05:35
Can we add this to the CONTRIBUTING.md please? I got caught out by it too.

**Comment by MikeMcQuaid** [comment] 2016-09-05 19:31
@anthonygreen We're going to improve the messaging (in a PR likely merged today) and I'm going to overhaul the behaviour so it assumes people are `HOMEBREW_DEVELOPER`s.
