### ISSUE TITLE
Bottle upload jobs failing on test-bot

### ISSUE THREAD

**Issue by apjanke** [Homebrew/brew#207] opened 2016-05-06 19:53 UTC
The jobs on the "Homebrew Bottles" queue have been failing about half the time today. I ran in to some failures yesterday, too.

<img width="553" alt="screen shot 2016-05-06 at 3 49 39 pm" src="https://cloud.githubusercontent.com/assets/2618447/15084555/2e5b8512-13a2-11e6-8a57-3c4a29581e09.png">

All of the failed ones that I looked at are failing with complaints about failure to lock refs in one of the Homebrew git repos. For example, http://bot.brew.sh/job/Homebrew%20Bottles/49221/.

```
[EnvInject] - Variables injected successfully.
[workspace] $ /bin/sh -xe /var/folders/3m/6yv2qtq95_s88tl3f26y5ymh0000gp/T/hudson3836490006099204134.sh
+ '[' -d .git ']'
+ rm -rf '.git/refs/heads/*.lock'
+ git fetch origin
+ git reset --hard origin/master
HEAD is now at d887dd3 brew install: make -s apply only to given formula, not deps (#205)
+ brew test-bot --ci-upload
cp /Users/brew/Jenkins/jobs/Homebrew PHP Pull Requests/configurations/axis-version/el_capitan/builds/1709/archive/tokyo-tyrant-1.1.41_1.el_capitan.bottle.rb /Users/brew/Jenkins/jobs/Homebrew PHP Pull Requests/configurations/axis-version/el_capitan/builds/1709/archive/tokyo-tyrant-1.1.41_1.el_capitan.bottle.tar.gz /Users/brew/Jenkins/jobs/Homebrew PHP Pull Requests/configurations/axis-version/mavericks/builds/1709/archive/tokyo-tyrant-1.1.41_1.mavericks.bottle.rb /Users/brew/Jenkins/jobs/Homebrew PHP Pull Requests/configurations/axis-version/mavericks/builds/1709/archive/tokyo-tyrant-1.1.41_1.mavericks.bottle.tar.gz /Users/brew/Jenkins/jobs/Homebrew PHP Pull Requests/configurations/axis-version/yosemite/builds/1709/archive/tokyo-tyrant-1.1.41_1.yosemite.bottle.rb /Users/brew/Jenkins/jobs/Homebrew PHP Pull Requests/configurations/axis-version/yosemite/builds/1709/archive/tokyo-tyrant-1.1.41_1.yosemite.bottle.tar.gz /Users/brew/Jenkins/jobs/Homebrew Bottles/workspace
git checkout -f master
Already on 'master'
Your branch is ahead of 'origin/master' by 7 commits.
  (use "git push" to publish your local commits)
git reset --hard origin/master
HEAD is now at 2c4a963 phpbrew: update 1.21.1 bottle.
brew update
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at ea1315340e1a836d1ac0a37f07bc03348dfd4899 but expected 2c4a963efdae8dc1acb59b59b898e080aa587561
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at ea1315340e1a836d1ac0a37f07bc03348dfd4899 but expected 2c4a963efdae8dc1acb59b59b898e080aa587561
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at ea1315340e1a836d1ac0a37f07bc03348dfd4899 but expected 2c4a963efdae8dc1acb59b59b898e080aa587561
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at ea1315340e1a836d1ac0a37f07bc03348dfd4899 but expected 2c4a963efdae8dc1acb59b59b898e080aa587561
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at ea1315340e1a836d1ac0a37f07bc03348dfd4899 but expected 2c4a963efdae8dc1acb59b59b898e080aa587561
error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/Users/brew/Jenkins/jobs/Homebrew 
```

Anyone know what's going on here? About half the time, manually retrying the jobs works. About half the time, it fails again on attempts to lock refs.

Is there another Homebrew project that could be running on the `master` Jenkins node and touching the repo? Is there any way of getting a per-node view of all the activity that has run on that node, instead of viewing it by project build queue?

Full log is in this gist. https://gist.github.com/apjanke/588837bddf570c5ff9031124c52ee38f

**Comment by apjanke** [comment] 2016-05-06 20:50
Wait a minute. In each of the projects, it still does some Git activity on master. Most of the projects are set up with distinct workspaces, so they don't collide. You can see this by examining the Console Output for a build job on the [main node](http://bot.brew.sh/job/Homebrew%20Apache%20Pull%20Requests/56/console) and not one of the configurations (mavericks/yosemite/el capitan).

[Here's](http://bot.brew.sh/job/Homebrew%20Apache%20Pull%20Requests/56/console) what the Apache project's jobs look like:

```
GitHub pull request #117 of commit ab74c60e6c4ee74e8db31427c912be12adbc04dc, no merge conflicts.
Setting status of ab74c60e6c4ee74e8db31427c912be12adbc04dc to PENDING with url http://bot.brew.sh/job/Homebrew%20Apache%20Pull%20Requests/56/ and message: 'Build started sha1 is merged.'
[EnvInject] - Loading node environment variables.
Building on master in workspace /Users/brew/Jenkins/apache
 > git rev-parse --is-inside-work-tree # timeout=10
``` 

[Here's](http://bot.brew.sh/job/Homebrew%20Dupes%20Pull%20Requests/259/console) what Dupes looks like:
```
GitHub pull request #600 of commit f4a41ab27ef01e44385aedf2da77668d4f559604, no merge conflicts.
Setting status of f4a41ab27ef01e44385aedf2da77668d4f559604 to PENDING with url http://bot.brew.sh/job/Homebrew%20Dupes%20Pull%20Requests/259/ and message: 'Build started sha1 is merged.'
[EnvInject] - Loading node environment variables.
Building on master in workspace /Users/brew/Jenkins/dupes
 > git rev-parse --is-inside-work-tree # timeout=10
```

[Here's](http://bot.brew.sh/job/Homebrew%20Versions%20Pull%20Requests/1382/console) what Versions looks like:
```
GitHub pull request #1252 of commit 2bbb6bf27d6293a01c782c16e4ae9caa358ffc7d, no merge conflicts.
Setting status of 2bbb6bf27d6293a01c782c16e4ae9caa358ffc7d to PENDING with url http://bot.brew.sh/job/Homebrew%20Versions%20Pull%20Requests/1382/ and message: 'Build started sha1 is merged.'
[EnvInject] - Loading node environment variables.
Building on master in workspace /Users/brew/Jenkins/versions
 > git rev-parse --is-inside-work-tree # timeout=10
```

[Here's](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1448/console) what Core looks like:
```
GitHub pull request #914 of commit 76a950a7e0f339ec289dd80a6a36233f6689a9b0, no merge conflicts.
Setting status of 76a950a7e0f339ec289dd80a6a36233f6689a9b0 to PENDING with url http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1448/ and message: 'Build started sha1 is merged.'
[EnvInject] - Loading node environment variables.
Building on master in workspace /Users/brew/Jenkins/versions
 > git rev-parse --is-inside-work-tree # timeout=10
```

Wait a minute – "workspace `/Users/brew/Jenkins/versions`"? Not `/Users/brew/Jenkins/core`?

Here's a Jenkins build timeline from today.

<img width="355" alt="screen shot 2016-05-06 at 4 22 53 pm" src="https://cloud.githubusercontent.com/assets/2618447/15085221/e0168cb2-13a6-11e6-979b-eaac2504306e.png">

Some of those Bottles jobs are overlapping other jobs. Is that supposed to happen?

Homebrew Core Pull Requests # 1450 ran from 20:41:43 to 20:54:44
Homebrew Bottles # 49226 ran from 20:45:19 to 20:45:39 (and failed)

Similarly, Homebrew Bottles # 49228 overlapped a Homebrew Versions PR run.

Here's another clue. The error message from one of the failed bottle runs is complaining about an extant lock file in the `homebrew/versions` tap inside its workspace.

```
git reset --hard origin/master
HEAD is now at 96bff5b gnupg21: add 2.1.12 bottle.
brew update
error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/Users/brew/Jenkins/jobs/Homebrew Bottles/workspace/Library/Taps/homebrew/homebrew-versions/.git/refs/remotes/origin/master.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
```

Most of the others just complain about remote ref SHA mismatches.

```

git checkout -f master
Already on 'master'
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
git reset --hard origin/master
HEAD is now at a6b99a5 civl: remove cvc4 dependency
brew update
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at f08e21a7961085ca4452b778c0b56e8f4982a144 but expected a6b99a561cf09867c7613a6fdc937b53cc72ba65
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at f08e21a7961085ca4452b778c0b56e8f4982a144 but expected a6b99a561cf09867c7613a6fdc937b53cc72ba65
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at f08e21a7961085ca4452b778c0b56e8f4982a144 but expected a6b99a561cf09867c7613a6fdc937b53cc72ba65
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at f08e21a7961085ca4452b778c0b56e8f4982a144 but expected a6b99a561cf09867c7613a6fdc937b53cc72ba65
```

This is a brew update operation that seems to be interacting with some job's git operations.

Here's another thing. most of the projects seem to have their own workspaces. But Versions and Core do not. Could their workspaces be aliased to `/usr/local`, so that their local in-workspace git operations are acting on the same repo that Bottle's `brew update` is acting on?

```
robotunicorn:jobs brew$ pwd
/Users/brew/Jenkins/jobs
robotunicorn:jobs brew$ ls -ld */workspace
drwxr-xr-x+  2 brew  staff   68 Nov 27  2014 Homebrew Apache Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Oct 30  2014 Homebrew Binary Pull Requests/workspace
drwxr-xr-x+ 14 brew  staff  476 May  6 21:46 Homebrew Bottles/workspace
drwxr-xr-x+  2 brew  staff   68 Oct 25  2014 Homebrew Completions Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Dec 30  2014 Homebrew Devel-Only Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Oct 23  2014 Homebrew Dupes Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Oct 23  2014 Homebrew Games Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Oct 30  2014 Homebrew Head-Only Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Nov  4  2014 Homebrew Nginx Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Oct 30  2014 Homebrew PHP Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Oct 30  2014 Homebrew Python Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Oct 23  2014 Homebrew Science Pull Requests/workspace
drwxr-xr-x+  2 brew  staff   68 Feb  8  2014 Homebrew Testing/workspace
drwxr-xr-x+  2 brew  staff   68 Nov  6  2014 Homebrew X11 Pull Requests/workspace
robotunicorn:jobs brew$
```

**Comment by mikemcquaid** [comment] 2016-05-08 19:45
@apjanke The bottle job should be using the Homebrew just in the `Homebrew Bottles/workspace` workspace and not touching anything in `/usr/local`. Looking at the configuration this should be what's happening (but clearly isn't)?

**Comment by ilovezfs** [comment] 2016-05-09 12:18
it may be the rebase-is-default-now thing again

**Comment by mikemcquaid** [comment] 2016-05-10 09:05
> error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at f08e21a7961085ca4452b778c0b56e8f4982a144 but expected a6b99a561cf09867c7613a6fdc937b53cc72ba65

This is the issue; it's barfing at the different between `legacy-homebrew.git` and `brew.git`. I've pulled these into a separate upload job (http://bot.brew.sh/job/Legacy%20Homebrew%20Bottles/) which should have fixed the problem.

**Comment by UniqMartin** [comment] 2016-05-11 08:16
I don't think this is fixed yet. 😢 I pulled several bottles last night and for (almost) every one of them I had to restart a failed bottle job, sometimes twice, to make it succeed. The failed ones have a multitude of the usual `error: cannot lock ref` messages …

**Comment by mikemcquaid** [comment] 2016-05-11 08:18
Ok. I think somehow it's still related. It would be good if it was more than just me working on a fix here 😉

**Comment by apjanke** [comment] 2016-05-11 16:40
Sorry for lack of PR to go with the bug report. Really not familiar with this area of `brew`. Have been reading through the code and Jenkins output to figure out how to approach it, but still don't understand it well enough to suggest any concrete fix.

I'm going to log in to the box and manually examine its Homebrew installation to see if anything stands out.

The Jenkins build timeline only seems to be showing half a day's worth of runs. Is there a way to retain more of that so we can get a better view of things?

**Comment by apjanke** [comment] 2016-05-11 17:01
I added an email notification post-build step to the Homebrew Bottles project configuration, to notify me upon failure, so I can log in and get a fresh look at the state of the Homebrew prefix repos right after a failed run.

**Comment by UniqMartin** [comment] 2016-05-12 05:44
> It would be good if it was more than just me working on a fix here 😉

Agreed. I tried unsuccessfully yesterday. Looked at the `test-bot` code and spent a lot of time poking the Jenkins configuration. Even though I found nothing yet, I'm now much more familiar with Jenkins and have a much better understanding of our Jenkins setup.

> Sorry for lack of PR to go with the bug report. Really not familiar with this area of `brew`.

I don't think there's something to be sorry about. I too wouldn't know how to make a PR if I didn't know yet what the underlying issue is.

> The Jenkins build timeline only seems to be showing half a day's worth of runs. Is there a way to retain more of that so we can get a better view of things?

I bumped the number of “Homebrew Bottle” builds to retain from 50 to 100. I believe those builds are relatively lightweight, so shouldn't hurt to keep more of them and provides more data for investigation.

**Comment by ilovezfs** [comment] 2016-05-12 06:08
Is it clear when this started? Any hope of bisecting the problem rather than thinking about it?

**Comment by apjanke** [comment] 2016-05-12 13:19
> Is it clear when this started? Any hope of bisecting the problem rather than thinking about it?

I think the answer is "no" to both of these, because we don't retain enough build history in Jenkins. This has been going on for a few days, but the oldest job I see in Jenkins is [4970](http://bot.brew.sh/job/Homebrew%20Bottles/49570/), from just yesterday.

You could get an approximate date of when it started by looking through comments in PRs and seeing when we started having to re-run them more often, but I think it's several days back, based on my recall of when I started seeing a lot of those failed `brew pull` commands that required reruns.

**Comment by ilovezfs** [comment] 2016-05-12 13:57
@apjanke Could it be https://github.com/Homebrew/brew/commit/1c1c48c92005b27aba4e17e12b49c4d1cbb0b331

**Comment by mikemcquaid** [comment] 2016-05-12 14:20
It's definitely not related to the push. It feels to me that this started happening around the recently `brew pull` changes but I could be wrong. I pretty strongly suspect that something is using the `/usr/local` repository rather than the one in the working directory.

**Comment by UniqMartin** [comment] 2016-05-12 14:25
Was anything changed on Jenkins? There's currently a run of 20 bottle jobs that didn't have the issue.

> @apjanke Could it be 1c1c48c92005b27aba4e17e12b49c4d1cbb0b331

Seems unlikely given that the problem is with the local Git repository (the one on our CI) and not with the remote and the change shouldn't have an influence on the former. (At least that's what I thought.)

But upon closer inspection, those pushes are also messing with the `master` tag and the Git errors are about `refs/remotes/origin/master`. Additionally, the state of `master` might be different between the first (now removed) and the second `git push`. I'd say reverting this change and checking whether that fixes the issue wouldn't be a horrible thing. The problem that is being addressed in the commit seems a lot less pressing than these constant Git-related bottle job failures.

**Comment by apjanke** [comment] 2016-05-12 14:27
> Was anything changed on Jenkins?

Not that I'm aware of. I added a notify-on-failure alert with myself in the recipients list, but didn't make any other changes and don't know of any.

**Comment by mikemcquaid** [comment] 2016-05-12 14:28
The last change I made was the legacy bottles separation. It could be that has fixed it now the backlog was worked through.

**Comment by UniqMartin** [comment] 2016-05-12 14:39
> The last change I made was the legacy bottles separation. It could be that has fixed it now the backlog was worked through.

It was worth a try, but I don't think this had any effect. 😢 It has been in place for like two days (?) and there have been failures since, even with PRs that have been opened less than a day ago.

**Comment by mikemcquaid** [comment] 2016-05-12 14:51
> error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/Users/brew/Jenkins/jobs/Homebrew Bottles/workspace/Library/Taps/homebrew/homebrew-core/.git/refs/remotes/origin/master.lock': File exists.

Added:
`rm -rf .git/refs/heads/*.lock Library/Taps/*/*/.git/refs/remotes/origin/*.lock`

**Comment by mikemcquaid** [comment] 2016-05-12 14:56
Replaced the `git fetch` with a `brew update` now that the `test-bot` redoing it is a quick no-op and so it cleans up every tap rather than just one. Once we have https://github.com/Homebrew/brew/pull/166 we shouldn't need to tap at all.

**Comment by mikemcquaid** [comment] 2016-05-17 20:16
Seems fixed now.

**Closed by mikemcquaid** 2016-05-17 20:16 UTC

**Comment by apjanke** [comment] 2016-05-17 20:59
I got an isolated spate of failure notifications yesterday, but nothing else recently. Does seem fixed.

**Comment by mikemcquaid** [comment] 2016-05-18 07:21
It'll still fail sometimes due to e.g. upload attempts after publishing but it looks generally right now 👍
