### ISSUE TITLE
"Already up-to-date" Bug with `brew update` in macOS 13.2.1

### ISSUE THREAD

**Issue by ocelotStride** [Homebrew/brew#14766] opened 2023-02-22 16:38 UTC
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ba6d87eed9ce31f42fa2b33a4e6067d9cf17f13f
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 49fbe33829353620bcfa42b99e356ce6c78fb07e
Core tap last commit: 13 hours ago
Core tap branch: master
Core tap JSON: 22 Feb 16:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew update` for daily update of the new formulae.

### What happened (include all command output)?

Already up-to-date

### What did you expect to happen?

I expect brew to output any changes and outdated software I have installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just run `brew update` and it says "Already up-to-date." I have tried `brew update-reset` and it didn't change anything. I can run `brew upgrade` and it will still upgrade outdated packages, but I just want the original functionality of `brew update` back.
```

**Comment by MikeMcQuaid** [comment] 2023-02-22 16:39
Duplicate of https://github.com/Homebrew/brew/issues/14706

**Closed by MikeMcQuaid** 2023-02-22 16:39 UTC
Labels: bug
