### ISSUE TITLE
brew cleanup Error: Unknown command: find

### ISSUE THREAD

**Issue by bentonam** [Homebrew/brew#69] opened 2016-04-11 14:53 UTC
Running `brew cleanup` errors and results in the following output:

```
[~]$ brew cleanup                                                                                                                                                    
Error: Unknown command: find
/usr/local/Library/brew.rb:127:in `exit'
/usr/local/Library/brew.rb:127:in `<main>'
```

I have uninstalled and reinstalled brew.  

`brew doctor` returns: Your system is ready to brew.

`ruby --version` is `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]`

**Comment by UniqMartin** [comment] 2016-04-11 15:00
Can you please post the output of `brew config` and `brew cleanup --debug` to help us investigate this issue? Thanks!

**Comment by bentonam** [comment] 2016-04-11 15:03
`brew config`

```
[~]$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4a7cd160c31969b79979ae9bd20afcf82d9513c0
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 530b134420af9a419c38a4f2e1da2d13e18b16f9
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.4-x86_64
Xcode: 7.3
CLT: N/A
Clang: 7.3 build 703
X11: N/A
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/aaronbenton/.rvm/rubies/ruby-2.2.1/bin/ruby
Java: 1.8.0_40, 1.7.0_79
```

`brew cleanup --debug`

```
[~]$ brew cleanup --debug
Error: Unknown command: find
/usr/local/Library/brew.rb:127:in `exit'
/usr/local/Library/brew.rb:127:in `<main>'
```

**Comment by UniqMartin** [comment] 2016-04-11 15:10
What does `which find` yield (it should be `/usr/bin/find`) and what is the output of `echo "$PATH"`? Have you intentionally or accidentally modified your `PATH` to exclude `/usr/bin`?

**Comment by bentonam** [comment] 2016-04-11 15:33
`which find`

```
[~]$ which find
/usr/bin/find
```

`echo "$PATH"`

```
/Users/aaronbenton/.rvm/gems/ruby-2.2.1/bin:/Users/aaronbenton/.rvm/gems/ruby-2.2.1@global/bin:/Users/aaronbenton/.rvm/rubies/ruby-2.2.1/bin:/Users/aaronbenton/.nvm/versions/node/v5.10.1/bin:./node_modules/.bin:/usr/local/opt/coreutils/libexec/gnubin:/bin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/aaronbenton/.rvm/bin
```

`/usr/bin` is listed in the path

**Comment by UniqMartin** [comment] 2016-04-11 16:09
Thanks! To be honest I'm stuck and out of ideas. And trying to reproduce this by temporarily removing `/usr/bin` from PATH showed me that things will break much earlier in various ways, so thinking this might be the issue was silly. Hopefully someone else has an idea how to debug this further …

**Comment by DomT4** [comment] 2016-04-11 18:51
Does this reproduce if you just do `brew` without any arguments or is it exclusive to `brew cleanup` as far as you're aware?

**Comment by bentonam** [comment] 2016-04-11 19:09
As far as I have seen it is exclusive to `brew cleanup`

**Comment by DomT4** [comment] 2016-04-11 19:41
Can you check `brew list` as well?

**Comment by bentonam** [comment] 2016-04-11 19:57
`brew list` returns the following output

```
[~]$ brew list
autoconf  coreutils  freetype  git	    jpeg	  libksba  libtiff  libyaml  nvm      pcre	 pkg-config  thefuck  vim  z
automake  docker     gdbm      imagemagick  libgpg-error  libpng   libtool  lynx     openssl  phantomjs  readline    tree     xz   zsh
```

**Comment by UniqMartin** [comment] 2016-04-11 20:01
Really weird; can you give us the outputs of `file /usr/bin/find` and running it without any arguments, i.e., `/usr/bin/find`?

**Comment by DomT4** [comment] 2016-04-11 20:04
Can you try `brew list --unbrewed` as well? You don't need to provide the output, it's just somewhere else I know we explicitly use `find` and I'm trying to narrow down whether _how_ we call `find` adds to your error or doesn't.

**Comment by bentonam** [comment] 2016-04-11 20:09
@UniqMartin 
`file /usr/bin/find`

```
[~]$ file /usr/bin/find
/usr/bin/find: Mach-O 64-bit executable x86_64
[~]$ find
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
[~]$ /usr/bin/find
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

@DomT4 The command `brew list --unbrewed`  worked as well.

**Comment by UniqMartin** [comment] 2016-04-11 20:18
Can you provide the output of `ls -l $(brew --prefix)/Library/Homebrew/cmd/cleanup.rb` and if that file exists (it should), check whether its contents are those of https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/cleanup.rb?

**Comment by UniqMartin** [comment] 2016-04-11 20:22
And if you're using `bash` as a shell: What is the output of `type brew`?

**Comment by bentonam** [comment] 2016-04-11 21:26
@UniqMartin 

`ls -l $(brew --prefix)/Library/Homebrew/cmd/cleanup.rb`

```
[~]$ ls -l $(brew --prefix)/Library/Homebrew/cmd/cleanup.rb
-rw-r--r-- 1 aaronbenton 1214 Apr 11 10:39 /usr/local/Library/Homebrew/cmd/cleanup.rb
```

The contents of the file are identical from what I have on my machine to what is in master.

`type brew`

```
[~]$ type brew
brew is an alias for brew
```

**Comment by UniqMartin** [comment] 2016-04-11 21:34
> ```
> [~]$ type brew
> brew is an alias for brew
> ```

This looks suspicious (you seem to be using ZSH as your shell). Aliasing `brew` to itself doesn't make much sense. Can you please try (and post the output of):

```
unalias brew
type brew
brew cleanup
```

**Comment by ilovezfs** [comment] 2016-04-12 11:08
Something seems to be literally calling `brew find`.

**Comment by bentonam** [comment] 2016-04-12 12:57
@UniqMartin 

```
unalias brew
type brew
brew cleanup
```

This appears to have worked.  Thanks!

**Comment by ilovezfs** [comment] 2016-04-12 12:58
@bentonam Right but that's not going to be persistent. Open a new terminal window, and same problem, right?

**Comment by xu-cheng** [comment] 2016-04-12 13:09
Try `which brew` to debug the root cause

**Comment by bentonam** [comment] 2016-04-12 16:05
Somehow this was in my `.bash_aliases` 

```
alias brew='brew '
```

**Comment by ilovezfs** [comment] 2016-04-12 16:13
I cannot reproduce the issue just by setting that alias.

**Comment by ilovezfs** [comment] 2016-04-12 16:31
@bentonam also, probably unrelated but worth mentioning

>/Users/aaronbenton/.rvm/gems/ruby-2.2.1/bin:/Users/aaronbenton/.rvm/gems/ruby-2.2.1@global/bin:/Users/aaronbenton/.rvm/rubies/ruby-2.2.1/bin:/Users/aaronbenton/.nvm/versions/node/v5.10.1/bin:./node_modules/.bin:/usr/local/opt/coreutils/libexec/gnubin:/bin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/aaronbenton/.rvm/bin

```
/usr/local/opt/coreutils/libexec/gnubin
```
It's a really bad idea to have that in your PATH.

**Comment by bentonam** [comment] 2016-04-12 17:03
Thanks @ilovezfs I have removed it.

**Comment by UniqMartin** [comment] 2016-04-13 18:44
It would be interesting to understand the root cause of the problem, as the alias alone cannot explain the strange behavior. But closing, as the issue is basically resolved.

**Closed by UniqMartin** 2016-04-13 18:44 UTC
Labels: user configuration
