### ISSUE TITLE
pc_path for pkgconfig conflicts with keg-only packages

### ISSUE THREAD

**Issue by crujose** [Homebrew/brew#6731] opened 2019-11-12 22:44 UTC
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Using `pkg-config` from the pkgconfig formulae to get cflags from libxml2:
```
$ brew info pkgconfig
pkg-config: stable 0.29.2 (bottled)
Manage compile and link flags for libraries
https://freedesktop.org/wiki/Software/pkg-config/
/usr/local/Cellar/pkg-config/0.29.2 (11 files, 626.9KB) *
  Poured from bottle on 2019-11-12 at 13:21:27
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pkg-config.rb
```

## What happened (include command output)
```
$ pkg-config --cflags libxml-2.0
-I/usr/include/libxml2
```
However, `/usr/include` is non-existent on MacOS 10.14 (and possibly earlier).

## What you expected to happen

Probably nothing because libxml2 is keg-only and I did not set `PKG_CONFIG_PATH`.
This is clearly mentioned in the Caveats for libxml2:
```
==> Caveats
libxml2 is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have libxml2 first in your PATH run:
  echo 'export PATH="/usr/local/opt/libxml2/bin:$PATH"' >> ~/.bash_profile

For compilers to find libxml2 you may need to set:
  export LDFLAGS="-L/usr/local/opt/libxml2/lib"
  export CPPFLAGS="-I/usr/local/opt/libxml2/include"

For pkg-config to find libxml2 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
```

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install pkgconfig`
2. `pkg-config --cflags libxml-2.0` and note the output
3. `brew install libxml2` repeating step 2 should produce the same output
4. `PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig" pkg-config --cflags libxml-2.0` and note that the output is now `-I/usr/local/Cellar/libxml2/2.9.9_2/include/libxml2`

This seems to be caused by the pc_path used by pkg-config:
```
$ pkg-config --variable=pc_path pkg-config
/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
```

I don't believe it should include `HOMEBREW_LIBRARY` as part of its path (it's the last one listed above).  This appears to have been intentionally added by the formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pkg-config.rb#L22

Note that this directory contains libxml-2.0.pc but its contents are not valid/relevant:
```
$ cat /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14/libxml-2.0.pc 
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
modules=1

Name: libXML
Version: 2.9.4
Description: libXML library version2.
Requires:
Libs: -L${libdir} -lxml2
Libs.private: -lz -lpthread -licucore -lm
Cflags: -I${includedir}/libxml2
```

For reference, here are the contents of the libxml-2.0.pc installed by brew:
```
$ cat /usr/local/Cellar/libxml2/2.9.9_2/lib/pkgconfig/libxml-2.0.pc 
prefix=/usr/local/Cellar/libxml2/2.9.9_2
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
modules=1

Name: libXML
Version: 2.9.9
Description: libXML library version2.
Requires:
Libs: -L${libdir} -lxml2
Libs.private:  -lpthread -lz   -liconv -lm  
Cflags: -I${includedir}/libxml2 
```

This problem could happen for a number of packages, I just happened to be dealing with libxml2.  Here are the contents of the `HOMEBREW_LIBRARY` path:
```
$ ls /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14/
libcurl.pc    libexslt.pc   libxml-2.0.pc libxslt.pc    sqlite3.pc    uuid.pc       zlib.pc
```
These pkgconfig files come from the [brew](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/os/mac/pkgconfig) repository but it's not clear to me why/if they're necessary.  Likewise, it's not clear to me why/if the `HOMEBREW_LIBRARY` path should exist for the [pkgconfig formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pkg-config.rb#L22).

**Comment by MikeMcQuaid** [comment] 2019-11-13 16:54
> However, `/usr/include` is non-existent on MacOS 10.14 (and possibly earlier).

This is the root and a duplicate of https://github.com/Homebrew/brew/issues/5068.

**Closed by MikeMcQuaid** 2019-11-13 16:54 UTC
