### ISSUE TITLE
`brew unbottled` finds no unbottled dependencies

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#9451] opened 2020-12-07 18:10 UTC
Maybe I am misunderstanding how `brew unbottled` works. I didn't expect this result:

```
$ brew unbottled --tag arm64_big_sur
==> Getting formulae...
==> Getting analytics data...
==> Populating dependency tree...
==> Unbottled :arm64_big_sur dependencies (sorted by installs in the last 90 days)
No unbottled dependencies found!
$ brew unbottled --tag arm64_big_sur gmp
==> Populating dependency tree...
==> Unbottled :arm64_big_sur dependencies
No unbottled dependencies found!
$ brew unbottled --tag arm64_big_sur node
==> Populating dependency tree...
==> Unbottled :arm64_big_sur dependencies
No unbottled dependencies found!
```

**Comment by issyl0** [comment] 2020-12-07 19:01
For completeness, what did you expect the result to be?

**Comment by issyl0** [comment] 2020-12-07 22:52
I don't know how yet (👀 🤔), but I think it might be interpreting `arm64_big_sur` as `big_sur`. For example, I get the same output when I specify `big_sur` or `arm64_big_sur`:

```
➜ brew unbottled --tag big_sur
==> Getting formulae...
==> Getting analytics data...
==> Populating dependency tree...
==> Unbottled :big_sur dependencies (sorted by installs in the last 90 days)
No unbottled dependencies found!

➜ brew unbottled --tag arm64_big_sur
==> Getting formulae...
==> Getting analytics data...
==> Populating dependency tree...
==> Unbottled :arm64_big_sur dependencies (sorted by installs in the last 90 days)
No unbottled dependencies found!

And the `--total` for each of those is the same: `44/5687 remaining.`

**Comment by issyl0** [comment] 2020-12-07 23:34
I managed to narrow it down through the bottles code to https://github.com/Homebrew/brew/blob/ff28d7c69b7b7e026757c63f15d00f98f07e5cec/Library/Homebrew/extend/os/mac/utils/bottles.rb#L25-L30.

If you remove the `|| find_older_compatible_tag` from that code, then `--total` returns `4953/5687 remaining` for `arm64_big_sur`, which seems like an entirely more reasonable number.

Indeed, `grep -ri ":arm64_big_sur" $(brew --repo homebrew/core)/Formula/ | wc -l` returns `165` which _just about_ matches the difference between the total formulae calculation above, if you also subtract the 563 `bottle :unneeded` formulae too. That is, 5687 - 586 - 185 = 4959 which is good enough for my purposes tonight.

I'm going to go out on a limb and say that it shouldn't be able to find older compatible bottles for ARM architectures (as there are none, the rest are Intel), so something needs tweaking there. But that's beyond my capabilities at 11pm, and I don't have an ARM Mac to test it on.

**Comment by issyl0** [comment] 2020-12-08 00:07
Digging further (I should really go to bed), `MacOS::Version.from_symbol(tag)` in `find_older_compatible_tag` in the above file returns `11`, which is why it's grabbing Big Sur (Intel) bottles. This is because it's [doing an "any architectures" search](https://github.com/Homebrew/brew/blob/e416668a2529d75eb9e83772d0e29c64c965c107/Library/Homebrew/os/mac/version.rb#L26-L34)

**Comment by issyl0** [comment] 2020-12-08 09:08
Reading the other issues relating to bottle detection for ARM, looks like this is the same problem as #9449, caused by #9443.

**Comment by MikeMcQuaid** [comment] 2020-12-08 17:36
This is fixed for now and will be fixed properly by https://github.com/Homebrew/brew/pull/9464

**Closed by MikeMcQuaid** 2020-12-08 17:36 UTC
