### ISSUE TITLE
Juju.rd Formulae lacking compatibility with macOS 11 Big Sur

### ISSUE THREAD

**Issue by nmacgregor** [Homebrew/brew#9193] opened 2020-11-18 19:13 UTC
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am new to git, so if I am submitting the incorrect type of issue for this I apologize.
I was trying to use `juju ssh` to connect to a remote system.

## What happened (include command output)
I failed to connect to the system and received the following response:

<details>
  <summary>Command output</summary>
  <pre>

 panic: cannot determine host series: unknown series version 20

goroutine 1 [running]:
github.com/juju/juju/vendor/github.com/juju/os/series.mustHostSeries(0x2540be400, 0x760b620)
	/private/tmp/juju-20200219-10933-1brz0ic/juju-core_2.7.2/src/github.com/juju/juju/vendor/github.com/juju/os/series/series.go:50 +0x65
github.com/juju/juju/api.init()
	/private/tmp/juju-20200219-10933-1brz0ic/juju-core_2.7.2/src/github.com/juju/juju/api/certpool.go:19 +0x17f

  </pre>
</details>

## What you expected to happen

I expected to connect to the machine. I did some looking and found that Juju hard codes os versions, and they came out with a quick fix the other day https://github.com/juju/os/commit/10720519c304290ca6b6e7586a60ce0015323cfe.

## Output of `brew config` and `brew doctor` commands

<pre>
### Brew Doctor:

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  sshfs

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  charm

Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install python@3.9

Run `brew missing` for more details.

###Brew Config:

HOMEBREW_VERSION: 2.5.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 07b3aa69f8dc5098437cf2562864558bae2d45aa
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 93ca3c41051b3ae2d5cda8152829b7fa69f5dbd6
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.1, 1.8.202.08, 1.8.0_202
macOS: 11.0.1-x86_64
CLT: 12.0.31.1
Xcode: 12.2
</pre>

**Comment by issyl0** [comment] 2020-11-18 19:26
Yes, Juju is reproducibly [currently broken](https://github.com/Homebrew/homebrew-core/issues/65000) on Big Sur due to the issue you mention. It's [this bug on Juju's bug tracker](https://bugs.launchpad.net/juju/+bug/1904252), and we await a [new `juju` release](https://github.com/juju/juju/releases) (2.8.7, according to the Juju devs) with the upstream fix that you linked.

> Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

**Closed by issyl0** 2020-11-18 19:26 UTC
