### ISSUE TITLE
brew gives unhelpful advice on syntax errors

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#2497] opened 2017-04-15 16:49 UTC
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
-----

If you've got borked syntax in a formula, which you then try to install, `brew` essentially tells you you've screwed the name up & should try again even though there's a glaring syntax failure reported at the same time.

It should be obvious enough what needs fixing, but let's face it, Homebrew has seen confused users over less obtuse errors before now.

```
~> brew install mysql-cluster
Error: mysql-cluster: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mysql-cluster.rb:117: syntax error, unexpected ')', expecting keyword_end
==> Searching for similarly named formulae...
This similarly named formula was found:
mysql-cluster
To install it, run:
  brew install mysql-cluster
==> Searching taps...
```

**Comment by ilovezfs** [comment] 2017-04-15 16:54
@zmwangx any idea why the missing code is being triggered despite the syntax error? I'd think this would just die on the syntax error and halt.

**Comment by zmwangx** [comment] 2017-04-15 17:06
Syntax error results in `FormulaUnreadableError` (`formulary.rb:28`), which subclasses `FormulaUnavailableError`, which in turn triggers missing formula code.

Maybe `FormulaUnreadableError` should not subclass `FormulaUnavailableError`.

**Comment by chdiza** [comment] 2017-04-15 21:01
It's not only syntax errors that reveal this behavior.

This bit me yesterday, only I didn't even get told there was a syntax error in there.  I had renamed a formula in my local tap from `foo` to `bar`, but forgot to change `class Foo` to `class Bar` at the top of the formula.  I think that's technically not a ruby syntax error, so `brew` just kept telling me that no formula of that name could be found.  It took half an hour to figure out what was going on.  I didn't think to check the contents of `bar.rb`, because I thought "surely if there was some problem with that file, `brew` would spew some other complaint instead of pretending the file doesn't exist".
```
$ ls /usr/local/hb/Library/taps/chdiza/homebrew-dizaone | grep "bar"
$ bar.rb

$ brew install  chdiza/dizaone/bar
Error: No available formula with the name "chdiza/dizaone/bar"
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by zmwangx** [comment] 2017-04-15 22:17
@chdiza Your case probably could be handled better, but it is expected behavior. Well, I think "Searching taps..." does nothing here; but "Searching for a previously deleted formula..." and "Searching for similarly named formulae..." do very real things.

**Comment by chdiza** [comment] 2017-04-15 23:41
I find it baffling to call it "expected" that `brew` would treat this case just as if I had typed `brew install hybybzjfjnfnqqqqqqqqqq`; but if it really is what should be expected,  then brew *should* look in other taps for something with that name, just as if I had typed `brew install hybybzjfjnfnqqqqqqqqqqq`

When `brew` sees that `bar.rb` is incorrectly formed (in whatever minor way that currently causes it to claim there is no such formula), it should raise a complaint and die.  It could say "bar.rb is not a legal homebrew formula" or something like that.  Or it could say "Found a `bar.rb`, but it is not a legal Homebrew formula; looking elsewhere" and then not die but keep going as it does now.  That way, at least the output would leave *some* kind of clue for the user.

**Comment by zmwangx** [comment] 2017-04-15 23:47
> I find it baffling to call it "expected" brew would treat this case just as if I had typed brew install hybybzjfjnfnqqqqqqqqqq

It doesn't. "Searching for a previously deleted formula..." and "Searching for similarly named formulae..." are limited to qualified formulae in the tap specified. You can easily test this out yourself. That's why I said "Searching taps..." does nothing, because you'll never find the qualified formula in another tap. So missing formula handling code is definitely doing what it's expected to do.

> When brew sees that bar.rb is incorrectly formed (in whatever minor way that currently causes it to claim there is no such formula), it should raise a complaint and die.

And that is why I said it "probably could be handled better", but not the fault of missing formula handling code.

> it should raise a complaint and die...

Sure, raise a PR? This is an extremely narrow corner case, so someone needs to volunteer.

**Comment by zmwangx** [comment] 2017-04-15 23:55
#2498 suppresses "Searching taps..." when a qualified formula is missing.

**Comment by chdiza** [comment] 2017-04-16 02:34
The really unexpected (and confusing) part is the `No available formula with the name "bar"` part.  It would not be any *less* unexpected  if the part about "searching taps" were left off.  I agree that that part is unnecessary and should be dropped, but dropping that doesn't really help.

> but not the fault of missing formula handling code.

I don't know enough Homebrew internals to pin blame on a specific area, which is why I didn't blame any specific area.  I still don't know enough, but I'm now going to blame (:smile:): whichever code is saying "OK, even though this file exists and we know exactly what's wrong with it, we should keep completely silent about that and instead just treat this just like we would a nonexistent file.  So here you go, missing-formula-handling-code, do your thing."

**Comment by zmwangx** [comment] 2017-04-16 03:29
> The really unexpected (and confusing) part is the No available formula with the name "bar" part.

I don't think that's new, and that's a separate issue.

The issue is about "unhelpful advice", and I was enlisted to discuss that, so I discussed just that.

**Comment by chdiza** [comment] 2017-04-16 12:36
But the core reason that the advice is unhelpful, in both my case and @DomT4's case, is that `brew` should never even make it to the stage where it's looking for a "missing" formula.  I took that to be the "the issue".

**Comment by chdiza** [comment] 2017-04-16 12:59
In `formulary.rb`, lines 34-39, something called a "NameError" is  spotted, and then instead of a bailout,  "FormulaClassUnavailableError" is raised.  It looks like a backtrace was requested, but this isn't making it to the terminal.

I can see in `exceptions.rb` that "FormulaClassUnavailableError" is a subclass of "FormulaUnavailableError".  Perhaps this should not be the case, or perhaps there is a way to make the raising of "FormulaClassUnavailableError" in line 39 of `formulary.rb` result in a bailout rather than a more generic FormulaUnavailableError.

E.g., experimentation reveals that if I replace line 39 of `formulary.rb` with: `raise e.to_s`, then `brew` behaves as expected if I try to `brew install` a formula with a mismatching class name at the top:
```
$ brew install  chdiza/dizaone/bar
Error: No available formula with the name "bar"
In formula file: /usr/local/hb/Library/Taps/chdiza/homebrew-dizaone/bar.rb
Expected to find class Bar, but only found: Foo.
```

I will make a PR with this replacement of line 39 if someone thinks that's an OK manoevre.

**Comment by MikeMcQuaid** [comment] 2017-04-16 13:05
I'm behind on my notifications but I think the fix for this is to `rescue FormulaClassUnavailableError` and make that a no-op to avoid triggering the current `FormulaUnavailableError` behaviour.

**Comment by chdiza** [comment] 2017-04-16 13:11
Elsewhere in Homebrew, someone recognized the need to stop FormulaClassUnavailableError from triggering the missing formula code; see lines 209-213 of `install.rb`:
```
    rescue FormulaClassUnavailableError => e
      # Need to rescue before `FormulaUnavailableError` (superclass of this)
      # is handled, as searching for a formula doesn't make sense here (the
      # formula was found, but there's a problem with its implementation).
      ofail e.message
```

**Comment by chdiza** [comment] 2017-04-16 13:16
> the fix for this is to rescue FormulaClassUnavailableError and make that a no-op to avoid triggering the current FormulaUnavailableError behaviour.

Will making it a no-op result in a helpful error message at the terminal?  (I don't know what "making it a no-op" involves.)

**Comment by MikeMcQuaid** [comment] 2017-04-16 13:18
> Elsewhere in Homebrew, someone recognized the need to stop FormulaClassUnavailableError from triggering the missing formula code; see lines 209-213 of install.rb:

I would use the same format elsewhere, yep.

**Comment by chdiza** [comment] 2017-04-16 13:49
@MikeMcQuaid If I understand correctly, and probably I don't, the choice is between having L39 of `formulary.rb` replaced with `raise e.to_s`, or having it replaced with: `ofail e`.

The former results in exactly the sort of message to the user that I would expect (pasted earlier in the thread), while the latter causes the following, far less helpful (but still better than the current situation) messaging:
```
brew install  chdiza/dizaone/bar
Error: undefined method `new' for #<FormulaClassUnavailableError:0x007fedc0074fd0>
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
```

I note that the former, if also used to replace line 28 of `formulary.rb`, is a way of fixing @DomT4's complaint too.  For instance, if delete an `end` in some formula and then try to install it, I would get:
```
brew install  chdiza/dizaone/foo
Error: /usr/local/hb/Library/Taps/chdiza/homebrew-dizaone/foo.rb:15: syntax error, unexpected end-of-input, expecting keyword_end
```
(and not then hit the missing-formula routine).

**Comment by MikeMcQuaid** [comment] 2017-04-17 14:19
Opened a PR in https://github.com/Homebrew/brew/pull/2502.

**Closed** 2017-04-19 09:39 UTC
