### ISSUE TITLE
Brew Fish completions are failing with: illegal option -- r

### ISSUE THREAD

**Issue by guw** [Homebrew/brew#9463] opened 2020-12-08 16:57 UTC
Originally opened at https://github.com/fish-shell/fish-shell/issues/7536 but it looks like this is specific to the Homebrew Fish completions.

The following screenshot demonstrates the problem:
![image](https://user-images.githubusercontent.com/191472/101515108-49197600-397e-11eb-9566-118603ef8b2d.png)

Basically, when typing "brew install <cursor>" and `tab` at cursor position the error from sed is printed. This seems to be related to Brew specific Fish completions.

**Comment by faho** [comment] 2020-12-08 16:58
Duplicate of #9388

**Closed** 2020-12-08 17:33 UTC
