### ISSUE TITLE
upgrading formulae compiled as universal results is thin version being installed

### ISSUE THREAD

**Issue by sashkab** [Homebrew/brew#3413] opened 2017-11-02 12:36 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.3.6-150-g302bc8b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 302bc8be22c9f645a110815f52f252a78c666d0f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: de6b738db712ae50829a9d0d4fff61646f04346c
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 9.0.1.0.1.1506734476
X11: 2.7.11 => /opt/X11
```

```
$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:

- What you were trying to do (and why)

   Project I'm working requires use of the universal version of the Python interpreter. Unfortunately, Python 3 is not included in the macOS, so I have to compile myself. I've been using `--universal` option until it was removed, so I started to maintain [tap][1] for universal Python and another [one][2] with required libraries, pulled  out of homebrew-core before removal of the `--universal`.

- What happened (include command output)

    Recently, I've upgraded python using `brew update && brew upgrade` command and resulting python27 and python36 taps where resulted in creation of the thin binaries, only x86_64. Running `brew reinstall sashkab/python/python27 --universal` didn't help, so I had to `brew uninstall <formulae> && brew install <formulae> --universal` in order to fix this problem. I've made sure that these taps are installed as kegs, and then I just use them in my python's virtual environments.

- What you expected to happen

   I expected `brew update && brew upgrade` will create universal binaries for formulaes which were complied with the universal flag on.
- Step-by-step reproduction instructions (by running `brew` commands)

   1.  `brew install sashkab/python/python27 --universal`
   2. wait for updated formulae. 
   3. `brew update && brew upgrade`

[1]: https://github.com/sashkab/homebrew-python
[2]: https://github.com/sashkab/homebrew-universal

**Comment by amyspark** [comment] 2017-11-04 13:35
I can confirm this with `weechat`. When the formula is updated, it should be rebuilt with the options that had been stored in the Tab, but it is not:
https://github.com/Homebrew/brew/blob/b806a53d88938ab2d2aeb5e96651ed6d47efcdf9/Library/Homebrew/cmd/upgrade.rb#L122-L124

Can you replace `f.build` with `tab` in the line above and check if the problem persists?

**Comment by sashkab** [comment] 2017-11-25 14:15
It’s not been fixed yet. So it’s still valid but report.

**Comment by ilovezfs** [comment] 2017-11-25 14:18
If you're already maintaining it in your own tap, you can use `ENV.universal_binary` in the install method unconditionally and not have `--universal` as an option.

**Comment by sashkab** [comment] 2017-11-25 14:22
I still want to allow users to install not only universal versions.

**Comment by MikeMcQuaid** [comment] 2017-12-01 13:37
> brew install sashkab/python/python27 --universal
> wait for updated formulae.
> brew update && brew upgrade

@sashkab Can you paste the output of running them, please?

**Comment by MikeMcQuaid** [comment] 2017-12-01 13:42
@amyspark You deleted your previous comment; were you able to reproduce this? If so, can I also get the commands you ran and the full output? Thanks!

**Comment by ilovezfs** [comment] 2017-12-01 13:56
I cannot reproduce this.
```
iMac-TMP:homebrew-python joe$ file /usr/local/Cellar/python27/2.7.14/bin/python2
/usr/local/Cellar/python27/2.7.14/bin/python2: Mach-O universal binary with 2 architectures
/usr/local/Cellar/python27/2.7.14/bin/python2 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/Cellar/python27/2.7.14/bin/python2 (for architecture i386):	Mach-O executable i386
iMac-TMP:homebrew-python joe$ file /usr/local/Cellar/python27/2.7.14_1/bin/python2
/usr/local/Cellar/python27/2.7.14_1/bin/python2: Mach-O universal binary with 2 architectures
/usr/local/Cellar/python27/2.7.14_1/bin/python2 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/Cellar/python27/2.7.14_1/bin/python2 (for architecture i386):	Mach-O executable i386
iMac-TMP:homebrew-python joe$ 
```

**Comment by amyspark** [comment] 2017-12-01 14:02
@MikeMcQuaid No, I wasn't able to reproduce this. I recall that I even checked if the `--universal` flag was stored in the tab and reused upon upgrade.

**Comment by amyspark** [comment] 2017-12-01 14:15
I tried with a much smaller example: the `usqlite` formula from the reporter's tap. I manually rolled it back to:
```ruby
  url "https://sqlite.org/2017/sqlite-autoconf-3200100.tar.gz"
  version "3.20.1"
  sha256 "ec66595b29bc0798b023a5122021ea646ab4fa9e2f735937c5426feeba950742"
```
`brew install` result:

```
amalia@Sakura:/usr/local/Homebrew$ brew install sashkab/homebrew-universal/usqlite --universal
==> Installing usqlite from sashkab/universal
==> Downloading https://sqlite.org/2017/sqlite-autoconf-3200100.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/usqlite/3.20.1 --enable-dynamic-extensions --enable-readline --disable-editline
==> make install
==> Caveats
Homebrew has detected an existing SQLite history file that was created
with the editline library. The current version of this formula is
built with Readline. To back up and convert your history file so that
it can be used with Readline, run:

  sed -i~ 's/\\040/ /g' ~/.sqlite_history

before using the `sqlite` command-line tool again. Otherwise, your
history will be lost.

This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/usqlite/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/usqlite/lib
    CPPFLAGS: -I/usr/local/opt/usqlite/include

==> Summary
🍺  /usr/local/Cellar/usqlite/3.20.1: 11 files, 5.2MB, built in 1 minute 14 seconds 
amalia@Sakura:/usr/local/Homebrew$ file /usr/local/Cellar/usqlite/3.20.1/lib/libsqlite3.dylib
/usr/local/Cellar/usqlite/3.20.1/lib/libsqlite3.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386:Mach-O dynamically linked shared library i386]
/usr/local/Cellar/usqlite/3.20.1/lib/libsqlite3.dylib (for architecture x86_64)Mach-O 64-bit dynamically linked shared library x86_64
/usr/local/Cellar/usqlite/3.20.1/lib/libsqlite3.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
```
After "updating" the formula:
```
amalia@Sakura:/usr/local/Homebrew$ brew upgrade usqlite
==> Upgrading 1 outdated package, with result:
sashkab/universal/usqlite 3.21.0
==> Upgrading sashkab/universal/usqlite --universal
==> Downloading https://sqlite.org/2017/sqlite-autoconf-3210000.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/usqlite/3.21.0 --enable-dynamic-exten
==> make install
==> Caveats
Homebrew has detected an existing SQLite history file that was created
with the editline library. The current version of this formula is
built with Readline. To back up and convert your history file so that
it can be used with Readline, run:

  sed -i~ 's/\\040/ /g' ~/.sqlite_history

before using the `sqlite` command-line tool again. Otherwise, your
history will be lost.

This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/usqlite/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/usqlite/lib
    CPPFLAGS: -I/usr/local/opt/usqlite/include

==> Summary
🍺  /usr/local/Cellar/usqlite/3.21.0: 11 files, 5.2MB, built in 1 minute 17 seconds
amalia@Sakura:/usr/local/Homebrew$ file /usr/local/Cellar/usqlite/3.21.0/lib/libsqlite3.dylib
/usr/local/Cellar/usqlite/3.21.0/lib/libsqlite3.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386:Mach-O dynamically linked shared library i386]
/usr/local/Cellar/usqlite/3.21.0/lib/libsqlite3.dylib (for architecture x86_64)Mach-O 64-bit dynamically linked shared library x86_64
/usr/local/Cellar/usqlite/3.21.0/lib/libsqlite3.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
```
Judging from the output above, `ENV.universal_binary if build.universal?` is a successful workaround.

**Comment by ilovezfs** [comment] 2017-12-01 14:49
>successful workaround

That's not a workaround. That's how it works.

**Comment by amyspark** [comment] 2017-12-01 15:29
@ilovezfs apologies, I misunderstood [your comment above](https://github.com/Homebrew/brew/issues/3413#issuecomment-346943225).

**Comment by MikeMcQuaid** [comment] 2017-12-01 18:15
Given multiple maintainers/contributors cannot reproduce this: closing.

**Closed by MikeMcQuaid** 2017-12-01 18:15 UTC
