### ISSUE TITLE
Keep icons in the Mac OS dock when upgrading version

### ISSUE THREAD

**Issue by wojciechczyz** [Homebrew/brew#11861] opened 2021-08-16 08:11 UTC
### Provide a detailed description of the proposed feature

Find a way to keep icons in mac os dock when app is upgraded.

### What is the motivation for the feature?

At the moment, upgrading version of Apps with icons in dock removes their icons.

### How will the feature be relevant to at least 90% of Homebrew users?

Frequently used apps such as Chrome, Firefox, Visual Studio Code etc have their icons removed.

### What alternatives to the feature have been considered?

manually find app, then mark "Keep in Dock" again.

**Comment by carlocab** [comment] 2021-08-16 08:36
Duplicate of Homebrew/homebrew-cask#102721

**Closed** 2021-08-16 08:36 UTC
Labels: features
