### ISSUE TITLE
Homebrew on Linux seems to ignore EDITOR environment setting

### ISSUE THREAD

**Issue by aaronliu0130** [Homebrew/brew#6646] opened 2019-10-27 04:23 UTC
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I was trying to edit a formula(let's say hello in this example) for contribution.

# What happened (include command output)

Even though I set $EDITOR to nano, brew still tries to use "edit" which will spawn an error due to no set mailcaps for it.

<details>
  <summary>Command output</summary>
  <pre>
  aaron@zenbook:~/lintcode$ brew doctor                                                                                   
Please note that these warnings are just used to help the Homebrew maintainers                                          
with debugging if you file an issue. If everything you use Homebrew for is                                              
working fine: please don't worry or file an issue; just ignore this. Thanks!                                                                                                                                                                    
Warning: umask is currently set to 000. Directories created by Homebrew cannot                                          
be world-writable. This issue can be resolved by adding "umask 002" to                                                  
your ~/.bash_profile:                                                                                                     
echo 'umask 002' >> ~/.bash_profile                                                                                   
aaron@zenbook:~/lintcode$ echo 'umask 002' >> ~/.bash_profile                                                           
aaron@zenbook:~/lintcode$ brew doctor                                                                                   
Please note that these warnings are just used to help the Homebrew maintainers                                          
with debugging if you file an issue. If everything you use Homebrew for is                                              
working fine: please don't worry or file an issue; just ignore this. Thanks!                                                                                                                                                                    
Warning: umask is currently set to 000. Directories created by Homebrew cannot                                          
be world-writable. This issue can be resolved by adding "umask 002" to                                                  
your ~/.bash_profile:                                                                                                     
echo 'umask 002' >> ~/.bash_profile                                                                                   
aaron@zenbook:~/lintcode$ umask 002                                                                                     
aaron@zenbook:~/lintcode$ brew doctor                                                                                   
Your system is ready to brew.                                                                                           
aaron@zenbook:~/lintcode$ brew edit hello                                                                               
Editing /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrewcore/Formula/hello.rb                        
Warning: Using edit because no editor was set in the environment.                                                       
This may change in the future, so we recommend setting EDITOR,                                                          
or HOMEBREW_EDITOR to your preferred text editor.                                                                       
Error: no "edit" mailcap rules found for type "application/x-ruby"                                                      
Error: Failure while executing; `edit 
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-
core/Formula/hello.rb` exited with 3.                                                                   
aaron@zenbook:~/lintcode$ brew config                                                                                   
HOMEBREW_VERSION: 2.1.15-63-g090259b                                                                                    
ORIGIN: https://github.com/Homebrew/brew                                                                                
HEAD: 090259b97304cd303fb0e4b3cefdf7bf9a2596fd                                                                          
Last commit: 2 days ago                                                                                                 
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core                                                             
Core tap HEAD: 3a8bdf1a86ee96aa94a665dfb30d41e87965d34b                                                                 
Core tap last commit: 17 hours ago                                                                                      
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew                                                                             
HOMEBREW_CACHE: /home/aaron/.cache/Homebrew                                                                             
HOMEBREW_LOGS: /home/aaron/.cache/Homebrew/Logs                                                                         
HOMEBREW_DEV_CMD_RUN: 1                                                                                                 
CPU: octa-core 64-bit skylake                                                                                           
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby        
Clang: N/A                                                                                                              
Git: 2.17.1 => /usr/bin/git                                                                                             
Curl: 7.58.0 => /usr/bin/curl                                                                                          
Kernel: Linux 4.4.0-18362-Microsoft x86_64 GNU/Linux                                                                    
OS: Ubuntu 18.04.3 LTS (bionic)                                                                                         
Host glibc: 2.27                                                                                                        
/usr/bin/gcc: 7.4.0                                                                                                     
glibc: N/A                                                                                                              
gcc: N/A                                                                                                                
xorg: N/A
aaron@zenbook:~/lintcode$ echo $EDITOR
nano
  
  </pre>
</details>

# What you expected to happen

I expected homebrew to edit in nano. `git commit -v` edits in nano now.

# Step-by-step reproduction instructions (by running `brew` commands)

```bash
EDITOR=nano
brew edit hello
#Optional, Just to see that git does.
git init
echo "abc">>abc.txt
git add .
git commit -v
```
I'm using windows wsl ubuntu.

**Comment by dawidd6** [comment] 2019-10-27 07:53
Try `EDITOR=nano brew edit hello` and tell what happened.

**Comment by aaronliu0130** [comment] 2019-10-27 08:01
@dawidd6 That's already in my `.profile` file. But anyway, here it is.
```bash
aaron@zenbook:~$ echo $EDITOR
nano
aaron@zenbook:~$ brew edit hello
Editing /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hello.rb
Warning: Using edit because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR,
or HOMEBREW_EDITOR to your preferred text editor.
Error: no "edit" mailcap rules found for type "application/x-ruby"
Error: Failure while executing; `edit /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hello.rb` exited with 3.
```

**Comment by MikeMcQuaid** [comment] 2019-10-28 09:09
Did you `export` it? Closing this as I can't reproduce.

**Closed by MikeMcQuaid** 2019-10-28 09:10 UTC
