### ISSUE TITLE
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Library/LaunchAgents/homebrew.mxcl.httpd.plist` exited with 5

### ISSUE THREAD

**Issue by SteveG-Intracto** [Homebrew/brew#11289] opened 2021-04-29 19:11 UTC
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 94ce3236a517dfae6b492dcb4fd6b726a6175e8f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5f8dbcc6187ecc8f7fe81631455f70c64cabaf03
Core tap last commit: 50 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: 12.5
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to install httpd on a clean installed Mac OSX Big Sur.

### What happened (include all command output)?

I've installed a fresh Mac OSX by doing a clean install. Next step was installing homebrew by doing the following commands:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew doctor
Your system is ready to brew.
brew --version
Homebrew 3.1.4
Homebrew/homebrew-core (git revision 5f8dbcc618; last commit 2021-04-29)

### What did you expect to happen?

That the httpd services get started for doing my setup on my Mac.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openssl
brew install httpd
brew services start httpd
```

**Comment by carlocab** [comment] 2021-04-29 19:16
Duplicate of https://github.com/Homebrew/homebrew-core/issues/76192

**Closed by carlocab** 2021-04-29 19:16 UTC
Labels: bug
