### ISSUE TITLE
macOS Catalina no longer includes Ruby by default

### ISSUE THREAD

**Issue by pipboy96** [Homebrew/brew#6258] opened 2019-06-25 14:47 UTC
# A detailed description of the proposed feature

The default installer command for Homebrew (`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`) is not going to work on macOS Catalina since it no longer includes a Ruby interpreter by default [(source)](https://en.wikipedia.org/wiki/MacOS_Catalina#Removed_components).

I believe the best way to deal with that is to create a Bash wrapper that will install Ruby and then run Homebrew installer.

# The motivation for the feature

Making Homebrew installable with a single command on latest macOS version.

# How the feature would be relevant to at least 90% of Homebrew users

This issue impacts the install process and requires the user to install Ruby interpreter manually.

# What alternatives to the feature have been considered

Asking users to take some manual steps to install a Ruby interpreter (this is much less trivial than copying one command into the terminal).

**Comment by MikeMcQuaid** [comment] 2019-06-25 14:54
From the issue bot:

> If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

Don't create duplicate issues, please.

Duplicate of #6256

**Closed by MikeMcQuaid** 2019-06-25 14:54 UTC

**Comment by pipboy96** [comment] 2019-06-25 14:59
@MikeMcQuaid Well, it was not actually reopened by the bot, it only checked for correct format once, and I guess no one would dig in closed issues and manually reopen it. Sorry for not checking for duplicates though. I already read more on this issue, macOS Catalina still includes the binaries.

**Comment by pipboy96** [comment] 2019-06-25 15:01
I don't like the fact that if you make an incorrectly formatted issue, it is closed and even if you fix it, it's buried in closed issues (since no one will probably re-enable it).

**Comment by MikeMcQuaid** [comment] 2019-06-25 15:07
Continuing conversation in #6256
