### ISSUE TITLE
undefined method `audit_exceptions' for nil:NilClass

### ISSUE THREAD

**Issue by vraravam** [Homebrew/brew#11464] opened 2021-05-31 06:21 UTC
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.9-68-g990d5f0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 990d5f048fa429b15b2babe7c639104ce11da152
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 16c46fe92664bcd3484e4b26381dd3b4b5212a2d
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 3
HOMEBREW_EDITOR: code --goto
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED: set
HOMEBREW_VERBOSE_USING_DOTS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to run `brew audit --online --fix --cask Casks/ferdi-beta.rb` from [this PR](https://github.com/Homebrew/homebrew-cask-versions/pull/11092).

### What happened (include all command output)?

==> Downloading https://github.com/getferdi/ferdi/releases/download/v5.6.0-beta.6/Ferdi-5.6.0-beta.6.dmg
Already downloaded: /Users/vijay/Library/Caches/Homebrew/downloads/a265e331b11e108906ecd94cf1c145c11fbdce3137176d0b24ac72780b7f3094--Ferdi-5.6.0-beta.6.dmg
audit for ferdi-beta: failed
 - exception while auditing ferdi-beta: undefined method `audit_exceptions' for nil:NilClass
Error: 1 problem in 1 cask detected

### What did you expect to happen?

No errors (as a user) of the command

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. checkout the branch of that PR
2. Run the command: `brew audit --online --fix --cask Casks/ferdi-beta.rb`
```

**Comment by Rylan12** [comment] 2021-05-31 06:59
What happens if you run `brew audit --online --fix --cask ferdi-beta` instead of using the path?

Regardless of whether that fixes this or not, I cannot reproduce this:

```console
$ cd $(brew --repository homebrew/cask-versions)

$ gh pr checkout 11092
From https://github.com/Homebrew/homebrew-cask-versions
 * [new ref]             refs/pull/11092/head -> ferdi-beta-5.6.0-beta.6
Switched to branch 'ferdi-beta-5.6.0-beta.6'

$ brew audit --online --fix --cask Casks/ferdi-beta.rb
==> Downloading https://github.com/getferdi/ferdi/releases/download/v5.6.0-beta.6/Ferdi-5.6.0-beta.6.dmg
==> Downloading from https://github-releases.githubusercontent.com/169383267/08572880-c17b-11eb-97e0-17ff5d4c10fc?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Crede
######################################################################## 100.0%
audit for ferdi-beta: passed
```

**Comment by vraravam** [comment] 2021-05-31 07:03
![Uploading Screen Shot 2021-05-31 at 12.32.28 PM.png…]()

**Comment by Rylan12** [comment] 2021-05-31 07:09
Are you running this command in the `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions` directory?

**Comment by vraravam** [comment] 2021-05-31 07:11
no - i am running in the code folder where i have the codebase checked out.

The intention of this is to be done *before* the PR is raised, correct? So, I have the code checked out, and make the changes in a branch, and before raising the PR, I am trying to run the necessary commands.

**Comment by Rylan12** [comment] 2021-05-31 07:15
That's the problem, then. You should make the changes and run the commands in the tapped directory (i.e. `/usr/local/Homebrew/Library/Taps/*/homebrew-*`.

Following the [contributing guidelines](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md) has you make changes in this location.

That being said, I wouldn't be opposed to a PR that improves the messaging in this case so its more clear what's going on. TBH `brew audit` probably should fail as soon as it realizes that a formula or cask isn't in a tap.

**Comment by vraravam** [comment] 2021-05-31 07:35
hmm - im slightly not in agreement that the audit checks for a cask should be done in the main running location. So, lets say I am a macos user, and also using homebrew. And I find that one of the apps that I am using has a newer version. Based on your suggested guidelines, I need to 
1. cd into that `/usr/local/....` folder
2. Make my changes such that `brew audit` passes
3. `git checkout` a new branch right there
4. `git commit && git push`
5. `git checkout <main branch>`

Isn't this polluting the running version of brew such that it can get corrupted/stuck without getting new versions from other PRs that got merged? (especially if I forget to do the last step - which can happen each time the PR gets new comments that mandate edits.

**Comment by nandahkrishna** [comment] 2021-05-31 11:03
> Isn't this polluting the running version of brew such that it can get corrupted/stuck without getting new versions from other PRs that got merged? (especially if I forget to do the last step - which can happen each time the PR gets new comments that mandate edits.

When it's just a version bump without additional changes to the Formula or Cask, you could use `bump-formula-pr` or `bump-cask-pr`, which will ensure you don't stay on your PR branch (it'll go back to the default branch once your PR is created).

Even otherwise, I think contributors would deliberately make changes to their main or running installation, as they want to test out `brew`'s behaviour after making their changes. This is not only for the main Homebrew/brew repository but also for the core and cask taps.

If someone forgets to switch back to the default branch and they notice any issues, running `brew doctor` would tell them the problem and provide a solution too:
```
Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master
```

> Also, I diligently delete the branches for the PRs that I submit and subsequently get merged - whether its homebrew or other projects. For those folks who don't do this cleanup, their `/usr/local` directory will have too much cruft left around.

I do this too (and I'm sure many others do as well). Perhaps you could create a simple shell script that does this cleanup for you, when you see that your PR has been merged. You'd have to do this yourself whether or not you use the tapped location.

**Comment by MikeMcQuaid** [comment] 2021-05-31 11:31
Closing this for now but, as mentioned, would accept PRs to improve this.

**Closed by MikeMcQuaid** 2021-05-31 11:31 UTC
Labels: bug
