### ISSUE TITLE
Issue when a dependency depends on :mpi

### ISSUE THREAD

**Issue by dpo** [Homebrew/brew#3159] opened 2017-09-15 22:29 UTC
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/dpo/dcb38eec73e0a4c9a7dc60b6941a96f6

To help us debug your issue please explain:
- What you were trying to do (and why)

Build `homebrew/science/mumps` and dependencies against `mpich` to investigate https://github.com/Homebrew/homebrew-science/issues/6318.

- What happened (include command output)

The dependencies `parmetis` and `scalapack` (which depend on `:mpi`) can be built from source against `mpich`, but `mumps` cannot:

```bash
$ brew install mpich # after uninstalling open-mpi and everything depending on it
$ brew install -s parmetis scalapack # works fine

$ brew install -s mumps
==> Installing mumps from homebrew/science
==> Installing dependencies for homebrew/science/mumps: open-mpi
==> Installing homebrew/science/mumps dependency: open-mpi
Error: Cannot install open-mpi because conflicting formulae are installed.
mpich: because both install mpi__ compiler wrappers

Please brew unlink mpich before continuing.
```

- What you expected to happen

See `mumps` compile against `mpich` since the `:mpi` dependency is satisfied.

- Step-by-step reproduction instructions (by running `brew` commands)

# Symptom

It seems that if a formula has a dependency D that depends on `:mpi`, then Homebrew wants to install `open-mpi`, regardless of whether D is already installed and regardless of whether it's been built from source against `mpich`. Here's a minimal example with a trimmed down `mumps.rb`:
```ruby
class Mumps < Formula
  desc "Parallel Sparse Direct Solver"
  homepage "http://mumps-solver.org"
  url "http://mumps.enseeiht.fr/MUMPS_5.1.1.tar.gz"
  sha256 "a2a1f89c470f2b66e9982953cbd047d429a002fab9975400cef7190d01084a06"

  depends_on :mpi
  # depends_on "scalapack"  # scalapack depends_on :mpi

  def install
    puts "Hello, MUMPS!"
  end
end
```
Assume `open-mpi` is not installed but `mpich` is. Then `brew install -s` the above formula succeeds (i.e., does not complain about installing `open-mpi`).

Now, uncomment the commented out line (and even comment out the explicit `:mpi` dependency) and assume `scalapack` was built from source against `mpich`:
```
$ otool -L /usr/local/opt/scalapack/lib/libscalapack.dylib 
/usr/local/opt/scalapack/lib/libscalapack.dylib:
	...
	/usr/local/opt/mpich/lib/libmpifort.12.dylib (compatibility version 14.0.0, current version 14.0.0)
	/usr/local/opt/mpich/lib/libmpi.12.dylib (compatibility version 14.0.0, current version 14.0.0)
	/usr/local/opt/mpich/lib/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.0.0)
	...
```
Then
```
$ brew install -s /tmp/mumps.rb
==> Installing dependencies for mumps: open-mpi
==> Installing mumps dependency: open-mpi
Error: Cannot install open-mpi because conflicting formulae are installed.
  mpich: because both install mpi__ compiler wrappers

Please `brew unlink mpich` before continuing.
```

I've inserted debugging statements in `mpi_requirement.rb` and `satisfy` returns `true`. Nevertheless, Homebrew wants `open-mpi`. It would be great to know if others can reproduce this.

**Comment by scpeters** [comment] 2017-09-15 23:38
I'm working on reproducing this. Can you clarify in your instructions that you ran `brew install mpich` before installing `parmetis` and `scalapack`? I ran through the instructions without `mpich` installed at first, which I think is not the procedure you intend.

**Comment by scpeters** [comment] 2017-09-15 23:42
I'm able to reproduce the problem with installing `mumps`.

**Comment by dpo** [comment] 2017-09-15 23:44
> Can you clarify in your instructions that you ran brew install mpich before installing parmetis and scalapack

Yes, that's correct.

**Comment by scpeters** [comment] 2017-09-15 23:50
Making `:mpi` a required dependency instead of `:recommended` seemed to fix it for me. I don't know why.

~~~
diff --git a/mumps.rb b/mumps.rb
index cd6206a..ac3e8fe 100644
--- a/mumps.rb
+++ b/mumps.rb
@@ -13,7 +13,7 @@ class Mumps < Formula
     sha256 "a6a62e8a4fda29745279f33b3b0dec6adffcda91311e6967f93db5b8d1466566" => :x86_64_linux
   end
 
-  depends_on :mpi => [:cc, :cxx, :f90, :recommended]
+  depends_on :mpi => [:cc, :cxx, :f90]
   depends_on "openblas" => OS.mac? ? :optional : :recommended
   depends_on "veclibfort" if build.without?("openblas") && OS.mac?
   depends_on :fortran
~~~

**Comment by dpo** [comment] 2017-09-15 23:53
No, that's deceiving because all the `build.with? "mpi"` in the `install` method evaluate to `false` and you're really building a sequential version of `mumps`. Check `otool -L /usr/local/opt/mumps/lib/libdmumps.dylib`.

**Comment by scpeters** [comment] 2017-09-16 00:43
@dpo you are correct; I'll edit my comment

**Comment by scpeters** [comment] 2017-09-18 23:44
I think I have a fix in #3170

**Comment by scpeters** [comment] 2017-09-19 06:18
@ilovezfs pointed out a problem in #3170. Does it work for you if you explicitly tell `scalapack` to build from source as well (even though it's already built):

~~~
brew install -s mumps scalapack
~~~

**Comment by scpeters** [comment] 2017-09-19 06:29
The [install_bottle_for? function in formula_installer.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L119) checks if a given formula name has been listed on the command-line as wanting to be built from source. If you don't include one of these in the install command, the installer will think it should have a bottle and want to install `open-mpi`, even if the formula has already been installed.

I think the workaround is to just list all formulae that require `:mpi` in the install command so it will know not to build a bottle for that formula.

**Comment by ilovezfs** [comment] 2017-09-19 07:38
>I think the workaround is to just list all formulae that require :mpi in the install command so it will know not to build a bottle for that formula.

You can also `HOMEBREW_BUILD_FROM_SOURCE=1 brew install mumps` if you don't want to list them.

**Comment by dpo** [comment] 2017-09-19 14:26
That appears to work. Thanks! It should probably be documented somewhere because I imagine the same will happen with any dependency that has a `default_formula`.

**Comment by scpeters** [comment] 2017-09-19 16:36
@dpo maybe it could be documented in the caveats for `mpich`?

**Comment by MikeMcQuaid** [comment] 2017-09-22 19:37
> It should probably be documented somewhere because I imagine the same will happen with any dependency that has a default_formula.

Where do you think it should be documented?

**Comment by dpo** [comment] 2017-09-23 15:23
Ideally, I could imagine adding a message to a formula's caveats when a user builds it against a non-default dependency, but I'm not sure there is such a mechanism in Homebrew?! In the immediate future, we could add a paragraph to [Common-issues.md](https://github.com/Homebrew/brew/blob/master/docs/Common-Issues.md).

**Comment by MikeMcQuaid** [comment] 2017-09-23 15:30
@dpo Ok, I see. I think we could add an informational `ohai` message at installation time noting the requirement `default_formula` is being installed because a bottle is being poured. I don't consider this a bug or issue as-is, though, so closing but we'd welcome a PR.

**Closed by MikeMcQuaid** 2017-09-23 15:30 UTC

**Comment by dpo** [comment] 2017-09-23 16:01
@MikeMcQuaid Sounds good. Where should the `ohai` go? In the corresponding requirement?

**Comment by MikeMcQuaid** [comment] 2017-09-23 16:54
@dpo In should be something generic to all requirements so probably in `formula_installer`.
