### ISSUE TITLE
Gedit crashes at start

### ISSUE THREAD

**Issue by mariomac** [Homebrew/brew#1219] opened 2016-10-03 11:35 UTC
After upgrading brew, I get the next error when I try to open "gedit":

```
2016-10-03 13:34:18.782 gedit[9614:44934] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.

(gedit:9614): Gdk-WARNING **: GdkQuartzDisplay does not implement the monitor vfuncs

(gedit:9614): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

** (gedit:9614): WARNING **: Could not load theme icon user-bookmarks-symbolic: No se ha reconocido el formato de imagen del archivo

** (gedit:9614): WARNING **: Could not load theme icon user-home-symbolic: No se ha reconocido el formato de imagen del archivo

** (gedit:9614): WARNING **: Could not load theme icon drive-harddisk-symbolic: No se ha reconocido el formato de imagen del archivo
**
Gtk:ERROR:gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
Abort trap: 6
```

**Comment by MikeMcQuaid** [comment] 2016-10-03 12:23
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by apjanke** [comment] 2016-10-03 19:58
I can reproduce this on 10.11.6. `gedit` crashes on startup with the same errors.

May be due to a bad `gdk-pixbuf` bottle. Rebuilding `gdk-pixbuf` from source worked for me.

Rebuilding it in #5545.

**Comment by apjanke** [comment] 2016-10-03 21:47
Fixed by https://github.com/Homebrew/homebrew-core/pull/5545. Please do a `brew update; brew upgrade` to pick up the fix, and let us know if you have any further problems.

**Closed by apjanke** 2016-10-03 21:47 UTC

**Comment by mariomac** [comment] 2016-10-04 07:46
Hi, thank you for your response and sorry for not following the troubleshooting steps.

Unfortunately the proposed solution do not work, so  I have reported it again by following the required steps: https://github.com/Homebrew/brew/issues/1222

Cheers.

**Comment by mariomac** [comment] 2016-10-04 11:27
Edit: It works now. Thank you!

**Comment by tuduongquyet** [comment] 2017-07-13 07:06
brew reinstall --build-from-source gdk-pixbuf

works.
