### ISSUE TITLE
"File not found" error when running most brew commands

### ISSUE THREAD

**Issue by straxhaber** [Homebrew/brew#14551] opened 2023-02-07 17:18 UTC
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-318-ge26784f
ORIGIN: https://github.com/Homebrew/brew
HEAD: e26784f424061ca16987afcb21e036c66a298492
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: deb1fd1f4212dfbfb26cd668d6aa49a17a3f9445
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 07 Feb 16:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Install, upgrade, uninstall packages (why is obvious... because Homebrew is awesome and it deserves use 😄)

### What happened (include all command output)?

```
> brew upgrade

Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/parallels.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

```
> brew uninstall colordiff

Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/vlc.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/installed_dependents.rb:46:in `find_some_installed_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:111:in `check_for_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:104:in `handle_unsatisfied_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:14:in `uninstall_kegs'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:60:in `uninstall'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

```
> brew uninstall --zap contexts

Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/firefox.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/installed_dependents.rb:46:in `find_some_installed_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:111:in `check_for_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:104:in `handle_unsatisfied_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:14:in `uninstall_kegs'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:60:in `uninstall'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

Formulas install, uninstall, or upgrade.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I am unsure how to get into this state. I have tried some basic troubleshooting:


> ls -al /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/{parallels,firefox}.rb

-rw-r--r--@ 1 myuser  admin  7529 Feb  7 09:06 /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb
-rw-r--r--@ 1 myuser  admin  3449 Dec 31 11:09 /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/parallels.rb
```

```
> brew update-reset

==> Fetching /opt/homebrew...

==> Resetting /opt/homebrew...
Reset branch 'master'
branch 'master' set up to track 'origin/master'.
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-cask...

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-cask...
Reset branch 'master'
branch 'master' set up to track 'origin/master'.
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-cask-fonts...

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-cask-fonts...
Reset branch 'master'
branch 'master' set up to track 'origin/master'.
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core...

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-core...
Reset branch 'master'
branch 'master' set up to track 'origin/master'.
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-services...

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-services...
Reset branch 'master'
branch 'master' set up to track 'origin/master'.
Your branch is up to date with 'origin/master'.
```

**Comment by joewiz** [comment] 2023-02-07 17:22
Agreed. I believe this is a dupe of https://github.com/Homebrew/brew/issues/14542.

**Comment by carlocab** [comment] 2023-02-07 17:48
Duplicate of #14542

**Closed** 2023-02-07 17:48 UTC
Labels: bug

**Comment by straxhaber** [comment] 2023-02-07 18:21
Thanks @joewiz @carlocab! I should've checked the existing issues first; my bad!
