### ISSUE TITLE
brew update gets stuck

### ISSUE THREAD

**Issue by TheElectroclassics** [Homebrew/brew#6966] opened 2020-01-22 18:36 UTC
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Tried to install YouTube-dl

## What happened (include command output)

Literally nothing. It gets stuck on Updating Homebrew. I ran brew update in verbose mode

<details>
  <summary>Command output</summary>

```
+ [[ -z '' ]]
+ [[ -z '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export HOMEBREW_UPDATE_TO_TAG=1
+ HOMEBREW_UPDATE_TO_TAG=1
+ [[ -z '' ]]
+ HOMEBREW_AUTO_UPDATE_SECS=300
+ [[ -e /usr/local/Cellar ]]
+ [[ ! -w /usr/local/Cellar ]]
+ [[ ! -w /usr/local/Homebrew ]]
+ [[ -n '' ]]
+ git --version
+ [[ -n '' ]]
+ export GIT_TERMINAL_PROMPT=0
+ GIT_TERMINAL_PROMPT=0
+ export 'GIT_SSH_COMMAND=ssh -oBatchMode=yes'
+ GIT_SSH_COMMAND='ssh -oBatchMode=yes'
+ [[ -z 1 ]]
+ QUIET_ARGS=()
+ [[ -z '' ]]
+ CURL_DISABLE_CURLRC_ARGS=(-q)
+ lock update
+ local name=update
+ local lock_dir=/usr/local/var/homebrew/locks
+ local lock_file=/usr/local/var/homebrew/locks/update
+ [[ -d /usr/local/var/homebrew/locks ]]
+ [[ -w /usr/local/var/homebrew/locks ]]
+ exec
+ exec
+ _create_lock 200 update
+ local lock_fd=200
+ local name=update
+ local ruby=/usr/bin/ruby
+ local python=/usr/bin/python
+ [[ -x /usr/bin/ruby ]]
+ [[ -x /usr/bin/python ]]
+ [[ -x /usr/bin/ruby ]]
+ /usr/bin/ruby -e 'exit(RUBY_VERSION >= '\''1.8.7'\'')'
+ /usr/bin/ruby -e 'File.new(200).flock(File::LOCK_EX | File::LOCK_NB) || exit(1)'
+ git_init_if_necessary
+ safe_cd /usr/local/Homebrew
+ cd /usr/local/Homebrew
+ [[ ! -d .git ]]
+ [[ -d /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core ]]
+ safe_cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
+ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
+ [[ ! -d .git ]]
+ [[ https://github.com/Homebrew/brew != \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/\H\o\m\e\b\r\e\w\/\b\r\e\w ]]
+ [[ https://github.com/Homebrew/homebrew-core != \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/\H\o\m\e\b\r\e\w\/\h\o\m\e\b\r\e\w\-\c\o\r\e ]]
+ safe_cd /usr/local/Homebrew
+ cd /usr/local/Homebrew
+ [[ -n '' ]]
+ trap '{ /usr/bin/pkill -P $$; wait; exit 130; }' SIGINT
+ local update_failed_file=/usr/local/Homebrew/.git/UPDATE_FAILED
+ rm -f /usr/local/Homebrew/.git/UPDATE_FAILED
+ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
+ [[ -d /usr/local/Homebrew/.git ]]
+ cd /usr/local/Homebrew
+ [[ -n 1 ]]
+ echo 'Checking if we need to fetch /usr/local/Homebrew...'
Checking if we need to fetch /usr/local/Homebrew...
++ repo_var /usr/local/Homebrew
++ local repo_var
++ repo_var=/usr/local/Homebrew
++ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ repo_var=
++ echo ''
+ TAP_VAR=
++ upstream_branch
++ local upstream_branch
+++ git symbolic-ref refs/remotes/origin/HEAD
++ upstream_branch=
++ upstream_branch=
++ [[ -z '' ]]
++ upstream_branch=master
++ echo master
+ UPSTREAM_BRANCH_DIR=master
+ declare UPSTREAM_BRANCH=master
++ git rev-parse -q --verify refs/remotes/origin/master
++ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
++ /Library/Developer/CommandLineTools/usr/bin/git rev-parse -q --verify refs/remotes/origin/master
+ declare PREFETCH_REVISION=23108f3c736030070ca1e4673652c20c503a7d02
+ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ git tag --list
++ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
++ /Library/Developer/CommandLineTools/usr/bin/git tag --list
+ [[ -z 0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.7.1
0.8
0.8.1
0.9
0.9.1
0.9.2
0.9.3
0.9.4
0.9.5
0.9.8
0.9.9
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.0.8
1.0.9
1.1.0
1.1.1
1.1.10
1.1.11
1.1.12
1.1.13
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.1.9
1.2.0
1.2.1
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
1.3.0
1.3.1
1.3.2
1.3.3
1.3.4
1.3.5
1.3.6
1.3.7
1.3.8
1.3.9
1.4.0
1.4.1
1.4.2
1.4.3
1.5.0
1.5.1
1.5.10
1.5.11
1.5.12
1.5.13
1.5.14
1.5.2
1.5.3
1.5.4
1.5.5
1.5.6
1.5.7
1.5.8
1.5.9
1.6.0
1.6.1
1.6.10
1.6.11
1.6.12
1.6.13
1.6.14
1.6.15
1.6.16
1.6.17
1.6.2
1.6.3
1.6.4
1.6.5
1.6.6
1.6.7
1.6.8
1.6.9
1.7.0
1.7.1
1.7.2
1.7.3
1.7.4
1.7.5
1.7.6
1.7.7
1.8.0
1.8.1
1.8.2
1.8.3
1.8.4
1.8.5
1.8.6
1.9.0
1.9.1
1.9.2
1.9.3
2.0.0
2.0.1
2.0.2
2.0.3
2.0.4
2.0.5
2.0.6
2.1.0
2.1.1
2.1.10
2.1.11
2.1.12
2.1.13
2.1.14
2.1.15
2.1.16
2.1.2
2.1.3
2.1.4
2.1.5
2.1.6
2.1.7
2.1.8
2.1.9
2.2.0
2.2.1
2.2.2
2.2.3
2.2.4 ]]
+ [[ -z '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
+ [[ -d /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git ]]
+ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
+ [[ -n 1 ]]
+ echo 'Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...'
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
++ repo_var /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
++ local repo_var
++ git config remote.origin.url
++ repo_var=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
++ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ repo_var=/homebrew/homebrew-cask
++ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
++ /Library/Developer/CommandLineTools/usr/bin/git config remote.origin.url
+++ echo -n /homebrew/homebrew-cask
+++ tr -C A-Za-z0-9 _
+++ tr '[:lower:]' '[:upper:]'
+ UPSTREAM_REPOSITORY_URL=https://github.com/Homebrew/brew
+ [[ https://github.com/Homebrew/brew = \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/* ]]
++ repo_var=_HOMEBREW_HOMEBREW_CASK
++ echo _HOMEBREW_HOMEBREW_CASK
+ UPSTREAM_REPOSITORY=Homebrew/brew
+ UPSTREAM_REPOSITORY=Homebrew/brew
+ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+ [[ -n 1 ]]
+ TAP_VAR=_HOMEBREW_HOMEBREW_CASK
++ sed -n 's/^ETag: "\([a-f0-9]\{32\}\)".*/\1/p' .git/GITHUB_HEADERS
++ upstream_branch
++ local upstream_branch
+++ git symbolic-ref refs/remotes/origin/HEAD
+ GITHUB_API_ETAG=12d5998bb91f48afe15099b8bf9e90e5
+ GITHUB_API_ACCEPT=application/vnd.github.v3+json
+ GITHUB_API_ENDPOINT=tags
++ curl -q --silent --max-time 3 --location --output /dev/null --write-out '%{http_code}' --dump-header /usr/local/Homebrew/.git/GITHUB_HEADERS --user-agent 'Homebrew/2.2.4 (Macintosh; Intel Mac OS X 10.15.2) curl/7.64.1' --header 'Accept: application/vnd.github.v3+json' --header 'If-None-Match: "12d5998bb91f48afe15099b8bf9e90e5"' https://api.github.com/repos/Homebrew/brew/tags
++ upstream_branch=refs/remotes/origin/master
++ upstream_branch=master
++ [[ -z master ]]
++ echo master
+ UPSTREAM_BRANCH_DIR=master
+ declare UPSTREAM_BRANCH_HOMEBREW_HOMEBREW_CASK=master
++ git rev-parse -q --verify refs/remotes/origin/master
++ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
++ /Library/Developer/CommandLineTools/usr/bin/git rev-parse -q --verify refs/remotes/origin/master
+ declare PREFETCH_REVISION_HOMEBREW_HOMEBREW_CASK=c22805bc3f5fca2d4b6f3a240a7a3c216da91dee
+ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+ [[ -z '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
+ [[ -d /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git ]]
+ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
+ [[ -n 1 ]]
+ echo 'Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...'
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
++ repo_var /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
++ git config remote.origin.url
++ local repo_var
++ repo_var=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
++ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
++ repo_var=/homebrew/homebrew-core
++ /Library/Developer/CommandLineTools/usr/bin/git config remote.origin.url
+++ echo -n /homebrew/homebrew-core
+++ tr -C A-Za-z0-9 _
+++ tr '[:lower:]' '[:upper:]'
+ UPSTREAM_REPOSITORY_URL=https://github.com/Homebrew/homebrew-cask
+ [[ https://github.com/Homebrew/homebrew-cask = \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/* ]]
+ UPSTREAM_REPOSITORY=Homebrew/homebrew-cask
+ UPSTREAM_REPOSITORY=Homebrew/homebrew-cask
+ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ repo_var=_HOMEBREW_HOMEBREW_CORE
++ echo _HOMEBREW_HOMEBREW_CORE
+ TAP_VAR=_HOMEBREW_HOMEBREW_CORE
++ git rev-parse refs/remotes/origin/master
++ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
++ /Library/Developer/CommandLineTools/usr/bin/git rev-parse refs/remotes/origin/master
++ upstream_branch
++ local upstream_branch
+++ git symbolic-ref refs/remotes/origin/HEAD
+ GITHUB_API_ETAG=c22805bc3f5fca2d4b6f3a240a7a3c216da91dee
+ GITHUB_API_ACCEPT=application/vnd.github.v3.sha
+ GITHUB_API_ENDPOINT=commits/master
++ curl -q --silent --max-time 3 --location --output /dev/null --write-out '%{http_code}' --dump-header /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git/GITHUB_HEADERS --user-agent 'Homebrew/2.2.4 (Macintosh; Intel Mac OS X 10.15.2) curl/7.64.1' --header 'Accept: application/vnd.github.v3.sha' --header 'If-None-Match: "c22805bc3f5fca2d4b6f3a240a7a3c216da91dee"' https://api.github.com/repos/Homebrew/homebrew-cask/commits/master
++ upstream_branch=refs/remotes/origin/master
++ upstream_branch=master
++ [[ -z master ]]
++ echo master
+ UPSTREAM_BRANCH_DIR=master
+ declare UPSTREAM_BRANCH_HOMEBREW_HOMEBREW_CORE=master
++ git rev-parse -q --verify refs/remotes/origin/master
++ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
++ /Library/Developer/CommandLineTools/usr/bin/git rev-parse -q --verify refs/remotes/origin/master
+ declare PREFETCH_REVISION_HOMEBREW_HOMEBREW_CORE=07fcb96b558b7ad18f36a9ba9a90752822fe988e
+ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+ [[ -z '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ wait
++ git config remote.origin.url
++ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
++ /Library/Developer/CommandLineTools/usr/bin/git config remote.origin.url
+ UPSTREAM_REPOSITORY_URL=https://github.com/Homebrew/homebrew-core
+ [[ https://github.com/Homebrew/homebrew-core = \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/* ]]
+ UPSTREAM_REPOSITORY=Homebrew/homebrew-core
+ UPSTREAM_REPOSITORY=Homebrew/homebrew-core
+ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ git rev-parse refs/remotes/origin/master
++ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
++ /Library/Developer/CommandLineTools/usr/bin/git rev-parse refs/remotes/origin/master
+ GITHUB_API_ETAG=07fcb96b558b7ad18f36a9ba9a90752822fe988e
+ GITHUB_API_ACCEPT=application/vnd.github.v3.sha
+ GITHUB_API_ENDPOINT=commits/master
++ curl -q --silent --max-time 3 --location --output /dev/null --write-out '%{http_code}' --dump-header /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/GITHUB_HEADERS --user-agent 'Homebrew/2.2.4 (Macintosh; Intel Mac OS X 10.15.2) curl/7.64.1' --header 'Accept: application/vnd.github.v3.sha' --header 'If-None-Match: "07fcb96b558b7ad18f36a9ba9a90752822fe988e"' https://api.github.com/repos/Homebrew/homebrew-core/commits/master
+ UPSTREAM_SHA_HTTP_CODE=304
+ [[ -f /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/FETCH_HEAD ]]
+ touch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/FETCH_HEAD
+ [[ -z '' ]]
+ [[ 304 = \3\0\4 ]]
+ exit
+ UPSTREAM_SHA_HTTP_CODE=200
+ [[ -f /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git/FETCH_HEAD ]]
+ touch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git/FETCH_HEAD
+ [[ -z '' ]]
+ [[ 200 = \3\0\4 ]]
+ [[ -n 1 ]]
+ echo 'Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...'
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
+ [[ -n '' ]]
+ git fetch --tags --force origin refs/heads/master:refs/remotes/origin/master
+ [[ -z /Library/Developer/CommandLineTools/usr/bin/git ]]
+ /Library/Developer/CommandLineTools/usr/bin/git fetch --tags --force origin refs/heads/master:refs/remotes/origin/master
+ UPSTREAM_SHA_HTTP_CODE=304
+ [[ -f /usr/local/Homebrew/.git/FETCH_HEAD ]]
+ touch /usr/local/Homebrew/.git/FETCH_HEAD
+ [[ -z '' ]]
+ [[ 304 = \3\0\4 ]]
+ exit

```
</details>

## What you expected to happen

Update and install

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install YouTube-dl

**Comment by MikeMcQuaid** [comment] 2020-01-27 00:23
How long did you wait? I cannot reproduce this so closing (it's likely related to your internet connection) but will reopen if we figure out something reproducible.

**Closed by MikeMcQuaid** 2020-01-27 00:23 UTC
