### ISSUE TITLE
SSH_AUTH_SOCK needs to be white listed when environment is filtered

### ISSUE THREAD

**Issue by paulmer** [Homebrew/brew#3503] opened 2017-11-29 14:14 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

```
brew config
HOMEBREW_VERSION: 1.3.8-65-g6cf38d0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 6cf38d0dd87ab215bc5be13bf98f3654531b6ef4
Last commit: 77 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f17f64c9aa75957ee7775f6a4d5d32db4a137b6d
Core tap last commit: 13 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_ENV_FILTERING: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GIT_CONFIG_DEVELOPERMODE: true
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.6 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/paulmer/.rvm/rubies/ruby-2.2.0/bin/ruby
Java: 1.8.0_77, 1.8.0_71, 1.8.0_60
macOS: 10.13.1-x86_64
Xcode: 9.1
CLT: 9.1.0.0.1.1508540944
X11: 2.7.11 => /opt/X11
```
```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/paulmer/login-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libmpg123.0.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  cpanminus
  php71
  ruby
  cloog

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  ruby@2.3
```

To help us debug your issue please explain:
- What you were trying to do (and why)
brew update with a tap to a local git repository accessed via ssh

- What happened (include command output)
Access to the repository fails because ssh authentication via public/private keys fails
(Paths and system information intentionally omitted [...])

```
brew update
Red Hat Enterprise Linux Server [...]

Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/[...] failed!
Updated Homebrew from 6cf38d0dd to 3f7e63a24.
No changes to formulae.
```

- What you expected to happen
tap should be updated

- Step-by-step reproduction instructions (by running `brew` commands)
Before I give you step-by-step details, let me explain the issue:  When environment filtering is enabled, the SSH_AUTH_SOCK variable is removed from the environment which causes SSH key authentication within git to fail.  The SSH_AUTH_SOCK variable should be whitelisted in bin/brew.

To reproduce:
1. Create a git repository for a tap, accessible via SSH.  Configure SSH keys to access the repository.
2. Tap the repository (without environment filtering): `HOMEBREW_NO_ENV_FILTERING=1 brew tap repo/name ssh://path/to/repo`.  This should access the tap using the configured SSH keys.
3. Brew update with filtering enabled: `HOMEBREW_NO_ENV_FILTERING= brew update`.  This will fail because SSH_AUTH_SOCK is filtered from the environment prior to running Git.

**Comment by reitermarkus** [comment] 2017-11-29 15:05
Duplicate of https://github.com/Homebrew/brew/pull/3493, but this provides a better justification for whitelisting it.

**Comment by paulmer** [comment] 2017-11-29 15:39
Ugh, sorry about the duplicate.

**Comment by MikeMcQuaid** [comment] 2017-11-29 16:00
> Error: Fetching /usr/local/Homebrew/Library/Taps/[...] failed!

Which tap failed? 

> Tap the repository (without environment filtering): HOMEBREW_NO_ENV_FILTERING=1 brew tap repo/name ssh://path/to/repo. This should access the tap using the configured SSH keys.

Is there a non-SSH URL you can use for this tap?

**Comment by jonatin** [comment] 2017-11-29 19:02
Depending on the environment, some internal taps might **only** be accessible via SSH. That's liable to be the case for teams that are hosting their internal taps outside of Github.com proper.

**Comment by MikeMcQuaid** [comment] 2017-11-29 19:03
@jonatin Is this the case for you, though?

**Comment by jonatin** [comment] 2017-11-29 19:10
Yes, it is, but I'm unable to share the full details. I'm stuck with several internal taps that can only be accessed via SSH for the majority of my users.

**Closed** 2017-11-30 09:29 UTC
