### ISSUE TITLE
portable ruby crashes

### ISSUE THREAD

**Issue by cblecker** [Homebrew/brew#4930] opened 2018-09-18 18:44 UTC
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I first was attempting install a new formula (csshx). This crashed with output, although the formula was installed. Other commands (like `brew update` or `brew doctor`) also crash with similar output.

- What happened (include command output)
https://gist.github.com/cblecker/bbe45f007bbb891ff358dea61529b50a

- What you expected to happen
The formula would be installed.

- Step-by-step reproduction instructions (by running `brew` commands)
Running `brew update`, `brew install <formula>`, or `brew doctor` displays this ruby crash output.

`brew config` output:
```
HOMEBREW_VERSION: 1.7.5-11-g47bebcd
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 47bebcdeca14ba52de3fd0067ab3aefe91fa2ec5
Last commit: 58 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: 12378f017b4e9843e09f76d199dc86e22cda2a22
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEVELOPER: true
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment] 2018-09-19 16:30
Duplicate of https://github.com/Homebrew/brew/issues/4923.

**Closed by MikeMcQuaid** 2018-09-19 16:30 UTC
