### ISSUE TITLE
API-based update downgraded cask

### ISSUE THREAD

**Issue by mitchblank** [Homebrew/brew#14483] opened 2023-02-02 18:52 UTC
### `brew doctor` output

```shell
This is from a long-lived install which I've also done formulae development on, so there are a lot of "installed kegs have no formulae" etc... really too much to quote.  No warnings related to casks though.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-189-g3af2f0e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3af2f0ececc848bca34ddbd5b876d20dc24a6aaa
Last commit: 39 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c7c38c40e91994ba2b59fa8570f836df0178d064
Core tap last commit: 83 minutes ago
Core tap branch: master
Core tap JSON: 01 Feb 01:49
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.TKKvVtmW0w/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```
(I elided `HOMEBREW_EDITOR` since it just pointed at my own vim-wrapping script I use as `$VISUAL` but not really relevant to this discussion)
```


### What were you trying to do (and why)?

I previously mentioned this in a comment on another issue ( https://github.com/Homebrew/brew/issues/14449#issuecomment-1414168433 ) and am filing it as a separate issue per a request there.

Normal `brew upgrade` just like I run frequently.

I've used this install for a lot of formulae (but not cask!) development.  My usual routine is:
```sh
$ cd $(brew --repo homebrew/core)/Formula
$ git pull
$ brew upgrade
```
I know that the `git pull` is something that `brew` can do automatically, but I just like to see what changes in the formulae repo day-to-day so I do it manually.

### What happened (include all command output)?

One of my casks which homebrew had previously upgraded, got downgraded:
```
$ git pull    
remote: Enumerating objects: 1044, done.
remote: Counting objects: 100% (821/821), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 1044 (delta 751), reused 789 (delta 722), pack-reused 223
Receiving objects: 100% (1044/1044), 607.67 KiB | 3.38 MiB/s, done.
Resolving deltas: 100% (754/754), completed with 131 local objects.
From https://github.com/Homebrew/homebrew-core
   0af99a0552a..c7c38c40e91  master     -> origin/master
Updating 0af99a0552a..c7c38c40e91
Fast-forward
[ ... eliding diffstat output ...]
122 files changed, 1215 insertions(+), 1183 deletions(-)
 create mode 100644 Formula/crfsuite.rb
time git pull: 0.41s/0.63s/28% user/kern, 3.604 elapsed

$ brew upgrade
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 7a5f6143d to cdc6a4f11.
Updated 1 tap (homebrew/cask-versions).

You have 11 outdated formulae and 1 outdated cask installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Upgrading 11 outdated packages:

[... bunch of non-cask upgrades, nothing notable ...]

==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
kitty 0.27.0 -> 0.26.5
==> Upgrading kitty
==> Downloading https://github.com/kovidgoyal/kitty/releases/download/v0.26.5/kitty-0.26.5.dmg
Already downloaded: /Users/mitch/Library/Caches/Homebrew/downloads/a5773a93f0d48a59da4eff9758367dcf45bc8a14630b78ae0be7da93fa9ebd7c--kitty-0.26.5.dmg
==> Backing App 'kitty.app' up to '/usr/local/Caskroom/kitty/0.27.0/kitty.app'
==> Removing App '/Applications/kitty.app'
==> Unlinking Binary '/usr/local/bin/kitty'
==> Moving App 'kitty.app' to '/Applications/kitty.app'
==> Linking Binary 'kitty.wrapper.sh' to '/usr/local/bin/kitty'
==> Purging files for version 0.27.0 of Cask kitty
```

### What did you expect to happen?

cask remains at the latest version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
It had been very insistent that it had the current version:

$ brew info --cask kitty
==> kitty: 0.26.5
https://github.com/kovidgoyal/kitty
/usr/local/Caskroom/kitty/0.26.5 (218B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/kitty.rb
==> Name
kitty
==> Description
GPU-based terminal emulator
==> Artifacts
kitty.app (App)
/usr/local/Caskroom/kitty/0.26.5/kitty.wrapper.sh -> kitty (Binary)
==> Analytics
install: 2,365 (30 days), 6,829 (90 days), 27,204 (365 days)
```

Looking at the status of the homebrew-cask git checkout showed that it hadn't been updated in 9 days (despite many "git upgrade"'s being run in that time)  I imagine that is due to some change in default wrt the new API stuff:
```
$ git l
f69317f19e - (HEAD -> master) adguard 2.9.2.1234 (9 days ago) <stevezhengshiqi>
[...]
```

After disabling the API another update fixed the problem:
```
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew upgrade
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
kitty 0.26.5 -> 0.27.0
[...]
```

As I would expect this was because it then automatically updated the git checkout:
```
$ git l
cc05495e4c - (HEAD -> master, origin/master, origin/HEAD) Upgrade Headlamp version to 0.15.0 (#140522) (82 minutes ago) <Joaquim Rocha>
[...]
```

So:
* Some change in the homebrew code caused it to stop updating my homebrew-cask git directory.  I gather this is intentional as part of the API transition
* At some point the API code correctly updated the "kitty" cask
* Today for some reason the API wasn't working (maybe an intermittent problem?) so I guess it fell back onto the now-outdated git checkout?!?  Unclear.
* Downgrade hijinks.

At a minimum it seems that there is some poor fallback behavior where it can end up relying on git files without updating them first leading to incorrect results, at least for installs that predate the introduction of the API.  Either it should be using API data or up-to-date git data, but there seems to be some instance where it ends up using not-updated git data to make package upgrade decisions.
```

**Comment by carlocab** [comment] 2023-02-03 01:26
What's the output of
```
export HOMEBREW_NO_INSTALL_FROM_API
brew update
brew outdated --cask
```
?

**Comment by mitchblank** [comment] 2023-02-03 02:14
Well right now they're not showing anything outdated, because the `git pull` from the successful update means that the git data is up-to-date.

If I try to force git into an old state, outdated shows kitty as "outdated"
```
$ git reset --hard f69317f19e
$ unset HOMEBREW_NO_INSTALL_FROM_API
$ brew outdated --cask
kitty (0.27.0) != 0.26.5
```
I don't know if there is a way to see if it is making an attempt to get newer data from the API?  `brew outdated -v -d --cask` doesn't print any extra info.  As far as I can see, it's idea of "outdated" only depends on the state of the git-repo, but unless `HOMEBREW_NO_INSTALL_FROM_API` is set it doesn't automatically update that.

**Comment by carlocab** [comment] 2023-02-03 06:56
Oops, I had meant `HOMEBREW_NO_INSTALL_FROM_API=1` up there. I'm also a bit unclear on the sequence of events here, especially with the manual `git pull`s in the mix.

My guess is that when you did `brew upgrade`, the API data was slightly behind the Homebrew/cask repo and so thought the latest version was `0.26.5`. Formulae will never be downgraded in this way, but I'm less sure about casks. It seems not, but if that's the case then I believe that was intentional. It just happens to interact weirdly with API installations.

**Comment by MikeMcQuaid** [comment] 2023-02-03 08:45
> My guess is that when you did `brew upgrade`, the API data was slightly behind the Homebrew/cask repo and so thought the latest version was `0.26.5`.

Yes, this is what happened. My suggestion would be to either `export HOMEBREW_NO_INSTALL_FROM_API=1` or not to rely on Git and the API being in sync.

**Comment by gromgit** [comment] 2023-02-03 10:28
> Formulae will never be downgraded in this way, but I'm less sure about casks

`brew outdated` separates formulae versions with `<` and cask versions with `!=`, so I suspect cask logic only cares that "latest version is not the installed version".

**Comment by Rylan12** [comment] 2023-02-03 10:44
Sorry, maybe I'm misunderstanding the issue here. Was the original (non-downgraded) cask built directly from the tap or is the API giving inconsistent version numbers?

**Comment by mitchblank** [comment] 2023-02-03 10:49
> Yes, this is what happened.

But as I mentioned, when the downgrade first happened my git cask data was 9 days stale, so the upgrade to `kitty` was done originally from API data.  So did the version of the cask advertised by the API go backwards?

> `brew outdated` separates formulae versions with `<` and cask versions with `!=`

Then that would imply there is a strong dependency on the set of versions only monotonically increasing.  So, for instance, any divergence between multiple API servers could cause problems since a client can get version X from server A and later get version X-1 from server B.  Before `homebrew --cask` was only relying on git (and github) to not take the repo checkout backwards which was a safe bet.

> My suggestion would be to either export `HOMEBREW_NO_INSTALL_FROM_API=1`...

Yes, I've done that on my installs after experiencing this problem.  I'm not against the API in principal (it sounds like it makes sense for the 95% case) but I often poke around the git directory to run `git log` etc to look at package history so I prefer the "full fat" version.

Still, I wanted to flag the issue with you developers since if the API is downgrade-prone (at least for casks) then I think it's going to become a source of problems.

**Comment by Rylan12** [comment] 2023-02-04 00:11
> So did the version of the cask advertised by the API go backwards?

Yeah, that's what I'm concerned about. As far as I can tell it shouldn't be possible for it to go backward like this which is why I'm confused. It seems like there's some edge case where casks are loaded from the taps when they shouldn't be, but I'll need to try to reproduce it on my machine to really tell.

> Yes, I've done that on my installs after experiencing this problem. I'm not against the API in principal (it sounds like it makes sense for the 95% case) but I often poke around the git directory to run `git log` etc to look at package history so I prefer the "full fat" version.

Yeah, it sounds like your specific requirements might be best fit to have `HOMEBREW_NO_INSTALL_FROM_API` set. That being said, I still think there's a bug here that others could run into that I want to fix if possible since there's still clearly some unpredictable behavior. The goal is that only very specific cases (like yours, maybe) actually require `HOMEBREW_NO_INSTALL_FROM_API` and everything else will work fine without it.



> Still, I wanted to flag the issue with you developers since if the API is downgrade-prone (at least for casks) then I think it's going to become a source of problems.

Thank you, I appreciate the report ❤️

**Comment by Rylan12** [comment] 2023-02-04 00:54
One way I could reproduce this kind of behavior is by changing the API URL that Homebrew uses to something that will definitely 404. If that happens, Homebrew tries to fall back to the existing cached JSON file but accidentally falls back to `nil` instead which causes it to fall even further back onto the taps.

I _think_ that will fix your issue so this will be closed when that is merged, but TBH I'm not totally sure so if it continues to happen let me know.

**Closed** 2023-02-04 12:47 UTC
Labels: bug, install from api
