### ISSUE TITLE
ZIMG SHA256 mismatch

### ISSUE THREAD

**Issue by micjoh** [Homebrew/brew#397] opened 2016-06-23 22:41 UTC
Trying to install MPV a dependencie ZIMG gets SHA256 mismatch.

==> Installing dependencies for mpv: zimg, vapoursynth
==> Installing mpv dependency: zimg
==> Downloading https://github.com/sekrit-twc/zimg/archive/release-2.1.tar.gz
==> Downloading from https://codeload.github.com/sekrit-twc/zimg/tar.gz/release-
######################################################################## 100,0%
Error: SHA256 mismatch
Expected: e6d6c6c60b38ebaf74e2ab934b5b90b54e61f34e0a3f111c9da82958335f25da
Actual: 09093bbb4d73865362e1e346762a6efdc9acc3d2cab6a2ebf5f00ba5d90b17c3

**Comment by scpeters** [comment] 2016-06-24 00:17
looks like a duplicate of https://github.com/Homebrew/homebrew-core/pull/1359

**Comment by MikeMcQuaid** [comment] 2016-06-25 19:30
> looks like a duplicate of Homebrew/homebrew-core#1359

Closing in favour of that.

**Closed by MikeMcQuaid** 2016-06-25 19:30 UTC
