### ISSUE TITLE
I just can't compile my formula after commit  82f5b51

### ISSUE THREAD

**Issue by markwu** [Homebrew/brew#7147] opened 2020-03-10 19:10 UTC
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I have no problem to compile my formula before commit https://github.com/Homebrew/brew/commit/82f5b510c1e895ca7cf5786bf197c4cd67d29469 , after update to brew master head I just can't compile my formula.

My formula list here: https://github.com/markwu/homebrew-personal/blob/master/Formula/zeal.rb

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew reinstall zeal
==> Reinstalling markwu/personal/zeal
==> Cloning https://github.com/zealdocs/zeal.git
Updating /Users/mark/Library/Caches/Homebrew/zeal--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at fc1f18f feat(core,registry): unmount HTTP server prefix on docset removal
==> Downloading https://raw.githubusercontent.com/markwu/homebrew-personal/master/Formula/zeal@head.diff
######################################################################## 100.0%
==> Patching
==> Applying zeal@head.diff
patching file src/libs/browser/CMakeLists.txt
patching file src/libs/core/CMakeLists.txt
patching file src/libs/ui/CMakeLists.txt
==> cmake ..
==> make
Last 15 lines from /Users/mark/Library/Logs/Homebrew/zeal/02.make:
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:330:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
13 errors generated.
make[2]: *** [src/libs/registry/CMakeFiles/Registry.dir/docsetregistry.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/libs/registry/CMakeFiles/Registry.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/markwu/homebrew-personal/issues

  </pre>
</details>

## What you expected to happen
```
$ brew reinstall zeal
==> Reinstalling markwu/personal/zeal
==> Cloning https://github.com/zealdocs/zeal.git
Updating /Users/mark/Library/Caches/Homebrew/zeal--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at fc1f18f feat(core,registry): unmount HTTP server prefix on docset removal
==> Downloading https://raw.githubusercontent.com/markwu/homebrew-personal/master/Formula/zeal@head.diff
Already downloaded: /Users/mark/Library/Caches/Homebrew/downloads/afb1b9a9c6ee32691eeb304942413483bdc9716abbe938f091612f2312913018--zeal@head.diff
==> Patching
==> Applying zeal@head.diff
patching file src/libs/browser/CMakeLists.txt
patching file src/libs/core/CMakeLists.txt
patching file src/libs/ui/CMakeLists.txt
==> cmake ..
==> make
🍺  /usr/local/Cellar/zeal/HEAD-fc1f18f: 9 files, 2MB, built in 35 seconds
Removing: /Users/mark/Library/Caches/Homebrew/zeal--patch--91ea0afb7f18865c859fa47301c6f12a4c9aec4556d8b705f7ce32c1caa8102a.diff... (1.9KB)
```

## Step-by-step reproduction instructions (by running `brew` commands)

```
$ brew install qt
$ brew tap markwu/personal
$ brew install qt5-webkit
$ brew install zeal
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.2.10-12-gb6812d2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b6812d2dfba0fa1825be0e20dcaa3b6128f43a93
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3e2b762e901599ff5d536f322feb2f45d35dad10
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CUSTOM_RUBY_HOME: /Users/mark/.rvm/rubies/ruby-2.6.5
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_231
macOS: 10.14.6-x86_64
CLT: 11.3.0.0.1.1574140115
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/mark/.phpbrew/php/php-7.3.15/bin/php-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.7m/greenlet/greenlet.h

Warning: You have uncommitted modifications to Homebrew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library && git stash && git clean -d -f

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install node

Run `brew missing` for more details.
</pre>

**Comment by MikeMcQuaid** [comment] 2020-03-10 19:14
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/markwu/homebrew-personal/issues

We don't support build issues with non-homebrew-core formulae. @Bo98 may be able to provide advice on the error messages.

**Comment by dawidd6** [comment] 2020-03-10 19:14
Should be fixed in: https://github.com/Homebrew/brew/commit/89f3a332644d1b9c41f7cab53ab9045aec2b517f

**Closed** 2020-03-10 19:14 UTC

**Comment by Bo98** [comment] 2020-03-10 19:15
The problem is that you should be using `std_cmake_args`, but aren't.

I don't think there's any other way to set `CMAKE_OSX_SYSROOT` outside that, short of a global `SDKROOT` or a `cmake` shim.

**Comment by markwu** [comment] 2020-03-10 19:20
@dawidd6 No, it dit not fix the issue.

@Bo98 Can you elaborate me more hints or point me some documents or information? Then, I can check it myself. Thanks.

**Comment by Bo98** [comment] 2020-03-10 19:21
Example usage of `std_cmake_args`: https://github.com/Homebrew/homebrew-core/blob/3146235d5f9fc22b3e090f91f1b639567f75691b/Formula/innoextract.rb#L21

**Comment by markwu** [comment] 2020-03-10 19:25
@Bo98 Ah, I see. ! Now, I known what you mean, and it fixed my issue. Great thanks!
