### ISSUE TITLE
Wrong bundle path when using `brew audit`

### ISSUE THREAD

**Issue by ivaquero** [Homebrew/brew#14083] opened 2022-11-03 13:39 UTC
### `brew config` output

```shell
ORIGIN: https://github.com/Homebrew/brew
HEAD: e7b213c0944e191ff11d61e588cd29a1b6e83867
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cebec10e186cf569bce945c2cc735505a453b21e
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: /usr/bin occurs before /opt/homebrew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/opt/homebrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

The following tools exist at both paths:
  cpan
  instmodsh
  db_upgrade
  perlivp
  pod2usage
  corelist
  db_hotbackup
  libnetcfg
  python3
  encguess
  db_printlog
  db_archive
  pip3
  pod2text
  ptardiff
  db_stat
  json_pp
  perl
  perlbug
  db_load
  piconv
  ptargrep
  h2ph
  prove
  podchecker
  shasum
  ptar
  pl2pm
  db_verify
  perlthanks
  xsubpp
  streamzip
  perldoc
  h2xs
  db_checkpoint
  pod2man
  enc2xs
  db_deadlock
  splain
  pod2html
  db_recover
  db_dump
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to audit my new cask locally.

### What happened (include all command output)?

An error was raised by wrong bundle path

```console
brew audit --cask dvc
/opt/homebrew/Library/Homebrew/shims/ruby/bundle:15:in `load': cannot load such file -- /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.24-arm64-darwin-22/exe/bundle (LoadError)
        from /opt/homebrew/Library/Homebrew/shims/ruby/bundle:15:in `<main>'
Error: failed to run `/opt/homebrew/Library/Homebrew/shims/ruby/bundle install`!
```

### What did you expect to happen?

The correct bundle path should be `/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.24/exe/bundle`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just to use `brew audit --cask dvc`
```

**Comment by MikeMcQuaid** [comment] 2022-11-04 12:12
@Bo98 any thoughts here?

**Comment by Bo98** [comment] 2022-11-04 12:33
See also: https://github.com/orgs/Homebrew/discussions/3814

Despite my attempts, I've not been able to reproduce this issue so far, so I don't know exactly what the issue is.

It _might_ be because of the workaround we have for System Ruby. I'm working with upstream to get that workaround integrated within Bundler. The workround upstream is slightly different than what we have in brew but has been confirmed to pass their CI and is near approval beyond some final unit test tweaks. I could try align our workaround to be more like that patch, but I don't know for sure if that's the issue or not.

**Comment by ivaquero** [comment] 2022-11-04 12:38
The file `/opt/homebrew/Library/Homebrew/shims/ruby/bundle` is as follows

```console
#!/usr/bin/env ruby
# frozen_string_literal: true

# Insert our system Ruby patch script, if neeeded.
# Fixes universal-ruby getting confused whether to install arm64 or x86_64 macOS versions.
# https://github.com/rubygems/rubygems/issues/4234
if RUBY_PLATFORM.match?(/universal\..*-darwin/)
  rubylib = File.expand_path("../../rubyext", File.dirname(__FILE__))
  ENV["RUBYLIB"] = rubylib
  $LOAD_PATH.unshift(rubylib) unless $LOAD_PATH.include?(rubylib)
  require "rubygems/defaults/operating_system" if defined?(Gem) # Reload if already loaded.
end

require "rubygems"
load Gem.activate_bin_path("bundler", "bundle", ">= 0.a")
```

It seems like a patch. I came across this error after I updated to Monterey.

**Comment by Bo98** [comment] 2022-11-04 12:44
> I could try align our workaround to be more like that patch, but I don't know for sure if that's the issue or not.

This would look something like: Bo98/brew@7f9a5d7bc1d27ffa3c9aa5d1663c258ba4303039

**Comment by ivaquero** [comment] 2022-11-04 12:50
Thank you for the info.

**Comment by Bo98** [comment] 2022-11-05 01:41
Can you try it now (after a `brew update`) and see if it's any different?

**Comment by ivaquero** [comment] 2022-11-05 01:54
I'm outside at the moment. I'll post the result here as soon as I get home ( in 40 min hopefully ).

**Comment by ivaquero** [comment] 2022-11-05 02:42
The output is as follows

```console
Fetching gem metadata from https://rubygems.org/.......
Fetching concurrent-ruby 1.1.10
Fetching zeitwerk 2.6.1
Fetching public_suffix 5.0.0
Fetching minitest 5.16.3
Installing zeitwerk 2.6.1
Installing public_suffix 5.0.0
Fetching ast 2.4.2
Fetching bindata 2.4.12
Installing minitest 5.16.3
Fetching msgpack 1.6.0
Installing ast 2.4.2
Using bundler 2.3.24
Fetching byebug 11.1.3
Installing bindata 2.4.12
Fetching connection_pool 2.3.0
Installing byebug 11.1.3 with native extensions
Installing msgpack 1.6.0 with native extensions
Installing connection_pool 2.3.0
Fetching did_you_mean 1.6.1
Fetching diff-lcs 1.5.0
Installing did_you_mean 1.6.1
Fetching docile 1.4.0
Installing diff-lcs 1.5.0
Fetching unf_ext 0.0.8.2
Fetching regexp_parser 2.6.0
Installing docile 1.4.0
Fetching hana 1.3.7
Installing hana 1.3.7
Fetching hpricot 0.8.6
Installing regexp_parser 2.6.0
Fetching json 2.6.2
Installing concurrent-ruby 1.1.10
Fetching uri_template 0.7.0
Installing json 2.6.2 with native extensions
Fetching mime-types-data 3.2022.0105
Installing uri_template 0.7.0
Fetching net-http-digest_auth 1.4.1
Installing net-http-digest_auth 1.4.1
Fetching racc 1.6.0
Installing mime-types-data 3.2022.0105
Fetching rubyntlm 0.6.3
Installing hpricot 0.8.6 with native extensions
Installing rubyntlm 0.6.3
Fetching webrick 1.7.0
Installing racc 1.6.0 with native extensions
Fetching webrobots 0.1.2
Installing webrick 1.7.0
Fetching mustache 1.1.1
Installing webrobots 0.1.2
Fetching parallel 1.22.1
Installing parallel 1.22.1
Fetching plist 3.6.0
Installing mustache 1.1.1
Fetching rack 3.0.0
Installing plist 3.6.0
Fetching rainbow 3.1.1
Installing rainbow 3.1.1
Fetching rdiscount 2.2.0.2
Installing rdiscount 2.2.0.2 with native extensions
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching rspec-support 3.11.1
Installing unf_ext 0.0.8.2 with native extensions
Fetching sorbet-runtime 0.5.10461
Installing rspec-support 3.11.1
Fetching ruby-progressbar 1.11.0
Installing ruby-progressbar 1.11.0
Fetching unicode-display_width 2.3.0
Installing sorbet-runtime 0.5.10461
Fetching ruby-macho 3.0.0
Installing unicode-display_width 2.3.0
Fetching simplecov-html 0.12.3
Installing ruby-macho 3.0.0
Fetching simplecov_json_formatter 0.1.4
Installing simplecov_json_formatter 0.1.4
Fetching warning 1.3.0
Installing simplecov-html 0.12.3
Fetching addressable 2.8.1
Installing warning 1.3.0
Fetching parser 3.1.2.1
Installing rack 3.0.0
Fetching elftools 1.2.0
Installing elftools 1.2.0
Fetching net-http-persistent 4.0.1
Fetching bootsnap 1.13.0
Installing net-http-persistent 4.0.1
Fetching ecma-re-validator 0.4.0
Installing bootsnap 1.13.0 with native extensions
Fetching i18n 1.12.0
Installing addressable 2.8.1
Fetching tzinfo 2.0.5
Installing ecma-re-validator 0.4.0
Fetching mime-types 3.4.1
Installing tzinfo 2.0.5
Fetching nokogiri 1.13.9 (arm64-darwin)
Installing i18n 1.12.0
Fetching parallel_tests 3.13.0
Installing mime-types 3.4.1
Fetching unf 0.1.4
Installing parallel_tests 3.13.0
Fetching rspec-core 3.11.0
Installing unf 0.1.4
Fetching rspec-expectations 3.11.1
Installing rspec-expectations 3.11.1
Fetching rspec-mocks 3.11.1
Installing rspec-mocks 3.11.1
Fetching rspec-sorbet 1.9.0
Installing rspec-sorbet 1.9.0
Fetching simplecov 0.21.2
Installing simplecov 0.21.2
Fetching patchelf 1.4.0
Installing patchelf 1.4.0
Fetching ronn 0.7.3
Installing rspec-core 3.11.0
Fetching json_schemer 0.2.21
Installing ronn 0.7.3
Fetching activesupport 6.1.7
Installing json_schemer 0.2.21
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching simplecov-cobertura 2.1.0
Installing simplecov-cobertura 2.1.0
Fetching rspec 3.11.0
Installing rspec 3.11.0
Fetching rspec-github 2.3.1
Installing rspec-github 2.3.1
Fetching rspec-its 1.3.0
Installing rspec-its 1.3.0
Fetching rspec-retry 0.6.2
Installing parser 3.1.2.1
Fetching rspec_junit_formatter 0.6.0
Installing activesupport 6.1.7
Fetching http-cookie 1.0.5
Installing rspec-retry 0.6.2
Fetching rspec-wait 0.0.9
Installing rspec_junit_formatter 0.6.0
Fetching rubocop-ast 1.21.0
Installing http-cookie 1.0.5
Installing rspec-wait 0.0.9
Installing rubocop-ast 1.21.0
Fetching rubocop 1.35.1
Installing rubocop 1.35.1
Fetching rubocop-performance 1.15.0
Fetching rubocop-rspec 2.13.2
Fetching rubocop-rails 2.16.1
Installing rubocop-rspec 2.13.2
Fetching rubocop-sorbet 0.6.11
Installing rubocop-performance 1.15.0
Installing rubocop-rails 2.16.1
Installing rubocop-sorbet 0.6.11
Installing nokogiri 1.13.9 (arm64-darwin)
Fetching mechanize 2.8.5
Installing mechanize 2.8.5
Bundle complete! 35 Gemfile dependencies, 77 gems now installed.
Bundled gems are installed into `../../../opt/homebrew/Library/Homebrew/vendor/bundle`
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:12: warning: already initialized constant Gem::VERSION
/Library/Ruby/Site/2.6.0/rubygems.rb:11: warning: previous definition of VERSION was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/compatibility.rb:14: warning: already initialized constant Gem::RubyGemsVersion
/Library/Ruby/Site/2.6.0/rubygems/compatibility.rb:15: warning: previous definition of RubyGemsVersion was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/compatibility.rb:18: warning: already initialized constant Gem::RbConfigPriorities
/Library/Ruby/Site/2.6.0/rubygems/compatibility.rb:18: warning: previous definition of RbConfigPriorities was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/compatibility.rb:27: warning: constant Gem::ConfigMap is deprecated
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/compatibility.rb:35: warning: constant Gem::ConfigMap is deprecated
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/defaults.rb:3: warning: already initialized constant Gem::DEFAULT_HOST
/Library/Ruby/Site/2.6.0/rubygems/defaults.rb:3: warning: previous definition of DEFAULT_HOST was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:117: warning: already initialized constant Gem::RUBYGEMS_DIR
/Library/Ruby/Site/2.6.0/rubygems.rb:115: warning: previous definition of RUBYGEMS_DIR was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:122: warning: already initialized constant Gem::WIN_PATTERNS
/Library/Ruby/Site/2.6.0/rubygems.rb:129: warning: previous definition of WIN_PATTERNS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:131: warning: already initialized constant Gem::GEM_DEP_FILES
/Library/Ruby/Site/2.6.0/rubygems.rb:138: warning: previous definition of GEM_DEP_FILES was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:141: warning: already initialized constant Gem::REPOSITORY_SUBDIRECTORIES
/Library/Ruby/Site/2.6.0/rubygems.rb:148: warning: previous definition of REPOSITORY_SUBDIRECTORIES was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:153: warning: already initialized constant Gem::REPOSITORY_DEFAULT_GEM_SUBDIRECTORIES
/Library/Ruby/Site/2.6.0/rubygems.rb:161: warning: previous definition of REPOSITORY_DEFAULT_GEM_SUBDIRECTORIES was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:162: warning: already initialized constant Gem::READ_BINARY_ERRORS
/Library/Ruby/Site/2.6.0/rubygems.rb:169: warning: previous definition of READ_BINARY_ERRORS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:172: warning: already initialized constant Gem::WRITE_BINARY_ERRORS
/Library/Ruby/Site/2.6.0/rubygems.rb:174: warning: previous definition of WRITE_BINARY_ERRORS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:185: warning: already initialized constant Gem::LOADED_SPECS_MUTEX
/Library/Ruby/Site/2.6.0/rubygems.rb:181: warning: previous definition of LOADED_SPECS_MUTEX was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:1345: warning: already initialized constant Gem::MARSHAL_SPEC_DIR
/Library/Ruby/Site/2.6.0/rubygems.rb:1308: warning: previous definition of MARSHAL_SPEC_DIR was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:157: warning: already initialized constant Gem::Version::VERSION_PATTERN
/Library/Ruby/Site/2.6.0/rubygems/version.rb:159: warning: previous definition of VERSION_PATTERN was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:158: warning: already initialized constant Gem::Version::ANCHORED_VERSION_PATTERN
/Library/Ruby/Site/2.6.0/rubygems/version.rb:160: warning: previous definition of ANCHORED_VERSION_PATTERN was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:17: warning: already initialized constant Gem::Requirement::OPS
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:12: warning: previous definition of OPS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:27: warning: already initialized constant Gem::Requirement::SOURCE_SET_REQUIREMENT
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:22: warning: previous definition of SOURCE_SET_REQUIREMENT was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:30: warning: already initialized constant Gem::Requirement::PATTERN_RAW
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:25: warning: previous definition of PATTERN_RAW was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:35: warning: already initialized constant Gem::Requirement::PATTERN
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:30: warning: previous definition of PATTERN was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:40: warning: already initialized constant Gem::Requirement::DefaultRequirement
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:35: warning: previous definition of DefaultRequirement was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:314: warning: already initialized constant Gem::Version::Requirement
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/platform.rb:198: warning: already initialized constant Gem::Platform::RUBY
/Library/Ruby/Site/2.6.0/rubygems/platform.rb:209: warning: previous definition of RUBY was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/platform.rb:204: warning: already initialized constant Gem::Platform::CURRENT
/Library/Ruby/Site/2.6.0/rubygems/platform.rb:215: warning: previous definition of CURRENT was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:9: warning: already initialized constant Gem::StubSpecification::PREFIX
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:9: warning: previous definition of PREFIX was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:12: warning: already initialized constant Gem::StubSpecification::OPEN_MODE
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:12: warning: previous definition of OPEN_MODE was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:18: warning: already initialized constant Gem::StubSpecification::StubLine::NO_EXTENSIONS
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:18: warning: previous definition of NO_EXTENSIONS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:21: warning: already initialized constant Gem::StubSpecification::StubLine::REQUIRE_PATHS
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:21: warning: previous definition of REQUIRE_PATHS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:31: warning: already initialized constant Gem::StubSpecification::StubLine::REQUIRE_PATH_LIST
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:31: warning: previous definition of REQUIRE_PATH_LIST was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification_policy.rb:4:in `<top (required)>': superclass mismatch for class SpecificationPolicy (TypeError)
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:16:in `<top (required)>'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:1365:in `<module:Gem>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:116:in `<top (required)>'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /opt/homebrew/Library/Homebrew/utils/gems.rb:47:in `setup_gem_environment!'
        from /opt/homebrew/Library/Homebrew/standalone/load_path.rb:13:in `<top (required)>'
        from /opt/homebrew/Library/Homebrew/standalone.rb:6:in `require_relative'
        from /opt/homebrew/Library/Homebrew/standalone.rb:6:in `<top (required)>'
        from /opt/homebrew/Library/Homebrew/utils/rubocop.rb:5:in `require_relative'
        from /opt/homebrew/Library/Homebrew/utils/rubocop.rb:5:in `<main>'
```

**Comment by Bo98** [comment] 2022-11-05 02:48
Ah ok, looks like that's a Rubygems problem which will have explained why I couldn't reproduce - it was likely causing the issues you had originally. You should probably remove the copy in `/Library/Ruby/Site`, but I've merged another fix (https://github.com/Homebrew/brew/pull/14098) which will hopefully avoid it, so test it out again after another `brew update` first.

**Comment by ivaquero** [comment] 2022-11-05 02:56
No problem.

**Comment by ivaquero** [comment] 2022-11-05 06:42
@Bo98 I believe this time it's Okay. Thank you!

**Comment by Bo98** [comment] 2022-11-05 15:17
Great! I think https://github.com/Homebrew/brew/pull/14099 covered that last error you had.

Good to know all is working now!

**Closed by Bo98** 2022-11-05 15:17 UTC
Labels: bug
