### ISSUE TITLE
Homebrew doesn't allow side-by-side Xcode 8.3.3 and 9.0 installations

### ISSUE THREAD

**Issue by jkili** [Homebrew/brew#2835] opened 2017-06-29 00:19 UTC
I have both 8.3.3 and 9.0 installed on MacOS High Sierra. 

When running brew upgrade xxxx, I am getting Error: Your Xcode (8.3.3) is too outdated. Please update to Xcode 9.0 (or delete it). Xcode can be updated from https://developer.apple.com/download/more/.

This seems a harsh position since 8.3.3 is the current release and 9.0 is only in BETA (and not stable yet).

**Comment by ilovezfs** [comment] 2017-06-29 05:04
What is the output of
```
xcode-select -p
```
and
```
brew config
```
and
```
brew doctor
```

**Comment by LeoNatan** [comment] 2017-06-29 12:14
Seeing the same issue. @ilovezfs  Here are my outputs:

```Leo-Natans-Wix-MPB:~ lnatan$ xcode-select -p
/Applications/Xcode.app/Contents/Developer```

```Leo-Natans-Wix-MPB:~ lnatan$ brew config
HOMEBREW_VERSION: >1.2.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76ed7898d002ed36e397c908f00589f62b78e641
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 623377fa6c659c89c1f8601fbdf0b2da59b76329
Core tap last commit: 3 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
xcodebuild: error: SDK "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk" cannot be located.
clang: error: unable to find utility "clang", not a developer tool or in PATH
Clang: N/A
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/lnatan/.rvm/rubies/ruby-2.0.0-p643/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 8.3.3
CLT: 9.0.0.0.1.1497666128
X11: N/A```

```Leo-Natans-Wix-MPB:~ lnatan$ brew doctor
xcodebuild: error: SDK "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk" cannot be located.
clang: error: unable to find utility "clang", not a developer tool or in PATH
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Ruby version 2.3.3 is unsupported on 10.13. Homebrew
is developed and tested on Ruby 2.0, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.

Warning: Your Xcode (8.3.3) is too outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/


Warning: Your Xcode (8.3.3) is outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/

If 9.0 is installed, you may need to:
  sudo xcode-select --switch /Applications/Xcode.app
Current developer directory is:
  /Applications/Xcode.app/Contents/Developer


Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/share/man/man1/prj2make.1
Leo-Natans-Wix-MPB:~ lnatan$ xcode-select -p
/Applications/Xcode.app/Contents/Developer```

This is blocking work.

**Comment by ilovezfs** [comment] 2017-06-29 12:18
OK. Please try this:

```
sudo mv /Applications/Xcode.app /Applications/Xcode-8.3.3.app
sudo mv /Applications/Xcode-beta.app /Applications/Xcode.app
```

**Comment by LeoNatan** [comment] 2017-06-29 12:21
@ilovezfs I actually wish to use 8.3.3, not 9.0

**Comment by ilovezfs** [comment] 2017-06-29 12:23
@LeoNatan we don't using 8.3.3 with brew on 10.13, but of course you can revert to whatever arrangement you want after doing whatever you need to do with brew.

**Comment by LeoNatan** [comment] 2017-06-29 12:25
That's a problem because one of the formulas does not support Xcode 9.

Why are you hardcoding which Xcode is used on which OS? Even after beta timeframe is over, it should be possible to switch an Xcode version on the fly using Apple provided tools, and brew should respect that setting.

**Comment by ilovezfs** [comment] 2017-06-29 12:29
>That's a problem because one of the formulas does not support Xcode 9.

You can use `brew install --force-bottle foo` to use the Sierra bottle.

>Why are you hardcoding which Xcode is used on which OS? Even after beta timeframe is over, it should be possible to switch an Xcode version on the fly using Apple provided tools, and brew should respect that setting.

Allowing arbitrary Xcode versions leads to avoidable build failures and additional support burden.

**Comment by ilovezfs** [comment] 2017-06-29 12:32
Does my suggestion in https://github.com/Homebrew/brew/issues/2835#issuecomment-311949286 get brew working again? (There's another thing I'd like you to test after testing that if possible.)

**Comment by LeoNatan** [comment] 2017-06-29 12:32
The formula is build from source, using a `--HEAD` argument.

>Allowing arbitrary Xcode versions leads to avoidable build failures and additional support burden.
I don't see how it is different right now.

**Comment by ilovezfs** [comment] 2017-06-29 12:36
>The formula is build from source, using a --HEAD argument.

Then you'll need to wait for it to be fixed with Xcode 9 (or help to fix it).

**Comment by LeoNatan** [comment] 2017-06-29 12:37
I'll take a look, thanks

**Comment by ilovezfs** [comment] 2017-06-29 12:38
>I'll take a look, thanks

You're welcome. Thanks for pitching in!

**Comment by ilovezfs** [comment] 2017-06-29 12:43
>(There's another thing I'd like you to test after testing that if possible.)

Specifically (if you get a chance to test this), does brew work if you have the original names
```
/Applications/Xcode.app
/Applications/Xcode-beta.app
```
and just run
```
sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer
```
?

**Comment by LeoNatan** [comment] 2017-06-29 12:55
This gives me a different failure:

```
/usr/local/opt/carthage/bin/carthage
/private/tmp/fbsimctl-20170629-88584-2o09wx/fbsimctl /private/tmp/fbsimctl-20170629-88584-2o09wx
*** Skipped downloading GCDWebServer.framework binary due to the error:
	"API rate limit exceeded for 91.199.119.160. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
*** Checking out GCDWebServer at "3.3.3"
*** xcodebuild output can be found in /var/folders/d0/q423mrk13bn_bx8wr416nsq40rv2wb/T/carthage-xcodebuild.b61q9y.log
*** Building scheme "GCDWebServers (Mac)" in GCDWebServer.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun dsymutil /tmp/fbsimctl-20170629-88584-2o09wx/fbsimctl/Carthage/Checkouts/GCDWebServer/Carthage/Build/Mac/GCDWebServers.framework/GCDWebServers -o /tmp/fbsimctl-20170629-88584-2o09wx/fbsimctl/Carthage/Checkouts/GCDWebServer/Carthage/Build/Mac/GCDWebServers.framework.dSYM

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/d0/q423mrk13bn_bx8wr416nsq40rv2wb/T/carthage-xcodebuild.b61q9y.log
```

However, in the linked log, build seems to have succeeded:
```
** BUILD SUCCEEDED **
```

**Comment by ilovezfs** [comment] 2017-06-29 12:57
>	"API rate limit exceeded for 91.199.119.160. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

You should be able to fix that by setting the environment variable `HOMEBREW_GITHUB_API_TOKEN` to your token. You can create one if you haven't already.

**Comment by LeoNatan** [comment] 2017-06-29 13:03
Doesn't that just give me a prebuilt framework? That's not a solution to the build issue.

**Comment by ilovezfs** [comment] 2017-06-29 13:05
Well currently it looks like it's just failing because that download is failing. It would be good to see if that dsymutil error goes away once you get the download working.

**Comment by jkili** [comment] 2017-07-04 23:30
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
$ brew config
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e5a81708bd4e4a85395d96277e20aa266607a6da
Core tap last commit: 7 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_102, 1.8.0_25, 1.7.0_51
macOS: 10.13-x86_64
Xcode: 8.3.3
CLT: N/A
X11: 2.7.11 => /opt/X11
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Ruby version 2.3.3 is unsupported on 10.13. Homebrew
is developed and tested on Ruby 2.0, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.

Warning: Your Xcode (8.3.3) is too outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/


Warning: Your Xcode (8.3.3) is outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/

If 9.0 is installed, you may need to:
  sudo xcode-select --switch /Applications/Xcode.app
Current developer directory is:
  /Applications/Xcode.app/Contents/Developer

**Comment by ilovezfs** [comment] 2017-07-04 23:33
`xcode-select -p` is printing `/Applications/Xcode.app/Contents/Developer`

If `/Applications/Xcode.app` is Xcode 8, that will not work.

**Comment by ilovezfs** [comment] 2017-07-04 23:36
```
Josephs-Mac:~ joe$ brew config|grep -i xc
Git: 2.13.0 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
Xcode: 9.0 => /Applications/Xcode-beta.app/Contents/Developer
Josephs-Mac:~ joe$ xcode-select -p
/Applications/Xcode-beta.app/Contents/Developer
Josephs-Mac:~ joe$
```

If Xcode 9 is Xcode-beta.app as it is for me,
```
sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer
```

**Comment by jkili** [comment] 2017-07-04 23:36
@ilovezfs I ran your mv commands, and yes that does fix the issue and I was able to update the formulae.

**Comment by ilovezfs** [comment] 2017-07-04 23:38
@jkili cool. And does it also work the other way, when Xcode.app is 8 and Xcode-beta.app is 9, and you've run `sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer` ?

**Comment by jkili** [comment] 2017-07-04 23:50
@ilovezfs Yes, that works as well.

**Comment by ilovezfs** [comment] 2017-07-04 23:51
Cool. Then it sounds like everything is behaving as intended, and side-by-side Xcode installs are possible.

**Closed** 2017-07-09 10:01 UTC

**Comment by jwintz** [comment] 2017-07-12 19:20
With Xcode-beta-3, Xcode-beta overwrites Xcode.app.

In order to make brew happy I came down to this horrible solution.

<img width="1077" alt="screen shot 2017-07-12 at 21 19 49" src="https://user-images.githubusercontent.com/3277054/28135822-dd874e8c-6747-11e7-8783-99545b781cc1.png">

**Comment by mjonyh** [comment] 2017-07-15 11:25
@ilovezfs : in my case, it works bro. thanks

**Comment by ilovezfs** [comment] 2017-07-15 11:27
@mjonyh glad to hear it.

**Comment by sarvanideekshitula** [comment] 2018-02-21 01:36
`$ xcode-select -p
/Library/Developer/CommandLineTools
$ brew config
HOMEBREW_VERSION: 1.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 021fe22e3c982b08346422d1e7897e929a709380
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e42ae6e44bd6c6b49d9715148d341fb596e9277c
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/sarvani/.rvm/rubies/ruby-2.4.1/bin/ruby
Java: 1.8.0_131
macOS: 10.13.1-x86_64
Xcode: 8.3.3
CLT: 9.2.0.0.1.1510905681
X11: N/A
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/bits/stdc++.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libyaml
  portaudio
  ruby

Warning: Your Xcode (8.3.3) is too outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.


Warning: Your Xcode (8.3.3) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.


Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/etc/bash_completion.d/_brew_services`

I want to install yarn and gave a command `brew install yarn` 
It gave an error like: `Error: Your Xcode (8.3.3) is too outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.`
Can you plz help me out.
