### ISSUE TITLE
Brew extremely slow with external taps

### ISSUE THREAD

**Issue by wrobelda** [Homebrew/brew#10550] opened 2021-02-07 01:12 UTC
**`brew config` output**

HOMEBREW_VERSION: 3.0.0-21-g551594e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 551594e695a6740a6bd9e60ba0e7899d3de9c97a
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bbefd0b98a3e14ba8a5291779900c4878b52b4a5
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.aOl7ufjlWR/org.xquartz:0
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_271
macOS: 11.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Trying to install a package from an external tap. 

It takes about 5-10 minutes between `==> Installing ABC from XYZ/123` and `==> Downloading https://ABC.tar.xz` 

While this is happening, ruby process sees constant 100% cpu usage.

**What happened (include all command output)?**

Nothing, really. Except, as explained, it takes 5-10 minutes from beginning until brew begins downloading the tarball with sources. 

**What did you expect to happen?**

I expected that it proceeded to download the tarball immediately after issuing the command. 

**Step-by-step reproduction instructions (by running `brew` commands)**

`brew tap kde-mac/kde https://invent.kde.org/packaging/homebrew-kde.git --force-auto-update`
`brew install kmymoney` or `brew install libalkimia`

**Comment by wrobelda** [comment] 2021-02-07 02:00
I run it with `--debug` and while it takes brew a while (30s or so) to load all the Formulas, the aforementioned 5-10 minutes delay happens between loading the last formula and curl downloading the tarball. No error or other message appears.

**Comment by jonchang** [comment] 2021-02-08 05:23
Can you try instrumenting this with `brew prof`? Did you see similar behavior when the tap was hosted on GitHub (kde-mac/homebrew-kde) or did it only start after moving to gitlab?

**Comment by wrobelda** [comment] 2021-03-02 17:37
@jonchang I am on M1, so `brew prof` doesn't work here yet.

**Comment by wrobelda** [comment] 2021-03-03 21:04
I just tried removing all external packages and the taps, and re-setting everything back again. Still the same issue.

**Comment by wrobelda** [comment] 2021-03-04 02:28
I am running brew with `--debug` and I noticed that the more `/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading` it goes through, the slower it gets, until it stops at some point. When I edited the formula it consistently stopped at and removed all of the `depends_on`, it moved on and managed to load some more formulas until it stopped again. It's quite clear that there's some loop/recurency issue calculating dependencies here. 

So I went ahead and did `brew deps kmymoney` and it unsurprisingly crashes with what looks like an indefinite loop:

```
Error: stack level too deep
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:94:in `initialize'
/opt/homebrew/Library/Homebrew/options.rb:85:in `new'
/opt/homebrew/Library/Homebrew/options.rb:85:in `initialize'
/opt/homebrew/Library/Homebrew/options.rb:81:in `new'
/opt/homebrew/Library/Homebrew/options.rb:81:in `create'
/opt/homebrew/Library/Homebrew/dependable.rb:39:in `options'
/opt/homebrew/Library/Homebrew/dependency.rb:44:in `to_formula'
/opt/homebrew/Library/Homebrew/dependency.rb:113:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
/opt/homebrew/Library/Homebrew/dependency.rb:98:in `expand'
(...)
/opt/homebrew/Library/Homebrew/dependency.rb:113:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
/opt/homebrew/Library/Homebrew/dependency.rb:98:in `expand'
/opt/homebrew/Library/Homebrew/dependency.rb:113:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
/opt/homebrew/Library/Homebrew/dependency.rb:98:in `expand'
/opt/homebrew/Library/Homebrew/formula.rb:1660:in `recursive_dependencies'
/opt/homebrew/Library/Homebrew/dependencies_helpers.rb:46:in `recursive_includes'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:179:in `deps_for_dependent'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:190:in `block in deps_for_dependents'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:190:in `map'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:190:in `deps_for_dependents'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:131:in `deps'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

**Comment by wrobelda** [comment] 2021-03-04 02:42
The loop is: kf5-parts -> kf5-kio -> kf5-extras -> kf5-khtml ->  kf5-kparts 

The loop is clearly on our end, but I'd still expect brew to immediately stop with error after noticing the first repetitive dependency loop. Unless I am missing something here?

**Comment by wrobelda** [comment] 2021-03-04 03:07
OK, so this now moves past those problematic formulas, the `brew deps kmymoney` shows a valid output immediately and yet _still_ brew just stops towards the end while still haven't finished loading all of them. There's clearly some other issues related to performance here. I'll appreciate debugging tips.

**Comment by carlocab** [comment] 2021-03-04 03:08
`brew readall` might help show you some problems.

**Comment by wrobelda** [comment] 2021-03-04 03:12
> brew readall

No output, assuming no issues.

**Comment by wrobelda** [comment] 2021-03-04 03:49
I tried to break down the dependencies list and install the coarse ones explicitly to see if that helps with anything, and it does – it still takes brew some 3-4 minutes to process it, but e.g. installing `kf5-kio` eventually moved on. So we're back to performance issue.

**Comment by yurikoles** [comment] 2021-03-04 14:16
```
$ brew prof -vd install kf5-tier1-frameworks -vd
<...>
/usr/local/Homebrew/Library/Homebrew/brew.rb:193: [BUG] object allocation during garbage collection phase
```
Logs are here: https://git.io/JqfwJ

**Comment by wrobelda** [comment] 2021-03-26 00:10
Still very much an issue.

**Comment by MikeMcQuaid** [comment] 2021-03-26 19:33
We'll review a PR but this seems specific to non-homebrew-core formulae.

**Closed by MikeMcQuaid** 2021-03-26 19:33 UTC
Labels: bug

**Comment by wrobelda** [comment] 2021-03-27 03:19
This is absolutely not specific to formulae, as it affects all of them in an _external_ tap. For what it's worth, I would assume you'd advise to test with other official home-brew taps before closing this preemptively.

**Comment by Bo98** [comment] 2021-03-27 04:55
I had a look at `kmymoney`, and the dependency tree is one of the largest things I've seen (2849 lines long!). The issue is because of that rather than any other factor.

I've opened #10951, which should substantially improve things for you.

**Comment by wrobelda** [comment] 2021-03-27 05:14
As noted, the smaller dependencies of kmymoney also take unreasonably long to process. Try "kf5-kio" for that matter.

**Comment by MikeMcQuaid** [comment] 2021-03-29 10:44
> For what it's worth, I would assume you'd advise to test with other official home-brew taps before closing this preemptively.

@wrobelda If you can reproduce it with homebrew/core formulae: we'll consider reopening. I don't see this as particularly actionable as-is.

**Comment by Bo98** [comment] 2021-03-29 11:20
> the smaller dependencies of kmymoney also take unreasonably long to process.

If you think it's not dep tree related, then I can't reproduce, sorry.

**Comment by wrobelda** [comment] 2021-03-29 14:19
> If you think it's not dep tree related, then I can't reproduce, sorry. The dependency tree was the only slowness in my tests, nothing else.

I would keep this open, since it is a valid bug, and wait until Apple fixes the underlying Ruby profiler issue on M1. Once that's done, I'll myself provide the provide the findings.

**Comment by Bo98** [comment] 2021-03-29 14:38
> wait until Apple fixes the underlying Ruby profiler issue on M1

https://github.com/Homebrew/brew/issues/10210 tracks that issue. I've been told that the issue will be fixed in an upcoming update (not sure if that means 11.3).

**Comment by MikeMcQuaid** [comment] 2021-03-29 14:46
We don't keep bugs open that aren't directly actionable for maintainers or a contributor.
