### ISSUE TITLE
Widespread error from `Dependency.expand` when a dependency has been unpublished

### ISSUE THREAD

**Issue by Empact** [Homebrew/brew#2027] opened 2017-02-15 20:28 UTC
### Bug reports:

E.g. the end of the output of `brew uninstall --debug some-other-keg` is:
```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
Error: No available formula with the name "postgresql93" 
/usr/local/Homebrew/Library/Homebrew/formulary.rb:227:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:97:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:84:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1515:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1542:in `missing_dependencies'
/usr/local/Homebrew/Library/Homebrew/keg.rb:143:in `block in find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:142:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:142:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:90:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:83:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

The problem is that I have a formula installed that depends on the now defunct/removed postgresql93 formula: https://github.com/johnschultz/homebrew-postgis-for-93

Adding some debug output to `Dependency.expand` reveals:

```
#<Formula postgis (stable) /usr/local/Homebrew/Library/Taps/johnschultz/homebrew-postgis-for-93/postgis.rb>
#<Dependencies: [#<Dependency: "pkg-config" [:build]>, #<Dependency: "gpp" [:build]>, #<Dependency: "postgresql93" []>, #<Dependency: "proj" []>, #<Dependency: "geos" []>, #<Dependency: "json-c" []>, #<Dependency: "gdal" [:recommended]>, #<Dependency: "sfcgal" [:recommended]>]>
#<Dependency: "postgresql93" []>
```

```
$ brew update
Updated 1 tap (caskroom/cask).
No changes to formulae.
$ brew config
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5c583c0177929689b44928af8a99e96b27404c84
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 5666
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/ben/.rbenv/shims/ruby => /Users/ben/.rbenv/versions/2.3.3/bin/ruby
Java: 1.7.0_45, 1.6.0_65-b14-462
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  postgis15
  postgresql91
  postgresql92
  rust
Error: No available formula with the name "postgresql93" 
```

### Propose a feature:

Skipping the dependencies that raise in `#to_formula` works for me. Generally it seems this should be a warning rather than an error condition:

```ruby
    def expand(dependent, deps = dependent.deps, &block)
      # Keep track dependencies to avoid infinite cyclic dependency recursion.
      @expand_stack ||= []
      @expand_stack.push dependent.name

      expanded_deps = []

      deps.each do |dep|
        next if dependent.name == dep.name

        case action(dependent, dep, &block)
        when :prune
          next
        when :skip
          next if @expand_stack.include? dep.name
          expanded_deps.concat(expand(dep.to_formula, &block))
        when :keep_but_prune_recursive_deps
          expanded_deps << dep
        else
          next if @expand_stack.include? dep.name
          formula = dep.to_formula rescue next
          expanded_deps.concat(expand(formula, &block))
          expanded_deps << dep
        end
      end

      merge_repeats(expanded_deps)
    ensure
      @expand_stack.pop
    end
```

**Comment by vladshablinsky** [comment] 2017-02-18 22:45
@Empact thanks for reporting this.

Yeah, I think it should warn rather than fail for the case when we uninstall formula with its dependencies and it probably should fail when we install formula which lacks dependencies. CC @alyssais.

**Comment by alyssais** [comment] 2017-02-19 09:40
Possibly related to #1928

**Comment by vladshablinsky** [comment] 2017-02-19 09:57
@alyssais yeah, I think this is pretty much the same.

**Comment by alyssais** [comment] 2017-02-19 12:18
Yeah, having investigated, this seems to be exactly the same issue, so I'm going to close this as a dupe of #1928 (but thanks for the detailed report @Empact — was super helpful).

**Closed by alyssais** 2017-02-19 12:18 UTC
