### ISSUE TITLE
Brew failing to fetch packages from github with curl error

### ISSUE THREAD

**Issue by breiter** [Homebrew/brew#785] opened 2016-08-22 13:04 UTC
```
$ sudo brew upgrade
==> Upgrading 1 outdated package, with result:
vim 7.4.2235
==> Upgrading vim
==> Using the sandbox
==> Downloading https://github.com/vim/vim/archive/v7.4.2235.tar.gz

curl: (35) SSL certificate problem: Couldn't understand the server certificate format
Error: Failed to download resource "vim"
Download failed: https://github.com/vim/vim/archive/v7.4.2235.tar.gz
$ sudo brew upgrade --verbose
==> Upgrading 1 outdated package, with result:
vim 7.4.2235
==> Upgrading vim
rm /opt/homebrew/bin/ex
rm /opt/homebrew/bin/rview
rm /opt/homebrew/bin/rvim
rm /opt/homebrew/bin/view
rm /opt/homebrew/bin/vim
rm /opt/homebrew/bin/vimdiff
rm /opt/homebrew/bin/vimtutor
rm /opt/homebrew/bin/xxd
rm /opt/homebrew/share/man/fr/man1/evim.1
rm /opt/homebrew/share/man/fr/man1/ex.1
rm /opt/homebrew/share/man/fr/man1/rview.1
rm /opt/homebrew/share/man/fr/man1/rvim.1
rm /opt/homebrew/share/man/fr/man1/view.1
rm /opt/homebrew/share/man/fr/man1/vim.1
rm /opt/homebrew/share/man/fr/man1/vimdiff.1
rm /opt/homebrew/share/man/fr/man1/vimtutor.1
rm /opt/homebrew/share/man/fr/man1/xxd.1
rm /opt/homebrew/share/man/fr.ISO8859-1/man1/evim.1
rm /opt/homebrew/share/man/fr.ISO8859-1/man1/ex.1
rm /opt/homebrew/share/man/fr.ISO8859-1/man1/rview.1
rm /opt/homebrew/share/man/fr.ISO8859-1/man1/rvim.1
rm /opt/homebrew/share/man/fr.ISO8859-1/man1/view.1
rm /opt/homebrew/share/man/fr.ISO8859-1/man1/vim.1
rm /opt/homebrew/share/man/fr.ISO8859-1/man1/vimdiff.1
rm /opt/homebrew/share/man/fr.ISO8859-1/man1/vimtutor.1
rm /opt/homebrew/share/man/fr.ISO8859-1/man1/xxd.1
rm /opt/homebrew/share/man/fr.UTF-8/man1/evim.1
rm /opt/homebrew/share/man/fr.UTF-8/man1/ex.1
rm /opt/homebrew/share/man/fr.UTF-8/man1/rview.1
rm /opt/homebrew/share/man/fr.UTF-8/man1/rvim.1
rm /opt/homebrew/share/man/fr.UTF-8/man1/view.1
rm /opt/homebrew/share/man/fr.UTF-8/man1/vim.1
rm /opt/homebrew/share/man/fr.UTF-8/man1/vimdiff.1
rm /opt/homebrew/share/man/fr.UTF-8/man1/vimtutor.1
rm /opt/homebrew/share/man/fr.UTF-8/man1/xxd.1
rm /opt/homebrew/share/man/it/man1/evim.1
rm /opt/homebrew/share/man/it/man1/ex.1
rm /opt/homebrew/share/man/it/man1/rview.1
rm /opt/homebrew/share/man/it/man1/rvim.1
rm /opt/homebrew/share/man/it/man1/view.1
rm /opt/homebrew/share/man/it/man1/vim.1
rm /opt/homebrew/share/man/it/man1/vimdiff.1
rm /opt/homebrew/share/man/it/man1/vimtutor.1
rm /opt/homebrew/share/man/it/man1/xxd.1
rm /opt/homebrew/share/man/it.ISO8859-1/man1/evim.1
rm /opt/homebrew/share/man/it.ISO8859-1/man1/ex.1
rm /opt/homebrew/share/man/it.ISO8859-1/man1/rview.1
rm /opt/homebrew/share/man/it.ISO8859-1/man1/rvim.1
rm /opt/homebrew/share/man/it.ISO8859-1/man1/view.1
rm /opt/homebrew/share/man/it.ISO8859-1/man1/vim.1
rm /opt/homebrew/share/man/it.ISO8859-1/man1/vimdiff.1
rm /opt/homebrew/share/man/it.ISO8859-1/man1/vimtutor.1
rm /opt/homebrew/share/man/it.ISO8859-1/man1/xxd.1
rm /opt/homebrew/share/man/it.UTF-8/man1/evim.1
rm /opt/homebrew/share/man/it.UTF-8/man1/ex.1
rm /opt/homebrew/share/man/it.UTF-8/man1/rview.1
rm /opt/homebrew/share/man/it.UTF-8/man1/rvim.1
rm /opt/homebrew/share/man/it.UTF-8/man1/view.1
rm /opt/homebrew/share/man/it.UTF-8/man1/vim.1
rm /opt/homebrew/share/man/it.UTF-8/man1/vimdiff.1
rm /opt/homebrew/share/man/it.UTF-8/man1/vimtutor.1
rm /opt/homebrew/share/man/it.UTF-8/man1/xxd.1
rm /opt/homebrew/share/man/ja/man1/evim.1
rm /opt/homebrew/share/man/ja/man1/ex.1
rm /opt/homebrew/share/man/ja/man1/rview.1
rm /opt/homebrew/share/man/ja/man1/rvim.1
rm /opt/homebrew/share/man/ja/man1/view.1
rm /opt/homebrew/share/man/ja/man1/vim.1
rm /opt/homebrew/share/man/ja/man1/vimdiff.1
rm /opt/homebrew/share/man/ja/man1/vimtutor.1
rm /opt/homebrew/share/man/ja/man1/xxd.1
rm /opt/homebrew/share/man/man1/evim.1
rm /opt/homebrew/share/man/man1/vim.1
rm /opt/homebrew/share/man/man1/vimdiff.1
rm /opt/homebrew/share/man/man1/vimtutor.1
rm /opt/homebrew/share/man/man1/xxd.1
rm /opt/homebrew/share/man/pl/man1/evim.1
rm /opt/homebrew/share/man/pl/man1/ex.1
rm /opt/homebrew/share/man/pl/man1/rview.1
rm /opt/homebrew/share/man/pl/man1/rvim.1
rm /opt/homebrew/share/man/pl/man1/view.1
rm /opt/homebrew/share/man/pl/man1/vim.1
rm /opt/homebrew/share/man/pl/man1/vimdiff.1
rm /opt/homebrew/share/man/pl/man1/vimtutor.1
rm /opt/homebrew/share/man/pl/man1/xxd.1
rm /opt/homebrew/share/man/pl.ISO8859-2/man1/evim.1
rm /opt/homebrew/share/man/pl.ISO8859-2/man1/ex.1
rm /opt/homebrew/share/man/pl.ISO8859-2/man1/rview.1
rm /opt/homebrew/share/man/pl.ISO8859-2/man1/rvim.1
rm /opt/homebrew/share/man/pl.ISO8859-2/man1/view.1
rm /opt/homebrew/share/man/pl.ISO8859-2/man1/vim.1
rm /opt/homebrew/share/man/pl.ISO8859-2/man1/vimdiff.1
rm /opt/homebrew/share/man/pl.ISO8859-2/man1/vimtutor.1
rm /opt/homebrew/share/man/pl.ISO8859-2/man1/xxd.1
rm /opt/homebrew/share/man/pl.UTF-8/man1/evim.1
rm /opt/homebrew/share/man/pl.UTF-8/man1/ex.1
rm /opt/homebrew/share/man/pl.UTF-8/man1/rview.1
rm /opt/homebrew/share/man/pl.UTF-8/man1/rvim.1
rm /opt/homebrew/share/man/pl.UTF-8/man1/view.1
rm /opt/homebrew/share/man/pl.UTF-8/man1/vim.1
rm /opt/homebrew/share/man/pl.UTF-8/man1/vimdiff.1
rm /opt/homebrew/share/man/pl.UTF-8/man1/vimtutor.1
rm /opt/homebrew/share/man/pl.UTF-8/man1/xxd.1
rm /opt/homebrew/share/man/ru.KOI8-R/man1/evim.1
rm /opt/homebrew/share/man/ru.KOI8-R/man1/ex.1
rm /opt/homebrew/share/man/ru.KOI8-R/man1/rview.1
rm /opt/homebrew/share/man/ru.KOI8-R/man1/rvim.1
rm /opt/homebrew/share/man/ru.KOI8-R/man1/view.1
rm /opt/homebrew/share/man/ru.KOI8-R/man1/vim.1
rm /opt/homebrew/share/man/ru.KOI8-R/man1/vimdiff.1
rm /opt/homebrew/share/man/ru.KOI8-R/man1/vimtutor.1
rm /opt/homebrew/share/man/ru.KOI8-R/man1/xxd.1
rm /opt/homebrew/share/man/ru.UTF-8/man1/evim.1
rm /opt/homebrew/share/man/ru.UTF-8/man1/ex.1
rm /opt/homebrew/share/man/ru.UTF-8/man1/rview.1
rm /opt/homebrew/share/man/ru.UTF-8/man1/rvim.1
rm /opt/homebrew/share/man/ru.UTF-8/man1/view.1
rm /opt/homebrew/share/man/ru.UTF-8/man1/vim.1
rm /opt/homebrew/share/man/ru.UTF-8/man1/vimdiff.1
rm /opt/homebrew/share/man/ru.UTF-8/man1/vimtutor.1
rm /opt/homebrew/share/man/ru.UTF-8/man1/xxd.1
rm /opt/homebrew/share/vim
rmdir /opt/homebrew/share/man/ru.UTF-8/man1
rmdir /opt/homebrew/share/man/ru.UTF-8
rmdir /opt/homebrew/share/man/ru.KOI8-R/man1
rmdir /opt/homebrew/share/man/ru.KOI8-R
rmdir /opt/homebrew/share/man/pl.UTF-8/man1
rmdir /opt/homebrew/share/man/pl.UTF-8
rmdir /opt/homebrew/share/man/pl.ISO8859-2/man1
rmdir /opt/homebrew/share/man/pl.ISO8859-2
rmdir /opt/homebrew/share/man/it.UTF-8/man1
rmdir /opt/homebrew/share/man/it.UTF-8
rmdir /opt/homebrew/share/man/it.ISO8859-1/man1
rmdir /opt/homebrew/share/man/it.ISO8859-1
rmdir /opt/homebrew/share/man/fr.UTF-8/man1
rmdir /opt/homebrew/share/man/fr.UTF-8
rmdir /opt/homebrew/share/man/fr.ISO8859-1/man1
rmdir /opt/homebrew/share/man/fr.ISO8859-1
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160822-43529-f9pua7.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /opt/homebrew/Library/Homebrew -- /opt/homebrew/Library/Homebrew/build.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb --verbose --with-lua
==> Downloading https://github.com/vim/vim/archive/v7.4.2235.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 https://github.com/vim/vim/archive/v7.4.2235.tar.gz -C 0 -o /Users/breiter/Library/Caches/Homebrew/vim-7.4.2235.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) SSL certificate problem: Couldn't understand the server certificate format
==> Sandbox log
Aug 22 14:53:23 kernel[0]: Sandbox: curl(43548) deny(1) file-write-data /private/var/db/mds/system/mds.lock
Aug 22 14:53:23 kernel[0]: Sandbox: curl(43548) deny(1) file-write-data /private/var/db/mds/system/mds.lock
Aug 22 14:53:23 kernel[0]: Sandbox: curl(43548) deny(1) file-write-data /private/var/db/mds/system/mds.lock
Aug 22 14:53:23 kernel[0]: Sandbox: curl(43549) deny(1) file-write-data /private/var/db/mds/system/mds.lock
Aug 22 14:53:23 kernel[0]: Sandbox: curl(43549) deny(1) file-write-data /private/var/db/mds/system/mds.lock
Aug 22 14:53:23 kernel[0]: Sandbox: curl(43549) deny(1) file-write-data /private/var/db/mds/system/mds.lock
Error: Failed to download resource "vim"
Download failed: https://github.com/vim/vim/archive/v7.4.2235.tar.gz
ln -s ../Cellar/vim/7.4.2210/bin/ex ex
ln -s ../Cellar/vim/7.4.2210/bin/rview rview
ln -s ../Cellar/vim/7.4.2210/bin/rvim rvim
ln -s ../Cellar/vim/7.4.2210/bin/view view
ln -s ../Cellar/vim/7.4.2210/bin/vim vim
ln -s ../Cellar/vim/7.4.2210/bin/vimdiff vimdiff
ln -s ../Cellar/vim/7.4.2210/bin/vimtutor vimtutor
ln -s ../Cellar/vim/7.4.2210/bin/xxd xxd
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr/man1/xxd.1 xxd.1
mkdir -p /opt/homebrew/share/man/fr.ISO8859-1
mkdir -p /opt/homebrew/share/man/fr.ISO8859-1/man1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.ISO8859-1/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.ISO8859-1/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.ISO8859-1/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.ISO8859-1/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.ISO8859-1/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.ISO8859-1/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.ISO8859-1/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.ISO8859-1/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.ISO8859-1/man1/xxd.1 xxd.1
mkdir -p /opt/homebrew/share/man/fr.UTF-8
mkdir -p /opt/homebrew/share/man/fr.UTF-8/man1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.UTF-8/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.UTF-8/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.UTF-8/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.UTF-8/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.UTF-8/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.UTF-8/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.UTF-8/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.UTF-8/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/fr.UTF-8/man1/xxd.1 xxd.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it/man1/xxd.1 xxd.1
mkdir -p /opt/homebrew/share/man/it.ISO8859-1
mkdir -p /opt/homebrew/share/man/it.ISO8859-1/man1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.ISO8859-1/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.ISO8859-1/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.ISO8859-1/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.ISO8859-1/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.ISO8859-1/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.ISO8859-1/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.ISO8859-1/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.ISO8859-1/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.ISO8859-1/man1/xxd.1 xxd.1
mkdir -p /opt/homebrew/share/man/it.UTF-8
mkdir -p /opt/homebrew/share/man/it.UTF-8/man1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.UTF-8/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.UTF-8/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.UTF-8/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.UTF-8/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.UTF-8/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.UTF-8/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.UTF-8/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.UTF-8/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/it.UTF-8/man1/xxd.1 xxd.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ja/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ja/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ja/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ja/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ja/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ja/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ja/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ja/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ja/man1/xxd.1 xxd.1
ln -s ../../../Cellar/vim/7.4.2210/share/man/man1/evim.1 evim.1
ln -s ../../../Cellar/vim/7.4.2210/share/man/man1/vim.1 vim.1
ln -s ../../../Cellar/vim/7.4.2210/share/man/man1/vimdiff.1 vimdiff.1
ln -s ../../../Cellar/vim/7.4.2210/share/man/man1/vimtutor.1 vimtutor.1
ln -s ../../../Cellar/vim/7.4.2210/share/man/man1/xxd.1 xxd.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl/man1/xxd.1 xxd.1
mkdir -p /opt/homebrew/share/man/pl.ISO8859-2
mkdir -p /opt/homebrew/share/man/pl.ISO8859-2/man1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.ISO8859-2/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.ISO8859-2/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.ISO8859-2/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.ISO8859-2/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.ISO8859-2/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.ISO8859-2/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.ISO8859-2/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.ISO8859-2/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.ISO8859-2/man1/xxd.1 xxd.1
mkdir -p /opt/homebrew/share/man/pl.UTF-8
mkdir -p /opt/homebrew/share/man/pl.UTF-8/man1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.UTF-8/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.UTF-8/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.UTF-8/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.UTF-8/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.UTF-8/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.UTF-8/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.UTF-8/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.UTF-8/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/pl.UTF-8/man1/xxd.1 xxd.1
mkdir -p /opt/homebrew/share/man/ru.KOI8-R
mkdir -p /opt/homebrew/share/man/ru.KOI8-R/man1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.KOI8-R/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.KOI8-R/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.KOI8-R/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.KOI8-R/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.KOI8-R/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.KOI8-R/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.KOI8-R/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.KOI8-R/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.KOI8-R/man1/xxd.1 xxd.1
mkdir -p /opt/homebrew/share/man/ru.UTF-8
mkdir -p /opt/homebrew/share/man/ru.UTF-8/man1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.UTF-8/man1/evim.1 evim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.UTF-8/man1/ex.1 ex.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.UTF-8/man1/rview.1 rview.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.UTF-8/man1/rvim.1 rvim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.UTF-8/man1/view.1 view.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.UTF-8/man1/vim.1 vim.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.UTF-8/man1/vimdiff.1 vimdiff.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.UTF-8/man1/vimtutor.1 vimtutor.1
ln -s ../../../../Cellar/vim/7.4.2210/share/man/ru.UTF-8/man1/xxd.1 xxd.1
ln -s ../Cellar/vim/7.4.2210/share/vim vim
```

However, the curl command works if I run the curl command manually:

```
$ sudo /usr/bin/curl --fail --remote-time --location --user-agent "Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0" https://github.com/vim/vim/archive/v7.4.2235.tar.gz -C 0 -o /Users/breiter/Library/Caches/Homebrew/vim-7.4.2235.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   118    0   118    0     0     83      0 --:--:--  0:00:01 --:--:--    83
100 12.2M  100 12.2M    0     0   254k      0  0:00:49  0:00:49 --:--:--  200k
```

Once the tarball is downloaded to `~/Library/Caches/Homebrew`, the update will work.

```
$ sudo mv ~/Library/Caches/Homebrew/vim-7.4.2235.tar.gz.incomplete ~/Library/Caches/Homebrew/vim-7.4.2235.tar.gz
$ sudo brew upgrade
==> Upgrading 1 outdated package, with result:
vim 7.4.2235
==> Upgrading vim
==> Using the sandbox
==> Downloading https://github.com/vim/vim/archive/v7.4.2235.tar.gz
Already downloaded: /Users/breiter/Library/Caches/Homebrew/vim-7.4.2235.tar.gz
==> ./configure --prefix=/opt/homebrew --mandir=/opt/homebrew/Cellar/vim/7.4.223
==> make
==> make install prefix=/opt/homebrew/Cellar/vim/7.4.2235 STRIP=true
🍺  /opt/homebrew/Cellar/vim/7.4.2235: 1,696 files, 23.2M, built in 50 seconds
```

I had the same issue for 3 other packages that where the source file was hosted on github. This is a new issue. I have been using brew for a long time. 

(I have homebrew installed in `/opt/homebrew` but that has never been an issue.)

**Comment by MikeMcQuaid** [comment] 2016-08-22 14:14
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by breiter** [comment] 2016-08-22 14:17
$ brew config && sudo brew doctor
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 31052a924f2d39df69a0e202972b5a9806ff5ac8
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0708161535023a6ad4079ccf1651abb074154064
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.3 => /opt/homebrew/bin/git
Perl: /usr/bin/perl
Python: /opt/homebrew/bin/python => /opt/homebrew/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /opt/homebrew/bin/ruby => /opt/homebrew/Cellar/ruby/2.3.1/bin/ruby
Java: N/A
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A
Password:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew is not installed to /usr/local
You can install Homebrew anywhere you want, but some brews may only build
correctly if you install in /usr/local. Sorry!

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
    openssl

**Comment by LumpyChen** [comment] 2016-08-23 03:17
I got the same problem on my vim with lua install (with sudo): 
```
brew install vim --with-lua
```
the output:
```
==> Using the sandbox
==> Downloading https://github.com/vim/vim/archive/v7.4.2235.tar.

curl: (35) SSL certificate problem: Couldn't understand the server certificate format
Error: Failed to download resource "vim"
Download failed: https://github.com/vim/vim/archive/v7.4.2235.tar.gz
```
I've been through my  troubleshooting
my `brew config`:
```
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a70c60baeacf6ec6835fb0112fb5d1c9dd51012a
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 495d9d8eb874263647d318db31f69899f10ad97f
Core tap last commit: 28 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.3 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
Java: 1.8.0_102, 1.6.0_65-b14-468
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A
```
And there aren't any errors or warnings with `brew doctor` in my mac

**Comment by MikeMcQuaid** [comment] 2016-08-23 09:36
I can't reproduce this. What country are you in @breiter and @LumpyChen and can you still reproduce this?

**Comment by breiter** [comment] 2016-08-23 09:56
Zimbabwe. I have no trouble accessing GitHub through my normal workflow and I can download the relevant files with curl.

**Comment by MikeMcQuaid** [comment] 2016-08-23 10:01
What does `which curl` show? Do you have `curl` installed through Homebrew?

**Comment by breiter** [comment] 2016-08-23 10:27
I do have homebrew curl installed but it is not in the `$PATH`. If you look at my original post, I provided output of running the curl command that `brew` builds and it worked. I don't know what else is going on in the execution environment. It didn't seem to be using my GitHub key -- at least the web UI said it had last been accessed by brew 4 days ago.

**Comment by MikeMcQuaid** [comment] 2016-08-23 10:32
@breiter Can you still reproduce this if you e.g. use `brew fetch --force`? What happens if you use the Homebrew curl?

**Comment by MikeMcQuaid** [comment] 2016-08-23 11:00
Closing in favour of https://github.com/Homebrew/brew/issues/796 which describes the problem.

**Closed by MikeMcQuaid** 2016-08-23 11:00 UTC
