### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dukegod** [Homebrew/brew#1099] opened 2016-09-23 05:58 UTC
Home-brew  version

Homebrew >1.0.0 (no git repository)
Homebrew/homebrew-core (git revision 8c8d0; last commit 2016-09-21)

when i input 

```
sudo -s
```
Error: Running Homebrew as root is extremely dangerous. As Homebrew does not
drop privileges on installation you are giving all build scripts full access
to your system. As a result of the macOS sandbox not handling the root user
correctly HOMEBREW_NO_SANDBOX has been set so the sandbox will not be used. If
we have not merged a pull request to add privilege dropping by November 1st
2016 running Homebrew as root will be disabled. No Homebrew maintainers plan
to work on this functionality.

**Comment by MikeMcQuaid** [comment] 2016-09-23 07:04
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by alexrockt** [comment] 2016-09-23 08:06
Should be fixed today with https://github.com/Homebrew/brew/pull/1090

**Comment by MikeMcQuaid** [comment] 2016-09-24 15:23
Closing as I don't know what the problem is.

**Closed by MikeMcQuaid** 2016-09-24 15:23 UTC
