### ISSUE TITLE
gpg broken after update

### ISSUE THREAD

**Issue by cleishm** [Homebrew/brew#708] opened 2016-08-13 14:58 UTC
After a `brew upgrade` today, the gpg binary is no longer linked into `/usr/local/bin/gpg`.

```
% brew list gnupg
/usr/local/Cellar/gnupg/1.4.20_1/bin/gpg-zip1
/usr/local/Cellar/gnupg/1.4.20_1/bin/gpg1
/usr/local/Cellar/gnupg/1.4.20_1/bin/gpgsplit1
/usr/local/Cellar/gnupg/1.4.20_1/bin/gpgv1
/usr/local/Cellar/gnupg/1.4.20_1/libexec/gnupg/ (4 files)
/usr/local/Cellar/gnupg/1.4.20_1/libexec/gpgbin/ (4 files)
/usr/local/Cellar/gnupg/1.4.20_1/share/gnupg/ (2 files)
/usr/local/Cellar/gnupg/1.4.20_1/share/info/gnupg1.info
/usr/local/Cellar/gnupg/1.4.20_1/share/locale/ (32 files)
/usr/local/Cellar/gnupg/1.4.20_1/share/man/ (3 files)
```

It appears to have installed a binary `gpg1` instead. However, this does not execute:

```
% /usr/local/bin/gpg1
dyld: Library not loaded: /usr/local/opt/libusb-compat/lib/libusb-0.1.4.dylib
  Referenced from: /usr/local/bin/gpg1
  Reason: image not found
[1]    41295 trace trap  /usr/local/bin/gpg1
```

Cheers,
Chris

**Comment by DomT4** [comment] 2016-08-13 15:02
> It appears to have installed a binary gpg1 instead.

Yeah, this is intentional. Debian is moving to this system very soon as well, and likely other Linux distros will follow as a consequence. Almost nothing cannot use at least 2.0.x of GnuPG now & it's significantly better supported, so people are trying to gently nudge `gpg1` out of general usage.

> However, this does not execute:

This looks specific to your local setup rather than a global issue. I'd try `brew reinstall libusb-compat`.

**Comment by DomT4** [comment] 2016-08-13 15:04
Oh, interesting. I see what may have happened here, bear with me a few minutes. I suspect because it was part of a wider PR it had access to a dependency it didn't have access to before & has decided to sniff it out of the environment.

**Comment by DomT4** [comment] 2016-08-13 15:17
Will be fixed by https://github.com/Homebrew/homebrew-core/pull/3856. Thanks for reporting this!

I can only presume our `gnupg` formula has never gone through the same build as our `libusb-compat` formula before now, which is impressive.

**Closed** 2016-08-13 15:20 UTC

**Comment by cleishm** [comment] 2016-08-13 15:30
Hi @DomT4,

Is there any way to warn users of this breaking change, or keep the `gpg` alias if gpg2 isn't installed?

This broke my whole dev tool chain, with no warning, so it's likely going to be a common issue.

Cheers,
Chris

**Comment by DomT4** [comment] 2016-08-13 15:42
There's notice of the change in the `gnupg` caveats, which will be printed on upgrade:
```
==> Caveats
All commands have been installed with the suffix '1'.

If you really need to use these commands with their normal names, you
can add a "gpgbin" directory to your PATH from your ~/.zshrc like:

    PATH="/usr/local/opt/gnupg/libexec/gpgbin:$PATH"

Note that doing so may interfere with GPG-using formulae installed via
Homebrew.
```

**Comment by cleishm** [comment] 2016-08-13 15:56
If that message was displayed during upgrade, I missed it!

Have you considered perhaps making the `gnupg` package install `gnupg2`? And then having a legacy `gnupg1` package for those who really do care. For my purposes, everything works ok now that I've installed `gnupg2`.

**Comment by DomT4** [comment] 2016-08-13 16:13
> If that message was displayed during upgrade, I missed it!

Quite easy to do, sadly. We've come to learn most users either involuntarily or deliberately skip over the `caveats`, but there's not really a better way to inform people of next steps or changes on a case-by-case basis 😕.

We're trying to cut down on the amount of less important caveats in the hope people come to see it less as noise & more as something worth glancing over.

> Have you considered perhaps making the gnupg package install gnupg2? And then having a legacy gnupg1 package for those who really do care.

This is very likely where things are going, but at the moment when we rename things we can't repurpose the old name.

Currently, when we rename `gnupg` to `gnupg1` for example, on the next `brew update` people are nudged `brew migrate <formula>`, which for compatibility's sake leaves a symlink of the old name pointing to the new name:

```
/usr/local/opt/polarssl -> ../Cellar/mbedtls/2.1.0
```
This means things don't suddenly break for external taps or upstream projects that have come to rely on being able to check `$(brew --prefix)/opt/polarssl`, etc, but does mean we can't immediately steal the old name for another formula.

It's a fun balance between optimising for our preferred outcome & optimising for not wildly breaking external taps or external projects that use or lean on `brew` on OS X/macOS.

**Comment by ahmedelgabri** [comment] 2016-08-14 14:02
> Quite easy to do, sadly. We've come to learn most users either involuntarily or deliberately skip over the caveats, but there's not really a better way to inform people of next steps or changes on a case-by-case basis 😕.

I missed it too & that's why I'm here 🙂, I agree that it's very easy to miss it especially if you upgrading/installing a couple of packages. So why not color it, or add characters around it like for example doing this

```
====================================================================
==> Caveats
==> All commands have been installed with the suffix '1'.
==>
==> If you really need to use these commands with their normal names, you
==> can add a "gpgbin" directory to your PATH from your ~/.zshrc like:
==>
==>    PATH="/usr/local/opt/gnupg/libexec/gpgbin:$PATH"
==>
==> Note that doing so may interfere with GPG-using formulae installed via
==> Homebrew.
====================================================================
```
or even both. Color & characters, this way it can pop up a bit?

**Comment by cleishm** [comment] 2016-08-14 14:17
You might also want to state more clearly that "this is a *breaking upgrade to gnupg*, which renames the gpg command line tool as gpg1". Also suggest users consider installing gnupg2 to resolve the issue.

There's still the problem of new users installing `gnupg`, which is the obvious package to install if you want to use gpg, and then being confused by the lack of a gpg command line tool.

**Comment by MikeMcQuaid** [comment] 2016-08-14 15:45
@DomT4 Is it maybe worth using `keg_only` here?

**Comment by DomT4** [comment] 2016-08-14 15:56
> So why not color it

Colour doesn't work well universally. We use bold in various places, for example, but because of the theme in my terminal (classic bright green on black) bolding barely shows up. Same sort of problem with colour. Also issues around colour-blindness making certain colours look different or less distinguishable, etc.

> & characters

I have less of an issue with drawing a band around a caveat output, but I'm unsure how much of a difference it would make.

> Also suggest users consider installing gnupg2 to resolve the issue.

This will have been done already for anyone who installed anything else in `homebrew/core` that had a `:gpg` dependency. We forced a pretty broad reinstallation that will have carried `gnupg2` with it.

> You might also want to state more clearly

I agree the caveats could be clearer, I'll commit something shortly.

> Is it maybe worth using keg_only here?

I don't think so in this case.

This change [is coming](https://debian-administration.org/users/dkg/weblog/116) in Debian _(actually, Debian's change is even less sympathetic to end users than we are, they've outright said they won't offer a semi-supported way to keep `gpg` pointing to 1.x at all)_, and likely others will follow, but being the first to do something inevitably leads to some reaction. Whilst this may seem hostile to some at this point it's going to become the norm.

If we want to really shove this change onto people hard we could bump the `gnupg` formula revision & add a `depends_on :gpg` line, which is of course an outright lie, but means every existing `gnupg` user who isn't using anything else in `homebrew/core` that `depends_on :gpg` would have their `gpg` symlink replaced now.

**Comment by cleishm** [comment] 2016-08-14 16:13
After reading that Debian announcement, it seems they are going with the strategy of making the `gnupg` binary package install 2.0 (stable) version. That's pretty sympathetic, as it means the only people who'll notice are those who explicitly depended on the version 1 (classic) semantics - which is probably few.

**Comment by DomT4** [comment] 2016-08-14 16:16
Install 2.1, actually, I believe, with `gnupg` moving to the `gnupg1` name. As I stated above, we can't steal old names currently, otherwise we'd be doing something similar.

**Comment by MikeMcQuaid** [comment] 2016-08-14 16:42
> As I stated above, we can't steal old names currently, otherwise we'd be doing something similar.

Given that I think our strategy should perhaps be different. `keg_only` feels to us like a more typical solution for soft-deprecations like this.

**Comment by DomT4** [comment] 2016-08-14 17:03
`keg_only` also means anything with a `gnupg` dependency needs to be env scripted forevermore, as well as making anyone who ever needs to call it on a command line use `/usr/local/opt/gnupg/bin/gpg`. I'm not sure that's any less hostile than simply shunting over the executable name.

We're at least following a Debian-esque path on this, rather than charting our own unique course, which long-term is a less heavy burden on both maintainers & end users. Either way we approach this is going to be in some ways user-hostile, breaking changes are.

I'll file a PR with some tweaks to the existing mechanism, but I think we've cushioned this pretty significantly already & the problem is less the change and more Homebrew's long-term problem around caveats being widely ignored/passed over & our relatively limited ways to communicate _any_ changes to end users who don't want to flick through the commit log.

**Comment by SimenB** [comment] 2016-08-15 12:10
Git commit signing broke for me after this, but a quick `git config --global gpg.program gpg1` fixed it. ATM I only use Mac, but might mess up if I go back to Linux in the future.

**Comment by diclophis** [comment] 2016-08-15 19:05
Thanks for letting everyone know in the mailing list about this breaking change...

**Comment by DomT4** [comment] 2016-08-15 19:15
@SimenB Unless you specifically need GnuPG 1.x for the older crypto, we (and upstream) pretty strongly recommend using `gnupg2`, which contains the plain executables.

> Thanks for letting everyone know in the mailing list about this breaking change...

@diclophis Thanks for understanding that Homebrew is extremely time consuming & almost nobody bothers to check the mailing list or Twitter from our prior experiences. Appreciate your constructive & carefully considered feedback.

**Comment by cleishm** [comment] 2016-08-15 19:34
I do have a question about your comment "Currently, when we rename gnupg to gnupg1 for example, on the next brew update people are nudged brew migrate <formula>, which for compatibility's sake leaves a symlink of the old name pointing to the new name".

Why do you need to rename `gnupg` to `gnupg1`? What would happen if you updated the formula in `gnupg` to install gnupg version 2, and added a new formula for `gnupg1`? Although I don't know what you'd do with the existing `gnupg2` formula, as you'd want to make that an alias.

**Comment by thewoolleyman** [comment] 2016-08-30 16:48
Just an FYI, it seems that `gpg-zip` no longer works.  It fails with the error:

`gpg-agent[51336]: command get_passphrase failed: Inappropriate ioctl for device`

Our workaround was to decrypt the file with `gpg --decrypt -o file.tar file.gpg` and then manually untar it.

**Comment by thewoolleyman** [comment] 2016-08-30 16:50
Oh, this issue is closed.  Should I open a new one for the `gpg-zip` problem?  Or is an issue on an upstream project more appropriate?  If so, where? 

cc @DomT4

**Comment by MikeMcQuaid** [comment] 2016-08-30 18:10
> Should I open a new one for the gpg-zip problem?

Yes, please. Follow the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information there so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment] 2016-08-30 18:15
@thewoolleyman I think your issue may be local, `Inappropriate ioctl for device` usually is, related to `tty` stuff IIRC.

It turns out `gpg-zip1` ignores the configure argument `--program-suffix=1` and still chucks `gpg` rather than `gpg1` into the script. Software is fun. I'll get that fixed at least.

**Comment by thewoolleyman** [comment] 2016-08-30 19:17
@DomT4 I would also tend to blame this on environment, but the new version is really the only variable.  I.e., on machines with only the older version (which are otherwise pretty much the same machine image, we use shared workstations built from images) it still works fine, but it fails on every machine that has the new version.  Same keys, encrypted files, everything else.

So my theory is still that something in gpg-zip1 isn't playing well with the new version or new way things are laid out.

Also, why isn't there a gpg-zip for gpg2?  I don't see any binary for it anywhere.  Did they remove it?

**Comment by DomT4** [comment] 2016-08-31 01:51
@thewoolleyman I poked at your issue quite a bit more, various keys, various machines, couldn't reproduce it 😞. Not sure what'd be going on there.

Try `brew update && brew reinstall gpg1` & try again, and if that doesn't work try `brew reinstall gpg1 -s` and try again. I'd be surprised if either resolves the issue, but it's an easy avenue to investigate.

> Also, why isn't there a gpg-zip for gpg2? I don't see any binary for it anywhere. Did they remove it?

They stopped installing it by default, along with `gpgsplit`, back in 2006 because installing those two tools introduced an unnecessary conflict-by-design between GnuPG 1.x and the incoming GnuPG 2.0.x. Still get built, but not installed automatically.

**Comment by thewoolleyman** [comment] 2016-08-31 15:21
OK, thanks, I'll try to dig into it more here to reproduce it on some different machines than our image.

**Comment by jbucaran** [comment] 2016-12-05 10:25
@DomT4 

Hi. I installed gnupg on a new machine and was unable to sign my git commits as well. I later realized the name had changed to gpg1 and later found a link to this discussion from [here](http://stackoverflow.com/a/40066889/2903889).

I also did `git config --global gpg.program gpg1` and everything was solved, except for one thing.

gpg1 command line interface text / output help was translated into Japanese!

My region is indeed Asia/Japan, so I figured this had to be a problem with my region. I uninstalled gnupg, temporarily changed my region to Americas/USA, and after installing gnupg again, gpg1 cli was in English again.

It seems to me the brew installer should be looking at my language settings, not my region settings to pick up the cli language. I'd be happy to look into this if you can show me the right direction.

I am on macOS.

**Comment by jbucaran** [comment] 2016-12-06 06:10
UPDATE: Changing the region only fixes the CLI temporarily. If I change my region back to Japan, the CLI translates into Japanese.

**Comment by apjanke** [comment] 2016-12-06 15:01
@jbucaran At the Unix command line level, language and region settings are tied together as part of the "locale" definition. And they are generally checked at run time, not installation time. Check the output of `locale` from the command line to see what yours is set to.

For example, mine is this.

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

That `en_US` means English/United States. It sounds like you want something like a `en_JP` behavior, but I think the only Japanese locale definitions have Japanese as the language. My guess is that setting the Region to Japanese in system preferences makes it choose from among the defined `*_JP` locales, and fall back to `ja_JP` when it can't find one matching your preferred English language.

**Comment by jbucaran** [comment] 2016-12-06 15:19
Hi @apjanke.

When I select Americas/USA as my region, `locale`'s output is:
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

When I select Asia/Japan, the output is:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

I managed resolve the issue by exporting LANG to `en_US.UTF-8` at the start of my shell.

Thanks!

**Comment by tcsiwula** [comment] 2017-12-09 00:37
This one liner fixed it for me:
``` git config --global gpg.program gpg2 ```
=)
