### ISSUE TITLE
brew uninstall can have counter-intuitive (and frustrating) results

### ISSUE THREAD

**Issue by telemachus** [Homebrew/brew#1524] opened 2016-11-17 14:07 UTC
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Calling `brew uninstall x y` can have very unhelpful results in cases where `y` depends on `x`. For example:

    $ brew uninstall gnupg2 dirmngr
    Error: Refusing to uninstall /usr/local/Cellar/dirmngr/1.1.1_2
    because it is required by gnupg2, which is currently installed.
    You can override this and force removal with:
      brew uninstall --ignore-dependencies dirmngr

Ideally `brew` should be able to work out that in the same command where I'm trying to uninstall `dirmngr`, I'm also uninstalling `gnupg2`. No dependency will be left unfulfilled, so I shouldn't need to add an extra flag here.

I'm not sure what exactly `brew` is doing here behind the scenes, but I suppose what I'm asking is that it does it a bit smarter. That is, if the blocker (here `gnupg2`) is *also* in the call to uninstall, then `brew` should go ahead and remove the item, shouldn't it? (There may be something I'm missing here. Sorry, if so. Over the next week or so, I can try to take a look at how `brew remove` is implemented and see if I can help with a PR as well.)

**Comment by MikeMcQuaid** [comment] 2016-11-17 14:25
> I'm not sure what exactly brew is doing here behind the scenes, but I suppose what I'm asking is that it does it a bit smarter.

Yep, a good point. CC @alyssais for thoughts on this and if you'd like to jump in on this.

**Comment by alyssais** [comment] 2016-11-17 14:28
Oh, interesting. It's supposed to be able to work that out — I think we even have a test for it! I'll look into why this isn't working.

**Comment by scpeters** [comment] 2016-11-17 18:55
I ran into a similar issue when trying to:

~~~
brew remove `brew list`
~~~

In that case I just added `--ignore-dependencies` and now it's working.

**Comment by alyssais** [comment] 2016-12-29 14:52
Note: since #1723, recommended dependencies (like `dirmngr` for `gnupg2`) will no longer be recorded in install receipts as runtime dependencies, so `brew uninstall dirmngr` will no longer error, even on its own.

To test for this bug, then, we need to use a required dependency instead, so I've been using this:

```sh
brew uninstall libgpg-error gnupg2
```

**Comment by alyssais** [comment] 2016-12-29 17:13
As far as I can tell, this is fixed in `master`. I can't reproduce it any more. :D

**Comment by alyssais** [comment] 2016-12-30 17:37
On further investigation, it is still there, just harder to reproduce because of some other changes.

But, I've finally figured out what the problem is, so a fix is incoming.

**Closed** 2016-12-31 17:33 UTC
