### ISSUE TITLE
brew upgrade fail

### ISSUE THREAD

**Issue by rmondragon** [Homebrew/brew#15993] opened 2023-09-11 13:51 UTC
### `brew doctor` output

```shell
→ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
→ brew config
HOMEBREW_VERSION: 4.1.10-29-g86acd12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 86acd120b829bd0bcffa52927f938e35305260b5
Last commit: 23 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c9c077652d8294bac511af819e3a4da6057d5285
Core tap last commit: 16 minutes ago
Core tap branch: master
Core tap JSON: 11 Sep 13:44 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-x86_64
CLT: N/A
Xcode: 14.3.1
```

### What were you trying to do (and why)?

brew upgrade

### What happened (include all command output)?

==> Upgrading tcl-tk
  8.6.13_4 -> 8.6.13_5

==> Pouring tcl-tk--8.6.13_5.ventura.bottle.tar.gz
Error: Parameter 'old': Expected type Pathname, got type String with value "@@HOMEBREW_PREFIX@@/opt/openssl@3/lib"
Caller: /usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:41
Definition: /usr/local/Homebrew/Library/Homebrew/os/mac/keg.rb:40
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:187:in `report_error'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:116:in `block in validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:201:in `each_args_value_type'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:41:in `block (3 levels) in relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:138:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:138:in `each_linkage_for'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:39:in `block (2 levels) in relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:337:in `ensure_writable'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:23:in `block in relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:22:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:22:in `relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:130:in `replace_placeholders_with_locations'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1287:in `pour'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:389:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:389:in `block in create_validator_procedure_fast0'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:437:in `install'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:389:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:389:in `block in create_validator_procedure_fast0'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:218:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:191:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:101:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:100:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:100:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:214:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:136:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

### What did you expect to happen?

during brew upgrade execution

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade
...
==> Upgrading tcl-tk
  8.6.13_4 -> 8.6.13_5

==> Pouring tcl-tk--8.6.13_5.ventura.bottle.tar.gz
Error: Parameter 'old': Expected type Pathname, got type String with value "@@HOMEBREW_PREFIX@@/opt/openssl@3/lib"
Caller: /usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:41
Definition: /usr/local/Homebrew/Library/Homebrew/os/mac/keg.rb:40
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:187:in `report_error'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:116:in `block in validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:201:in `each_args_value_type'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:41:in `block (3 levels) in relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:138:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:138:in `each_linkage_for'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:39:in `block (2 levels) in relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:337:in `ensure_writable'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:23:in `block in relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:22:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:22:in `relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:130:in `replace_placeholders_with_locations'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1287:in `pour'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:389:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:389:in `block in create_validator_procedure_fast0'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:437:in `install'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:389:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:389:in `block in create_validator_procedure_fast0'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:218:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:191:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:101:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:100:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:100:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:214:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:136:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by MikeMcQuaid** [comment] 2023-09-11 13:58
Duplicate of https://github.com/Homebrew/brew/issues/15990. Fix in progress in https://github.com/Homebrew/brew/pull/15992

**Closed by MikeMcQuaid** 2023-09-11 13:58 UTC
Labels: bug
