### ISSUE TITLE
error missing osxfuse when installing sshfs

### ISSUE THREAD

**Issue by two-dogs** [Homebrew/brew#9384] opened 2020-12-02 13:49 UTC
https://git.io/JIImQ <--- while installing sshfs, history shown here, error shown 'missing osxfuse' is also shown as installed.
i have not tried to force the install, i rather not force something till i am forced to.https://raw.githubusercontent.com/Homebrew/homebrew-core/851ace4477bcb17d8574654b122e4972f8d5f4a4/Formula/sshfs.rb <-- recipe shown here

i am not sure how to make macos-catalina show active Fuse from terminal output besides the method used above.
Fuse is shown on System Preferences.

**Comment by MikeMcQuaid** [comment] 2020-12-02 14:05
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/94072

Please always fill out the issue template.

**Closed by MikeMcQuaid** 2020-12-02 14:05 UTC

**Comment by two-dogs** [comment] 2020-12-02 14:30
@MikeMcQuaid , this seems circular, you closed because it is a dup of osxfuse cant install?? i have installed it just fine, unless brew is lying, in which case that is a separate issue.
i'll force install sshfs.
