### ISSUE TITLE
Error when installing brew

### ISSUE THREAD

**Issue by fastzhong** [Homebrew/brew#15642] opened 2023-07-07 04:13 UTC
### `brew doctor` output

```shell
❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.0.28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b4cfb033757b63ab0b128d01c58db76480956f9
Last commit: 14 hours ago
Core tap JSON: 07 Jul 04:06 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
```

### What were you trying to do (and why)?

having the same problem when brew update or reinstall brew `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

### What happened (include all command output)?

❯ brew update
Error: Failed to download https://formulae.brew.sh/api/cask_tap_migrations.jws.json!

### What did you expect to happen?

Error: Failed to download https://formulae.brew.sh/api/cask_tap_migrations.jws.json!

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
just run `brew update`
```

**Comment by knksmith57** [comment] 2023-07-07 04:16
heads up, this duplicates #15641

**Comment by p-linnane** [comment] 2023-07-07 04:23
Duplicate of https://github.com/Homebrew/brew/issues/15641

**Closed by p-linnane** 2023-07-07 04:23 UTC
Labels: bug
