### ISSUE TITLE
Package Installation Spinlock Forever under Sandbox

### ISSUE THREAD

**Issue by kevinastone** [Homebrew/brew#855] opened 2016-09-02 21:30 UTC
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo) && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Installation of certain packages (seen with `heroku` and `brew-gem`) will untar/unzip their downloaded files and then just spin forever.  The installation never completes. Installing them with `--no-sandbox` allows the installation to complete successfully.

**Comment by MikeMcQuaid** [comment] 2016-09-03 12:24
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by MikeMcQuaid** [comment] 2016-09-03 13:32
Closing as duplicate of https://github.com/Homebrew/brew/issues/827

**Closed by MikeMcQuaid** 2016-09-03 13:32 UTC
