### ISSUE TITLE
cask: check OS compatibility before downloading

### ISSUE THREAD

**Issue by leonklingele** [Homebrew/brew#6755] opened 2019-11-19 12:01 UTC
When trying to update an app to a version which is incompatible with my OS, Homebrew first downloads the update and then complains about a OS mismatch.
This should be done the other way around: first check the OS compatibility, then try to download the update.

### Actual result

```sh
$ brew cask upgrade calibre
[..]
==> Upgrading 1 outdated package:
calibre 3.48.0 -> 4.3.0
==> Upgrading calibre
==> Downloading https://download.calibre-ebook.com/4.3.0/calibre-4.3.0.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'calibre'.
==> Purging files for version 4.3.0 of Cask calibre
Error: macOS Mojave or newer is required.
```

### Expected result

```sh
$ brew cask upgrade calibre
[..]
==> Upgrading 1 outdated package:
calibre 3.48.0 -> 4.3.0
==> Upgrading calibre
Error: macOS Mojave or newer is required.
```

**Comment by vitorgalvao** [comment] 2019-11-19 16:18
Closing as a duplicate of https://github.com/Homebrew/homebrew-cask/issues/72474.

**Closed by vitorgalvao** 2019-11-19 16:18 UTC
Labels: cask
