### ISSUE TITLE
Some formulae hang when building under the sandbox

### ISSUE THREAD

**Issue by asm89** [Homebrew/brew#827] opened 2016-08-27 13:04 UTC
Installing chromedriver with sandboxing enabled is hanging forever for me. Running `pstree` revealed that the process got stuck on running:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -version Path
```

Running `sudo dtruss -p <pid>` revealed it was trying to access the following file:

```
open("/Users/asm/Library/Application Support/Parse/CADWoI1OTDpYECcR3P6a6XdJUUJIocbUPqCIKusT/applicationId.pflock\0", 0x222, 0x1FF)		 = -1 Err#1
```

Running the install with `brew install chromedriver --no-sandbox` made it work. I'm guessing this might not be chromedriver specific.

```
~ $ brew --version
Homebrew 0.9.9 (git revision 64091; last commit 2016-08-27)
Homebrew/homebrew-core (git revision 2eb0; last commit 2016-08-26)
```

**Comment by MikeMcQuaid** [comment] 2016-08-30 17:47
CC @xu-cheng for thoughts; have you seen hanging like this before and, if so, what did you do to work around/fix it?

**Comment by javache** [comment] 2016-09-09 21:20
@asm89 I just hit the same issue, maybe it's something FB-specific?

**Comment by xu-cheng** [comment] 2016-09-10 06:53
Sorry for the late response. It seems to me this is caused by this formula trying to create lock files outside the places we permitted. Hence, it hangs forever to wait for the lock.  

The deeper issue seems to be that Xcode and its SDK don't honor `$HOME` variable changes.

Some possible solutions:
* Found way to convince Xcode `$HOME` and `~/Library` path is located in `/tmp` folder.
* Allow certain Xcode processes running outside sandbox.
* Allow certain lock files be written outside the usual places. e.g. we can use ext name as criterial.

Of course the first solution is most preferred.

**Comment by xu-cheng** [comment] 2016-09-10 07:19
Are you sure it is `chromedriver` the formula in question? From what I see, that formula doesn't compile anything. Therefore, I cannot reproduce this problem locally.

**Comment by MikeMcQuaid** [comment] 2016-09-10 08:43
@xu-cheng thanks for the reply and solutions.

As two maintainers can't reproduce this, closing sorry.

**Closed by MikeMcQuaid** 2016-09-10 08:43 UTC
Labels: help wanted

**Comment by wez** [comment] 2016-09-10 16:04
I'm hitting this same Parse pflock issue while testing an update to the watchman formula... I'm also a Facebook employee, and `--no-sandbox` also made things tick over for me.

**Comment by MikeMcQuaid** [comment] 2016-09-10 18:18
I'd suggest you take this up with Facebook internal channels.

**Comment by asm89** [comment] 2016-09-11 18:50
@xu-cheng @MikeMcQuaid I've definitely only had this issue with chromedriver so far. Thanks for looking into it, but I understand you can't do much if you can't reproduce.

Interesting that my colleagues @javache and @wez are hitting the same issues.
