### ISSUE TITLE
`brew deps` `--include-build` & `--include-test` flags ignore `--missing`

### ISSUE THREAD

**Issue by dbrookman** [Homebrew/brew#15842] opened 2023-08-07 19:22 UTC
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.4-10-ga7d8ba1
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7d8ba131ee5ca8dcbe4574b1e5001eb3d81f13f
Last commit: 37 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 880569c6d3bcd9ed8970a79796c847aea80fa625
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 07 Aug 18:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.LWih3zyrgv/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew deps --include-build --include-test --missing mpv`

Trying to see which build / test dependencies for a formula have not been installed.

### What happened (include all command output)?

Even with `--missing` set, installed build / test dependencies are shown.

```
Warning: Treating mpv as a formula. For the cask, use homebrew/cask/mpv
docutils
meson
pkg-config
```
### What did you expect to happen?

```
Warning: Treating mpv as a formula. For the cask, use homebrew/cask/mpv
```
Shouldn't display build / test dependencies that have already been satisfied.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew deps --include-build --include-test --missing mpv
brew install docutils meson pkg-config
brew deps --include-build --include-test --missing mpv
```

**Comment by MikeMcQuaid** [comment] 2023-08-08 10:56
A potential short-term fix for this would be to make `--missing` conflict with `--include-build` if another @Homebrew/brew person can reproduce this issue and confirm it's not working as expected.

**Comment by apainintheneck** [comment] 2023-08-09 05:47
It looks like when we resolve recursive dependencies we only check if the dependency is satisfied (already installed) if none of the other criteria match. In this case, it gets skipped since the build and test flags are evaluated before them.

https://github.com/Homebrew/brew/blob/dc42544c59a26805825a56b323caeb9bbf696ff3/Library/Homebrew/dependencies_helpers.rb#L44-L55

If I move the satisfied check to the front here, it seems to work the way I'd expect it to but I'm not sure what other code relies on the current behavior. It looks like it's only referenced in the `brew deps` and `brew uses` commands at a glance.

**Comment by apainintheneck** [comment] 2023-08-09 05:52
I'll be honest and say I don't really understand the use case for `brew uses --missing`.

**Comment by MikeMcQuaid** [comment] 2023-08-09 07:43
> It looks like it's only referenced in the `brew deps` and `brew uses` commands at a glance.

Yeh, it's just used by them to share some code. Could you open a PR?

> I'll be honest and say I don't really understand the use case for `brew uses --missing`.

Yeh, I think it's just an inverse to `--installed`, I can't really think of a specific case there either.

**Comment by apainintheneck** [comment] 2023-08-10 05:05
I took another look and I guess I'm not entirely sure what the expected behavior is here. It seems like if `--missing` is set we should always skip every installed package and ignore it's dependencies, right?

We can't move the satisfied check before the other checks because it introduces some false positives (see https://github.com/Homebrew/brew/pull/15529).

It seems like the `if/elsif` might be the problem here. Do we really want to skip all of the other checks if the dependency is recommended but doesn't meet the criteria for pruning it?

Maybe it should work something like this (haven't test it yet):

```diff
diff --git a/Library/Homebrew/dependencies_helpers.rb b/Library/Homebrew/dependencies_helpers.rb
index dd2a3acd2..a2d0d26cc 100644
--- a/Library/Homebrew/dependencies_helpers.rb
+++ b/Library/Homebrew/dependencies_helpers.rb
@@ -41,19 +41,18 @@ module DependenciesHelpers
     cache_key = "recursive_includes_#{includes}_#{ignores}"
 
     klass.expand(root_dependent, cache_key: cache_key) do |dependent, dep|
-      if dep.recommended?
-        klass.prune if ignores.include?("recommended?") || dependent.build.without?(dep)
-      elsif dep.optional?
-        klass.prune if includes.exclude?("optional?") && !dependent.build.with?(dep)
-      elsif dep.build? || dep.test?
-        keep = false
-        keep ||= dep.test? && includes.include?("test?") && dependent == root_dependent
-        keep ||= dep.build? && includes.include?("build?")
-        klass.prune unless keep
-      elsif dep.satisfied?
-        klass.prune if ignores.include?("satisfied?")
+      prune = false
+      prune ||= dep.recommended? && ignores.include?("recommended?") || dependent.build.without?(dep)
+      prune ||= dep.optional? && includes.exclude?("optional?") && !dependent.build.with?(dep)
+      prune ||= dep.satisfied? && ignores.include?("satisfied?")
+      prune ||= begin
+        build_dep = dep.build? && includes.include?("build?")
+        test_dep = dep.test? && includes.include?("test?") && dependent == root_dependent
+        !build_dep && !test_dep
       end
 
+      klass.prune if prune
+
       # If a tap isn't installed, we can't find the dependencies of one of
       # its formulae, and an exception will be thrown if we try.
       Dependency.keep_but_prune_recursive_deps if klass == Dependency && dep.tap && !dep.tap.installed?
```

CC: @carlocab in case you have any insight into this since you fixed it two months ago.

**Comment by apainintheneck** [comment] 2023-08-12 05:02
I see what you're saying about this being a command that probably doesn't get used that much (at least with these options) but I'm not sure that just marking those two options as conflicting will solve things. The confusing thing for me is that there's no notion of precedence here.

There are two general types of options available for the `brew deps` command.

### Additive
```
      --include-build              Include :build dependencies for formula.
      --include-optional           Include :optional dependencies for
                                   formula.
      --include-test               Include :test dependencies for formula
                                   (non-recursive).
```

### Subtractive
```
      --skip-recommended           Skip :recommended dependencies for
                                   formula.
      --missing                    Show only missing dependencies.
```

It seems like any of the additive options could potentially conflict with one of the subtractive ones. Of course, recommended and optional are not used in core so that reduces the possibility of those causing problems for folks. Beyond that missing was only added to this command a few months ago. This seems to be true for the `brew uses` command. The word is even stronger there though which makes it even more confusing.

### Additive
```
      --include-build              Include all formulae that specify formula
                                   as :build type dependency.
      --include-test               Include all formulae that specify formula
                                   as :test type dependency.
      --include-optional           Include all formulae that specify formula
                                   as :optional type dependency.
```

### Subtractive
```
      --missing                    Only list formulae and casks that are not
                                   currently installed.
      --skip-recommended           Skip all formulae that specify formula as
                                   :recommended type dependency.
```

**Comment by MikeMcQuaid** [comment] 2023-08-14 11:37
@apainintheneck Yeh, I'm not sure what's best then 🤷🏻. Open to suggestions.

**Comment by dbrookman** [comment] 2023-08-14 15:35
My ~non~use case was: I maintain a [build script for mpv.app](https://gist.github.com/dbrookman/74b8bcfb37a23452f7137b83bca9580f) that depends on brew's mpv formula to install all the dependencies for simplicity's sake (mostly in case they change). There doesn't seem to be any way to run `brew install --only-dependencies` that also includes the build dependencies, so I started poking around for a way to feed the missing ones to `brew install`. Hence `brew deps --missing --include-build`--include-build`. But. But considering the script will almost certainly have to change if the build dependencies do, I decided it wasn't worth the effort.

I figured I'd submit the bug anyways, if only because the order of operations isn't clear. My first assumption was that the additive options would be applied first, followed by the subtractive options. PEMDAS-style like:
1. Required
2. Required + Build
3. (Required + Build) - not Missing

**Comment by MikeMcQuaid** [comment] 2023-08-14 18:13
> There doesn't seem to be any way to run `brew install --only-dependencies` that also includes the build dependencies

I haven't tried but `brew install --build-from-source --only-dependencies` or `brew install --build-bottle --only-dependencies` may work?

**Comment by dbrookman** [comment] 2023-08-15 19:11
> > There doesn't seem to be any way to run `brew install --only-dependencies` that also includes the build dependencies
> 
> I haven't tried but `brew install --build-from-source --only-dependencies` or `brew install --build-bottle --only-dependencies` may work?

It did, thanks for the tip!

**Comment by MikeMcQuaid** [comment] 2023-08-16 07:50
> It seems like any of the additive options could potentially conflict with one of the subtractive ones. Of course, recommended and optional are not used in core so that reduces the possibility of those causing problems for folks.

@apainintheneck Yeh, I agree with that. I'm tempted to mark them all as conflicting for that reason. Thoughts?

**Comment by MikeMcQuaid** [comment] 2023-08-17 11:08
> I think we should change it to work this way and update the language in the docs to reflect that change.

Works for me 👍🏻

**Closed** 2023-08-30 07:29 UTC
Labels: bug, in progress
