### ISSUE TITLE
Allow brew dump and cleanup to run offline

### ISSUE THREAD

**Issue by Moulick** [Homebrew/brew#14455] opened 2023-01-28 07:57 UTC
### `brew doctor` output

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  kubernetes-service-catalog-client
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-143-g10845a1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 10845a1122b916dc91d04f00a4d8b7b888d52654
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 70d133fdc25baa4aa4d6779bb74e4b4da5804171
Core tap last commit: 23 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I am trying to run `brew dump` and `brew cleanup`

### What happened (include all command output)?

```bash
❯ brew bundle dump --force --all --formula --taps --whalebrew --casks --mas --describe --file="$HOME/.Brewfile"
curl: (6) Could not resolve host: formulae.brew.sh
curl: (6) Could not resolve host: formulae.brew.sh
curl: (6) Could not resolve host: formulae.brew.sh
^C
```

```bash
❯ brew cleanup
curl: (6) Could not resolve host: formulae.brew.sh
curl: (6) Could not resolve host: formulae.brew.sh
curl: (6) Could not resolve host: formulae.brew.sh
curl: (6) Could not resolve host: formulae.brew.sh
curl: (6) Could not resolve host: formulae.brew.sh
curl: (6) Could not resolve host: formulae.brew.sh
^C
```

### What did you expect to happen?

Both commands successfully execute

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Run `brew cleanup` or `brew bundle dump --force --all --formula --taps --whalebrew --casks --mas --describe --file="$HOME/.Brewfile"`
```

**Comment by Moulick** [comment] 2023-01-28 07:58
This seems to be related to https://github.com/Homebrew/brew/issues/14451 and https://github.com/Homebrew/brew/issues/14445

**Comment by Rylan12** [comment] 2023-01-28 08:24
Agreed, the experience here needs to be improved. Thanks for reporting!

In the meantime, setting the `HOMEBREW_NO_INSTALL_FROM_API` environment variable should allow you to continue using those commands.

**Comment by apainintheneck** [comment] 2023-01-30 02:11
Seems like https://github.com/Homebrew/brew/issues/14462 is probably related.

**Comment by MikeMcQuaid** [comment] 2023-02-03 08:35
Marking as a duplicate of https://github.com/Homebrew/brew/issues/14451

**Closed by MikeMcQuaid** 2023-02-03 08:35 UTC
Labels: bug, install from api
