### ISSUE TITLE
Can't run brew style and audit: incompatible library version - jaro_winkler-1.5.2

### ISSUE THREAD

**Issue by ran-dall** [Homebrew/brew#6079] opened 2019-04-30 16:03 UTC
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Run `brew style`or `brew audit`

# What happened (include command output)

It tried to update Homebrew's gems?

 ```bash
brew style git
Fetching gem metadata from https://rubygems.org/.........                                                                                                                               
Using concurrent-ruby 1.1.5                                                                                                                                                             
Using minitest 5.11.3                                                                                                                                                                   
Using thread_safe 0.3.6                                                                                                                                                                 
Using ast 2.4.0                                                                                                                                                                         
Using backports 3.14.0                                                                                                                                                                  
Using bundler 2.0.1                                                                                                                                                                     
Using connection_pool 2.2.2                                                                                                                                                             
Fetching json 2.2.0                                                                                                                                                                     
Using docile 1.3.1                                                                                                                                                                      
Using simplecov-html 0.10.2                                                                                                                                                             
Using tins 1.20.2                                                                                                                                                                       
Using thor 0.19.4                                                                                                                                                                       
Using diff-lcs 1.3                                                                                                                                                                      
Fetching unf_ext 0.0.7.6                                                                                                                                                                
Fetching hpricot 0.8.6                                                                                                                                                                  
Installing json 2.2.0 with native extensions                                                                                                                                            
Installing hpricot 0.8.6 with native extensions                                                                                                                                         
Installing unf_ext 0.0.7.6 with native extensions                                                                                                                                       
Fetching jaro_winkler 1.5.2                                                                                                                                                             
Installing jaro_winkler 1.5.2 with native extensions                                                                                                                                    
Using mime-types-data 3.2019.0331                                                                                                                                                       
Using net-http-digest_auth 1.4.1                                                                                                                                                        
Using mini_portile2 2.4.0                                                                                                                                                               
Using ntlm-http 0.1.1                                                                                                                                                                   
Using webrobots 0.1.2                                                                                                                                                                   
Using mustache 1.1.0                                                                                                                                                                    
Using parallel 1.17.0                                                                                                                                                                   
Using plist 3.5.0                                                                                                                                                                       
Using rainbow 3.0.0                                                                                                                                                                     
Fetching rdiscount 2.2.0.1                                                                                                                                                              
Installing rdiscount 2.2.0.1 with native extensions                                                                                                                                     
Using rspec-support 3.8.0                                                                                                                                                               
Using ruby-progressbar 1.10.0                                                                                                                                                           
Using unicode-display_width 1.5.0                                                                                                                                                       
Using ruby-macho 2.2.0                                                                                                                                                                  
Using i18n 1.6.0                                                                                                                                                                        
Using tzinfo 1.2.5                                                                                                                                                                      
Using parser 2.6.3.0                                                                                                                                                                    
Using net-http-persistent 3.0.1                                                                                                                                                         
Using term-ansicolor 1.7.1                                                                                                                                                              
Using unf 0.1.4                                                                                                                                                                         
Using mime-types 3.2.2                                                                                                                                                                  
Fetching nokogiri 1.10.3                                                                                                                                                                
Using parallel_tests 2.28.0                                                                                                                                                             
Using activesupport 5.2.3                                                                                                                                                               
Using domain_name 0.5.20180417                                                                                                                                                          
Using rspec-core 3.8.0                                                                                                                                                                  
Using rspec-expectations 3.8.3                                                                                                                                                          
Using rspec-mocks 3.8.0                                                                                                                                                                 
Using rubocop 0.68.0                                                                                                                                                                    
Using simplecov 0.16.1                                                                                                                                                                  
Using http-cookie 1.0.3                                                                                                                                                                 
Using rspec 3.8.0                                                                                                                                                                       
Using rspec-its 1.3.0                                                                                                                                                                   
Using rspec-retry 0.6.1                                                                                                                                                                 
Using rubocop-performance 1.1.0                                                                                                                                                         
Using rubocop-rspec 1.32.0                                                                                                                                                              
Using coveralls 0.8.22                                                                                                                                                                  
Using rspec-wait 0.0.9                                                                                                                                                                  
Using simplecov-cobertura 1.3.1                                                                                                                                                         
Installing nokogiri 1.10.3 with native extensions                                                                                                                                       
Using ronn 0.7.3                                                                                                                                                                        
Using mechanize 2.7.6                                                                                                                                                                   
Bundle complete! 18 Gemfile dependencies, 57 gems now installed.                                                                                                                        
Bundled gems are installed into `/usr/local/Homebrew/Library/Homebrew/vendor/bundle`                                                                                                                                       
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jaro_winkler (LoadError)   
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                         
        from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop/string_util.rb:3:in `<top (required)>'                                       
        from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop.rb:17:in `require_relative'                                                  
        from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop.rb:17:in `<top (required)>'                                                  
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                         
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                         
        from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/exe/rubocop:6:in `<top (required)>'                                                      
        from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `load'                                                                                     
        from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `<main>'                                                                                   
Error: style check failed
```

# What you expected to happen

Run `style`

# Step-by-step reproduction instructions (by running `brew` commands)

```bash
brew style wget
Error: incompatible library version - /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.2/lib/jaro_winkler/jaro_winkler_ext.bundle                    
Please report this bug:                                                                                                                                                                 
  https://docs.brew.sh/Troubleshooting                                                                                                                                                  
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.2/lib/jaro_winkler.rb:6:in `<top (required)>'                                                       
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop/string_util.rb:3:in `<top (required)>'                                                    
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop.rb:17:in `require_relative'                                                               
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop.rb:17:in `<top (required)>'                                                               
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'                                                     
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'                                           
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/style.rb:23:in `check_style_impl'                                                                                                                  
/usr/local/Homebrew/Library/Homebrew/style.rb:10:in `check_style_and_print'                                                                                                             
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:65:in `style'                                                                                                                         
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'    
```

```bash
brew style git
Error: incompatible library version - /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.2/lib/jaro_winkler/jaro_winkler_ext.bundle                    
Please report this bug:                                                                                                                                                                 
  https://docs.brew.sh/Troubleshooting                                                                                                                                                  
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.2/lib/jaro_winkler.rb:6:in `<top (required)>'                                                       
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop/string_util.rb:3:in `<top (required)>'                                                    
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop.rb:17:in `require_relative'                                                               
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop.rb:17:in `<top (required)>'                                                               
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'                                                     
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'                                           
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'                                                      
/usr/local/Homebrew/Library/Homebrew/style.rb:23:in `check_style_impl'                                                                                                                  
/usr/local/Homebrew/Library/Homebrew/style.rb:10:in `check_style_and_print'                                                                                                             
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:65:in `style'                                                                                                                         
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'    
```
```bash
brew audit git
Error: incompatible library version - /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.2/lib/jaro_winkler/jaro_winkler_ext.bundle
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.2/lib/jaro_winkler.rb:6:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop/string_util.rb:3:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop.rb:17:in `require_relative'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.68.0/lib/rubocop.rb:17:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/Homebrew/Library/Homebrew/style.rb:23:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/style.rb:16:in `check_style_json'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:114:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

---

```bash
brew config
HOMEBREW_VERSION: 2.1.1-95-g2aefcb3                                                                                                                                                     
ORIGIN: https://github.com/Homebrew/brew                                                                                                                                                
HEAD: 2aefcb37c412438e7b2fac479b0a8f26a7c86c4c                                                                                                                                          
Last commit: 7 hours ago                                                                                                                                                                
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core                                                                                                                              
Core tap HEAD: 422ef941c0a2b69e9e1ab93612cfbb2ead581bf6                                                                                                                                 
Core tap last commit: 8 hours ago                                                                                                                                                       
HOMEBREW_PREFIX: /usr/local                                                                                                                                                             
HOMEBREW_DEV_CMD_RUN: 1                                                                                                                                                                 
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby                                                                                        
Clang: 10.0 build 1000                                                                                                                                                                  
Git: 2.21.0 => /usr/local/bin/git                                                                                                                                                       
Curl: 7.54.0 => /usr/bin/curl                                                                                                                                                           
macOS: 10.13.6-x86_64                                                                                                                                                                   
CLT: 10.1.0.0.1.1539992718                                                                                                                                                              
Xcode: 10.1                                                                                                                                                                             
```

**Comment by MikeMcQuaid** [comment] 2019-04-30 16:10
Duplicate of https://github.com/Homebrew/brew/issues/5561

**Closed by MikeMcQuaid** 2019-04-30 16:10 UTC

**Comment by ran-dall** [comment] 2019-04-30 17:12
@MikeMcQuaid Thanks 👏 I thought it might be related.
