### ISSUE TITLE
`brew cleanup -n` proposes removing formulae that should remain in the cache

### ISSUE THREAD

**Issue by jabenninghoff** [Homebrew/brew#8919] opened 2020-10-14 01:18 UTC
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Running `brew cleanup -n` to check what formulae and casks will be removed.

## What happened (include command output)

`brew cleanup -n` proposed removing a formula that should remain in the cache.

<details>
  <summary>Command output</summary>
  <pre>
$ brew cleanup -n
Would remove: /Users/jabenninghoff/Library/Caches/Homebrew/libsndfile--1.0.30.mojave.bottle.tar.gz (545.6KB)
Would remove: /Users/jabenninghoff/Library/Caches/Homebrew/Cask/atom--1.51.0.zip (183MB)
Would remove: /Users/jabenninghoff/Library/Caches/Homebrew/Cask/imazing--2.12.3.13827.dmg (152.9MB)
Would remove: /Users/jabenninghoff/Library/Caches/Homebrew/Cask/google-chrome--86.0.4240.75.dmg (91MB)
Would remove: /Users/jabenninghoff/Library/Caches/Homebrew/Cask/microsoft-office--16.41.20091302.pkg (1.5GB)
Would remove: /Users/jabenninghoff/Library/Caches/Homebrew/Cask/firefox--81.0.1.dmg (72.9MB)
Would remove: /Users/jabenninghoff/Library/Caches/Homebrew/Cask/flash-npapi--32.0.0.433.dmg (15.0MB)
Would remove: /Users/jabenninghoff/Library/Caches/Homebrew/Cask/skype--8.65.0.76.dmg (104.7MB)
Would remove: /Users/jabenninghoff/Library/Caches/Homebrew/Cask/graphicconverter--11.2.2,4491.zip (172.6MB)
==> This operation would free approximately 2.2GB of disk space.
  </pre>
</details>

## What you expected to happen

I expected `brew cleanup -n` to propose removing the listed casks, but not `libsndfile` which is still installed and current, and within the `HOMEBREW_CLEANUP_MAX_AGE_DAYS` of 36500 (100 years).

Additional info - I just noticed this today; and pulled additional diagnostics here. `libsndfile` was installed as a dependency.
```
$ brew uninstall libsndfile
Error: Refusing to uninstall /usr/local/Cellar/libsndfile/1.0.30
because it is required by ffmpeg, frotz, libsamplerate and rubberband, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies libsndfile

$ brew info libsndfile
libsndfile: stable 1.0.30 (bottled)
C library for files containing sampled sound
http://www.mega-nerd.com/libsndfile/
/usr/local/Cellar/libsndfile/1.0.30 (49 files, 1.5MB) *
  Poured from bottle on 2020-09-27 at 13:53:20
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libsndfile.rb
License: LGPL-2.1-or-later
==> Dependencies
Build: autoconf ✔, automake ✘, libtool ✔, pkg-config ✔
Required: flac ✔, libogg ✔, libvorbis ✔, opus ✔
==> Analytics
install: 129,367 (30 days), 359,536 (90 days), 807,517 (365 days)
install-on-request: 2,946 (30 days), 7,389 (90 days), 11,708 (365 days)
build-error: 0 (30 days)

$ cd ~/Library/Caches/Homebrew/
$ ls -lA libsndfile--1.0.30.mojave.bottle.tar.gz 
lrwxr-xr-x  1 jabenninghoff  staff  114 Oct  4 08:42 libsndfile--1.0.30.mojave.bottle.tar.gz -> downloads/888534255e254080170aff504d4632a70b1894a1d67a1b5d4dee879d79630eba--libsndfile-1.0.30.mojave.bottle.tar.gz
$ ls -lA downloads/888534255e254080170aff504d4632a70b1894a1d67a1b5d4dee879d79630eba--libsndfile-1.0.30.mojave.bottle.tar.gz 
-rw-r--r--  1 jabenninghoff  staff  558729 Sep 20 15:22 downloads/888534255e254080170aff504d4632a70b1894a1d67a1b5d4dee879d79630eba--libsndfile-1.0.30.mojave.bottle.tar.gz

$ ls -lAc libsndfile--1.0.30.mojave.bottle.tar.gz 
lrwxr-xr-x  1 jabenninghoff  staff  114 Oct  4 08:42 libsndfile--1.0.30.mojave.bottle.tar.gz -> downloads/888534255e254080170aff504d4632a70b1894a1d67a1b5d4dee879d79630eba--libsndfile-1.0.30.mojave.bottle.tar.gz
$ ls -lAc downloads/888534255e254080170aff504d4632a70b1894a1d67a1b5d4dee879d79630eba--libsndfile-1.0.30.mojave.bottle.tar.gz 
-rw-r--r--  1 jabenninghoff  staff  558729 Sep 27 13:53 downloads/888534255e254080170aff504d4632a70b1894a1d67a1b5d4dee879d79630eba--libsndfile-1.0.30.mojave.bottle.tar.gz
```

## Step-by-step reproduction instructions (by running `brew` commands)

Admittedly, this is hard to reproduce, but:

1. Add `export HOMEBREW_CLEANUP_MAX_AGE_DAYS=36500` to your `~/.bashrc`
1. Install brew formulae
1. Wait
1. Periodically run `brew cleanup -n`

This seems to be related to #7320. Since @MikeMcQuaid merged #7400, casks are not removed from `~/Library/Caches/Homebrew/`, but formulae occasionally are. I've observed this behavior on multiple systems, including Catalina.

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.6-33-g8437f51
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8437f518377f031ad1c37eb31793a1825a8bead0
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 46a7c2deadfed26305c90cdad34f6d590ffff690
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 36500
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.H6NltdOYVs/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 11.0 build 1100
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 15
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment] 2020-10-14 07:24
I can't reproduce this (on Catalina at least). Can you stick some debugging in your `Library/Homebrew/cleanup.rb` and see if you can figure out what is triggering this behaviour?

**Comment by jabenninghoff** [comment] 2020-10-14 11:24
I believe I've found the problem. This line is triggering the cleanup:

```
          return true if Utils::Bottles.file_outdated?(formula, self)
```

looking at the code, `brew cleanup` thinks that the `libsndfile` bottle is out of date, which it is - I confirmed with `brew fetch`:
```
$ brew fetch libsndfile
==> Downloading https://homebrew.bintray.com/bottles/libsndfile-1.0.30.mojave.bottle.1.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/5e0f78600b00ca0ebdbafe83e0a0a0a4833810233d714300acac13babb7553bf?respon
######################################################################## 100.0%
Downloaded to: /Users/agamemnon/Library/Caches/Homebrew/downloads/d2458dde46c84b49617065ca0bdbe5132e81d287ee016f425b5e9ad9654cc5b3--libsndfile-1.0.30.mojave.bottle.1.tar.gz
SHA256: 5e0f78600b00ca0ebdbafe83e0a0a0a4833810233d714300acac13babb7553bf
$ cd ~/Library/Caches/Homebrew/
$ ls -lA libsndfile--1.0.30.mojave.bottle.*
lrwxr-xr-x  1 jabenninghoff  staff  116 Oct 14 06:16 libsndfile--1.0.30.mojave.bottle.1.tar.gz -> downloads/d2458dde46c84b49617065ca0bdbe5132e81d287ee016f425b5e9ad9654cc5b3--libsndfile-1.0.30.mojave.bottle.1.tar.gz
lrwxr-xr-x  1 jabenninghoff  staff  114 Oct  4 08:42 libsndfile--1.0.30.mojave.bottle.tar.gz -> downloads/888534255e254080170aff504d4632a70b1894a1d67a1b5d4dee879d79630eba--libsndfile-1.0.30.mojave.bottle.tar.gz
$ brew fetch libsndfile
==> Downloading https://homebrew.bintray.com/bottles/libsndfile-1.0.30.mojave.bottle.1.tar.gz
Already downloaded: /Users/agamemnon/Library/Caches/Homebrew/downloads/d2458dde46c84b49617065ca0bdbe5132e81d287ee016f425b5e9ad9654cc5b3--libsndfile-1.0.30.mojave.bottle.1.tar.gz
SHA256: 5e0f78600b00ca0ebdbafe83e0a0a0a4833810233d714300acac13babb7553bf
```

So, `brew cleanup` is working as expected, removing the out of date bottle. This prompts a new question: can the outdated/upgrade logic be changed to match? That is, if there's a new bottled version of an installed formula available, can `brew` download and reinstall it as if it was an upgrade? I would think that would be desirable behavior.

**Comment by MikeMcQuaid** [comment] 2020-10-15 10:04
> So, `brew cleanup` is working as expected, removing the out of date bottle.

Agreed so closing 👍🏻 

> That is, if there's a new bottled version of an installed formula available, can `brew` download and reinstall it as if it was an upgrade? I would think that would be desirable behavior.

`brew reinstall` or `brew fetch` will both download the new bottle. `brew upgrade` intentionally doesn't because you don't need to upgrade (or we'd have increased the `revision`).

**Closed by MikeMcQuaid** 2020-10-15 10:04 UTC
