### ISSUE TITLE
Installing already installed cask is now a hard error

### ISSUE THREAD

**Issue by kaihowl** [Homebrew/brew#15295] opened 2023-04-23 14:58 UTC
### `brew doctor` output

```shell
❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.14-115-g4ddebd9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4ddebd9bd58d1bac7eadc70c5f48c73676173f09
Last commit: 15 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 15cc58f490ef218e460352ccd00ebf79f35b2491
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 23 Apr 14:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: N/A
Xcode: 14.3
Rosetta 2: false
```

### What were you trying to do (and why)?

As part of my dotfiles, several formulas and casks are installed and upgraded daily. This is accomplished by calling `brew install <formula>`. For already installed formulas, the command should issue a warning for an installed formula and upgrade it if it is outdated.

### What happened (include all command output)?

With https://github.com/Homebrew/brew/pull/15273 merged, the behavior for Casks regresses: Now an already installed Casks is a hard error and no longer a mere warning.

### What did you expect to happen?

An already installed cask should issue a warning but not be a hard error (with exit code != 0). If the cask is outdated, it should be upgraded. The behavior should be consistent with formulas.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`$ brew install alacritty`
`$ brew install alacritty`

(Run it twice in case it is not installed.)


Error: Cask 'alacritty' is already installed.

To re-install alacritty, run:
  brew reinstall --cask alacritty
```
```

**Comment by apainintheneck** [comment] 2023-04-23 17:20
Sounds like there are two issues here.

1. The regression with calling `brew install <cask>` and getting an error instead of a warning. You did a good job of finding out which commit caused the problem and this should be an easy fix.
2. When installing a cask that already is installed with `brew install <cask>`, it should upgrade it by default. This hasn't been the default behavior, at least recently, so we'd have to discuss this some more. I'm not sure that this behavior is intuitive or desirable.

I guess I'd like to know more about the scripts that you're running to see if some other command would work better for the second issue.

**Comment by kaihowl** [comment] 2023-04-23 20:30
Hey there, @apainintheneck,

thanks for responding so quickly (and even putting up a fix already). :)

Re (2): I made the assumption based on the help text that comes up for `brew install --help`. On re-reading the part now, though, I clearly see that only _formulas_ are upgraded automatically when outdated. That is on me.

```
Unless HOMEBREW_NO_INSTALL_UPGRADE is set, brew install formula will
upgrade formula if it is already installed but outdated.
```

The scripts I talk about can be seen here:
- [This is the wrapper function](https://github.com/kaihowl/dotfiles/blob/a9ef4c109a0445bba442c81405c484cb7bb30da2/common/brew.sh#L25-L26) that gets called when formulas/casks should be installed/upgraded.
- [This is an example](https://github.com/kaihowl/dotfiles/blob/a9ef4c109a0445bba442c81405c484cb7bb30da2/alacritty/install.sh#L8) where a cask (alacritty) instead of a formula gets installed.

I guess my wrong assumption about the upgrade behavior of casks means that I have a bug here: Once installed, alacritty will never be upgraded automatically.

Is that correct?

**Comment by apainintheneck** [comment] 2023-04-24 00:22
Yeah, to upgrade casks you have to use the `brew upgrade` command. You could also reinstall the cask but I doubt you'd want to do that each time.

Looking at your scripts I don't think there is any one command that will do exactly what you want. You could always check if a cask is already installed using `brew list --cask <name>` and then run the upgrade command in that case though.

We could also potentially change this code so that the cask and formula parts work the same way which wouldn't be too difficult. Maybe worth considering but it would be a breaking change so we'd have to be careful.

**Comment by apainintheneck** [comment] 2023-04-30 06:23
Thinking about this some more and I assume we'd want to exclude latest version and autoupdate casks from this upgrade on install behavior.

**Comment by MikeMcQuaid** [comment] 2023-04-30 08:55
@apainintheneck yeh, I'd think so, basically `brew upgrade` without `--greedy`?

**Comment by MikeMcQuaid** [comment] 2023-07-24 12:01
@apainintheneck works for me! Close it out if you're happy to do so.

**Closed** 2023-07-25 07:21 UTC
Labels: bug, in progress, cask
