### ISSUE TITLE
Update fails: unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by surajsharma** [Homebrew/brew#240] opened 2016-05-13 17:59 UTC
`brew update` ends with following error
```
fatal: Unable to find remote helper for 'https'
Error: Fetching /usr/local failed!
fatal: Unable to find remote helper for 'https'
Error: Fetching /usr/local/Library/Taps/caskroom/homebrew-cask failed!
Already up-to-date.

```

`brew doctor` does not find any error. only a warning about path.

**Comment by dunn** [comment] 2016-05-14 03:00
Can you post the output of `brew config`?

**Comment by surajsharma** [comment] 2016-05-14 16:35
apparently i did a `brew install git` and everythin works fine now! did not have git but didnt know brew needed it for updates.

**Comment by Blaisorblade** [comment] 2016-05-14 22:40
`brew` does use git for updates. Is it possible you had some version of `git` installed, but it lacked just support for HTTPS (because not compiled in)? Because that'd be my guess given the output you posted — I reproduced something similar (see below).

To verify that, I'd try `brew unlink git` followed by `which git` (and maybe post the output, in addition to `brew config`). Then do `brew link git` to make the Brew-installed git available again.

My output (with more taps so more errors):
```
$ mv /usr/local/Cellar/git/2.8.2_1/libexec/git-core/git-remote-https /usr/local/Cellar/git/2.8.2_1/libexec/git-core/git-remote-https-away
pgiarrusso [bluevelvet: /usr/local: 00:02: 7 (0)]
$ brew update
fatal: Unable to find remote helper for 'https'
fatal: Unable to find remote helper for 'https'
fatal: Unable to find remote helper for 'https'
fatal: Unable to find remote helper for 'https'
fatal: Unable to find remote helper for 'https'
Error: Fetching /usr/local/Library/Taps/homebrew/homebrew-binary failed!
Fetching /usr/local/Library/Taps/homebrew/homebrew-command-not-found failed!
Fetching /usr/local/Library/Taps/caskroom/homebrew-cask failed!
Fetching /usr/local/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Library/Taps/homebrew/homebrew-x11 failed!
```

Things that Homebrew could do:
- would it help diagnosis if brew had said "Git failed fetching /usr/local!" instead of `Fetching /usr/local failed!"? Changing the error would be easy (it's at https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/update.sh#L358).
-  beyond testing if Git exists (which brew update already appears to do), it could test for the helper's existence — it seems `echo | git remote-https origin` from `/usr/local` would work. Not sure this is worthwhile though.

**Comment by mikemcquaid** [comment] 2016-05-15 17:22
> it could test for the helper's existence — it seems echo | git remote-https origin from /usr/local would work. Not sure this is worthwhile though.

This seems like a good idea 👍  CC @xu-cheng

**Comment by xu-cheng** [comment] 2016-05-17 08:23
> This seems like a good idea 👍 CC @xu-cheng

I just test a bit. This won't work if the origin is not https, for example ssh or `git://`

**Comment by mikemcquaid** [comment] 2016-05-17 08:37
@xu-cheng Sure but in that case we can check? HTTPS is the default so we should handle that case not working, no?

**Comment by Blaisorblade** [comment] 2016-05-17 08:46
> This won't work if the origin is not https, for example ssh or git://

@xu-cheng Oh, I thought that `origin` in `/usr/local` is managed by Homebrew... Anyway, `echo | git remote-https https://github.com/Homebrew/brew.git` appears to work (with exit code 0) in any folder.

**Comment by Blaisorblade** [comment] 2016-05-17 08:57
> @xu-cheng Sure but in that case we can check? HTTPS is the default so we should handle that case not working, no?

My earlier command *breaks* (with a segfault) if `origin` is not HTTPS, my bad — which I guess is reasonable for you devs?

Separately, there are other helpers, but I think Homebrew need not check for them:
1. common ones (ssh/git/local repos) need no helper
2. HTTPS needs a helper which [is optional](https://github.com/git/git/blob/master/Makefile#L35-L37), though disabling it seems a bad idea. Should you want to support this, you could make the `remote-https` check conditional
3. stranger URLs are possible, but I've never seen them. If a user wants to use them, he should be fine with troubleshooting based on the Git error.

Orthogonally, when Homebrew shows an external command failed, it might be good to show the actual command and path (e.g. for advanced users in scenario 3), beyond mentioning Git.

**Comment by xu-cheng** [comment] 2016-05-17 08:58
@mikemcquaid My main concern is there are so many ways the git installation can be broken. So it seems unscalable to check all of them. Plus that the fact, git has already printed the necessary error message. So I would like to see more of issues report to add such check.(But sure, it can be done)

**Comment by mikemcquaid** [comment] 2016-05-17 09:13
Seems reasonable.

**Comment by UniqMartin** [comment] 2016-05-24 12:43
Closing since the original issue has been resolved and I agree that attempting to test whether `git` is broken won't scale and isn't necessary as the error message produced by `git` is pretty clear.

The only thing that looks like it could see some improvement would be to make the error summary printed by us clearer, e.g. by adding the command (with arguments) that failed to the error output, as suggested by @Blaisorblade. If anyone wants to give this a try, a PR is certainly welcome.

**Closed by UniqMartin** 2016-05-24 12:43 UTC
