### ISSUE TITLE
Using gcc45 from MATLAB: Incompatible library version

### ISSUE THREAD

**Issue by infinity277** [Homebrew/brew#148] opened 2016-04-26 00:24 UTC
Hi,

I get this error below when try to compile my code in Matlab.Why did this happen?

```
dyld: Library not loaded: /usr/local/opt/mpfr2/lib/libmpfr.1.dylib
  Referenced from: /usr/local/Cellar/gcc45/4.5.4/libexec/gcc/x86_64-apple-darwin13.4.0/4.5.4/cc1plus
  Reason: Incompatible library version: cc1plus requires version 4.0.0 or later, but libmpfr.1.dylib provides version 3.0.0
g++: Internal error: Trace/BPT trap: 5 (program cc1plus)
```

**Comment by apjanke** [comment] 2016-04-26 00:38
Sounds like a mismatch between the dylib in the `mpfr2` that `gcc45` was built against, and the current installation of `gcc45`.

I did a fresh installation of `gcc45

**Comment by infinity277** [comment] 2016-04-26 00:55
Hi,

I try to reinstall mpfr2 gcc45 but the error still appear in Matlab.
This appeared when I typed try brew info mpfr2

homebrew/versions/mpfr2: stable 2.4.2 (bottled) [keg-only]
Multiple-precision floating-point computations C lib
http://www.mpfr.org/
/usr/local/Cellar/mpfr2/2.4.2 (24 files, 2.7M)
  Poured from bottle
From: https://github.com/Homebrew/homebrew-versions/blob/master/mpfr2.rb
==> Dependencies
Required: gmp4 ✔
==> Options
--with-32-bit
	
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with mpfr in main repository.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/mpfr2/lib
    CPPFLAGS: -I/usr/local/opt/mpfr2/include

**Comment by apjanke** [comment] 2016-04-26 01:10
What are you doing in Matlab that ends up calling this? I have a Matlab license, so I may be able to reproduce it, if you can supply enough details.

Could you also post the output of `brew config` and `brew doctor`?

**Comment by infinity277** [comment] 2016-04-26 01:27
I try to compile SPArse Modeling Software(http://spams-devel.gforge.inria.fr/downloads.html) in Matlab.

brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: df489cfde25b9ea59fdf12c67876a18c13dde4aa
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2443bf529cd1612a8fc51729c603660139262bdd
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.9.5-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-462
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

brew doctor
Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.

You should probably `sudo chown -R $(whoami)` them:
    /usr/local/share/man/de
    /usr/local/share/man/de/man1

**Comment by UniqMartin** [comment] 2016-04-27 12:30
What version of MATLAB are you using? You're most likely running into this issue because MATLAB is bundling its own version of `libmpfr` and that version gets precedence. You either need to build outside of MATLAB or (preferably) use Clang as that's the only officially supported compiler for MATLAB on OS X.

**Comment by infinity277** [comment] 2016-04-28 04:22
I used Matlab 2013a(version 8.1.0.064)

**Comment by UniqMartin** [comment] 2016-04-28 14:55
MATLAB R2013a internally uses a shell script to set up its environment before it starts the graphical user interface. One of the environment variables being set is `DYLD_LIBRARY_PATH` and one of the paths contained in this variable is `/Applications/MATLAB_R2013a.app/bin/maci64`. This directory contains an older version of `libmpfr.1.dylib`. Because `DYLD_LIBRARY_PATH` takes precedence above the paths recorded inside a binary like `cc1plus`, it tries to load the library that is part of MATLAB (because it has the same file name) instead of the one installed by Homebrew. You can check the contents of that environment variable from within MATLAB:

```matlab
getenv('DYLD_LIBRARY_PATH')
```

That's an issue specific to MATLAB and unfortunately there's nothing Homebrew can do about this. I'd strongly suggest to use Clang (as that's the only officially supported compiler by MathWorks on OS X). If that's not possible, because you need OpenMP and/or FORTRAN support, you can try building outside of MATLAB or you can try resetting `DYLD_LIBRARY_PATH` from withing MATLAB by running

```matlab
setenv('DYLD_LIBRARY_PATH', '')
```

before trying to use `gcc45`. Hopefully one of those ideas works for you. Good luck!

Closing, as this is not an issue with Homebrew.

**Closed by UniqMartin** 2016-04-28 14:55 UTC
