### ISSUE TITLE
Parallels Desktop creates a file called prlexec.8

### ISSUE THREAD

**Issue by KMamedoff** [Homebrew/brew#1741] opened 2016-12-28 15:22 UTC
Everytime I start Parallels it creates a file named "prlexec.8" in "/usr/local/share/man/man8/" directory. It causes an issue with Homebrew. "brew doctor" command says "Broken symlinks were found. Remove them with `brew prune`: /usr/local/share/man/man8/prlexec.8". It goes away after executing "brew prune" command but it happens again after using Parallels.

**Comment by MikeMcQuaid** [comment] 2016-12-28 17:57
If Parallels is creating a broken symlink then that's an issue with parallels. Closing as a duplicate of https://github.com/Homebrew/brew/issues/1566; please don't recreate closed issues like that, thanks.

**Closed by MikeMcQuaid** 2016-12-28 17:57 UTC
