### ISSUE TITLE
Anything poured from bottle reinstalls from source with the `--build-bottle` flag.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#3047] opened 2017-08-12 04:33 UTC
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
~> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Ruby version 2.3.3 is unsupported on 10.13. Homebrew
is developed and tested on Ruby 2.0, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.

~> brew config
HOMEBREW_VERSION: 1.3.1-27-gd6d681c
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d6d681ca01f8acf6b8d5e66cc1ca67310e9b8913
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 826a1ddfc5401ae94ada11ba697e4df3707992a8
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.1 => /usr/local/opt/git/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.4.1/bin/ruby
Java: 1.8.0_141
macOS: 10.13-x86_64
Xcode: 9.0 => /Applications/Xcode-beta.app/Contents/Developer
CLT: 9.0.0.0.1.1501856957
X11: N/A
```

This seems to be the same issue as with `wxmac` the other day: https://github.com/Homebrew/homebrew-core/pull/16178#issuecomment-320295292, except it can be reproduced across multiple formulae now I've had the time to actually look at it a bit more.

```
~> cat /usr/local/Cellar/apr/1.6.2/INSTALL_RECEIPT.json
{"homebrew_version":"1.2.3-71-g13576111e","used_options":[],"unused_options":[],"built_as_bottle":true,"poured_from_bottle":true,"installed_as_dependency":null,"installed_on_request":null,"changed_files":["libexec/bin/apr-1-config","libexec/build-1/libtool","INSTALL_RECEIPT.json","libexec/build-1/apr_rules.mk","libexec/build-1/find_apr.m4","libexec/lib/libapr-1.la","libexec/lib/pkgconfig/apr-1.pc"],"time":1498593608,"source_modified_time":1497012981,"HEAD":null,"stdlib":null,"compiler":"clang","runtime_dependencies":[],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apr.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"1.6.2","devel":null,"head":null,"version_scheme":0}}}%
```

```
~> brew reinstall apr -v
==> Reinstalling apr
/usr/bin/sandbox-exec -f /tmp/homebrew20170812-41614-1gojrls.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apr.rb --build-bottle --verbose
```

```
==> Cleaning
==> Finishing up
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall apr`
```

And that persists until you `brew rm apr && brew install apr -s -v`. If you pour a bottle and then `brew reinstall` that formula, even when specifically telling `brew` to build from source rather than use the bottle this time, `--build-bottle` is passed onto the build.

Reproduces with multiple formulae, just using `apr` as an example here because it builds quickly 😄.

**Comment by MikeMcQuaid** [comment] 2017-08-12 12:03
This isn't quite accurate; it's related to you being on High Sierra and bottles not being available there. If you `brew reinstall --force-bottle` or modify the `apr` bottle to be `sierra_or_later` you won't reproduce this. Honestly, I'm not sure this is the wrong behaviour?

**Comment by DomT4** [comment] 2017-08-12 13:28
I presumed but hadn't confirmed myself it was somewhat High Sierra related but it still doesn't _smell_ like the right behaviour to me. I'm happy to defer to you on this since you wrote the code involved heh, but it feels a little peculiar to me that `--build-bottle` is "sticky".

It feels like bad UX to `reinstall` something previously poured from bottle & the assumption be that I'm trying to build another bottle, especially since we don't run `postinstall` for anything built intending to be a bottle & if you're reinstalling multiple things at once those messages are easy to miss.

To me `--build-bottle` is an internal flag in much the same way as `--build-from-source` is and I wouldn't expect the latter to be respected across `reinstall` unless I explicitly asked it to be. Indeed, if I'd previously installed `gcc` from source & I executed `reinstall` on the formula when it has a High Sierra bottle available and it proceeds to build from source again I'd probably cry for my CPU a little bit 😸.

**Comment by MikeMcQuaid** [comment] 2017-08-12 13:54
> I'm happy to defer to you on this since you wrote the code involved heh, but it feels a little peculiar to me that --build-bottle is "sticky".

It's sticky only if there's no bottle available, if that changes anything.

**Comment by DomT4** [comment] 2017-08-13 02:21
I'm unsure it's desirable but I'm happy to defer to you. If you're cool with the existing behaviour I can learn to remember to use `rm && install` rather than `reinstall` for the time being.

It's not an enormous problem or anything. Just made sense to me to check in as to whether it was an intentional design choice & one folks are happy with.

**Comment by MikeMcQuaid** [comment] 2017-08-13 09:25
@DomT4 What are the series of commands you're running to reproduce this?

**Comment by DomT4** [comment] 2017-08-13 13:11
If you want a full reproduction:
```
~> brew install apr --force-bottle
~> brew reinstall apr
```
should do the trick. I always pass the `-v` flag but I doubt verbosity is having any effect here.

**Comment by MikeMcQuaid** [comment] 2017-08-13 14:36
It seems like the correct behaviour that `--force-bottle` is not sticky to me but: I dunno. I'm closing this not because it's perfect but because I'm not sure what a better version would be. A PR might be the best place to talk about this but feel free to not make one. Thanks for the clear reproduction 👍

**Closed by MikeMcQuaid** 2017-08-13 14:36 UTC

**Comment by DomT4** [comment] 2017-08-13 14:54
> I'm closing this not because it's perfect but because I'm not sure what a better version would be.

Aye, to be fair I'm not sure quite where to move with this either. In some situations the status quo seems perfectly desirable, and it shouldn't impact most users unless that formula is lacking a bottle for that version of macOS as you said. I don't know. I'll think about it a bit, maybe I'll stumble onto something tossing ideas around my mind 😄.

**Comment by ilovezfs** [comment] 2017-08-13 20:15
If we're rebuilding and slipping in `--build-bottle`, doesn't that mean postinstall will be skipped? :bug:

**Comment by DomT4** [comment] 2017-08-13 20:33
Yes.

```
~> rm -rf /usr/local/etc/openssl
~> brew reinstall openssl -v
==> Reinstalling openssl
/usr/bin/sandbox-exec -f /tmp/homebrew20170813-22642-1v5bf0r.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb --build-bottle --verbose

[snip]
==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2l: 1,720 files, 19.8MB, built in 4 minutes 58 seconds

==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall openssl`

~> openssl s_client -connect duckduckgo.com:443
Verify return code: 20 (unable to get local issuer certificate)
```

**Comment by ilovezfs** [comment] 2017-08-13 20:36
At least it prints the message telling you what to do, I guess.

Can you reproduce the issue in a case where `--force-bottle` has not been used?

**Comment by DomT4** [comment] 2017-08-13 20:38
If a bottle has been previously installed, aye. But bear in mind all of my bottles would have been installed on Sierra given none officially exist for High Sierra yet, although I could lie about that locally easily enough to test. Give me a minute.

**Comment by DomT4** [comment] 2017-08-13 20:47
```
~> brew install apr --build-bottle

~> brew bottle apr
==> Determining apr bottle rebuild...
==> Bottling apr-1.6.2.high_sierra.bottle.1.tar.gz...
==> Detecting if apr-1.6.2.high_sierra.bottle.1.tar.gz is relocatable...
./apr-1.6.2.high_sierra.bottle.1.tar.gz
  bottle do
    cellar :any
    rebuild 1
    sha256 "efe1bc268055a14e8ee58b61462b1d95aeb0161ef36313281fe05d634937afa1" => :high_sierra
  end

~> brew reinstall apr -v
==> Downloading https://homebrew.bintray.com/bottles/apr-1.6.2.high_sierra.bottle.1.tar.gz
Already downloaded: /usr/local/var/homebrewcache/apr-1.6.2.high_sierra.bottle.1.tar.gz
==> Verifying apr-1.6.2.high_sierra.bottle.1.tar.gz checksum
==> Pouring apr-1.6.2.high_sierra.bottle.1.tar.gz
tar xzf /usr/local/var/homebrewcache/apr-1.6.2.high_sierra.bottle.1.tar.gz
==> Finishing up
/usr/bin/sandbox-exec -f /tmp/homebrew20170813-99590-wwkw3x.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apr.rb -v
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because Apple's CLT package contains apr.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/apr/bin:$PATH"' >> ~/.zshrc

==> Summary
🍺  /usr/local/Cellar/apr/1.6.2: 68 files, 3.2MB

~> brew reinstall apr -v -s
==> Reinstalling apr
/usr/bin/sandbox-exec -f /tmp/homebrew20170813-99814-bb01vz.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apr.rb --verbose
==> Downloading https://www.apache.org/dyn/closer.cgi?path=apr/apr-1.6.2.tar.bz2
```

So yeah, Mike was correct that the behaviour only reproduces where a bottle doesn't exist for that version of macOS.
