### ISSUE TITLE
brew list --cask outputting uninstalled casks 

### ISSUE THREAD

**Issue by jweyer8** [Homebrew/brew#13150] opened 2022-04-15 16:06 UTC
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 56415326bb8c9eccc6e53f3997b4e062b36402af
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: afa4538954ae879c2071d3a16c67600b174d5f32
Core tap last commit: 45 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: 16-core 64-bit ivybridge
Clang: 12.0.0 build 1200
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### `brew doctor` output

```shell
Warning: The following directories are not writable by your user:
/usr/local/share/man/man8

You should change the ownership of these directories to your user.
  sudo chown -R $(whoami) /usr/local/share/man/man8

And make sure that your user has write permission.
  chmod u+w /usr/local/share/man/man8

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/share/man/man8/prl_convert.8
  /usr/local/share/man/man8/prl_disk_tool.8
  /usr/local/share/man/man8/prlctl.8
  /usr/local/share/man/man8/prlexec.8
  /usr/local/share/man/man8/prlsrvctl.8
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to get a list of installed casks to determine if I need to install the casks or not. Chef.io is also using `brew list --cask` for this reason, as you can see [here](https://github.com/chef/chef/blob/7a3bfd077fe852e68439ecd2fe0ed480168a2d6b/lib/chef/resource/homebrew_cask.rb#L100).

### What happened (include all command output)?

As shown by the output below, `brew list --cask` outputs parallels; however, when `brew info parallels` is run it shows that parallels is not actually installed:

`brew list --cask`
parallels parallels-virtualization-sdk vagrant

`brew info parallels`
parallels: 17.1.2-51548 (auto_updates)
https://www.parallels.com/products/desktop/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/parallels.rb
==> Name
Parallels Desktop
==> Description
Desktop virtualization software
==> Artifacts
Parallels Desktop.app (App)
==> Analytics
install: 950 (30 days), 2,572 (90 days), 9,011 (365 days)

### What did you expect to happen?

the 'parallels' cask should not be included in the output of `brew list --cask` as it is not installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew list --cask`
`brew info <cask>`
```

**Comment by amadejpapez** [comment] 2022-04-15 16:28
Looks like a duplicate of https://github.com/Homebrew/brew/issues/13139. The fix for it was merged 2 days ago https://github.com/Homebrew/brew/pull/13141.

**Closed** 2022-04-18 08:17 UTC
Labels: bug

**Comment by jweyer8** [comment] 2022-04-18 16:25
@amadejpapez I am still hitting the same issue after updating to 3.4.7 which contains #13141.

**Comment by EricFromCanada** [comment] 2022-04-18 16:47
What's the result of running `ls $(brew --caskroom)/parallels`? And what happens when running `brew uninstall --cask parallels`?

**Comment by jweyer8** [comment] 2022-04-18 16:54
@EricFromCanada 

`ls -l $(brew --caskroom)/parallels` # => total 0
`brew uninstall --cask parallels` # => Error: Cask 'parallels' is not installed.

**Comment by EricFromCanada** [comment] 2022-04-18 17:20
Running `brew list` or `brew list --cask` simply [passes the Cellar or Caskroom path to `ls`](https://github.com/Homebrew/brew/blob/8a7f082b30832abee01abf1b016dd0773a958e10/Library/Homebrew/cmd/list.rb#L121). It appears the "parallels" folder wasn't removed from your Caskroom path when the cask was uninstalled, which is why it was listed. In my testing, though, running `brew uninstall --cask parallels` after installing removed the folder properly, so some other issue must be involved.

**Comment by jweyer8** [comment] 2022-04-18 18:00
@EricFromCanada 

Yeah, it looks like it wasn't deleted from the Caskroom path. I'm thinking that the issue might be related to the fact that the 'parallels' directory only contains a '.metadata' subdirectory:

```
tree -a parallels

parallels
└── .metadata
    └── config.json
```
