### ISSUE TITLE
Incorrect selection of Xcode location

### ISSUE THREAD

**Issue by AndrejSoroj** [Homebrew/brew#1587] opened 2016-11-27 19:09 UTC
After installing homebrew, it found an incorrect Xcode version and force me to update Xcode although it up-to-date.

Here is the case:
I have one drive with installed OSX 10.9 and there is XCode 5.1 here

I've installed OS 10.12 on second drive and also installed latest XCode 8.1

After installing homebrew on second drive it asking me to update XCode.

```
$ brew doctor
Warning: Your Xcode (5.1) is too outdated.
Please update to Xcode 8.1 (or delete it).
Xcode can be updated from the App Store.
```

```
$ brew config
HOMEBREW_VERSION: 1.1.1
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.1-x86_64
Xcode: 5.1 => /Volumes/MAC X 9/Applications/Xcode.app/Contents/Developer
CLT: 8.1.0.0.1.1476494586
X11: N/A
```

I've tried to unmount the first drive and then homebrew found correct Xcode, but when I mount it back Homebrew switching to wrong Xcode version from first drive.

**Comment by MikeMcQuaid** [comment] 2016-11-28 08:47
What are the full paths of both of your Xcodes? Thanks!

**Comment by AndrejSoroj** [comment] 2016-11-28 11:57
XCode 5.1 - /Volumes/MAC X 9/Applications/Xcode.app
XCode 8.1 - /Applications/Xcode.app

Don't know does it make sense or not but installing sequence was the following:
- install homebrew on just installed fresh osx 10.12.1
- homebrew asked to install CLT. I've installed it
- homebrew said that I have outdated XCode 5.1 and need update it to 8.1
- installed XCode 8.1 from App Store.
- homebrew still doesn't see XCode 8.1

**Comment by samdmarshall** [comment] 2016-11-28 12:53
It might be important to check the **xcode-select** path by running `xcode-select -p` on the terminal to see which one is taking priority on the system. That should be based on your boot disk, not any attached disk.

**Comment by MikeMcQuaid** [comment] 2016-11-28 12:54
@samdmarshall Thanks for the comment, I think we already factor this in but I'm thinking a general rule to always prioritise e.g. `/Applications` over `/Volumes` is the right thing.

**Comment by MikeMcQuaid** [comment] 2016-11-28 12:55
To be explicit: @AndrejSoroj can you paste the output of your `xcode-select -p` here? Thanks!

**Comment by AndrejSoroj** [comment] 2016-11-28 14:07
```
$ xcode-select -p
/Library/Developer/CommandLineTools
```

**Comment by MikeMcQuaid** [comment] 2016-11-29 17:16
@AndrejSoroj You should probably `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`

**Comment by ilovezfs** [comment] 2016-12-04 09:43
Isn't this a duplicate of https://github.com/Homebrew/legacy-homebrew/issues/47579 which was closed: https://github.com/Homebrew/legacy-homebrew/issues/47579#issuecomment-222317018

**Comment by MikeMcQuaid** [comment] 2016-12-04 14:19
@ilovezfs Yep, more or less. I might actually try to fix it this time, though 😉

**Comment by ilovezfs** [comment] 2016-12-04 14:26
The "broken" behavior is much more fun, though.

**Comment by samdmarshall** [comment] 2017-01-10 14:58
@MikeMcQuaid is there any development work that I could help with to move this issue along?

I also wanted to verify with you that the fix that gets implemented properly addresses this case:
If I have Xcode on my computer, but `xcode-select` is pointed to the CLT, which is a newer version than the Xcode.app, my expectations are that brew will
* use the CLT for building.
* not complain about Xcode versions being out of date.

**Closed** 2017-01-11 19:08 UTC
Labels: bug, in progress

**Comment by MikeMcQuaid** [comment] 2017-01-11 19:13
@samdmarshall I'd have loved you to help with that but I'd just finished the PR in https://github.com/Homebrew/brew/issues/1816.



> use the CLT for building.

This was already the case 👍 

> not complain about Xcode versions being out of date.

This is not the case because some buildsystems don't require Xcode but will find and use it if it's there. We no longer block installation unless Xcode is extremely outdated but we'll still warn about it (but it can be safely ignored). I appreciate the warning may be annoying but because we don't control upstream build systems we need to optimise for our own support load.

**Comment by samdmarshall** [comment] 2017-01-11 19:18
As long as they are not going to prohibit building unless the requirement is on having Xcode.app, not the CLT, then i'm ok with that. My experience was the mere act of having the older version of Xcode.app found on the system prevented *any* brew installation, regardless of requirements.

**Comment by MikeMcQuaid** [comment] 2017-01-11 19:45
That issue should be fixed now (or in the next tag, depending). If it is not, please feel free to chime in because how you describe it is how I want it to be 👍

**Comment by giovino** [comment] 2017-07-26 15:03
The brew feature to search and find Xcode.app using spotlight caused an error message and confusion. 

Scenario:

Day 1: New Mac install homebrew and many applications using brew. 
Day 5: Move a usb drive with Time Machine backups from the old machine to the new machine.
Day 6: brew update reports xcode is out of date.

With a few hours of research[1], I understand how and why brew has discovered a new (old) version of xcode. 

```
brew config
...
Xcode: /Volumes/USB Drive/Backups.backupdb/MBP/2015-12-29-003755/Macintosh HD/Applications/Xcode.app/Contents/Developer
CLT: 8.3.2.0.1.1492020469
...
```

`/Volumes/USB Drive/Backups.backupdb/` is a time machine backup from another machine. In this case it would have been nice for brew to not pull Xcode.app locations out of the time machine backup.  

Thanks for all the hard work the brew team puts it, it is _very_ appreciated. 

[1] (https://github.com/Homebrew/brew/issues/1587 https://github.com/Homebrew/legacy-homebrew/issues/47579 https://github.com/Homebrew/legacy-homebrew/pull/47752)

**Comment by MikeMcQuaid** [comment] 2017-07-27 14:30
@giovino We'll consider rejecting Xcodes from the backup directory. In future please don't comment on closed issues with your own take, thanks.
