### ISSUE TITLE
[search] results no longer include casks

### ISSUE THREAD

**Issue by rprimus** [Homebrew/brew#655] opened 2016-08-07 13:49 UTC
Sun Aug  7 14:49:44 BST 2016

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

brew search is ignoring casks

Info:
```
ProductName:   	Mac OS X
ProductVersion:	10.11.6
BuildVersion:  	15G31

 % brew --version
Homebrew 0.9.9 (git revision b8ce1; last commit 2016-08-06)
Homebrew/homebrew-core (git revision 0107c; last commit 2016-08-07)

rprimus@mbp /usr/local/Cellar/ruby/2.3.1
 % brew cask --version
0.60.0 (git revision c26c2; last commit 45 minutes ago)
```

```
% mdfind -name lunchy
/usr/local/Cellar/zsh-completions/0.19.0/share/zsh-completions/_lunchy
/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/lunchy.rb

rprimus@mbp /usr/local/Cellar/ruby/2.3.1
 % brew search lunchy
No formula found for "lunchy".
==> Searching pull requests...

rprimus@mbp /usr/local/Cellar/ruby/2.3.1
 % brew cask search lunchy
==> Exact match
lunchy
```

### Previously,  ```brew search``` results included casks as well as other taps (even if not installed).
It appears that ```casks``` are not being included:

```
 % brew search ssh
assh                         gssh                         homebrew/php/php54-ssh2      libssh                       pssh                         sshrc                        tmux-cssh
autossh                      homebrew/dupes/openssh ✔     homebrew/php/php55-ssh2      libssh2 ✔                    rssh                         sshtrix                      vassh
csshx                        homebrew/fuse/sshfs ✔        homebrew/php/php56-ssh2      mpssh                        ssh-copy-id                  sshuttle                     zssh
git-ssh                      homebrew/php/php53-ssh2      homebrew/php/php70-ssh2      mussh                        sshguard                     stormssh ✔
homebrew/completions/stormssh-completion                                                             Caskroom/versions/ssh-tunnel-manager-beta

rprimus@mbp /usr/local/Cellar/ruby/2.3.1
 % brew cask search ssh
==> Partial matches
bassshapes     	    ssh-tunnel-manager 	sshfs

rprimus@mbp /usr/local/Cellar/ruby/2.3.1
 % brew search sshfs
homebrew/fuse/sshfs ✔
```

**Comment by ilovezfs** [comment] 2016-08-07 14:02
Your output actually does show casks in the results:
```
Caskroom/versions/ssh-tunnel-manager-beta
```

I think this is a duplicate of https://github.com/Homebrew/brew/issues/415.

**Comment by ilovezfs** [comment] 2016-08-07 14:15
Actually, no, you're right. It's just that they're two entirely separate commands:

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/search.rb

https://github.com/caskroom/homebrew-cask/blob/master/lib/hbc/cli/search.rb

**Comment by ilovezfs** [comment] 2016-08-07 14:30
@rprimus yeah this looks like a bug. Do you mind trying this diff
```
Josephs-MacBook-Pro:local joe$ git diff
diff --git a/Library/Homebrew/cmd/search.rb b/Library/Homebrew/cmd/search.rb
index 9574ba7..cfcf38a 100644
--- a/Library/Homebrew/cmd/search.rb
+++ b/Library/Homebrew/cmd/search.rb
@@ -143,7 +143,11 @@ module Homebrew
         end
       end
 
-      paths = tree["Formula"] || tree["HomebrewFormula"] || tree["Casks"] || tree["."] || []
+      paths = []
+      paths += tree["Formula"] if tree["Formula"]
+      paths += tree["HomebrewFormula"] if tree["HomebrewFormula"]
+      paths += tree["Casks"] if tree["Casks"]
+      paths += tree["."] if tree["."]
       cache[key] = paths.map { |path| File.basename(path, ".rb") }
     end
```
It seems to reveal the problem :)

**Comment by UniqMartin** [comment] 2016-08-07 14:39
Indeed, the problem is relatively new as it's not too long ago that the legacy `brew-cask` formula in homebrew/cask has been moved to the `Formula/` directory. I guess a simpler fix would be the following (and it stays true to our assumption that there's always only one formula directory in a tap), though I'm not sure the code that uses this is prepared to deal with multiple trees.

```ruby
paths = tree["Formula"] || tree["HomebrewFormula"] || tree["."] || []
paths += tree["Casks"] || []
```

homebrew/cask is a bit of a special case here as it contains both a formula and casks.

**Comment by UniqMartin** [comment] 2016-08-07 14:40
@ilovezfs Nice and spot-on diagnosis by the way! :+1:

**Comment by ilovezfs** [comment] 2016-08-07 14:40
@UniqMartin I think we want
```
      paths = [
        tree["Formula"],
        tree["HomebrewFormula"],
        tree["Casks"],
        tree["."],
      ].compact.reduce([], :|)
```

**Comment by rprimus** [comment] 2016-08-07 14:43
Sun Aug  7 15:42:54 BST 2016

@ilovezfs your original code returned the original behaviour:

```
:!brew search sshfs
homebrew/fuse/sshfs ✔
Caskroom/cask/sshfs
```

**Comment by ilovezfs** [comment] 2016-08-07 14:45
@rprimus cool. second version also gets same results
```
Josephs-MacBook-Pro:local joe$ brew search sshfs
homebrew/fuse/sshfs
Caskroom/cask/sshfs
```

**Comment by ilovezfs** [comment] 2016-08-07 14:52
@UniqMartin yup
```
paths = tree["Formula"] || tree["HomebrewFormula"] || tree["."] || []
paths += tree["Casks"] || []
```
works too, of course.

>homebrew/cask is a bit of a special case here as it contains both a formula and casks.

That sounds like a "bug" to me. Perhaps they can separate them "appropriately."

**Comment by ilovezfs** [comment] 2016-08-07 15:03
@UniqMartin I think your code might have trouble in the case of casks at the root + a Formula directory, whereas it would not have trouble with formulae at the root plus a Cask directory, which seems like a slightly odd asymmetry. Neither is probably a configuration we'd want to support, so seems possibly undesirable to "accidentally" support one.

**Comment by UniqMartin** [comment] 2016-08-07 15:08
> I think we want […]

Nope, see [`Tap#formula_dir`](https://github.com/Homebrew/brew/blob/b8ce1fe1b2abfc6b38a6c6451ef8074f2a83a8eb/Library/Homebrew/tap.rb#L304-L306) where we pick exactly one directory where we look for formulae. This search code needs to be consistent with that.

> I think your code might have trouble in the case of casks at the root + a Formula directory, whereas it would not have trouble with formulae at the root plus a Cask directory, which seems like a slightly odd asymmetry.

This asymmetry can be easily explained. As far as I'm aware, casks were always stored in `Casks/` directory and never anywhere else, so that's the only location inspect for casks. The other three locations are (partially for historical reasons) all valid candidates for then picking the one true formula directory …

**Comment by ilovezfs** [comment] 2016-08-07 15:12
>Nope, see Tap#formula_dir where we pick exactly one directory where we look for formulae. This search code needs to be consistent with that.

Ah OK, so throwing the Cask tree in as well doesn't break that assumption since the casks are not True Formulae?

**Comment by UniqMartin** [comment] 2016-08-07 15:22
> Ah OK, so throwing the Cask tree in as well doesn't break that assumption since the casks are not True Formulae?

Correct. Though if anyone asked me, the Cask support in `brew search` (that only includes caskroom/cask and caskroom/versions and always searches the GitHub repository, no matter what is installed locally or not) feels a bit tucked on. It just never bothered me enough as I'm not a Cask user and maybe we can get this fixed with the progressing integration …

(Just noticed: I wrote homebrew/cask before but I obviously meant to write caskroom/cask.)

**Comment by ilovezfs** [comment] 2016-08-07 15:46
@UniqMartin yeah I agree. It feels very intrusive to return cask results when caskroom/cask isn't even tapped, especially with no way to suppress it.

**Closed** 2016-08-08 09:55 UTC
Labels: bug, in progress
