### ISSUE TITLE
Add HTTPS support to http://brew.sh

### ISSUE THREAD

**Issue by tennysonholloway** [Homebrew/brew#824] opened 2016-08-26 23:26 UTC
The main website, http://brew.sh, does not support HTTPS connections. This issue was reported in #490 but nothing was done. This is unacceptable, considering there are multiple free solutions to enable HTTPS on the website.

Having a HTTPS website is critically important for many reasons, including but not limited to
* Distributing installation instructions that cannot be easily modified by adversaries (especially when the installation instructions are not a binary, but rather plain-text instructions to pipe to bash)
* Being a responsible website operator in 2016
* Not being "shamed" in search results: https://motherboard.vice.com/read/google-will-soon-shame-all-websites-that-are-unencrypted-chrome-https 
* Conveying competency and responsibility in security practices to your users.

A very easy, free solution to enable HTTPS on the website, is to use cloudflare in combination with github pages. See this blog post for instructions: https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

A very easy, and perhaps better solution, is to host the website elsewhere, and use a free certificate from https://letsencrypt.org/

Thanks!

**Comment by tdsmith** [comment] 2016-08-26 23:40
Closing as a duplicate of https://github.com/Homebrew/homebrew.github.io/issues/98; thanks for the nudge.

**Closed by tdsmith** 2016-08-26 23:40 UTC

**Comment by DomT4** [comment] 2016-08-27 00:38
As I noted before in the Issue Tim linked: https://github.com/Homebrew/homebrew.github.io/issues/98#issuecomment-230172239. Because things do not appear to be happening doesn't mean they aren't. Please try to be a little understanding of that without the subtle digs at us, Thanks.
