### ISSUE TITLE
burp-suite `can’t be opened because Apple cannot check it for malicious software`

### ISSUE THREAD

**Issue by epelc** [Homebrew/brew#7009] opened 2020-02-06 01:53 UTC
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install `burp-suite` cask

## What happened (include command output)
You get this popup and these errors in your terminal

![image](https://user-images.githubusercontent.com/5204642/73899009-44b19780-4859-11ea-8e7d-b1317808c68f.png)

<details>
  <summary>Command output</summary>
  <pre>

brew cask install burp-suite 
==> Downloading https://portswigger.net/burp/releases/download?product=community&version=2020.1&type=MacOsx
Already downloaded: /Users/ed/Library/Caches/Homebrew/downloads/d88b0ad73ccb6798f8ace6e161bbfceedef57936a7a551ead58955d562739a64--burpsuite_community_macos_v2020_1.dmg
==> Verifying SHA-256 checksum for Cask 'burp-suite'.
==> Installing Cask burp-suite
==> Running installer script 'Burp Suite Community Edition Installer.app/Contents/MacOS/JavaApplicationStub'
==> Purging files for version 2020.1 of Cask burp-suite
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/burp-suite/2020.1/Burp\ Suite\ Community\ Edition\ Installer.app/Contents/MacOS/JavaApplicationStub -q` exited with .
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew` commands)
`brew cask install burp-suite` should install burp suite

## Output of `brew config` and `brew doctor` commands

<pre>
brew config
HOMEBREW_VERSION: 2.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b5ce2d4f171f4ac2260e57bd51a8b3e1769c8b36
Core tap last commit: 80 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
bCurl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_131
macOS: 10.15.2-x86_64
CLT: 11.0.33.16
Xcode: 11.3.1
reXQuartz: 2.7.11 => /opt/X11
ed@ibeast2go dotfiles % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
</pre>

**Comment by issyl0** [comment] 2020-02-06 10:51
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/75296. On that issue, cask maintainers determined this not to be an issue with Homebrew Cask.

**Closed by issyl0** 2020-02-06 10:51 UTC

**Comment by MikeMcQuaid** [comment] 2020-02-06 13:40
> Install `burp-suite` cask

Please read the issue template in future and file this on the correct repository.
