### ISSUE TITLE
`Dependency.expand` tags dependencies incorrectly

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#15045] opened 2023-03-23 19:58 UTC
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.9-48-g78feddc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 78feddce94e5c5abe2e9c9ab764f766a87fa9a41
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e9d6b4aa122c2b9f11d3b7ae56966f21409a742b
Core tap last commit: 45 minutes ago
Core tap branch: master
Core tap JSON: 19 Mar 19:56 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dual-core 64-bit skylake
Clang: 15.0.7
Git: 2.39.2 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.4.0-1104-azure x86_64 GNU/Linux
OS: Ubuntu 22.04.2 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

Use `Dependency.expand` to calculate the recursive dependencies of `aravis`.

I wanted to see why it was being tested as a dependent in Homebrew/homebrew-core#126416 even though it only has a `:build` dependency on `gobject-introspection`.

### What happened (include all command output)?

In `brew irb`, run
```ruby
Dependency.expand(:aravis.f) do |_, dependency|
  Dependency.keep_but_prune_recursive_deps if dependency.build? && !dependency.test?
end
```
This produces:
```
=> [#<Dependency: "xz" [:test]>, #<Dependency: "gobject-introspection" []>, #<Dependency: "gtk-doc" [:build]>, #<Dependency: "meson" [:build]>, #<Dependency: "ninja" [:build]>, #<Dependency: "pkg-config" [:test]>, #<Dependency: "gettext" []>, #<Dependency: "gtk+3" []>, #<Dependency: "intltool" []>, 
[snip]
```
We can see that `gobject-introspection` is not tagged as a `:build` dependency, when [it should be](https://github.com/Homebrew/homebrew-core/blob/e9d6b4aa122c2b9f11d3b7ae56966f21409a742b/Formula/aravis.rb#L18).

### What did you expect to happen?

`gobject-introspection` should be tagged as a build dependency of `aravis`.

This is important in `test-bot`, where we use the [output of `Dependency.expand`](https://github.com/Homebrew/homebrew-test-bot/blob/184728e746793f83e54d9a19681dad15bed42091/lib/tests/formulae_dependents.rb#L107-L109) to find the [runtime dependents of a formula](https://github.com/Homebrew/homebrew-test-bot/blob/184728e746793f83e54d9a19681dad15bed42091/lib/tests/formulae_dependents.rb#L134-L138).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above.
```

**Comment by issyl0** [comment] 2023-03-23 22:56
I don't know what the problem is, but adding the following debugging output and running the sample command is potentially enlightening? It reveals a bunch of `gobject_introspection` deps that oscillate between `[]` and `[:build]` in `merge_temporality`?

```diff
diff --git a/Library/Homebrew/dependency.rb b/Library/Homebrew/dependency.rb
index 15ea12ecb..104bfdde0 100644
--- a/Library/Homebrew/dependency.rb
+++ b/Library/Homebrew/dependency.rb
@@ -177,6 +177,11 @@ class Dependency
     def merge_tags(deps)
       other_tags = deps.flat_map(&:option_tags).uniq
       other_tags << :test if deps.flat_map(&:tags).include?(:test)
+      if deps.map(&:name).include?("gobject-introspection")
+        puts "merge_tags: #{deps.map(&:name).join(", ")}"
+        puts "merge_necessity: #{merge_necessity(deps)}"
+        puts "merge_temporality: #{merge_temporality(deps)}"
+      end
       merge_necessity(deps) + merge_temporality(deps) + other_tags
     end
```

**Comment by carlocab** [comment] 2023-03-23 23:35
Hmmm, yes. New theory: `Dependency.expand` is behaving correctly, we're just using it wrong.

I think what is happening is that `aravis` has a build dependency on a formula that has a runtime dependency on `gobject-introspection`.

**Comment by Rylan12** [comment] 2023-03-24 02:39
Here's the dependency tree that's causing this:

```
aravis
├── gtk+3
│   ├── pango
│   │   ├── harfbuzz
│   │   │   ├── pygobject3  [test]
│   │   │   │   └── gobject-introspection
...
```

**Comment by Bo98** [comment] 2023-03-24 04:08
Yeah this is a test-bot problem.

There's perhaps an argument whether the tags should recurse, but we don't do anything to test dependencies anyway in test-bot and that would need adjusting regardless.

**Comment by MikeMcQuaid** [comment] 2023-03-24 08:51
> Hmmm, yes. New theory: `Dependency.expand` is behaving correctly, we're just using it wrong.

> At the end, `merge_temporality` only returns `:build` if all occurrences of the dependency are `:build`.

Given these: not convinced this is a Homebrew/brew issue at all. Closing out here but feel free to open and move to test-bot if desired.

I guess I would note that this is the sort of bug that will just sit open forever unless one of the folks who cares about it here opens a PR. I'm increasingly less convinced of the merit of having these sort of "only affects maintainers" issues open.

**Closed by MikeMcQuaid** 2023-03-24 08:51 UTC
Labels: bug

**Comment by carlocab** [comment] 2023-03-24 10:25
I don't know, there's still something off about the behaviour of `Dependency.expand`. It seems to ignore the path to a dependency and only considers the final tag.

Consider `cargo-bundle`, whose only dependency line is
```ruby
depends_on "rust" => [:build, :test]
```
(i.e. there are no other dependencies)

Running
```ruby
Dependency.expand("cargo-bundle".f) do |_, dependency|
  Dependency.keep_but_prune_recursive_deps if dependency.build? && !dependency.test?
end
```
produces
```
=> [#<Dependency: "cmake" [:build]>,
 #<Dependency: "ninja" [:build]>,
 #<Dependency: "python@3.11" [:build]>,
 #<Dependency: "ca-certificates" []>,
 #<Dependency: "openssl@3" []>,
 #<Dependency: "pkg-config" []>,
 #<Dependency: "rust" [:build, :test]>]
```
`rust` is tagged correctly as `[:build, :test]`, but why don't `ca-certificates`, `openssl@3`, and `pkg-config` inherit the `:test` tag from `rust`? `cmake` and `ninja` look suspicious as well, but that seems to be a product of the way we chose to expand dependencies.

**Comment by MikeMcQuaid** [comment] 2023-03-24 10:31
@carlocab This is essentially a private API. If it's not working as expected: it's 99% that it's not being called as expected. `brew test-bot` makes use of these sort of private APIs for performance/flexibility reasons. Perhaps it should not. I'm dubious that this is something that needs fixed in Homebrew/brew rather than the code adjusted in Homebrew/homebrew-test-bot.

I will agree that this API is unintuitive but, at this point, changing it is far more likely to break things for actual Homebrew users.

**Comment by Rylan12** [comment] 2023-03-24 15:07
> `rust` is tagged correctly as `[:build, :test]`, but why don't `ca-certificates`, `openssl@3`, and `pkg-config` inherit the `:test` tag from `rust`? `cmake` and `ninja` look suspicious as well, but that seems to be a product of the way we chose to expand dependencies.

This is just not part of the functionality of `Dependency.expand` since it does not have any logic that causes tags to recurse. So there's no attempt at inheriting the `:test` tag. `cmake` and `ninja` are build dependencies of `rust` so they show up as `:build`. `openssl@3` and `pkg-config` are runtime deps (and `ca-certificates` is a runtime dep of `openssl@3`) so they all show up as runtime deps.

**Comment by carlocab** [comment] 2023-03-25 04:41
> This is just not part of the functionality of `Dependency.expand` since it does not have any logic that causes tags to recurse.

Yes, my point is that anywhere we want to use `Dependency.expand`, the tags should recurse. `Dependency.expand` is used to expand the dependency tree of the formula given as an argument. If the tags do not recurse, then you have constructed that dependency tree wrongly.
