### ISSUE TITLE
brew update fails - 

### ISSUE THREAD

**Issue by bartonfriedland** [Homebrew/brew#5735] opened 2019-02-14 13:57 UTC
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)
I was trying to update brew

# What happened (include command output)

ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-binary failed!

# What you expected to happen

I expected brew to run without errors.

# Step-by-step reproduction instructions (by running `brew` commands)

This morning when I ran brew update I received an error "Could could not read Username for 'https://github.com': terminal prompts disabled" and found this web page (https://jacopretorius.net/2018/05/git-error-could-not-read-username.html) & followed gitconfig instructions to enable SSH.

Now when I run brew update I get the error above. Explicit brew install and doctor commands work without issue.

**Comment by sgsunder** [comment] 2019-02-14 15:40
I'm having the same problem.

From my investigation, it looks like these repositories were either moved, set private, or straight up deleted:

- https://github.com/Homebrew/homebrew-x11
- https://github.com/Homebrew/homebrew-boneyard
- https://github.com/Homebrew/homebrew-tex
- https://github.com/Homebrew/homebrew-fuse
- https://github.com/Homebrew/homebrew-binary

which is causing the problem to begin with.

**Comment by bestlong** [comment] 2019-02-14 15:59
my fix step:
```
~$ brew update
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard failed!
~$ brew tap
Updating Homebrew...
aspnet/dnx
atlassian/tap
drone/drone
homebrew/boneyard
homebrew/cask
homebrew/core
homebrew/dupes
homebrew/php
homebrew/python
homebrew/science
homebrew/services
homebrew/versions
~$ brew untap homebrew/boneyard
Untapping homebrew/boneyard...
Untapped (96 files, 414.4KB).
~$ brew update
Already up-to-date.
~$
```

**Comment by thoha** [comment] 2019-02-14 15:59
I had a different but probably related problem (that also broke my Homebrew): When I tried to update Homebrew it went into an infinite loop during which nothing seemed to happen. 

When I now run brew update it says it's already up to date, except that it cannot find the command line tools (that are actually installed and that worked until the failed update). I tried reverting Homebrew to the previous version, and that fails too.

Running brew doctor gives two warnings:
"Xcode alone is not sufficient on Dunno." (because it can't find the command line tools)
and:
"Homebrew's sbin was not found in your PATH but you have installed formulae that put executables in /usr/local/sbin."
Executing the command given after the last warning does nothing.

**Comment by thoha** [comment] 2019-02-14 16:20
Okay, editing my bash profile manually fixed the second error and replaced it by a new one (invalid macOS version).

**Comment by brianeclow** [comment] 2019-02-14 16:21
Also missing is https://github.com/Homebrew/homebrew-completions

**Comment by MikeMcQuaid** [comment] 2019-02-14 17:19
> From my investigation, it looks like these repositories were either moved, set private, or straight up deleted:
> 
> * https://github.com/Homebrew/homebrew-x11
> * https://github.com/Homebrew/homebrew-boneyard
> * https://github.com/Homebrew/homebrew-tex
> * https://github.com/Homebrew/homebrew-fuse
> * https://github.com/Homebrew/homebrew-binary
> 
> which is causing the problem to begin with.

Yes. That's because they were all empty and have been for at least a year and in most cases over two years. They were slowing down every `brew update` checking for updates to them.

**Comment by MikeMcQuaid** [comment] 2019-02-14 17:21
Duplicate of https://github.com/Homebrew/brew/issues/5734

**Closed by MikeMcQuaid** 2019-02-14 17:21 UTC
