### ISSUE TITLE
`brew irb` errors immediately when `HOMEBREW_PRY=1`

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#14634] opened 2023-02-15 03:12 UTC
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.21-132-g724e3e6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 724e3e646abf04474b083f581a963a52e39fe47d
Last commit: 34 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0bbb89420e74756a5a5c145ed7efa4a32f7e7e7c
Core tap last commit: 2 days ago
Core tap branch: master
Core tap JSON: 15 Feb 03:07 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_PRY: set
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.39.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.4.0-1103-azure x86_64 GNU/Linux
OS: Ubuntu 22.04.1 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

Use `HOMEBREW_PRY=1 brew irb` to programmatically examine the contents of formulae.

### What happened (include all command output)?

```
linuxbrew@codespaces-07ca68:/workspaces/brew$ HOMEBREW_PRY=1 brew irb
Error: cannot load such file -- method_source
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/pry-0.14.2/lib/pry/pry_instance.rb:3:in `require'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/pry-0.14.2/lib/pry/pry_instance.rb:3:in `<top (required)>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/pry-0.14.2/lib/pry.rb:61:in `require'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/pry-0.14.2/lib/pry.rb:61:in `<top (required)>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/irb.rb:54:in `require'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/irb.rb:54:in `irb'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

For a Ruby REPL to start.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
HOMEBREW_PRY=1 brew irb
```

**Comment by Bo98** [comment] 2023-02-15 03:21
I think this is caused by how we remove vendored gems via git.

Workaround is to delete your local pry gem in `vendor/bundle/ruby/...` and re-trigger the install

**Comment by carlocab** [comment] 2023-02-15 03:36
Hmm, yea, makes sense:
```
39c6f7d6fbaba464798751c2c42f8f881da00e80 is the first bad commit
commit 39c6f7d6fbaba464798751c2c42f8f881da00e80
Author: apainintheneck <apainintheneck@gmail.com>
Date:   Sun Feb 5 20:54:15 2023 -0800

    Stop including `*flight` block source in cask API

    Originally we were going to try and load the *flight blocks from the API
    but we ended up going with downloading the caskfile for the subset of
    casks that need this functionality for consisty's sake.

    This reverts the following commits from most recent to oldest:
    - ffc74a51fb32b66a4cd8bc41dbd076dd23d9100e
    - e5616e94fe42505434c330be35eeafef2739944f
    - d1490c3d5c087d00f2bca1787cce331202b195c5
    - 7ca5a5d9a71a73f21bbb8555a38048f027bee89b
    - 2d5d132713d0701d02d5ff33e9918812d13d2a83

    It also changes how *flight blocks are handled in `.to_h`.
    Essentially, when *flight blocks exist they are just included
    as a hash of the artifact to nil to indicate that they exist.

    More information isn't necessary since we don't evaluate
    the current source code in the *flight artifacts that
    we get from the API.

 .gitignore                                         |   1 +
 Library/Homebrew/Gemfile                           |   1 -
 Library/Homebrew/Gemfile.lock                      |   1 -
 .../cask/artifact/abstract_flight_block.rb         |   6 -
 Library/Homebrew/cask/cask.rb                      |   3 +-
 Library/Homebrew/cask/cask_loader.rb               |   6 +-
 Library/Homebrew/test/cask/cask_spec.rb            |  48 -------
 .../fixtures/cask/Casks/conditional-flight.rb      |  21 ---
 .../gems/method_source-1.0.0/lib/method_source.rb  | 141 -------------------
 .../lib/method_source/code_helpers.rb              | 154 ---------------------
 .../lib/method_source/source_location.rb           | 138 ------------------
 .../lib/method_source/version.rb                   |   3 -
 12 files changed, 4 insertions(+), 519 deletions(-)
 delete mode 100644 Library/Homebrew/test/support/fixtures/cask/Casks/conditional-flight.rb
 delete mode 100644 Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source.rb
 delete mode 100644 Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/code_helpers.rb
 delete mode 100644 Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/source_location.rb
 delete mode 100644 Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/version.rb
```

**Comment by carlocab** [comment] 2023-02-15 03:40
Ok, that worked. Thanks for the tip! Would be nice for `brew` to handle this better somehow, but not really sure how that would work.

**Comment by Bo98** [comment] 2023-02-15 04:47
I suppose having `pry` a part of the Gemfile probably would improve things here, though I don't think there was a universal agreement to the approach (I still think gem groups makes sense for stuff like that).

There's been various other issues caused by vendor gem changes over the years (including `brew doctor` failures in homebrew-core), but it seems we've ironed that out a little.

**Comment by MikeMcQuaid** [comment] 2023-02-15 07:29
I'd be game to start including all these sorts of development gems that are installed optionally and/or we remove those that aren't really used.

**Comment by MikeMcQuaid** [comment] 2023-03-08 12:54
@apainintheneck given your recent PR: is this still a problem?

**Comment by apainintheneck** [comment] 2023-03-09 02:52
This is something completely different than what was covered in my PR.

**Comment by apainintheneck** [comment] 2023-03-09 08:45
I actually ran into the exact same error as @carlocab when working with `pry` and this thread was very helpful. I agree that it'd be nice to have a better way of handling dev dependencies but it's a relatively easy fix in this case.

**Comment by apainintheneck** [comment] 2023-04-17 01:00
This was fixed in https://github.com/Homebrew/brew/commit/d69c3ef3df7c332fdc646e0533b898b661f5fccf by vendoring `pry`.

**Closed by apainintheneck** 2023-04-17 01:00 UTC
Labels: bug, help wanted

**Comment by MikeMcQuaid** [comment] 2023-04-17 11:15
Thanks for cleaning this up @apainintheneck 🙇🏻
