### ISSUE TITLE
`brew update` produced a git merge conflict, but no error shown

### ISSUE THREAD

**Issue by sjackman** [Homebrew/brew#1827] opened 2017-01-12 00:23 UTC
_From @timotheecour on January 12, 2017 0:6_

```
brew update
Updated 4 taps (homebrew/core, homebrew/versions, homebrew/boneyard, homebrew/science).
==> New Formulae
homebrew/science/ntcard                                                                                                                                                                                               homebrew/versions/mapnik2
==> Updated Formulae
homebrew/versions/gnupg21    

brew install ldc
Error: /home/timothee/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ldc.rb:7: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
/home/timothee/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ldc.rb:18: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/home/timothee/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ldc.rb:22: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes

```

ie, a merge conflict (i had local modifications)

=> `brew update` should show that there was an error instead of silently succeeding

_Copied from original issue: Linuxbrew/homebrew-core#1573_

**Comment by sjackman** [comment] 2017-01-12 00:23
I believe the default behaviour is that it stashes your uncommitted local modifications.

**Comment by MikeMcQuaid** [comment] 2017-01-12 00:26
What tag is Linuxbrew on currently? Can you or @timotheecour figure out how to reproduce this?

**Comment by sjackman** [comment] 2017-01-12 00:30
Linuxbrew is currently at tag 1.1.6.

**Comment by MikeMcQuaid** [comment] 2017-01-12 00:32
> Linuxbrew is currently at tag 1.1.6.

Great news 🎉. Will make it much easier to triage and fix these things.

**Comment by MikeMcQuaid** [comment] 2017-01-16 19:52
> (i had local modifications)

I missed this before. Closing this out not because it's ideal but because we decided to make `brew update` such that people who make local modifications will know how to figure them out themselves. We don't pop the stash for non-`HOMEBREW_DEVELOPER`s.

**Closed by MikeMcQuaid** 2017-01-16 19:52 UTC
