### ISSUE TITLE
Patch failure on brew install --build-from-source --HEAD boost

### ISSUE THREAD

**Issue by jashsayani** [Homebrew/brew#3081] opened 2017-08-23 07:14 UTC
### Patch failure on brew install --build-from-source

Here is some diagnostic information:

- What you were trying to do (and why)
I am trying to install the `boost` package (build from source) by running `brew install --build-from-source  --HEAD boost` - because just installing `boost` doesnt work as expected - seeing following error: `ld: symbol(s) not found for architecture x86_64`. Hence installing from source (as I read that it fixes the architecture error).

- What happened (include command output)
```
$ brew install --build-from-source --HEAD boost
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
………
==> Cloning https://github.com/boostorg/boost.git
Updating /Users/itsme/Library/Caches/Homebrew/boost--git
==> Checking out branch master
==> Downloading https://github.com/boostorg/serialization/commit/1d86261581230e2
Already downloaded: /Users/itsme/Library/Caches/Homebrew/boost--patch-56620635277eccbb20d970d9a1cdd803b9bb18790f108bd225594ff9d2d9e8bd.diff
==> Patching
==> Applying 1d86261581230e2dc5d617a9b16287d326f3e229.diff
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/include/boost/serialization/array.hpp b/include/boost/serialization/array.hpp
|index 61708b3075e3319f2255529044718bf152a91052..612d1a61985556447168984d8dfbc151b11c46d5 100644
|--- a/include/boost/serialization/array.hpp
|+++ b/include/boost/serialization/array.hpp
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Error: Failure while executing: /usr/bin/patch -g 0 -f -p2 -i /private/tmp/boost--patch-20170823-36129-leaywu/1d86261581230e2dc5d617a9b16287d326f3e229.diff
$ 
```

- What you expected to happen
Successful install by building from source.

- Step-by-step reproduction instructions (by running `brew` commands)
1. Run `brew install --build-from-source  --HEAD boost`
2. Notice failure to patch

**Comment by apjanke** [comment] 2017-08-23 08:41
I can reproduce.

I suspect what's happened is that [this `boost::serialization` patch](https://github.com/Homebrew/homebrew-core/blob/e32f6f66f2c535bc1189990f3e9dd4fda5299468/Formula/boost.rb#L42-L47) has been merged upstream, and needs to be pulled inside the `stable do` block, so it is no longer applied to `--HEAD` builds.

**Comment by apjanke** [comment] 2017-08-23 08:48
Testing a formula patch to do that now. It'll take a while because `boost` is a big build.

**Comment by ilovezfs** [comment] 2017-08-23 08:48
not worth bothering: I'm doing 1.65.0 right now

**Comment by ilovezfs** [comment] 2017-08-23 08:49
See https://github.com/Homebrew/homebrew-core/pull/17122.

**Comment by apjanke** [comment] 2017-08-23 08:49
Ah. Thanks for the heads-up. Killing my builds & branch.

**Comment by MikeMcQuaid** [comment] 2017-08-23 17:34
@jashsayani Please report issues like this to Homebrew/homebrew-core (as directed by the issue template which you didn't fully fill out).

**Closed by MikeMcQuaid** 2017-08-23 17:34 UTC
