### ISSUE TITLE
Add `shellenv --force` and `shellenv -h`

### ISSUE THREAD

**Issue by abitrolly** [Homebrew/brew#12659] opened 2022-01-02 13:28 UTC
### Provide a detailed description of the proposed feature

Add two commands.

    shellenv --force               - force output regardless of state of environment
    shellenv -h                    - show this help

### What is the motivation for the feature?

As explained in https://github.com/Homebrew/brew/issues/11851 `shellenv` doesn't return any output, and it is hard to debug what's going on without investing some hours to browse this tracker.

I am installing Homebrew in CI and script can not find `brew`, so I need to see what `shellenv` produces.

### How will the feature be relevant to at least 90% of Homebrew users?

Hopefully they won't have to debug their shell setup when (re)installing `brew`, but if they will, this will be handy.

### What alternatives to the feature have been considered?

Finding the list of variables that `shellenv` sets by asking here, and reading the source.

**Comment by carlocab** [comment] 2022-01-02 13:37
You can view the help for `shellenv` with `brew help shellenv`. The same is true for any `brew` subcommand, and I don't think we should make the interface inconsistent (i.e. `brew shellenv -h` shows the help but, say, `brew install -h` might not).

#11851 should be fixed by now. You're likely using an outdated version of `brew`. What's the output of `brew config` and `brew doctor` on the machine you're having issues with?

**Comment by abitrolly** [comment] 2022-01-02 14:22
```shell
➜  ~ brew shellenv                                                                                                                                                   /0,0s
➜  ~ brew config  
HOMEBREW_VERSION: 3.2.9-64-g6da8630
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6da8630f4e077b38883f6ea57d96e4002f7b8599
Last commit: 4 months ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 51b47956b0713413d134a533759a1873e53a3578
Core tap last commit: 2 months ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit haswell
Clang: N/A
Git: 2.33.1 => /bin/git
Curl: 7.79.1 => /usr/bin/curl
Kernel: Linux 5.15.11-200.fc35.x86_64 x86_64 GNU/Linux
OS: Fedora release 35 (Thirty Five)
Host glibc: 2.34
/usr/bin/gcc: 11.2.1
/usr/bin/ruby: 3.0.2
glibc: N/A
gcc@5: N/A
xorg: N/A                                                                                                                                                            /1,9s
➜  ~ brew update
Already up-to-date.   
```

```shell
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libnghttp2

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install curl git

Run `brew missing` for more details.                                                                                                                                 /3,3s
➜  ~ git --version
git version 2.33.1                                                                                                                                                   /0,0s
➜  ~ curl --version
curl 7.79.1 (x86_64-redhat-linux-gnu) libcurl/7.79.1 ...
```

**Comment by abitrolly** [comment] 2022-01-02 14:24
Is the problem that I am using system `git` and `curl` binaries?

**Comment by carlocab** [comment] 2022-01-02 14:40
No, the problem is that you're using a very old version of `brew`:
```
Last commit: 4 months ago
```
Do `brew update` before calling `brew shellenv`.

**Closed by carlocab** 2022-01-02 14:40 UTC
Labels: features

**Comment by abitrolly** [comment] 2022-01-02 14:47
It appeared that I am on a different branch.
```
➜  ~ cd /home/linuxbrew/.linuxbrew/Homebrew                                                                                                                          /0,0s
➜  Homebrew git:(desc-v-search) git status
On branch desc-v-search
nothing to commit, working tree clean             
```
I've created the branch when filling https://github.com/Homebrew/brew/issues/11932 and didn't revert back to `master`. Not sure why `brew config` and `brew update` didn't detect that.

After switching back to `master` I could update to latest 3.3.9.
```shell
➜  Homebrew git:(desc-v-search) git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.                                                                                                                      /0,2s
➜  Homebrew git:(master) git branch --merged | egrep -v "(^\*|master|dev|main)" | xargs git branch -d
Deleted branch desc-v-search (was 6da8630f4).
Deleted branch stable (was 92cf90471).                                                                                                                               /0,2s
➜  Homebrew git:(master) brew update
HOMEBREW_CORE_GIT_REMOTE set: using https://github.com/Homebrew/homebrew-core for Homebrew/core Git remote.
remote: Enumerating objects: 62778, done.
remote: Counting objects: 100% (14984/14984), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 62778 (delta 14975), reused 14975 (delta 14968), pack-reused 47794
Receiving objects: 100% (62778/62778), 36.39 MiB | 2.43 MiB/s, done.
Resolving deltas: 100% (45288/45288), completed with 4719 local objects.
From https://github.com/Homebrew/homebrew-core
 + 51b47956b07...648dc81da0a master     -> origin/master  (forced update)
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:cd7fffb18ef9338baa670fc5e8fce99b0e3cc0f0fd7627bcbb56f3c8d54161d4
######################################################################## 100.0%
==> Pouring portable-ruby-2.6.8.x86_64_linux.bottle.tar.gz
==> Migrating formulae from linuxbrew-core to homebrew-core
...
```

And the `shellenv` is fixed indeed.
```shell
➜  Homebrew git:(master) brew shellenv
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";                                                                                               /0,1s
```
