### ISSUE TITLE
`brew rm node` leaves a ton of manpage symlinks unremoved

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#2435] opened 2017-04-01 22:37 UTC
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

I don't really use `node`, but I poured the bottle to play with something briefly.  Then I did `brew rm node`.  Then I did `brew prune`, and beheld all this stuff that didn't get removed but sure seems like it should.  Mostly its manpages, but there's a few thinngs in `opt` too:
```
rm /usr/local/share/man/man1/npm-README.1
rm /usr/local/share/man/man1/npm-access.1
rm /usr/local/share/man/man1/npm-adduser.1
rm /usr/local/share/man/man1/npm-bin.1
rm /usr/local/share/man/man1/npm-bugs.1
rm /usr/local/share/man/man1/npm-build.1
rm /usr/local/share/man/man1/npm-bundle.1
rm /usr/local/share/man/man1/npm-cache.1
rm /usr/local/share/man/man1/npm-completion.1
rm /usr/local/share/man/man1/npm-config.1
rm /usr/local/share/man/man1/npm-dedupe.1
rm /usr/local/share/man/man1/npm-deprecate.1
rm /usr/local/share/man/man1/npm-dist-tag.1
rm /usr/local/share/man/man1/npm-docs.1
rm /usr/local/share/man/man1/npm-doctor.1
rm /usr/local/share/man/man1/npm-edit.1
rm /usr/local/share/man/man1/npm-explore.1
rm /usr/local/share/man/man1/npm-help-search.1
rm /usr/local/share/man/man1/npm-help.1
rm /usr/local/share/man/man1/npm-init.1
rm /usr/local/share/man/man1/npm-install-test.1
rm /usr/local/share/man/man1/npm-install.1
rm /usr/local/share/man/man1/npm-link.1
rm /usr/local/share/man/man1/npm-logout.1
rm /usr/local/share/man/man1/npm-ls.1
rm /usr/local/share/man/man1/npm-outdated.1
rm /usr/local/share/man/man1/npm-owner.1
rm /usr/local/share/man/man1/npm-pack.1
rm /usr/local/share/man/man1/npm-ping.1
rm /usr/local/share/man/man1/npm-prefix.1
rm /usr/local/share/man/man1/npm-prune.1
rm /usr/local/share/man/man1/npm-publish.1
rm /usr/local/share/man/man1/npm-rebuild.1
rm /usr/local/share/man/man1/npm-repo.1
rm /usr/local/share/man/man1/npm-restart.1
rm /usr/local/share/man/man1/npm-root.1
rm /usr/local/share/man/man1/npm-run-script.1
rm /usr/local/share/man/man1/npm-search.1
rm /usr/local/share/man/man1/npm-shrinkwrap.1
rm /usr/local/share/man/man1/npm-star.1
rm /usr/local/share/man/man1/npm-stars.1
rm /usr/local/share/man/man1/npm-start.1
rm /usr/local/share/man/man1/npm-stop.1
rm /usr/local/share/man/man1/npm-team.1
rm /usr/local/share/man/man1/npm-test.1
rm /usr/local/share/man/man1/npm-uninstall.1
rm /usr/local/share/man/man1/npm-unpublish.1
rm /usr/local/share/man/man1/npm-update.1
rm /usr/local/share/man/man1/npm-version.1
rm /usr/local/share/man/man1/npm-view.1
rm /usr/local/share/man/man1/npm-whoami.1
rm /usr/local/share/man/man1/npm.1
rm /usr/local/share/man/man5/npm-folders.5
rm /usr/local/share/man/man5/npm-global.5
rm /usr/local/share/man/man5/npm-json.5
rm /usr/local/share/man/man5/npmrc.5
rm /usr/local/share/man/man5/package.json.5
rm /usr/local/share/man/man7/npm-coding-style.7
rm /usr/local/share/man/man7/npm-config.7
rm /usr/local/share/man/man7/npm-developers.7
rm /usr/local/share/man/man7/npm-disputes.7
rm /usr/local/share/man/man7/npm-index.7
rm /usr/local/share/man/man7/npm-orgs.7
rm /usr/local/share/man/man7/npm-registry.7
rm /usr/local/share/man/man7/npm-scope.7
rm /usr/local/share/man/man7/npm-scripts.7
rm /usr/local/opt/node@7
rm /usr/local/opt/nodejs
rm /usr/local/opt/npm
Pruned 69 symbolic links from /usr/local
No apps unlinked from /Applications
```

**Comment by chdiza** [comment] 2017-04-01 22:39
Note that while the `node` bottle was installed, I never used `npm` or anything like that.

**Comment by MikeMcQuaid** [comment] 2017-04-02 08:42
> rm /usr/local/opt/node@7
> rm /usr/local/opt/nodejs
> rm /usr/local/opt/npm

These will be addressed by https://github.com/Homebrew/brew/pull/2433.

The rest are manually made in `postinstall` for Node's formula hence why Homebrew can't "find" them. It should be fixable but may cause unacceptable performance regressions (i.e. a `brew prune` runtime every `brew uninstall` but we will try anyway)

**Comment by chdiza** [comment] 2017-04-02 12:55
> These will be addressed by #2433.

I'm confused then.  I thought I had already pulled in #2433 when I tried the node example.

**Comment by chdiza** [comment] 2017-04-02 13:06
Well, I tried it again and indeed those last three symlinks in `opt` did get removed.  So it's just the manpages.

> It should be fixable but may cause unacceptable performance regressions (i.e. a brew prune runtime every brew uninstall but we will try anyway)

Maybe a kind of "restricted" prune will do the trick.  A regular prune I have found will destroy *any* dead symlink in /usr/local/the-usual-suspects, even if the symlink's target is not in the Cellar.  (For instance, I have some custom symlinks in /usr/local/bin pointing to the `bb*` binaries embedded in BBEdit.app.  On occasion,  I temporarily have no BBEdit.app on my machine, and `brew prune` destroys these, and then when BBEdit.app is back on my machine I have to wonder why `bbedit` no longer works and then recreate the links.)  A restricted prune will only kill symlinks whose targets are in the Cellar

(Actually, now that I think about it, what I'm calling "restricted" prune should just be how regular prune works.)

**Comment by chdiza** [comment] 2017-04-03 14:15
Perhaps `remove` should call prune iff one of the arguments to `remove` is known to have a postinstall.  Just spitballin'.

**Closed** 2017-06-02 10:43 UTC
Labels: bug

**Comment by chdiza** [comment] 2017-06-09 20:52
This is actually not fixed by Homebrew/homebrew-core/pull/14171, contrary to its commit message.

Today I installed node, then did `brew rm --force node`.  All the same dead symlinks to npm manpages were present.

**Comment by DomT4** [comment] 2017-06-10 20:53
It's fixed presuming you upgrade, install, reinstall or postinstall `node` at least once more before removal. Otherwise just `brew prune` them as directed, but the actual cause of the problem has been fixed by the commit.

**Comment by DomT4** [comment] 2017-06-10 20:56
```
~> brew rm node
~> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install node

Run `brew missing` for more details.
~> brew install node
~> brew doctor
Your system is ready to brew.
~> brew rm node
~> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install node

Run `brew missing` for more details.
```

**Comment by chdiza** [comment] 2017-06-11 14:44
Uh oh!

**Comment by DomT4** [comment] 2017-06-11 16:41
The warning is expected, I have `ios-sim` installed locally. Are you still having trouble? 🙈

**Comment by chdiza** [comment] 2017-06-11 17:38
> Are you still having trouble?

No, I *can* of course use `brew prune` (and did this).  It seems totally absurd, however, that one has to do this at all.    Especially since (IIUC) the man pages in `/usr/local/share` are supposed to be copies and not symlinks.  Probably I just don't UC :)

There is no parallel problem, as far as I know, with dead symlinks from installations of other scripting lanuages with their own package manager---like `ruby`  or `python`---for which HB tries to preserve those sub-installations across version bumps.

**Comment by ilovezfs** [comment] 2017-06-11 17:40
@chdiza it has to do with our super-cool way of handling `npm` (you can look at node's post_install method if you're curious).

**Comment by DomT4** [comment] 2017-06-11 18:08
Yes, `npm` is a rather special case due to its complex history with Homebrew. We break a fair few of our own rules about how formulae should behave simply because doing so keeps the risk of breakage for Homebrew, users & upstream as minimal as possible.

**Comment by DomT4** [comment] 2017-06-11 18:09
> No, I can of course use brew prune (and did this)

Also just to reiterate, if you'd run `brew postinstall node` once before removing it you wouldn't need to `prune` at all. The assumption is that most users who have `node` installed will not have uninstalled it between that commit & the release ILZ merged the other day.
