### ISSUE TITLE
Redesign `on_os` (i.e. `on_macos` and `on_linux`) blocks

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#11687] opened 2021-07-09 20:20 UTC
### Provide a detailed description of the proposed feature

I don't have a detailed description, because I'm not sure what the correct way to do this just yet is. However, I think it would be useful to rethink the design and use of our `on_macos` and `on_linux` blocks in Homebrew/core.

### What is the motivation for the feature?

Having to use `on_macos` and `on_linux` blocks often help make for readable code, but they do have two shortcomings:

1. The single-line syntax isn't as natural as a single-line `if` or `unless`, and it's not as straightforward to standardise.
2. They don't provide a natural way to express "do this for Linux or macOS versions newer than x".

As an example of the first item, suppose I wanted to do `make foo` in an install method, but only on Linux. Currently, I could do
```ruby
on_linux { system "make", "foo" }
```
or
```ruby
on_linux do
  system "make", "foo"
end
```
Both, to me, are less natural than
```ruby
system "make", "foo" if OS.linux?
```
Using `if OS.linux?` also has the benefit of a syntax check ruling out blocks of the form
```ruby
if OS.linux?
  system "make", "foo"
end
```
in favour of a single-line declaration. I'm not aware of a way to make Rubocop express a preference between a single-line `on_linux do` block and the form with braces on a single line.

This isn't to say we should start using `OS.mac?` or `OS.linux?` in Homebrew/core, but it would be nice if we could change `on_macos` and `on_linux` to be more like `if OS.mac?` or `if OS.linux?` in the ways I mention above.

As an example of the second item, see Homebrew/homebrew-core#80914. In that PR, I think it would be a lot nicer to just be able to declare additional resources for Linux and Big Sur or newer so that the install method can just do
```ruby
resources.each do |r|
  r.stage do
    system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
    system "make", "install"      
  end
end
```
However, since we can't use `on_macos` or `on_linux` to express what we need here (not without duplication, at least), we've made the install method brittle with respect to changes in the formula's resources.

I should also point out that we currently take advantage of statements like `if MacOS.version <= :mojave` evaluating to true on Linux in order to express that we want something done on Linux or on Mojave or older ([example](https://github.com/Homebrew/homebrew-core/blob/843eca6b944c46f363deb9e79c7e722d80e74d38/Formula/llvm.rb#L119-L125)) which isn't exactly intuitive or expected for someone who isn't familiar with how `MacOS.version` works.

### How will the feature be relevant to at least 90% of Homebrew users?

It probably won't be but it would be nice if we had more readable formulae.

### What alternatives to the feature have been considered?

The status quo.

**Comment by carlocab** [comment] 2021-07-10 02:11
Also, this might just be personal preference but using the ternary operator in Homebrew/homebrew-core#80917 seems nicer.

**Comment by Rylan12** [comment] 2021-07-10 15:34
Just curious (because I don't know much about these blocks other than what they do), why were they introduced instead of just using `if OS.mac?` and `is OS.linux?` (which I believe we _did_ use in the past).

(I'm also not going to push for changing them regardless of what the answer is, I'm just curious)

**Comment by iMichka** [comment] 2021-07-11 15:13
When I started the work to backport linux changes to homebrew-core, there was a "negotiation" about the syntax. First we added `uses_from_macos` (which has also some drawbacks regarding the logic). Then, if I remember well, @MikeMcQuaid was in favour of these new blocks, mainly to be able to add audits for them. I had no strong opinion so I just started implementing them, because I also did not want to bikeshed the thing too much and get the migration going.

Finally we have added `Hardware::CPU.arm?` all over the place and there was no such discussion in that case.

If we change anything, I would like this to happen AFTER we have archived linuxbrew-core.

**Comment by dawidd6** [comment] 2021-07-11 15:36
Ye, the `if Hardware::CPU.arm?` and `if MacOS.version` are used all over the place and it's fine, but it wasn't fine to use `if OS.linux?` (which is used in brew or test-bot tho). I'm not sure why, the audit reason mentioned above just does not speak to me.

**Comment by Rylan12** [comment] 2021-07-11 15:48
There are actually two categories of `on_os` block, right? I think they're functionally identical but [one can be used in the root formula class](https://github.com/Homebrew/homebrew-core/blob/f40446d280f8aaa5d757140c53a8d9895a5f48c4/Formula/htop.rb#L30-L32) (i.e. to restrict dependencies) and [the other can be used in the `install` method](https://github.com/Homebrew/homebrew-core/blob/f40446d280f8aaa5d757140c53a8d9895a5f48c4/Formula/htop.rb#L37) to restrict certain lines.

A major difference between them is that the root-level block is restricted to only wrap certain methods (`depends_on`, `patch`, `resource`, `deprecate!`, `disable!`, `conflicts_with`, `keg_only`, and `ignore_missing_libraries`). I wonder if this is the main use for the blocks. If it is, this seems like something that should be restricted for arm/linux as well, right?

I'd like to hear what @MikeMcQuaid has to say about the reasoning because I feel like there's something being missed here (I doubt he would push for something that didn't have a well thought-out reason at the time).

If it _is_ only for the restricting of the blocks to those components listed above, I wonder if we want to only require using the blocks in the root of the class and, in the `install` method, use `if`s. And, the same could be true for `on_arm`/`on_linux` and maybe an equivalent for macOS versions like `on_macos ">= :mojave" { }`.

> If we change anything, I would like this to happen AFTER we have archived linuxbrew-core.

Definitely agree

**Comment by MikeMcQuaid** [comment] 2021-07-12 09:39
Thanks for mentioning me here folks. As a starting point:

> If we change anything, I would like this to happen AFTER we have archived linuxbrew-core.

I strongly agree with this. Does this issue have some good suggestions and discussion for improvements? Absolutely. To change anything now, though, will make the (almost complete!) work of getting rid of linuxbrew-core that much harder.

---

Onto the actual discussion.

> * The single-line syntax isn't as natural as a single-line `if` or `unless`, and it's not as straightforward to standardise.

So: the biggest motivation for the blocks is that something like 
```ruby
if OS.linux?
  depends_on "foo"
else
  depends_on "bar"
end
```

really sucks for the way we use the formula API. Let me explain why:

Back in The Old Days: things were simpler. We didn't have formulae.brew.sh, we didn't use Linux to query information about macOS formulae (and vice versa), we had no plans of ever merging Linuxbrew (as it was named) into even Homebrew/brew.

Even then, though: there were problems. The most common one was:
```ruby
depends_on "foo" if build.include?("--foo")
```

This looks nice and natural. The problem is after you've actually installed this formula if you want to query the dependencies of the formula you need to remember that `--foo` was passed somewhere. This massively complicated a bunch of logic (that we've thankfully been able to do away with). To make things worse:
```ruby
if build.include?("--foo")
  depends_on "foo"
else
  depends_on "bar"
end
```

now you need to remember to store `--foo` but what if you want to somehow indicate this or query both dependencies in different situations? Because you're relying on an actual Ruby structure there's literally no way beyond using something like RuboCop::AST (which we didn't use until relatively recently) to get both dependencies here.

The lingering pain of this is why I wanted us to move to a block form. To go back to this example:
```ruby
if OS.linux?
  depends_on "foo"
else
  depends_on "bar"
end
```

this reads pretty nicely but has the problem I mentioned above. Alternatively,

```ruby
on_linux
  depends_on "foo"
end

on_macos
  depends_on "bar"
end
```

This does actually let us at runtime decide whether or not to evaluate both, one or neither of these. This makes the job of formulae.brew.sh, `brew info`, etc. a lot easier.

Additionally, before we had `on_linux` we also had `uses_from_macos`. My goal overall with all the `if OS.linux?` stuff was to move away from Linux-specific conditionals to higher-level conditionals (like `uses_from_macos`) that explained _why_ things were conditional or add new DSLs that abstracted this OS differences into Homebrew/brew instead. 

On that front I feel like my goals may have failed but this seems like a good chance to be doing this.

Onto @Rylan12's point:

> A major difference between them is that the root-level block is restricted to only wrap certain methods (`depends_on`, `patch`, `resource`, `deprecate!`, `disable!`, `conflicts_with`, `keg_only`, and `ignore_missing_libraries`). I wonder if this is the main use for the blocks. If it is, this seems like something that should be restricted for arm/linux as well, right?

Yes, I think it would be worth having a `on_arm` or similar here. This is fairly good timing because (somewhat) imminently the "macOS formulae" and "linux formulae" on https://formulae.brew.sh aren't really going to make much sense once we have homebrew-core and linuxbrew-core merged and we'll want to display Linux and macOS dependencies on the same page (as e.g. the versions will be the same) and it'd be nice to use this as an opportunity to show ARM dependencies too.

> * They don't provide a natural way to express "do this for Linux or macOS versions newer than x".

I think we don't need this for Linux but I think we do for macOS. It'd be a good addition. Something like what we do for `uses_from_macos` makes sense to me:

```
on_macos(since: :mojave)
  depends_on "bar"
end
```

Finally:
> I should also point out that we currently take advantage of statements like `if MacOS.version <= :mojave` evaluating to true on Linux in order to express that we want something done on Linux or on Mojave or older ([example](https://github.com/Homebrew/homebrew-core/blob/843eca6b944c46f363deb9e79c7e722d80e74d38/Formula/llvm.rb#L119-L125)) which isn't exactly intuitive or expected for someone who isn't familiar with how `MacOS.version` works.

Yes, I've long disliked this. I think we should change Linux to be like the `--generic` architecture where `MacOS` is literally not defined. We should do the same IMO for `Xcode` too. 

---

So, my current position is:
- we should add `on_arm` for the root-level blocks outside of e.g. `def install` (this could happen now i.e. before the linuxbrew-core merge)
- we should add `on_macos(since: :mojave)` and a e.g. `before:` for the root-level blocks outside of e.g. `def install` (this could happen now i.e. before the linuxbrew-core merge)
- we still want `on_linux` and `on_macos` for the root-level blocks outside of e.g. `def install`. Inside of `def install` I think we can return to doing `OS.linux?` instead (after the linuxbrew-core merge has happened)
- we should undefine `MacOS` and `Xcode` on Linux and move to either gating them with `OS.mac?` conditionals or, ideally, add new DSLs that explain better what's going on here(after the linuxbrew-core merge has happened)
- when doing any of the above we should be asking ourselves if we see the same patterns across 3+ formulae: "how/what would be a DSL that could be added to make this more readable AND more DRY AND (ideally) more concise)

Thanks for the lovely, friendly and constructive discussion so far folks. Y'all are great ❤️

**Comment by issyl0** [comment] 2021-07-13 22:35
> ... imminently the "macOS formulae" and "linux formulae" on https://formulae.brew.sh aren't really going to make much sense once we have homebrew-core and linuxbrew-core merged and we'll want to display Linux and macOS dependencies on the same page (as e.g. the versions will be the same).

I will take the greatest pleasure in ripping out the `formula-linux` generation code from https://formulae.brew.sh, having been the one to add it.

**Closed** 2021-09-08 12:43 UTC
Labels: help wanted, features, in progress
