### ISSUE TITLE
invalid flags silently accepted

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#2169] opened 2017-02-24 19:29 UTC
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

```
brew link --overwrite --dryrun numpy
... 380 symlinks created
```
I passed the wrong flag (should've been `--dry-run`) but brew should've complained about that instead of silently ignoring. This is a more general issue (not just for `brew link`)

**Comment by ilovezfs** [comment] 2017-02-24 19:44
Right. There's no validation of those options. PR(s) welcome :)

**Comment by MikeMcQuaid** [comment] 2017-02-24 21:10
Duplicate of https://github.com/Homebrew/brew/issues/1860. Please check for duplicates in future, thanks.

**Closed by MikeMcQuaid** 2017-02-24 21:10 UTC
