### ISSUE TITLE
Need help : even brew doctor fails 

### ISSUE THREAD

**Issue by oliviermarti** [Homebrew/brew#1654] opened 2016-12-12 15:49 UTC
```
marti@Spip-/usr/local/Homebrew 👉  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
Error: Formulae found in multiple taps:
 * cartr/qt4/shiboken
 * homebrew/boneyard/shiboken

Please use the fully-qualified name e.g. cartr/qt4/shiboken to refer the formula.
```

I'm trying to make some cleaning in my brew install : removing pyqt, qt4, etc ... It fails because I've tried to install some day a qt4 from another tap, and now I can't uninstall anything. It always with that message that even `brew doctor` says. I've tried a lot of things : `tap`, `untap`, `tap --repair`, etc... 

Any hint ?
Thank's

Olivier 

```
marti@Spip-/usr/local/Homebrew 👉  brew config
HOMEBREW_VERSION: 1.1.2-80-g666463c
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 666463ca2be08261cf103e4870b267f5b461a7f3
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a4d50c465d7398710f04022fafea080c7da83347
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_66
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: N/A
X11: 2.7.11 => /opt/X11
```

**Comment by vladshablinsky** [comment] 2016-12-12 17:14
I can reproduce this with `pyqwt` which depends on `pyqt`

and `Formulary` can't resolve it due to several possible options:

* cartr/qt4/pyqt
* homebrew/boneyard/pyqt

> I'm trying to make some cleaning in my brew install : removing pyqt, qt4, etc ... It fails because I've tried to install some day a qt4 from another tap, and now I can't uninstall anything. 

@oliviermarti what exactly are you trying to do? It seems strange that uninstall is not working.

**Comment by vladshablinsky** [comment] 2016-12-12 17:17
@MikeMcQuaid I think it's a bug, but not sure how we should handle this. The fail in doctor appears when we check missing dependencies and there are several formulae with some name.

```bash
Error: Formulae found in multiple taps:
 * cartr/qt4/pyqt
 * homebrew/boneyard/pyqt

Please use the fully-qualified name e.g. cartr/qt4/pyqt to refer the formula.
/usr/local/Homebrew/Library/Homebrew/formulary.rb:336:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:97:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:84:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1488:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1507:in `missing_dependencies'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:14:in `block in missing_deps'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:13:in `missing_deps'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:880:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Steps to reproduce:

```bash
brew tap cartr/qt4
brew tap homebrew/boneyard
brew install pyqwt
```

**Comment by MikeMcQuaid** [comment] 2016-12-13 14:38
@oliviermarti You should `brew untap homebrew/boneyard`

@vladshablinsky Nice work! The fix for this is probably to always deprioritise `homebrew/boneyard` so it's only used as a last resort and other taps always take priority.

**Comment by oliviermarti** [comment] 2016-12-13 14:49
@MikeMcQuaid 
Been there, done that !

It doesn't work, probably because `brew doctor `'retap' homebrew/boneyard. I whish I could get rid of these taps, but how :-(

Olivier

```
marti@Spip-~ 👉  brew untap homebrew/boneyard
Untapping homebrew/boneyard... (304 files, 605.6K)
Untapped 270 formulae
marti@Spip-~ 👉  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
==> Tapping homebrew/boneyard
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard'...
remote: Counting objects: 283, done.
remote: Compressing objects: 100% (279/279), done.
remote: Total 283 (delta 4), reused 178 (delta 4), pack-reused 0
Receiving objects: 100% (283/283), 179.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
Tapped 270 formulae (303 files, 604.7K)
Error: Formulae found in multiple taps:
 * cartr/qt4/shiboken
 * homebrew/boneyard/shiboken

Please use the fully-qualified name e.g. cartr/qt4/shiboken to refer the formula.
marti@Spip-~ 👉
```

**Comment by MikeMcQuaid** [comment] 2016-12-13 14:50
Try to `brew uninstall --force homebrew/boneyard/shiboken; brew untap homebrew/boneyard`

**Comment by oliviermarti** [comment] 2016-12-13 14:55
Still stuck :

```
marti@Spip-~ 👉  brew uninstall --force homebrew/boneyard/shiboken; brew untap homebrew/boneyard
Error: Formulae found in multiple taps:
 * cartr/qt4/shiboken
 * homebrew/boneyard/shiboken

Please use the fully-qualified name e.g. cartr/qt4/shiboken to refer the formula.
Untapping homebrew/boneyard... (303 files, 604.7K)
Untapped 270 formulae
marti@Spip-~ 👉  brew uninstall --force homebrew/boneyard/shiboken
Error: No available formula with the name "homebrew/boneyard/shiboken"
Please tap it and then try again: brew tap homebrew/boneyard
marti@Spip-~ 👉  brew untap homebrew/boneyard
Error: No available tap homebrew/boneyard.
marti@Spip-~ 👉  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
==> Tapping homebrew/boneyard
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard'...
remote: Counting objects: 283, done.
remote: Compressing objects: 100% (279/279), done.
remote: Total 283 (delta 4), reused 178 (delta 4), pack-reused 0
Receiving objects: 100% (283/283), 179.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
Tapped 270 formulae (303 files, 604.7K)
Error: Formulae found in multiple taps:
 * cartr/qt4/shiboken
 * homebrew/boneyard/shiboken

Please use the fully-qualified name e.g. cartr/qt4/shiboken to refer the formula.
marti@Spip-~ 👉  brew uninstall --force homebrew/boneyard
Error: No available formula with the name "homebrew/boneyard"
```

**Comment by MikeMcQuaid** [comment] 2016-12-13 14:56
`rm -rf /usr/local/Cellar/shiboken` and then `brew untap homebrew/boneyard` and try again.

**Comment by oliviermarti** [comment] 2016-12-13 15:04
```
marti@Spip-~ 👉  rm -rf /usr/local/Cellar/shiboken
marti@Spip-~ 👉  brew untap homebrew/boneyard
Untapping homebrew/boneyard... (303 files, 604.7K)
Untapped 270 formulae
marti@Spip-~ 👉  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
==> Tapping homebrew/boneyard
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard'...
remote: Counting objects: 283, done.
remote: Compressing objects: 100% (279/279), done.
remote: Total 283 (delta 4), reused 178 (delta 4), pack-reused 0
Receiving objects: 100% (283/283), 179.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
Tapped 270 formulae (303 files, 604.7K)
Error: Formulae found in multiple taps:
 * cartr/qt4/shiboken
 * homebrew/boneyard/shiboken

Please use the fully-qualified name e.g. cartr/qt4/shiboken to refer the formula.
```

But :

```
marti@Spip-~ 👉  find /usr/local -name shiboken
marti@Spip-~ 👉
```

Where does it still find urge to summon shiboken ?????

**Comment by MikeMcQuaid** [comment] 2016-12-18 21:05
What does `brew missing` and `brew doctor` report? Does this still happen after you `brew update`? Thanks!

**Comment by oliviermarti** [comment] 2016-12-19 08:46
Response is the same before and after a `brew update`: 
```
marti@Spip-~ 👉  brew missing
Error: Formulae found in multiple taps:
 * cartr/qt4/shiboken
 * homebrew/boneyard/shiboken

Please use the fully-qualified name e.g. cartr/qt4/shiboken to refer the formula.
marti@Spip-~ 👉  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
Error: Formulae found in multiple taps:
 * cartr/qt4/shiboken
 * homebrew/boneyard/shiboken

Please use the fully-qualified name e.g. cartr/qt4/shiboken to refer the formula.
marti@Spip-~ 👉
```

**Comment by MikeMcQuaid** [comment] 2016-12-23 20:38
Thanks, I'll look into this over the Christmas vacation.

**Comment by MikeMcQuaid** [comment] 2016-12-31 18:35
What does `cat /usr/local/opt/shiboken/INSTALL_RECEIPT.json` output?

**Comment by oliviermarti** [comment] 2017-01-01 20:32
I have no directory` /usr/local/opt/shiboken`

Olivier

**Comment by MikeMcQuaid** [comment] 2017-01-02 10:09
@oliviermarti What does `brew list shiboken` output? Thanks!

**Comment by MikeMcQuaid** [comment] 2017-01-02 18:07
Sorry, just `brew list`. Thanks!

**Comment by oliviermarti** [comment] 2017-01-03 07:28
```
marti@Spip-~ 👉  brew list
antlr2			gcc48			isl			little-cms2		pygtk
atk			gdal			isl011			lzlib			pykep
atkmm			gdb			jasper			md5sha1sum		pyqt
autoconf		gdbm			jbig2dec		mono			pyside
automake		gdk-pixbuf		jpeg			mpfr			python
avfs			geos			json-c			mpfr2			python3
boost			gettext			libevent		mpio			qt
boost-python		ghostscript		libffi			ncl			readline
c-ares			giflib			libgcrypt		nco			scipy
cairo			glib			libgeotiff		ncview			shared-mime-info
cairomm			glibmm			libgpg-error		netcdf			simple-mtpfs
cdo			globus-toolkit		libidn			netpbm			sip
cloog			gmp			liblwgeom		nettle			sloccount
cloog018		gmp4			libmpc			ntfs-3g			sqlite
cmake			gnutls			libmpc08		numpy			sshfs
coreutils		gobject-introspection	libmtp			open-mpi		swig
dos2unix		grib-api		libotr			openssl			szip
doxygen			grsync			libpng			p7zip			texinfo
e2fsprogs		gsl			libpng12		pango			tor
ecj			gtk+			libsigc++		pangomm			tree
exiftool		gtkglext		libsodium		pangox-compat		udunits
exiv2			gtkmm			libspatialite		parallel		watch
ext2fuse		harfbuzz		libssh2			pcre			wget
ext4fuse		hdf5			libtasn1		pidgin			xz
fontconfig		hicolor-icon-theme	libtiff			pixman			zeromq
freetype		hunspell		libtool			pkg-config
freexl			icu4c			libusb			proj
gawk			imagemagick		libusb-compat		py2cairo
gcc			intltool		libxml2			pygobject
marti@Spip-~ 👉
```

Olivier

PS : I'm back at work, and will respond faster now ..!

**Comment by MikeMcQuaid** [comment] 2017-01-03 20:03
Can you `brew update` and see if you can still reproduce this?

**Comment by oliviermarti** [comment] 2017-01-04 08:51
Brew update works fine : 

```
marti@Spip-~ 👉  brew update
X11 forwarding request failed on channel 1
Already up-to-date.
marti@Spip-~ 👉
```

I have the problem with doctor and uninstall. update, upgrade,liste works fine.

Olivier

**Comment by MikeMcQuaid** [comment] 2017-01-04 10:00
@oliviermarti Thanks! Can I see the new `brew config`, `brew list`, `brew doctor` and `cat /usr/local/opt/pyside/INSTALL_RECEIPT.json` output? Thanks!

**Comment by oliviermarti** [comment] 2017-01-04 10:23
I the following attached gzip : 

[BrewSierraBug.zip](https://github.com/Homebrew/brew/files/684370/BrewSierraBug.zip)

Olivier

**Comment by MikeMcQuaid** [comment] 2017-01-10 03:26
New strategy here: can I see the output of `brew missing --debug` (or any command that’s failing, anyone).

Thanks!

**Comment by oliviermarti** [comment] 2017-01-10 07:33
Attached. Hope this help ...

Olivier

[brew_missing_debug.txt](https://github.com/Homebrew/brew/files/695486/brew_missing_debug.txt)

**Comment by MikeMcQuaid** [comment] 2017-01-16 18:48
Ok, this is imply an issue with having a formula in multiple tapped taps where at least one or more formula has `depends_on "$FORMULA"` where `$FORMULA` is the name of a formula that exists in multiple taps. You need to `brew untap homebrew/boneyard`.

**Closed by MikeMcQuaid** 2017-01-16 18:48 UTC
Labels: bug
