### ISSUE TITLE
Ask for required user input before installation

### ISSUE THREAD

**Issue by forthrin** [Homebrew/brew#1293] opened 2016-10-15 07:17 UTC
When running `brew upgrade`, Homebrew will tick away doing its job, but suddenly it will stop (at Vagrant for example), and ask for my root password.

First of all, I thought that Homebrew was based on _not_ requiring the root password, but this is a Cask so maybe that's why.

Anyway, it's kind of annoying if you start a large upgrade, go to the zoo, only to come home hours later and find Homebrew's done almost nothing because it needed the root password after 5 minutes.

I don't know if the update/upgrade process requires any other user interaction except entering the root password, but here are my proposals for resolving the issue:

A) When running Homebrew, do a two pass operation, where the first checks if any packages will require the root password. If so, ask for it up-front.

B) Forbid any packages to require the password, so they'll have to rewrite their app to work at a user level. (They may alternatively require the root password the first time the new version is run.)

**Comment by reitermarkus** [comment] 2016-10-15 07:55
> B) Forbid any packages to require the password, so they'll have to rewrite their app to work at a user level. (They may alternatively require the root password the first time the new version is run.)

This is pretty much impossible, because in most, if not all, cases, it's not the application that needs the password, but the installer.

**Comment by vitorgalvao** [comment] 2016-10-15 09:26
> When running Homebrew, do a two pass operation, where the first checks if any packages will require the root password. If so, ask for it up-front.

As a side note, for now you can easily accomplish exactly that with `sudo -v` ([docs](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/sudo.8.html)):

> If given the -v (validate) option, sudo will update the user's time stamp, prompting for the user's password if necessary.  This extends the sudo timeout for another 5 minutes (or whatever the timeout is set to in sudoers) but does not run a command.

**Comment by MikeMcQuaid** [comment] 2016-10-15 09:47
> This is pretty much impossible, because in most, if not all, cases, it's not the application that needs the password, but the installer.

Something that I think is good practice, though, is to ensure whenever the password is prompted that you tell the user why, even if it's just `installing X needs sudo:` or even `installing a .pkg file, you may be prompted for your password:`

@forthrin Do you have any logs of the operation so we might be able to see what caused it?

**Comment by forthrin** [comment] 2016-10-15 10:05
```
==> Downloading https://releases.hashicorp.com/vagrant/1.8.6/vagrant_1.8.6.dmg
Already downloaded: /Users/olav/Library/Caches/Homebrew/Cask/vagrant--1.8.6.dmg
==> Verifying checksum for Cask vagrant
==> Running installer for vagrant; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is Vagrant
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
🍺  vagrant was successfully installed!

```

**Comment by MikeMcQuaid** [comment] 2016-10-15 10:17
> ==> Running installer for vagrant; your password may be necessary.

@forthrin To be fair, it did/does say that. Do you think it would be better if that was after "Package installers may write to any location ...."?

**Comment by vitorgalvao** [comment] 2016-10-15 10:58
@MikeMcQuaid If I understood @forthrin’s problem correctly, the issue isn’t with a particular install not saying it will need a password, it’s when you are installing a bunch of them and a single one stops the others from proceeding because it needs your password but you weren’t present to give it (because you set the upgrades going and went somewhere). So the issue is only relevant when more than one cask is being installed.

@forthrin On another note, I’m not sure what command you ran, but `brew upgrade` does not touch casks and we have no upgrade functionality for casks yet. Your comment can be taken into account when considering exactly how to implement `brew cask upgrade`, but at the moment the official stance is that we (the HBC part) officially do not support any upgrade functionality, and that any method you pick to fake it is unsupported and done at your our risk.

**Comment by MikeMcQuaid** [comment] 2016-10-15 11:10
> So the issue is only relevant when more than one cask is being installed.

I see. In that case I think it's somewhat unavoidable for security reasons as maintaining it so any `brew` subprocess can `sudo` with impunity after a password has been requested is a bad idea for security.

**Comment by forthrin** [comment] 2016-10-15 11:26
@vitorgalvao is right. The problem having to sit in front of the computer for hours in case an installer wants a password during a long series of installs (which can happen anywhere).

The command I'm using is:

alias bu='brew update; brew upgrade; brew cask list | xargs brew cask install --force'

**Comment by MikeMcQuaid** [comment] 2016-10-15 11:34
`sudo brew cask install` handles that, FYI, but I have no idea whether the @Homebrew/cask folks recommend it.

**Comment by adidalal** [comment] 2016-10-16 18:10
Don't use `sudo brew cask`, it'll lead to permission issues down the line.
ie. https://github.com/caskroom/homebrew-cask/issues/25547

**Comment by MikeMcQuaid** [comment] 2016-10-16 19:57
@adidalal In that case it's probably worth removing https://github.com/Homebrew/brew/blob/de880f1e870d91dd838228de2987f9bd6d194aef/Library/Homebrew/brew.sh#L244. I do still think that `cask` should prompt with for exactly the command it's going to run before running it and make the preceding message specifically state why root access is needed.

**Comment by forthrin** [comment] 2016-10-17 10:02
I agree with @adidalal that it should be an absolute requirement for packages to write specifically and exactly why they need root access. Once you give a package root access the privilege, how do you know it does not do illegitimate things with these privileges? Security must be a priority these days.

Fictional example of how this could be solved:

    $ brew cask upgrade
    Checking packages ...
    The following packages require your root password to upgrade:

    Vagrant:
    cp /tmp/installer/default.cfg /etc
    mkdir /usr/local/vagrant

    MySQL:
    chown $USER /usr/local/mysql

    Enter password:

Refusing to enter the password would upgrade the rest of the packages, but not those listed.

**Comment by vitorgalvao** [comment] 2016-10-17 14:29
@forthrin You seem to be going from the idea we control what the exact actions the package is taking and asking for `sudo`, but we don’t have such granularity. The only thing we’re doing is saying “Hey, [`installer`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/installer.8.html), [install this](https://github.com/Homebrew/brew/blob/0296439c832a915be9b73456c0c26bc6c79c271d/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb#L55)” and it’s going to say “[Can do](https://youtu.be/CRMcSAgoabw)! But I need elevated privileges”.

That’s why I also think that printing the exact command we’re going to run is not that useful in this case. If we had

```
==> Running installer for vagrant; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> The command we’re running is `sudo installer -pkg /path/to/package.pkg -target /`
Password:
```

Would that be better? Perhaps, but marginally, as you still have no idea what’s happening anyway, and still have no control.

**Comment by MikeMcQuaid** [comment] 2016-10-17 14:34
> Would that be better? Perhaps, but marginally, as you still have no idea what’s happening anyway, and still have no control.

Personally I think something like that would be superior, yeh 👍

**Comment by forthrin** [comment] 2016-10-18 05:56
Some specifics would make it easier to understand the situation:

1. How many percent of packages require the root password?
1. What are the most common reasons packages require the root password?
1. Can all packages in theory be reprogrammed not to require the root password? If no, why not?
1. Could a requirement/mechanism be created that let Homebrew ask a package, "Will you require the root password"? (I would assume there is already a dogma that packages must adhere to.)

**Comment by vitorgalvao** [comment] 2016-10-18 08:33
1. `grep` for the `pkg` stanza and you’ll get a starting idea (on a phone, now. Can’t do it).
2. Installing a `pkg`. Also, uninstalling things.
3. No. because we just install things, and try to be as close as possible to the manual installation, so we’re dependent on how the developers upstream decide to do it. Also, the system simply requires elevated privileges for some things. Unless you convinced every developer and Apple to work so these things wouldn’t require `sudo`, no chance.
4. In theory, evaluating casks with `pkg` would already do most of that.

I’ll add that some of this has already been discussed in the past, but there was lack of interest in actually implementing, so it was scrapped for more urgent things.

**Comment by forthrin** [comment] 2016-10-18 17:48
How about this:

1. Echo to the terminal the commands that requires the root password. A little or incomplete information is better than nothing.
1. grep for pkg, or whatever other easily detectable giveaway for a root password prompt. Then do either of the following:

A) Order these packages first in the installation queue, so the password prompt comes straight after starting the upgrade process. This also increases the chances of UNIX reusing the password.

B) Explicitly ask for the root password before starting the installation process, and then feed it to whatever password prompt occurs during an installation.

**Comment by MikeMcQuaid** [comment] 2016-10-18 18:08
> This also increases the chances of UNIX reusing the password.
> 
> Explicitly ask for the root password before starting the installation process, and then feed it to whatever password prompt occurs during an installation.

These two things make the process significantly less secure as now anything else can get unauthenticated root access for the duration of that process.

**Comment by forthrin** [comment] 2016-10-18 18:24
Good point. Homebrew maybe forces the prompt every time? Option A or C are still valid: Isolate the packages that require the root password so they don't abrupt the installation flow of those who don't.

**Comment by MikeMcQuaid** [comment] 2016-11-06 17:54
Closing this out as there doesn't seem to be forward motion on it but reopen if you disagree Cask folks.

**Closed by MikeMcQuaid** 2016-11-06 17:54 UTC
Labels: cask
