### ISSUE TITLE
Latest Xcode: "A newer Command Line Tools release is available"

### ISSUE THREAD

**Issue by 9mm** [Homebrew/brew#3560] opened 2017-12-11 18:18 UTC
When I'm running `brew doctor` I get the following warning:

```
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```

However, I have the [latest Xcode](https://developer.apple.com/news/releases/) installed: `Version 9.2 (9C40b)`. I also have it selected using `xcode-select` tool (or the Xcode GUI, same thing).

`brew` is fully up to date.

I'm using OSX `10.13.2 (17C88)`

**Brew Config**

```
~ » brew config
HOMEBREW_VERSION: 1.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: f42d8acde3907b90ea32cef01445744288984a4c
Last commit: 62 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dbceaf77dcc7c2552d58c7773a891ef7ea7eaf33
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/zesty/.rbenv/shims/ruby => /Users/zesty/.rbenv/versions/2.4.2/bin/ruby
Java: N/A
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.1.0.0.1.1508540944
X11: N/A
```

**Brew Doctor**

```
~ » brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config
```

**Comment by scpeters** [comment] 2017-12-11 18:28
I'm seeing the same problem on my sierra and high sierra machines that have CLT 9.1.0.0.1.1508540944 but no Xcode installed. I've looked for updates in the app store, but it doesn't show any updates for the CLT.

**Comment by scpeters** [comment] 2017-12-11 18:51
Potential temporary fix in #3562 until a new CLT version is available from the App Store.

**Comment by scpeters** [comment] 2017-12-11 18:55
This is a duplicate of #3555

**Comment by MikeMcQuaid** [comment] 2017-12-11 20:22
> If everything you use Homebrew for is working fine: please don't worry or file an issue; just ignore this.

Please, please read these messages.

**Closed by MikeMcQuaid** 2017-12-11 20:22 UTC
