### ISSUE TITLE
[DepthPacketStreamParser::onDataReceived] not all subsequences received 0

### ISSUE THREAD

**Issue by kafilah** [Homebrew/brew#94] opened 2016-04-15 19:43 UTC
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue.

### Feature Requests:

**Please note by far the quickest way to get a new feature into Homebrew is to file a [Pull Request](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by kafilah** [comment] 2016-04-15 19:44
[DepthPacketStreamParser::onDataReceived] not all subsequences received 0

I keep getting this every time I run a test!

**Comment by UniqMartin** [comment] 2016-04-15 21:46
Sorry, but from what you posted it's not obvious whether this is a Homebrew issue or what part of Homebrew the issue is related to. To help us debug this issue, can you explain:

- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by apjanke** [comment] 2016-04-18 19:11
This looks like an issue with the OpenKinect/`libfreenect` development library. While that can be installed via Homebrew, problems coding with it are probably not due to the Homebrew installation process, and it's not something we support beyond the installation.

I'm closing this out as not a Homebrew problem. If you think this is in fact an issue with Homebrew's installation of `libfreenect`, and not a problem with OpenKinect itself or your use of it, please re-open an issue on [the `homebrew/core` repo](https://github.com/homebrew/homebrew-core), where we track issues with individual formulae.

**Closed by apjanke** 2016-04-18 19:11 UTC
Labels: needs response
