### ISSUE TITLE
brew outdated --greedy-auto-updates shows up to date casks

### ISSUE THREAD

**Issue by gabrielwhite** [Homebrew/brew#13093] opened 2022-04-05 21:02 UTC
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 33709297cf9cb37605cf4efcb7151905baf8ccf5
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e33ac36ae8ac976c24e49c474899158d90b261ab
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-x86_64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew outdated --greedy-auto-updates 

### What happened (include all command output)?

brew outdated --greedy-auto-updates 
brave-browser (1.37.109.0,137.109) != 1.37.109.0,137.109
dropbox (145.4.4921) != 145.4.4921
firefox (98.0.2) != 98.0.2
google-chrome (100.0.4896.75) != 100.0.4896.75
zoom (5.10.1.5839) != 5.10.1.5839

(deleted a bunch of other applications, but you get the idea)

### What did you expect to happen?

No output, as all packages are up to date

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew outdated --greedy-auto-updates
```

**Comment by gabrielwhite** [comment] 2022-04-05 22:03
After reboot the problem went away. Leaving this issue open in case anyone else experiences the same.

**Comment by MikeMcQuaid** [comment] 2022-04-06 09:05
> After reboot the problem went away. Leaving this issue open in case anyone else experiences the same.

Closing if you can't reproduce this.

**Closed by MikeMcQuaid** 2022-04-06 09:05 UTC
Labels: bug
