### ISSUE TITLE
Something wrong with command brew vendor-gems

### ISSUE THREAD

**Issue by JuPlutonic** [Homebrew/brew#5812] opened 2019-02-26 10:58 UTC
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
n/w
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
n/w
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?
n/w

# What you were trying to do (and why)

I'm tested ```brew vendor-gems``` command what actually works but after ```brew cleanup``` command all brew commands exept ```brew style``` produce errors.

# What happene/Step-by-step reproduction instructions

<details>
  <summary>Command output</summary>
  <pre>
>brew cleanup
Removing: /home/linuxbrew/.linuxbrew/Cellar/autoconf-archive/2018.03.13... (585 files, 3.6MB)
Removing: /home/linuxbrew/.linuxbrew/Cellar/libdrm/2.4.94... (81 files, 1MB)
Warning: Skipping mpd: most recent version 0.21.4_4 not installed
Warning: Skipping qt: most recent version 5.12.1 not installed
Warning: Skipping qwt: most recent version 6.1.3_5 not installed
Warning: Skipping linuxbrew/xorg/xkeyboardconfig: most recent version 2.26 not installed
Removing: /home/salessionato/.cache/Homebrew/go_cache... (4,242 files, 85.7MB)
Pruned 103 symbolic links and 4 directories from /home/linuxbrew/.linuxbrew
Removing rubocop (0.64.0)
>brew doctor

/media/salessionato/Ruby/ruby/.rbenv/versions/2.4.5/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
	from /media/salessionato/Ruby/ruby/.rbenv/versions/2.4.5/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:10:in `<top (required)>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:21:in `require_relative'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:21:in `<main>'
  </pre>
</details>

# To resolve the issue you need to execute brew style command

**Comment by MikeMcQuaid** [comment] 2019-02-26 11:00
> [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
> [ ] ran `brew config` and `brew doctor` and included their output with your issue?

You need to do these.

Duplicate of https://github.com/Homebrew/brew/issues/5798.

@JuPlutonic Please slow down and write better, more detailed issues (and PRs) and follow all the requested steps.

**Closed by MikeMcQuaid** 2019-02-26 11:00 UTC
