### ISSUE TITLE
ended up with homebrew in /usr/local *and* /usr/local/Homebrew and now totally stuck

### ISSUE THREAD

**Issue by nrser** [Homebrew/brew#1081] opened 2016-09-22 12:07 UTC
### Bug reports:

i'm guessing that homebrew moved it's installation location from `/usr/local` to /usr/local/Homebrew` or something, and did so automagically at some point?

i ran a system sync script that installs homebrew (via git checkout) into `/usr/local` and seems to have ended up with it installed in **both** locations.

it still says here that it's highly recommended to install it to `/usr/local`:

https://github.com/Homebrew/brew/blob/master/docs/Installation.md#installation

this is really confusing. is there documentation somewhere of what was changed and where and how everything should be now? i need to update that script. should users **only** be installing from the install script from now on?

further details for people that might hit the same issues...

i started getting this error:

```
$ brew upgrade
Checking out v1.0.1 in /usr/local...
To checkout v1.0.1 in /usr/local run:
  'cd /usr/local && git checkout v1.0.1
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
zplug

==> Migrating HOMEBREW_REPOSITORY (please wait)...
Error: /usr/local/Homebrew already exists.
Please remove it manually or uninstall and reinstall Homebrew into a new
location as the migration cannot be done automatically.
```

i did

```
rm -rf /usr/local/Homebrew
cd /usr/local
git reset --hard origin/master
git checkout 1.0.1 # not sure if this was needed
brew upgrade # this triggered did the migration to /usr/local/Homebrew
```

and now i'm only getting the bug form #1079, which i guess is getting addressed:

```
$ brew upgrade
Checking out v1.0.1 in /usr/local/Homebrew...
To checkout v1.0.1 in /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git checkout v1.0.1

$ cd /usr/local/Homebrew && git checkout v1.0.1
Already on 'v1.0.1'
```

things seems to work now besides that message, but i'm not totally sure.

**Comment by zmwangx** [comment] 2016-09-22 12:08
You can completely ignore the v1.0.1 message.

**Comment by spool** [comment] 2016-09-22 13:13
Here's what I got: 
```
$ brew update
Checking out v1.0.1 in /usr/local/Homebrew...
To checkout master in /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git checkout master
Checking out v1.0.1 in /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
To checkout master in /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask run:
  'cd /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.1' at the same time.
Did you intend to checkout 'refs/tags/1.0.1' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.1
Checking out v1.0.1 in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
To checkout master in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.1' at the same time.
Did you intend to checkout 'refs/tags/1.0.1' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.1
Checking out v1.0.1 in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes...
To checkout master in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.1' at the same time.
Did you intend to checkout 'refs/tags/1.0.1' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.1
Checking out v1.0.1 in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science...
To checkout master in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.1' at the same time.
Did you intend to checkout 'refs/tags/1.0.1' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.1
Checking out v1.0.1 in /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac...
To checkout master in /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac run:
  'cd /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.1' at the same time.
Did you intend to checkout 'refs/tags/1.0.1' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.1
Already up-to-date.
Checking out v1.0.1 in /usr/local/Homebrew...
To checkout v1.0.1 in /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git checkout v1.0.1
```
Just updating again I get:
```
$ brew update
Checking out v1.0.1 in /usr/local/Homebrew...
To checkout v1.0.1 in /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git checkout v1.0.1
Updated 4 taps (caskroom/cask, homebrew/core, homebrew/games, homebrew/science).
```
Is that what correct?

**Comment by zmwangx** [comment] 2016-09-22 13:40
@spool You should be good now.

**Comment by spool** [comment] 2016-09-22 13:44
@zmwangx Thanks very much. The `'cd /usr/local/Homebrew && git checkout v1.0.1` might lead to confusion for others. May be worth amending that message to avoid worry.

**Comment by MikeMcQuaid** [comment] 2016-09-22 14:09
Message has been fixed and will be released 🔜

**Comment by MikeMcQuaid** [comment] 2016-09-22 14:21
Released, run `brew update`.

**Comment by MikeMcQuaid** [comment] 2016-09-22 14:22
(twice)

**Closed by MikeMcQuaid** 2016-09-22 14:21 UTC

**Comment by spool** [comment] 2016-09-22 14:33
Still get this:

```
$ brew update
Checking out v1.0.1 in /usr/local/Homebrew...
To checkout v1.0.1 in /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git checkout v1.0.1
Already up-to-date.
```

**Comment by MikeMcQuaid** [comment] 2016-09-24 15:22
@spool You can safely ignore that and it will go away in future.

**Comment by WonderCsabo** [comment] 2016-10-09 14:09
@MikeMcQuaid i am still getting the error message as the OP, although i have a new version:

```sh
$ brew update
...
==> Migrating HOMEBREW_REPOSITORY (please wait)...
Error: /usr/local/Homebrew already exists.
Please remove it manually or uninstall and reinstall Homebrew into a new
location as the migration cannot be done automatically.
$ brew --version
Homebrew 1.0.6
Homebrew/homebrew-core (git revision ac62; last commit 2016-10-09)
```

**Comment by MikeMcQuaid** [comment] 2016-10-09 14:19
@WonderCsabo I guess I need to improve that message. Is it unclear what you need to do from reading it?

**Comment by WonderCsabo** [comment] 2016-10-09 15:27
Sorry, somehow i mixed up the comments in this thread and thought i should ignore this message because it will go away. But now i see that was for another error. I now deleted the `/usr/local/Homebrew` folder.

**Comment by paulhybryant** [comment] 2016-10-18 05:52
Hi,

In my machine, homebrew is migrated to /usr/local/Homebrew, but the binaries are still symlinked in /usr/local/bin.

Is that expected? 

Or the expected behavior is that binaries should be linked in /usr/local/Homebrew/bin and I need to add that in the PATH?

Thanks,

**Comment by MikeMcQuaid** [comment] 2016-10-18 06:50
> In my machine, homebrew is migrated to /usr/local/Homebrew, but the binaries are still symlinked in /usr/local/bin.
> 
> Is that expected?

Yep, that's expected.

**Comment by paulhybryant** [comment] 2016-10-18 07:13
Thanks @MikeMcQuaid 
If I reinstall homebrew from scratch, is it still the same (binaries are symlinked to /usr/local/bin)?

Just want to make sure this is not specific to homebrew migrated from an existing installation.

**Comment by MikeMcQuaid** [comment] 2016-10-18 07:17
That's the same locations as you'll get for a clean install, yep.

**Comment by paulhybryant** [comment] 2016-10-18 08:03
Is it possible to have homebrew symlink the binaries somewhere else?
Is the only way to do that is to install homebrew to non-standard location?

**Comment by MikeMcQuaid** [comment] 2016-10-18 08:04
If you have the binaries symlinked somewhere else you cannot use many of our binary packages and would have to install to a non-standard location, yes.

**Comment by paulhybryant** [comment] 2016-10-18 08:19
ok. Thank you!
