### ISSUE TITLE
Shimmed make is silencing warnings even with --verbose

### ISSUE THREAD

**Issue by jtanx** [Homebrew/brew#1034] opened 2016-09-20 05:03 UTC
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

I was running into an issue where what should have been outputting a ton of warnings gave off no warnings at all - example build log: https://travis-ci.org/fontforge/fontforge/jobs/161231014

And I was very perplexed. Some further digging suggests that the shimmed make which makes use of xcrun which is also shimmed is piping the output to /dev/null? This is totally unexpected behaviour, as I should be able to see all warnings when building with `--verbose`.

If I just run `/usr/bin/xcrun /usr/bin/make` (from within the interactive shell), warnings appear as they should, but whatever the xcrun shim is doing is dumping all warnings into the void.

---

Just tried - `--env=std` doesn't help.

**Comment by MikeMcQuaid** [comment] 2016-09-26 08:49
Thanks for the bug report. Just to let you know that this write-up is good and it's on my list of things to work on.

**Comment by ilovezfs** [comment] 2016-11-14 13:35
This should probably be reserved for debug mode.

**Comment by MikeMcQuaid** [comment] 2017-08-05 16:59
This is no longer on my list of things to work on but I'll happily help someone else who wishes to do so.

**Comment by amyspark** [comment] 2017-12-03 01:03
Are there any (easy) examples to trigger this? AFAIK everything is rerouted to the log:
https://github.com/Homebrew/brew/blob/780e86904beff771e9f7e90fa9e53dd9dc4aeeaf/Library/Homebrew/formula.rb#L1863
and printed only in case of failure:
https://github.com/Homebrew/brew/blob/780e86904beff771e9f7e90fa9e53dd9dc4aeeaf/Library/Homebrew/formula.rb#L1776-L1796

**Comment by jtanx** [comment] 2017-12-03 02:03
It's been a long time since I bothered looking at Homebrew, so not sure of an easy example. But easy enough is what does the output from a current build of FontForge (from Homebrew) look like?

Compare against our Travis build which runs without: https://travis-ci.org/fontforge/fontforge/jobs/310179410

There are a ton of compiler warnings, which should show up similarly when built under Homebrew.

**Comment by amyspark** [comment] 2017-12-03 13:08
@jtanx Thanks for the tip.
Redirecting `stderr` to the log file prevents the warnings from showing up. Perhaps we should *copy* `$stderr` output to both screen and log when using `--verbose`? E.g. like this [stackoverflow question](https://stackoverflow.com/questions/9433924/how-can-i-copy-stdout-to-a-file-without-stopping-it-showing-onscreen-using-ruby) .

**Comment by MikeMcQuaid** [comment] 2018-01-24 10:47
> AFAIK everything is rerouted to the log

I'm going to close this as "expected behaviour" then (partly as well because it's been literally years with no work on it). Sorry!

**Closed by MikeMcQuaid** 2018-01-24 10:47 UTC
Labels: help wanted
