### ISSUE TITLE
Postinstall fails for openssl@1.1 and gnutls formula on Apple Silicon Mac

### ISSUE THREAD

**Issue by brentward** [Homebrew/brew#10181] opened 2020-12-29 17:00 UTC
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? (ran brew doctor but the issues it reported were wrong, noted in gist)
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (No logs)
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
brew config: https://gist.github.com/brentward/8ad7e0812089b9fe9499d7a283ef1d98
brew doctor: https://gist.github.com/brentward/15cfc06631a70668534bb962a73f3316

## What you were trying to do (and why)

On Apple Silicon Mac when brew installed openssl@1.1 and gnutls as dependencies for pyenv and gpg respectively I got warnings: 
```
==> Installing pyenv dependency: openssl@1.1
==> Pouring openssl@1.1-1.1.1i.arm64_big_sur.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openssl@1.1`
```
and 
```
==> Installing gnupg dependency: gnutls
==> Pouring gnutls-3.6.15.arm64_big_sur.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall gnutls`
```
respectively. So I attempted the postinstall commands as instructed

## What happened (include command output)

<details>
  <summary>Command output of: brew postinstall openssl@1.1</summary>
  <pre>

 ```
❯ brew postinstall openssl@1.1 -dv
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Postinstalling openssl@1.1
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201229-26088-ca0bns.sb nice ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/postinstall.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openssl@1.1`
==> An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - security

/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:124:in ``'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:124:in `macos_post_install'
/opt/homebrew/Library/Homebrew/extend/os/mac/on_os.rb:8:in `on_macos'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:115:in `post_install'
/opt/homebrew/Library/Homebrew/formula.rb:1062:in `block (2 levels) in run_post_install'
/opt/homebrew/Library/Homebrew/formula.rb:904:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1061:in `block in run_post_install'
/opt/homebrew/Library/Homebrew/utils.rb:530:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1050:in `run_post_install'
/opt/homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```
 </pre>
</details>
<details>
  <summary>Command output of: brew postinstall gnutls</summary>
  <pre>

```
❯ brew postinstall gnutls -dv     
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb
==> Postinstalling gnutls
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201229-26242-1g3cec.sb nice ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/postinstall.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall gnutls`
==> An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - security

/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:73:in ``'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:73:in `post_install'
/opt/homebrew/Library/Homebrew/formula.rb:1062:in `block (2 levels) in run_post_install'
/opt/homebrew/Library/Homebrew/formula.rb:904:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1061:in `block in run_post_install'
/opt/homebrew/Library/Homebrew/utils.rb:530:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1050:in `run_post_install'
/opt/homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```
  </pre>
</details>

## What you expected to happen

Postintall scripts should have ran without failing due to an exception. Both of them seem to be failing doing the same thing which is it can't find the security command when run in backticks like this: ```certs_list = `security find-certificate -a -p #{keychains.join(" ")}` ```
here: https://github.com/Homebrew/homebrew-core/blob/239ebee1f006dd5dcd658e5603936decc1aea4dc/Formula/openssl%401.1.rb#L124
and here: https://github.com/Homebrew/homebrew-core/blob/239ebee1f006dd5dcd658e5603936decc1aea4dc/Formula/gnutls.rb#L73

## Step-by-step reproduction instructions (by running `brew install` commands)

This can be reproduced by executing:
```
brew install pyenv
brew postinstall openssl@1.1
```
and
```
brew install gpg
brew postinstall gnutls
```

**Comment by brentward** [comment] 2020-12-30 00:18
Ok.

I'm not sure if this is helpful at all but I was able to do the relevant stuff from the postinstall method in my own ruby script file and generate what looks to me like a correct cert.pem file. So my system does have the ability to run what is in the postinstall script under some environments. 

My script was:
```
require 'english'

keychains = %w[
  /System/Library/Keychains/SystemRootCertificates.keychain
]

certs_list = `security find-certificate -a -p #{keychains.join(" ")}`
certs = certs_list.scan(
  /-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----/m,
)
valid_certs = certs.select do |cert|
  IO.popen("/opt/homebrew/Cellar/openssl@1.1/1.1.1i/bin/openssl x509 -inform pem -checkend 0 -noout >/dev/null", "w") do |openssl_io
    openssl_io.write(cert)
    openssl_io.close_write
  end
  $CHILD_STATUS.success?
end

opensslcert = File.new("./cert.pem", "w+")
opensslcert.write(valid_certs.join("\n") << "\n")
```

**Comment by MikeMcQuaid** [comment] 2020-12-31 13:15
I'm afraid closing this because we can't reproduce or until we've got multiple users reporting this issue.

**Closed by MikeMcQuaid** 2020-12-31 13:15 UTC
