### ISSUE TITLE
ghostscript build fails due to bad SHA for patch

### ISSUE THREAD

**Issue by apjanke** [Homebrew/brew#12550] opened 2021-12-11 22:22 UTC
### `brew config` output

```shell
janke@catawba ~ % brew config
HOMEBREW_VERSION: 3.3.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: dbec9de77ebc65a4845a5e672950219aa19b35b8
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c30e800a8fc987040875b6ad8450dc3075caea13
Core tap last commit: 15 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode-12.4.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4 => /Applications/Xcode-12.4.app/Contents/Developer
janke@catawba ~ %
```

### `brew doctor` output

```shell
janke@catawba ~ % brew doctor
Your system is ready to brew.
janke@catawba ~ %
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install ghostscript from source (so I can install it to an alternate prefix).

```
brew install -s ghostscript
```

### What happened (include all command output)?

Fails due to a SHA mismatch on one of the patch files.

```
janke@catawba ~ % brew update
Already up-to-date.
janke@catawba ~ % brew install -s ghostscript
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/manifests/0.29.2_3
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/ac691fc7ab8ecffba32a837e7197101d271474a3a84cfddcc30c9fd6763ab3c6--pkg-config-0.29.2_3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/blobs/sha256:80f141e695f73bd058fd82e9f539dc67471666f
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/2eb97c6a59faa873b2307277af0934389d877dfb814a19277ededd6d4e9ced87--pkg-config--0.29.2_3.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libpng/manifests/1.6.37
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/e6be7ba72607e72eff6fd2dc3cbad15128f3b3b35a78f2578706d2a8be708f8b--libpng-1.6.37.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libpng/blobs/sha256:c8e74da602c21f978cd7ee3d489979b4fc6681e71f6
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/323c61143c0e0d0382cfab972bab9dc9e090dcb712c4ab4a55e82f8a49119ed0--libpng--1.6.37.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/freetype/manifests/2.11.0
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/6fc9daabfd87e1ebb1707b1edfc1d3cb1ac44c91a6af0bdbd3a4e9ea0d01c9af--freetype-2.11.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/freetype/blobs/sha256:619ef51d198b0c4451e55d02f750c0f8f41614dcf
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/5a5e93a47089a9647ded7af8dc7cd8099957c09daf9e7f7f6214ebb7cd2b4aa7--freetype--2.11.0.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/fontconfig/manifests/2.13.1
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/debaf44112be1164e2f8ede78309c5b2b410920f922624d7cc4c2e19b137a850--fontconfig-2.13.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/fontconfig/blobs/sha256:64ff208b28613dfe2a65b9d74fd9b0129f3ca7e
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/474112b9deeab1c2d87e486a4e9a4600ac5d7e1f49c86ef9a1398e0a0405fd41--fontconfig--2.13.1.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/jbig2dec/manifests/0.19
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/7ccee54c3223d3dac8893faecaf641cbaa6e7032422a6edff1a185f73b0b19cd--jbig2dec-0.19.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/jbig2dec/blobs/sha256:7e70d2b2472b4116d1f98b7518f124067dbfa8e4d
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/cd56b6997f7f4f11d6d27104534216c75f3a8d8fbf01c6641275e69d1daefcf3--jbig2dec--0.19.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/jpeg/manifests/9d
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/836c7f243edc4d36e975f06b8d15317160e5e980aef89cde50019a7de8e441f3--jpeg-9d.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/jpeg/blobs/sha256:8f7b82a952fb3937889c7f22da1403e5338cd32049591
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/f004521bfea5d1da4a36ef1fcf2b07881587785b81a93eff01c9f2c7d393139d--jpeg--9d.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libidn/manifests/1.38
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/b606009980d04ef3c224db0f19854dd91004ec10fcdf9214505295e3558e3bda--libidn-1.38.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libidn/blobs/sha256:ce069c2b604d6dd0194541bc510a43d0e1eecacd816
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/71f655342f306303d71b9fa31329f63be831fdbc46ba8aaee005a2854270720a--libidn--1.38.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/manifests/4.3.0
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/c24b87e3eea7ffd536298b1b0782aa3506514ec9547e00fd90cde106f050376a--libtiff-4.3.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/blobs/sha256:e413c1170e33242eb941683d14ae51de594a013b8c
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/58b198db790cd0284de3cafcd9915fe5822a21c0e003a3275ecd3203f932d4ae--libtiff--4.3.0.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/little-cms2/manifests/2.12
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/8e1a3605b9203cec4705fe33526153ef223c608a4645c2e1c0edec97a07166db--little-cms2-2.12.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/little-cms2/blobs/sha256:0f782fa69d2e12e9c1765df4ae1b7bd8714340
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/5a0db77e2bd9ef584ab1c39bc7fb095e4a2bb7f31248778c5cb5eb6c290882bf--little-cms2--2.12.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/openjpeg/manifests/2.4.0
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/6494a703dabcd1098ca6282f8458da18046343c1762c906434cd061384f0b9d0--openjpeg-2.4.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/openjpeg/blobs/sha256:80426609c75b98ee0ee394e9017bb621dc73dd2d6
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/928e62e88269d7b55a9cc163a2718ed956fa8983819c89c2cd0ceebb56f2965c--openjpeg--2.4.0.catalina.bottle.tar.gz
==> Downloading http://git.ghostscript.com/?p=ghostpdl.git;a=patch;h=830afae5454dea3bff903869d82022306890a96c
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/e76c7e0ae52dbd20f28f187e9cb784e87ef49e8e4b35de8635499754be1d0d6c--ghostpdl.git-830afae5454dea3bff903869d82022306890a96c.patch
Error: ghostscript: SHA256 mismatch
Expected: b0b7a042e50f3eb5f7de8f8e833397953f8730030c71572ae372f44f7144c9bb
  Actual: 9c282e3f732b5c182ab761e187850d9f4c29d938a93e3785d9cb6ced13111d6c
    File: /Users/janke/Library/Caches/Homebrew/downloads/e76c7e0ae52dbd20f28f187e9cb784e87ef49e8e4b35de8635499754be1d0d6c--ghostpdl.git-830afae5454dea3bff903869d82022306890a96c.patch
To retry an incomplete download, remove the file above.
janke@catawba ~ % rm /Users/janke/Library/Caches/Homebrew/downloads/e76c7e0ae52dbd20f28f187e9cb784e87ef49e8e4b35de8635499754be1d0d6c--ghostpdl.git-830afae5454dea3bff903869d82022306890a96c.patch
janke@catawba ~ % brew install -s ghostscript
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/manifests/0.29.2_3
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/ac691fc7ab8ecffba32a837e7197101d271474a3a84cfddcc30c9fd6763ab3c6--pkg-config-0.29.2_3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/blobs/sha256:80f141e695f73bd058fd82e9f539dc67471666f
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/2eb97c6a59faa873b2307277af0934389d877dfb814a19277ededd6d4e9ced87--pkg-config--0.29.2_3.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libpng/manifests/1.6.37
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/e6be7ba72607e72eff6fd2dc3cbad15128f3b3b35a78f2578706d2a8be708f8b--libpng-1.6.37.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libpng/blobs/sha256:c8e74da602c21f978cd7ee3d489979b4fc6681e71f6
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/323c61143c0e0d0382cfab972bab9dc9e090dcb712c4ab4a55e82f8a49119ed0--libpng--1.6.37.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/freetype/manifests/2.11.0
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/6fc9daabfd87e1ebb1707b1edfc1d3cb1ac44c91a6af0bdbd3a4e9ea0d01c9af--freetype-2.11.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/freetype/blobs/sha256:619ef51d198b0c4451e55d02f750c0f8f41614dcf
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/5a5e93a47089a9647ded7af8dc7cd8099957c09daf9e7f7f6214ebb7cd2b4aa7--freetype--2.11.0.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/fontconfig/manifests/2.13.1
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/debaf44112be1164e2f8ede78309c5b2b410920f922624d7cc4c2e19b137a850--fontconfig-2.13.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/fontconfig/blobs/sha256:64ff208b28613dfe2a65b9d74fd9b0129f3ca7e
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/474112b9deeab1c2d87e486a4e9a4600ac5d7e1f49c86ef9a1398e0a0405fd41--fontconfig--2.13.1.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/jbig2dec/manifests/0.19
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/7ccee54c3223d3dac8893faecaf641cbaa6e7032422a6edff1a185f73b0b19cd--jbig2dec-0.19.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/jbig2dec/blobs/sha256:7e70d2b2472b4116d1f98b7518f124067dbfa8e4d
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/cd56b6997f7f4f11d6d27104534216c75f3a8d8fbf01c6641275e69d1daefcf3--jbig2dec--0.19.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/jpeg/manifests/9d
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/836c7f243edc4d36e975f06b8d15317160e5e980aef89cde50019a7de8e441f3--jpeg-9d.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/jpeg/blobs/sha256:8f7b82a952fb3937889c7f22da1403e5338cd32049591
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/f004521bfea5d1da4a36ef1fcf2b07881587785b81a93eff01c9f2c7d393139d--jpeg--9d.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libidn/manifests/1.38
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/b606009980d04ef3c224db0f19854dd91004ec10fcdf9214505295e3558e3bda--libidn-1.38.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libidn/blobs/sha256:ce069c2b604d6dd0194541bc510a43d0e1eecacd816
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/71f655342f306303d71b9fa31329f63be831fdbc46ba8aaee005a2854270720a--libidn--1.38.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/manifests/4.3.0
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/c24b87e3eea7ffd536298b1b0782aa3506514ec9547e00fd90cde106f050376a--libtiff-4.3.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/blobs/sha256:e413c1170e33242eb941683d14ae51de594a013b8c
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/58b198db790cd0284de3cafcd9915fe5822a21c0e003a3275ecd3203f932d4ae--libtiff--4.3.0.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/little-cms2/manifests/2.12
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/8e1a3605b9203cec4705fe33526153ef223c608a4645c2e1c0edec97a07166db--little-cms2-2.12.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/little-cms2/blobs/sha256:0f782fa69d2e12e9c1765df4ae1b7bd8714340
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/5a0db77e2bd9ef584ab1c39bc7fb095e4a2bb7f31248778c5cb5eb6c290882bf--little-cms2--2.12.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/openjpeg/manifests/2.4.0
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/6494a703dabcd1098ca6282f8458da18046343c1762c906434cd061384f0b9d0--openjpeg-2.4.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/openjpeg/blobs/sha256:80426609c75b98ee0ee394e9017bb621dc73dd2d6
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/928e62e88269d7b55a9cc163a2718ed956fa8983819c89c2cd0ceebb56f2965c--openjpeg--2.4.0.catalina.bottle.tar.gz
==> Downloading http://git.ghostscript.com/?p=ghostpdl.git;a=patch;h=830afae5454dea3bff903869d82022306890a96c
######################################################################## 100.0%
Error: ghostscript: SHA256 mismatch
Expected: b0b7a042e50f3eb5f7de8f8e833397953f8730030c71572ae372f44f7144c9bb
  Actual: 9c282e3f732b5c182ab761e187850d9f4c29d938a93e3785d9cb6ced13111d6c
    File: /Users/janke/Library/Caches/Homebrew/downloads/e76c7e0ae52dbd20f28f187e9cb784e87ef49e8e4b35de8635499754be1d0d6c--ghostpdl.git-830afae5454dea3bff903869d82022306890a96c.patch
To retry an incomplete download, remove the file above.
janke@catawba ~ %
```

### What did you expect to happen?

Builds and installs without errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew install -s ghostscript
```
```

**Comment by Bo98** [comment] 2021-12-11 22:46
Duplicate of https://github.com/Homebrew/homebrew-core/issues/90916. Should however be fixed now.

**Closed by Bo98** 2021-12-11 22:46 UTC
Labels: bug

**Comment by apjanke** [comment] 2021-12-12 00:41
It's fixed now. Thanks! Sorry for filing the bug in the wrong place.
