### ISSUE TITLE
Crash in xquartz.rb: Error: undefined method `/' for nil:NilClass

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#1585] opened 2016-11-27 15:50 UTC
The crash is
```
Error: undefined method `/' for nil:NilClass
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xquartz.rb:127:in `bin'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:22:in `homebrew_extra_paths'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:111:in `determine_path'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:45:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:89:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
iMac-TMP:~ joe$ 
```
___

reproducer (assuming xquartz is not installed):
```
brew install --ignore-dependencies pangox-compat
brew install -dvs gtkglext
```

reproducer (assuming xquartz is already installed via cask):
```
brew install pangox-compat
brew cask uninstall xquartz
brew install -dvs gtkglext
```

**Comment by vitorgalvao** [comment] 2016-11-27 15:58
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.
> (…)
> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.

**Comment by ilovezfs** [comment] 2016-11-27 16:18
@vitorgalvao sorry but it's totally unacceptable to close another maintainer's issue like that.

**Comment by vitorgalvao** [comment] 2016-11-27 17:13
@ilovezfs Oh, I very much apologise! I thought I was in HBC when I checked the issue. Completely my mistake

Again, I’m terribly sorry!

**Comment by ilovezfs** [comment] 2016-11-27 18:18
@vitorgalvao no worries :) Feel free to fix the bug as penance :p

**Comment by apjanke** [comment] 2017-01-13 07:43
I'm afraid I can't reproduce this. `pangox-compat` won't install (from the boneyard) on either El Cap or Sierra for me, and `brew install -dvs gtkglext` succeeds on both. I tried variations of installing and uninstalling `xquartz` and trying some other packages, and nothing triggered it. Any other way to reproduce? Which OS version was this on?

I took a look through the relevant `brew` code and have no idea what's causing this; it seems like all the calls to `XQuartz`'s `bin` are properly guarded with `installed?` checks.

**Comment by ilovezfs** [comment] 2017-01-13 09:13
You should be able to just revert core to before I killed off pangox-compat.

**Comment by ilovezfs** [comment] 2017-01-20 05:27
voilà: https://gist.github.com/ilovezfs/1729d82df679e3ec5696fa635619948c

**Comment by MikeMcQuaid** [comment] 2017-12-08 15:45
Chatted with @ilovezfs on Slack and this doesn't seem to be a common/recent problem and I'm pretty sure the recent X11 requirement changes addressed this so: closing.

**Comment by ilovezfs** [comment] 2017-12-08 15:55
This is actually still reproducible in the same way described above.

**Comment by ilovezfs** [comment] 2017-12-08 16:02
```
$ git -C "$(brew --repo homebrew/core)" show 0bd1a81^:Formula/pangox-compat.rb > "$(brew --repo homebrew/core)"/Formula/pangox-compat.rb
$ git -C "$(brew --repo homebrew/core)" checkout d2292b6^ -- Formula/gtkglext.rb 
$ brew install --ignore-dependencies pangox-compat
$ brew install -dvs gtkglext
```

**Comment by ilovezfs** [comment] 2017-12-08 16:21
Simpler reproducer:
```
iMac-TMP:homebrew-core joe$ git diff
diff --git a/Formula/lzip.rb b/Formula/lzip.rb
index c349894..097b96b 100644
--- a/Formula/lzip.rb
+++ b/Formula/lzip.rb
@@ -1,4 +1,5 @@
 class Lzip < Formula
+depends_on "xclip"
   desc "LZMA-based compression program similar to gzip or bzip2"
   homepage "http://www.nongnu.org/lzip/lzip.html"
   url "https://download.savannah.gnu.org/releases/lzip/lzip-1.19.tar.gz"
iMac-TMP:homebrew-core joe$ brew install --ignore-dependencies xclip
==> Downloading https://homebrew.bintray.com/bottles/xclip-0.13.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/xclip-0.13.el_capitan.bottle.tar.gz
==> Pouring xclip-0.13.el_capitan.bottle.tar.gz
Warning: xclip has broken dynamic library links:
  /opt/X11/lib/libXmu.6.dylib
  /opt/X11/lib/libX11.6.dylib
Rebuild this from source with:
  brew reinstall --build-from-source xclip
If that's successful, file an issue here:
  https://github.com/Homebrew/homebrew-core/issues
==> Summary
🍺  /usr/local/Cellar/xclip/0.13: 11 files, 65.8KB
iMac-TMP:homebrew-core joe$ brew install -dvs lzip
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lzip.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xclip.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/usr/bin/sandbox-exec -f /tmp/homebrew20171208-29979-26z7hs.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lzip.rb --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lzip.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xclip.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
Error: undefined method `/' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/os/mac/xquartz.rb:154:in `bin'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:24:in `homebrew_extra_paths'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:107:in `determine_path'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:42:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:91:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:192:in `<main>'
iMac-TMP:homebrew-core joe$
```

**Closed** 2017-12-09 20:47 UTC
Labels: in progress
