### ISSUE TITLE
fatal: unable to access '...': .netrc parser error

### ISSUE THREAD

**Issue by yermulnik** [Homebrew/brew#18726] opened 2024-11-06 22:43 UTC
### What were you trying to do (and why)?

`brew update` with `.netrc` file present in `$HOME` directory

### What happened (include all command output)?

```shell
> brew update
==> Updating Homebrew...
fatal: unable to access 'https://filippo.io/age/': .netrc parser error
fatal: unable to access 'https://github.com/Homebrew/brew/': .netrc parser error
fatal: unable to access 'https://str4d.xyz/rage/': .netrc parser error
Error: Fetching /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/filippo.io/homebrew-age failed!
Fetching /home/linuxbrew/.linuxbrew/Homebrew failed!
Fetching /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/str4d.xyz/homebrew-rage failed!
```

It's more of a FYI as the issue is with underlying cURL: https://github.com/curl/curl/issues/15496

**Comment by ZhongRuoyu** [comment] 2024-11-07 03:55
Thanks for the heads up. I'm closing this as there's currently nothing actionable from Homebrew's side. But we can update our curl when upstream ships a fix.

**Closed by ZhongRuoyu** 2024-11-07 03:55 UTC
Labels: bug

**Comment by mnasruul-xxi** [comment] 2024-11-07 05:56
Hello i have same error, but my action with golang private repository, before ist ok, but now error

**Comment by adamskicool** [comment] 2024-11-07 07:42
I have the same error as @mnasruul-xxi

**Comment by ZhongRuoyu** [comment] 2024-11-07 07:58
As a workaround you may run `brew` with system Git, like:

```
HOMEBREW_GIT_PATH=/usr/bin/git brew update
```

**Comment by LKaemmerling** [comment] 2024-11-07 08:44
In case someone else finds this, the root cause for alpine to be broken is a libcurl update to 8.11: https://github.com/curl/curl/issues/15496 

The curl team is already working on a fix.

**Comment by mnasruul-xxi** [comment] 2024-11-07 08:51
Thank you @LKaemmerling

**Comment by alfaruqii** [comment] 2024-11-07 09:56
> In case someone else finds this, the root cause for alpine to be broken is a libcurl update to 8.11: [curl/curl#15496](https://github.com/curl/curl/issues/15496)
> 
> The curl team is already working on a fix.

thanks for the information bro

**Comment by ZhongRuoyu** [comment] 2024-11-07 12:35
Homebrew curl will be updated when Homebrew/homebrew-core#196952 is merged in a few hours.

**Comment by ZhongRuoyu** [comment] 2024-11-07 15:42
The fix is in. You can now get it with `brew update && brew upgrade curl`.

**Comment by mellery451** [comment] 2024-11-08 16:26
this is still broken in brew on linux - is linux-brew updating at a different cadence ?

**Comment by mellery451** [comment] 2024-11-08 16:35
oh - wow. yes, I'm hitting the >128 char issue (the error message is basically the same unfortunately). should we build curl --HEAD to get this fix ?

**Comment by ZhongRuoyu** [comment] 2024-11-08 16:47
> should we build curl --HEAD to get this fix ?

I've opened Homebrew/homebrew-core#197094 to backport that fix to Homebrew curl too. Once that's merged, you can do `brew reinstall curl` to get the updated version. If you want it fixed now, `brew install --head curl` is also an option.

**Comment by ZhongRuoyu** [comment] 2024-11-08 23:36
FYI @mellery451: Homebrew/homebrew-core#197094 is now merged. You can now do `brew update && brew reinstall curl` to get the fix.

**Comment by mellery451** [comment] 2024-11-08 23:52
working now - thank you!
