### ISSUE TITLE
Update Failure When git's abbreviateCommands is TRUE

### ISSUE THREAD

**Issue by srguglielmo** [Homebrew/brew#7374] opened 2020-04-16 14:29 UTC
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was attempting to fetch the newest version of Homebrew and all formulae from GitHub while the git config option `rebase.abbreviateCommands` is true.

I perform git rebases routinely via CLI and prefer to have [the `rebase.abbreviateCommands` option](https://git-scm.com/docs/git-config#Documentation/git-config.txt-rebaseabbreviateCommands) enabled. However, I found that this breaks Homebrew. The issue is immediately resolved by setting the option to false (`git config --global rebase.abbreviateCommands false`).

## What happened (include command output)

Executing `brew update -v` while `rebase.abbreviateCommands` is true provides the following output (note the _"error: nothing to do"_):

<details>
  <summary>Command output</summary>
  <pre>
# brew update -v
Checking if we need to fetch /usr/local/Homebrew...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services...
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 8 (delta 6), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (8/8), 1.06 KiB | 216.00 KiB/s, done.
From https://github.com/Homebrew/homebrew-core
   d874b06712..9c6d32178a  master     -> origin/master
Updating /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
 Formula/futhark.rb | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)
error: nothing to do

Already up-to-date.
  </pre>
</details>

When checking the status of the above homebrew-core repo, you can see it _has_ been fetched, but _not_ merged forward:

<details>
  <summary>Command output</summary>
  <pre>
# git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core status
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.

nothing to commit, working tree clean
  </pre>
</details>

The upstream changes to GitHub/homebrew-core continue to pile up and, thus,`brew upgrade` never upgrades any packages.

## What you expected to happen

I expected Homebrew to fetch package updates successfully regardless of my personal `~/.gitconfig`.

## Step-by-step reproduction instructions (by running `brew` commands)

- `git config --global rebase.abbreviateCommands true` (only once to set config)
- `brew update; brew upgrade`

## Output of `brew config` and `brew doctor` commands

<pre>
# brew config
HOMEBREW_VERSION: 2.2.13-48-gd6ffbf5
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6ffbf5bb66e60d51e063926175e588c462aa6b3
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d874b06712ec20efd86f2fbf20e97aa2f24e9f5b
Core tap last commit: 38 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: vim -e
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_INSTALL_CLEANUP: set
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 11.4.0.0.1.1583798712
Xcode: N/A

# brew doctor
Your system is ready to brew.
</pre>

I'm not sure if this is a proper solution, but maybe the following two lines can be changed to `git -c rebase.abbreviateCommands=false rebase` to override the option (if set)? I can submit a PR if desired.

https://github.com/Homebrew/brew/blob/d6ffbf5bb66e60d51e063926175e588c462aa6b3/Library/Homebrew/cmd/update.sh#L256
https://github.com/Homebrew/brew/blob/d6ffbf5bb66e60d51e063926175e588c462aa6b3/Library/Homebrew/cmd/update.sh#L258 

Thanks,
Steve

**Comment by MikeMcQuaid** [comment] 2020-04-16 14:48
> I'm not sure if this is a proper solution, but maybe the following two lines can be changed to `git -c rebase.abbreviateCommands=false rebase` to override the option (if set)? I can submit a PR if desired.

We can confider that once we see this affecting multiple users. For now I'd advise you to alter your user or repo configuration accordingly. Thanks!

**Comment by MikeMcQuaid** [comment] 2020-04-16 14:53
Actually, it looks like https://github.com/Homebrew/homebrew-core/issues/52623 may be related.

I find it pretty confusing that `git` is making `git rebase` a no-op effectively based on a `git rebase -i` configuration flag? This sounds like a `git` bug to me. I'm ok with having a workaround but I think it's worth reporting to `git`, too.

**Comment by srguglielmo** [comment] 2020-04-16 15:03
> Actually, it looks like [Homebrew/homebrew-core#52623](https://github.com/Homebrew/homebrew-core/issues/52623) may be related.

Agreed; that looks exactly like the issue I've been having. The updates keep piling up.

> I find it pretty confusing that `git` is making `git rebase` a no-op effectively based on a `git rebase -i` configuration flag? This sounds like a `git` bug to me. I'm ok with having a workaround but I think it's worth reporting to `git`, too.

Agreed as well. I will submit the issue to git@vger.kernel.org within a day or two. Thanks!

**Comment by ericvw** [comment] 2020-04-16 15:12
I noticed this occurs when I upgraded `git >= 2.26` via Homebrew — the issue does not occur on `git < 2.26`.

https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.26.0.txt indicates that the backend changed for the default `git rebase`.

**Comment by MikeMcQuaid** [comment] 2020-04-16 15:14
@ericvw do you have the same Git configuration flag set (or anything similar)?

**Comment by ericvw** [comment] 2020-04-16 15:24
> @ericvw do you have the same Git configuration flag set (or anything similar)?

Yes — it turns out I do have `rebase.abbreviateCommands` set to `true`.  I have also confirmed when unsetting this configuration option that I don't observe the issue when running `brew update`.

**Comment by Bo98** [comment] 2020-04-16 16:41
Yes, it is related to the backend change. The issue is that with a simple fast forward results in a `noop` in the rebase, but `noop` has no abbreviated command so things break.

There was a patch posted on their mailing list: https://lore.kernel.org/git/20200330124236.6716-2-alban.gruin@gmail.com/ (easier viewing at https://github.com/agrn/git/commit/058d9c128c63b0a4849b384b358cca9bb19c56db) but there hasn't been progress in a couple of weeks.

**Comment by MikeMcQuaid** [comment] 2020-04-17 08:07
@Bo98 thoughts on:
1) pulling current version until we have a fixed version
2) having a temporary `brew update` workaround
3) applying that patch

?

**Comment by Bo98** [comment] 2020-04-17 09:52
While the bug is serious in the context of Homebrew (any fix will require users to first do `brew update-reset` or figure out there's something in their config that has worked for years that broke things), it doesn't seem to be seen as serious enough in the Git community for them to rush out a patch. Or fix it on `master` for that matter.

I'd lean on 2 or 3. Is Git installed outside of Homebrew a concern?

**Comment by MikeMcQuaid** [comment] 2020-04-17 09:58
> Is Git installed outside of Homebrew a concern?

Don't think so.

Other options:
4. just use the system Git if they have a bad Git version installed.
5. tell people to unset that configuration variable

**Comment by Bo98** [comment] 2020-04-17 10:16
3, 4 and potentially 5 will tie it to Git versions.

I suppose another question is removing the workaround in the future. If the workaround or warning is on brew's side then it should only be removed when we are confident everyone has moved off of 2.26.x (could be months). A patch in homebrew-core would be removed immediately when the issue is fixed and released.

**Comment by MikeMcQuaid** [comment] 2020-04-17 10:19
> A patch in homebrew-core would be removed immediately when the issue is fixed and released.

As much as I hate it: yeh, let's do that. The patch has been submitted upstream.

**Comment by Bo98** [comment] 2020-04-17 10:36
Yeah, a bug affecting `brew update` is about as serious as it gets. We've patched for less.

I'll get something together within the hour.

**Comment by Bo98** [comment] 2020-04-17 12:44
Homebrew/homebrew-core#53266

**Comment by MikeMcQuaid** [comment] 2020-04-18 12:40
Fixed by https://github.com/Homebrew/homebrew-core/pull/53266

**Closed by MikeMcQuaid** 2020-04-18 12:40 UTC
Labels: help wanted

**Comment by sluongng** [comment] 2020-04-26 06:46
This broke when I tried to `brew install --HEAD git` today as the patches do not applied cleanly

```
==> Downloading https://github.com/agrn/git/commit/058d9c128c63b0a4849b384b358cca9bb19c56db.patch?full_index=1
######################################################################## 100.0%
==> Patching
==> Applying 058d9c128c63b0a4849b384b358cca9bb19c56db.patch
patching file sequencer.c
Hunk #1 FAILED at 1578.
Hunk #2 FAILED at 4963.
Hunk #3 FAILED at 4973.
3 out of 3 hunks FAILED -- saving rejects to file sequencer.c.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/git--patch-20200426-53499-1uo0zs1/058d9c128c63b0a4849b384b358cca9bb19c56db.patch` exited with 1.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.
```

Could you please NOT putting a personal monkey patch file into the distribution?
And please link the upstream mailing list thread for tracking.

**Comment by jonchang** [comment] 2020-04-26 06:59
> Please create pull requests instead of asking for help on Homebrew's GitHub, Discourse, Twitter or IRC.
