### ISSUE TITLE
"Empty archive" error when install formulas with tar.xz archives, after upgrading to Xcode 8

### ISSUE THREAD

**Issue by zhouyan** [Homebrew/brew#969] opened 2016-09-15 09:17 UTC
I have just upgraded to Xcode 8 and run `xcode-select --install` after the upgrading. I tried to reinstall all formulas I had. And I encountered errors as the following, for example, when installing `git`,
```
$ brew install git --verbose
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160915-13630-1k3cym9.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/build.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/git.rb --verbose
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.10.0.tar.xz
Already downloaded: /Users/Zhou/Library/Caches/Homebrew/git-2.10.0.tar.xz
==> Verifying git-2.10.0.tar.xz checksum
Error: Empty archive
```
This error only happens with formulas using a source packed as `tar.xz` instead of `gz` or `bz2`. I tried to manually uncompress the package via `tar xf` and it works fine.

**Comment by MikeMcQuaid** [comment] 2016-09-15 09:21
Try to `brew uninstall --force xz`.

**Comment by zhouyan** [comment] 2016-09-15 09:34
I already tried that before submiting this issue. `xz` just got reinstalled back as a dependencies for those formulas and the same issue persists.

**Comment by mistydemeo** [comment] 2016-09-15 09:37
Can you install the CLT, then `brew reinstall xz`, and try again? This is a problem caused by having Xcode 8 on 10.11 without the CLT, which we'll be adding a warning for (#965).

**Comment by zhouyan** [comment] 2016-09-15 09:39
Both were done. The first thing I did was to install CLT even before I try to do anything with brew.

**Comment by mistydemeo** [comment] 2016-09-15 09:44
What happens if you run `xz` on the commandline?

**Comment by zmwangx** [comment] 2016-09-15 09:45
Or just `brew test xz`.

**Comment by zhouyan** [comment] 2016-09-15 09:49
`brew test xz` fail with the following

```
$ brew test xz
Testing xz
==> Using the sandbox
==> /usr/local/Cellar/xz/5.2.2/bin/xz /tmp/xz-test-20160915-23199-1gis089/data.txt
Last 15 lines from /Users/Zhou/Library/Logs/Homebrew/xz/test.01.xz:
2016-09-15 17:47:00 +0800

/usr/local/Cellar/xz/5.2.2/bin/xz
/tmp/xz-test-20160915-23199-1gis089/data.txt

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/xz/5.2.2/bin/xz
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/xz/5.2.2/bin/xz
  Expected in: /usr/lib/libSystem.B.dylib

Error: xz: failed
Failed executing: /usr/local/Cellar/xz/5.2.2/bin/xz /tmp/xz-test-20160915-23199-1gis089/data.txt
/usr/local/Library/Homebrew/formula.rb:1608:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1545:in `open'
/usr/local/Library/Homebrew/formula.rb:1545:in `system'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/xz.rb:35:in `block in <class:Xz>'
/usr/local/Library/Homebrew/formula.rb:1446:in `block (2 levels) in run_test'
/usr/local/Library/Homebrew/formula.rb:775:in `with_logging'
/usr/local/Library/Homebrew/formula.rb:1445:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1439:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

However, uncompress seems to work just fine. For example `cd ~/Library/Cache/Homebrew; tar xf whatever.tar.xz` works just fine.

**Comment by zmwangx** [comment] 2016-09-15 09:50
Your `/usr/bin/tar` has nothing to do with xz.

Typical Xcode 8 on El Cap debacle.

Please pour our bottle in the meantime rather than compile from source.

**Comment by zhouyan** [comment] 2016-09-15 09:54
OK, I guess I have just to wait a few more days for the new OS. It sounds like Xcode 8 on Sierra is better and it is only a problem of Xcode 8 on Ei Cap

**Comment by zmwangx** [comment] 2016-09-15 09:56
Here's some background reading: https://github.com/Homebrew/homebrew-core/issues/4809#issuecomment-247021138.

And https://github.com/Homebrew/brew/pull/970 will hopefully fix the problem.

**Comment by zmwangx** [comment] 2016-09-15 09:58
> I guess I have just to wait a few more days for the new OS.

By the way, be advised that if you need anything on [this list](https://github.com/Homebrew/homebrew-core/issues/4841) you'd better hold out a little longer.

**Comment by DomT4** [comment] 2016-09-15 11:38
Anyone impacted should `brew reinstall xz`. This should be fixed by ILZ's sterling work in https://github.com/Homebrew/brew/pull/970, but you'll need to reinstall the broken `xz`.

**Comment by zmwangx** [comment] 2016-09-17 18:11
Closing due to inactivity.

**Closed by zmwangx** 2016-09-17 18:11 UTC
