### ISSUE TITLE
concurrent / parallel downloader/installer of dependencies

### ISSUE THREAD

**Issue by hamza72x** [Homebrew/brew#14741] opened 2023-02-21 01:34 UTC
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Hey!

Do you guys have any plan to implement concurrent or parallel downloader/installer (specially for larger dependencies)?

It will be much faster for larger dependencies. For example, my wrapper achived around 50/60% time efficiency while installing `ffmpeg`: https://www.youtube.com/watch?v=VVfNutjzF64

Repo: https://github.com/hamza72x/brewc

If you guys plan to implement such feature, I am happy to collaborate.

### What is the motivation for the feature?

Increasing the efficiency of installation.

### How will the feature be relevant to at least 90% of Homebrew users?

It can be 50/60% faster for larger dependencies.

### What alternatives to the feature have been considered?

N/A

**Comment by carlocab** [comment] 2023-02-21 01:41
Duplicate of #13924

**Comment by carlocab** [comment] 2023-02-21 01:41
Thanks for the suggestion anyway!

**Closed by carlocab** 2023-02-21 01:41 UTC
Labels: features
