### ISSUE TITLE
Warning: Calling 'depends_on :python3' is deprecated!

### ISSUE THREAD

**Issue by jvanderen1** [Homebrew/brew#3717] opened 2018-01-22 08:30 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
```
Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'
```
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

`brew config` output
```HOMEBREW_VERSION: 1.5.0-21-g97f0ef4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 97f0ef4c49d0f2f2a62a82e7ca21945d7cbe2c7c
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 69f7494815e6643781ac221bb46450f94c848280
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_101, 1.8.0_31
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

`brew doctor` output
```
Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'

Your system is ready to brew.
```

To help us debug your issue please explain:

Similar to #3711, every time I run `brew update` or `brew doctor`, I get the same warning message.

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment] 2018-01-22 08:50
Thanks. We're aware as you already noticed, and it's fixed in master.

**Comment by ilovezfs** [comment] 2018-01-22 10:52
This should be fixed now if you `brew update`

**Comment by ilovezfs** [comment] 2018-01-23 09:30
What's the output of
```
find $(brew --cellar) -maxdepth 4 -mindepth 4 -regex '.*\.rb$' -exec grep -r 'depends_on :python3' "{}" \;
```
and
```
find $(brew --cache) -regex '.*\.rb$' -exec grep -r 'depends_on :python3' "{}" \;
```
and
```
grep -r 'depends_on :python3' /usr/local/Homebrew/Library/Taps
```

**Comment by aniss** [comment] 2018-01-23 10:02
@ilovezfs 

```
/usr/local/Cellar/boost-python/1.62.0/.brew/boost-python.rb:  depends_on :python3 => :optional
/usr/local/Cellar/boost-python/1.63.0/.brew/boost-python.rb:  depends_on :python3 => :optional
/usr/local/Cellar/boost-python/1.64.0/.brew/boost-python.rb:  depends_on :python3 => :optional
/usr/local/Cellar/boost-python/1.65.0/.brew/boost-python.rb:  depends_on :python3 => :optional
/usr/local/Cellar/boost-python/1.65.1/.brew/boost-python.rb:  depends_on :python3 => :optional
/usr/local/Cellar/boost-python/1.66.0/.brew/boost-python.rb:  depends_on :python3 => :optional
/usr/local/Cellar/matplotlib/1.5.1/.brew/matplotlib.rb:  depends_on :python3 => :optional
/usr/local/Cellar/matplotlib/2.0.0/.brew/matplotlib.rb:  depends_on :python3 => :optional
/usr/local/Cellar/matplotlib/2.0.0_1/.brew/matplotlib.rb:  depends_on :python3 => :optional
/usr/local/Cellar/matplotlib/2.0.1/.brew/matplotlib.rb:  depends_on :python3 => :optional
/usr/local/Cellar/matplotlib/2.0.2/.brew/matplotlib.rb:  depends_on :python3 => :optional
/usr/local/Cellar/numpy/1.11.2/.brew/numpy.rb:  depends_on :python3 => :optional
/usr/local/Cellar/numpy/1.12.0/.brew/numpy.rb:  depends_on :python3 => :optional
/usr/local/Cellar/numpy/1.12.1/.brew/numpy.rb:  depends_on :python3 => :optional
/usr/local/Cellar/numpy/1.13.0/.brew/numpy.rb:  depends_on :python3 => :optional
/usr/local/Cellar/numpy/1.13.1/.brew/numpy.rb:  depends_on :python3 => :optional
/usr/local/Cellar/numpy/1.13.1_1/.brew/numpy.rb:  depends_on :python3 => :recommended
/usr/local/Cellar/numpy/1.13.3/.brew/numpy.rb:  depends_on :python3 => :recommended
/usr/local/Cellar/pillow/3.4.2/.brew/pillow.rb:  depends_on :python3 => :optional
/usr/local/Cellar/pillow/4.1.0/.brew/pillow.rb:  depends_on :python3 => :optional
/usr/local/Cellar/pillow/4.1.1/.brew/pillow.rb:  depends_on :python3 => :optional
/usr/local/Cellar/pillow/4.2.0/.brew/pillow.rb:  depends_on :python3 => :optional
/usr/local/Cellar/pillow/4.2.1/.brew/pillow.rb:  depends_on :python3 => :optional
```

The two last commands return an empty.

**Comment by ilovezfs** [comment] 2018-01-23 10:07
OK. What is the output of `brew config` now?

And if you
```
brew uninstall -f --ignore-dependencies boost-python matplotlib numpy pillow
```
does it fix it?

**Comment by aniss** [comment] 2018-01-23 14:40
@ilovezfs Yep. 👍 cheers.

**Comment by jvanderen1** [comment] 2018-01-23 14:54
@ilovezfs I did something very similar and the issue was fixed for me as well.

**Comment by ilovezfs** [comment] 2018-01-23 14:55
@jvanderen1 Can you elaborate? This shouldn't be happening at all unless it's a current version of a formula still in a tap.

**Comment by jvanderen1** [comment] 2018-01-23 15:04
For me, I had two dependencies, being `matplotlib` and `numpy`. After I uninstalled them, I reinstalled them, and now the `depends_on :python3' is deprecated!` message does not appear.

**Comment by ilovezfs** [comment] 2018-01-23 15:06
@jvanderen1 what does `brew config` show for you

**Comment by jvanderen1** [comment] 2018-01-23 15:06
After running `brew config`:
```
HOMEBREW_VERSION: 1.5.1-3-ge056e85
ORIGIN: https://github.com/Homebrew/brew
HEAD: e056e85078c5a8e79d187508cf391b9cd47ab2cf
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 23098a60e159640da6a287baa7327903ad34b64f
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_101, 1.8.0_31
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

**Comment by ilovezfs** [comment] 2018-01-23 15:11
@jvanderen1 where was the matplotlib installed from?

**Comment by jvanderen1** [comment] 2018-01-23 15:16
@ilovezfs (Off the top of my head) I wanna say `matplotlib` was installed from homebrew. However, I couldn't find it using `brew search matplotlib`. So for the new install, I used `pip3 -mpip install matplotlib`.

**Comment by ilovezfs** [comment] 2018-01-23 15:17
OK I think I know what's going on.

**Comment by fish2000** [comment] 2018-01-23 22:05
@ilovezfs please do share – for at least a week now, I have been getting these sorts of warning messages, tacked onto the tail end of `brew update` output or at the start of what `brew upgrade` prints:

![screen shot 2018-01-23 at 4 48 43 pm](https://user-images.githubusercontent.com/378969/35302784-c0d694a0-005d-11e8-967e-5604aba2174a.jpg)

… in my case, the warnings cited described their root causes as either e.g. the use of a symbol instead of a string in a dependency declaration – of which there were, like, two or three, all from my own personal tap, all of which I immediately fixed and pushed – but then all the rest were showing source lines corresponding not to formulae but to `[dependency_collector.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/os/mac/dependency_collector.rb)`, an internal part of Homebrew’s core. 

While I am neither a Rubyist nor a Homebrew-ist of any note, I did look at the source in question and found it… opaque – and without a ready clue as to where to try next. Searching for the name of the source file yielded two issues that appear related: #3711 (closed) and #3721 (still open) – both of which offer their respective OPs working, albeit ad-hoc, solutions. 

I should stress that the warning messages, in my case, are just that – messages. Nothing, in my case, appears actually broken. I just wanted to report them here and stay ahead of the curve, so to speak. My thanks, all of you, for the hard work.

**Comment by ilovezfs** [comment] 2018-01-23 22:27
see https://github.com/Homebrew/brew/pull/3725

**Comment by MikeMcQuaid** [comment] 2018-01-24 10:27
This should be fixed if you `brew update` now, thanks.

**Closed by MikeMcQuaid** 2018-01-24 10:27 UTC

**Comment by jvanderen1** [comment] 2018-01-24 19:19
@MikeMcQuaid Thanks Mike!
