### ISSUE TITLE
libraries with dependencies can still break their dependencies silently

### ISSUE THREAD

**Issue by ahundt** [Homebrew/brew#1416] opened 2016-10-31 08:16 UTC
### Bug reports:

As discussed in a long prior thread, it appears changing libraries that have dependencies can break those dependencies silently because they are not automatically re-bottled. (sorry all the repos moved and I can't find the original)

Evience of this can be found in https://github.com/Homebrew/homebrew-science/pull/4524 and the history of `eigen.rb`.

**Comment by MikeMcQuaid** [comment] 2016-11-02 18:04
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by scpeters** [comment] 2016-11-02 18:28
My guess is that it's related to formulae that have dependencies that live in other taps. If the dependency gets rebuilt, the downstream taps will need to rebuild their bottles. For example, formula revisions for boost users in core were bumped in https://github.com/Homebrew/homebrew-core/pull/5364, but boost users in `homebrew/science` were probably broken right when that was merged.

Cross-tap bottle breakages seems like a good topic for a [brew-evolution](https://github.com/Homebrew/brew-evolution/blob/master/process.md) pull request to me. I'll be happy to participate there, since this affects a tap that I maintain. I don't have any immediate ideas though.

**Comment by MikeMcQuaid** [comment] 2016-11-05 01:51
https://github.com/Homebrew/brew/issues/620 hasn't been closed so I'm going to close this in favour of that.

**Closed by MikeMcQuaid** 2016-11-05 01:51 UTC

**Comment by ahundt** [comment] 2016-11-08 02:02
@scpeters yes that's a correct assessment. @MikeMcQuaid sorry for the redundant issue, I had spent 15 minutes looking for #620 again before I posted but couldn't find it! Wrote it down where I can find it again. :-)
