### ISSUE TITLE
Brew livecheck shows a deprecated formula

### ISSUE THREAD

**Issue by Porkepix** [Homebrew/brew#16366] opened 2023-12-20 00:37 UTC
### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 4.2.0-19-g23ce2d5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 23ce2d5bf81e71d8bf9fdf9198d8d23724f0966b
Last commit: 6 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2659dc1585f282f0e7ebaa3b8c42ffade59e5f5c
Core tap last commit: 28 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: quad-core 64-bit skylake
Clang: N/A
Git: 2.43.0 => /bin/git
Curl: 8.5.0 => /bin/curl
Kernel: Linux 6.5.6-arch2-1 x86_64 GNU/Linux
OS: Arch Linux
Host glibc: 2.38
/usr/bin/gcc: 13.2.1
/usr/bin/ruby: 3.0.6
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

Checking formulas to bump with `brew livecheck`.

### What happened (include all command output)?

One deprecated formula is listed.

### What did you expect to happen?

It shouldn't list it considering Homebrew disallow the bump on it.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
List formulas to bump with `brew livecheck -q --eval-all --newer-only`.
See that `cling` is part of it.
Try to bump it (`$ brew bump --open-pr cling`)
See that it disallows the bump due to deprecation.
```

Double end of issue note:

- I feel like it's strange to both ask `brew doctor` output, and have a check mark stating "My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue."
- I checked the last check mark despite mentioning a formula as this kind of issue would appear on any formula meeting the same criterias. The statement seems therefore pretty restrictive, I'd say?

**Comment by MikeMcQuaid** [comment] 2023-12-20 12:01
CC @homebrew/core @samford for thoughts. I don't know how much this is intentional or not and, if not, what the fix would be (e.g. `livecheck` should skip these, we should remove `livecheck` blocks when we deprecated, etc. etc.)

---

> * I feel like it's strange to both ask `brew doctor` output, and have a check mark stating "My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue."

That's because we want to people with failing `brew doctor` output to not create issues.


> * I checked the last check mark despite mentioning a formula as this kind of issue would appear on any formula meeting the same criterias. The statement seems therefore pretty restrictive, I'd say?

The reasoning for it is: if it affects only a single formula: it should be on that formula's tap instead.

**Comment by SMillerDev** [comment] 2023-12-20 13:16
We have been removing the blocks for versioned formulae, but I'm not sure "It shouldn't list it considering Homebrew disallow the bump on it" is actually true. I think it heavily depends on the formula.

In my view, software in security-only mode is deprecated since upstream doesn't support it any more than it absolutely needs to. But if a security update is released livecheck should pick it up for sure. However, if it is `: does_not_build` I don't see much value in keeping the livecheck.

**Comment by EricFromCanada** [comment] 2023-12-20 14:34
It can be helpful to see that a newer version is available even when the current version doesn't build. In this case, it looks like they've tagged a new [1.0 release](https://github.com/root-project/cling/releases/tag/v1.0) whose fixes may match what was [requested earlier](https://github.com/Homebrew/homebrew-core/pull/131473#issuecomment-1556060545). That's why I had `bump` [only show "(deprecated)"](https://github.com/Homebrew/brew/pull/16314) in such cases

**Comment by SMillerDev** [comment] 2023-12-20 15:28
Yes, I think both me and Eric are saying that there should not be any difference.

**Comment by samford** [comment] 2023-12-20 18:52
Yes, this is intentional behavior in livecheck. For a bit of context, livecheck will only skip a formula as deprecated if it doesn't have a `livecheck` block and this is by design. There are times when we deprecate a formula but it could potentially be undeprecated in the future if a newer version fixes problems, so there's still some value to checking for new versions (as Eric mentioned). This is the reason why I typically leave `livecheck` blocks when the reason is `:does_not_build` (and sometimes also `unmaintained`, as that may or may not change in the future).

That said, surfacing the deprecated/disabled status in livecheck's debug and verbose JSON output (specifically in the `meta` information) may make sense. We could also add a `(deprecated)` (or `(disabled)`) parenthetical to the normal output (like `(guessed)`) if that's helpful.

**Comment by Bo98** [comment] 2023-12-21 01:59
Only postgresql 11 should be showing up as deprecated.

**Comment by MikeMcQuaid** [comment] 2023-12-21 08:43
Happy to continue discussing here but closing as it seems to be by design.

**Closed by MikeMcQuaid** 2023-12-21 08:43 UTC
Labels: bug
