### ISSUE TITLE
Error: Not Found on Augustus bump

### ISSUE THREAD

**Issue by Porkepix** [Homebrew/brew#13635] opened 2022-08-02 22:54 UTC
### `brew config` output

```shell
[clement@T470-clement homebrew-core]$ brew config
HOMEBREW_VERSION: 3.5.7-11-g8a153de
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a153de2bc6a335080d877c0eb14d71e2ff8c537
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4cc4e3e0234a5e9d374fbea37def2466680b29ea
Core tap last commit: 17 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit skylake
Clang: N/A
Git: 2.37.1 => /bin/git
Curl: 7.84.0 => /bin/curl
Kernel: Linux 5.18.12-arch1-1 x86_64 GNU/Linux
OS: Arch Linux
Host glibc: 2.35
/usr/bin/gcc: 12.1.0
/usr/bin/ruby: 3.0.4
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I tried to bump `augustus` formula

### What happened (include all command output)?

```
[clement@T470-clement homebrew-core]$ brew bump-formula-pr --version 3.4.0 augustus --debug
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/augustus.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/git --version
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Linuxbrew/3.5.7-11-g8a153de\ \(Linux\;\ x86_64\ \"Arch\ Linux\"\)\ curl/7.84.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=augustus\+repo\%3AHomebrew\%2Fhomebrew-core\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --dump-header /tmp/github_api_headers20220803-1176993-1ty02fi
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Linuxbrew/3.5.7-11-g8a153de\ \(Linux\;\ x86_64\ \"Arch\ Linux\"\)\ curl/7.84.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=augustus\+3.4.0\+repo\%3AHomebrew\%2Fhomebrew-core\+state\%3Aclosed\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --dump-header /tmp/github_api_headers20220803-1176993-7gp133
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Linuxbrew/3.5.7-11-g8a153de\ \(Linux\;\ x86_64\ \"Arch\ Linux\"\)\ curl/7.84.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/augustus/Homebrew/homebrew-core/pulls/94124/files --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --dump-header /tmp/github_api_headers20220803-1176993-1jq5ume
Error: Not Found
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github/api.rb:300:in `raise_error'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github/api.rb:233:in `open_rest'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:506:in `get_pull_request_changed_files'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:482:in `block in check_for_duplicate_pull_requests'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:481:in `select'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:481:in `check_for_duplicate_pull_requests'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:474:in `check_closed_pull_requests'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:459:in `check_new_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:142:in `bump_formula_pr'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

To not raise any error.

### Step-by-step reproduction instructions (by running `brew` commands)

Just run `brew bump-formula-pr --version 3.4.0 augustus` or `brew bump --open-pr augustus`.

Not sure if the issue is on the formula itself or within `brew`, so opened it here, might reopen in the other repo if needed.
From what I can see, the last url it tried to curl is a bit strange, but dunno why it tries this query.

EDIT: Encountered the same issue with `psalm` formula.

**Comment by p-linnane** [comment] 2022-08-03 04:35
See https://github.com/Homebrew/brew/issues/13634#issuecomment-1203000675

**Comment by MikeMcQuaid** [comment] 2022-08-03 11:48
Duplicate of https://github.com/Homebrew/brew/issues/13634

**Closed by MikeMcQuaid** 2022-08-03 11:48 UTC
Labels: bug
